### ISSUE TITLE
2022 (November) dev meeting

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof#100]
Date: 09.-11.11.2022

Location: Magdeburg

Organisation: @gnn 

Draft agenda: https://github.com/oemof/oemof/wiki/Meeting-2022.11

**Comment by jnnr** [comment]
Meanwhile, the FNE yearly network meeting is planned to take place on 8./9.11.22. Can and should the dev meeting be rescheduled?

**Comment by joroeder** [comment]
> Meanwhile, the FNE yearly network meeting is planned to take place on 8./9.11.22. Can and should the dev meeting be rescheduled?

FNE? Forschungsnetzwerk Energiesystemanalyse? I think there are already rooms reserved for the next dev meeting, right? @gnn
I think it is not an option anymore to reschedule the meeting.

However, there is still support needed to organise the meeting. I will shortly add the organisation template -- please feel free to add yourself somewhere below.

**Comment by joroeder** [comment]
*steps-to-organize an oemof meeting*

**Previous meeting (half a year in advance)**
- [ ] Decide on location
- [ ] Decide on date
- [ ] Announce date and location in new Issue, that addresses the organisation of the next meeting

**3-6 Months before**
- [ ] Look for sufficient rooms in your Institutue / University / City / Elsewhere

**2-3 Months before**
- [ ] Ask for sessions
- [ ] Ask chairs for each session how long it might take --> Agenda input
- [ ] Announce that everybody can have a slot on demand

**1-2 Months before**
- [ ] Promote the meeting via our channels 
- [ ] Publish agenda draft

**1-2 Weeks before**
- [ ] Send material to participants, if needed (e.g. a short intro for setting-up your fork etc. for hands-on sessions on dev meetings)

**Actual meeting**
- [ ] Meet
- [ ] Add streams to physical meetings / broadcasting the sessions!

**Tipps**

1. Tag sessions with e.g. #hands-on  #tutorials (beginner/advanced) # decision wanted #feedback wanted #open discussion #hard-code #usage #35 
2. Idea: ask the participants if they consider themselves as users or developpers in the registration list
3. Collect the presentations maybe beforehand!
4. Prepare tutorials with a repository (requirements file to install a fresh environment + data) maybe even jupyter notebook? ipython notebook [problem: installation using pip/ conda] --> Look at @fwitte's wonderful example!

**Comment by joroeder** [comment]
I don't know. So I am not involved in the FNE meeting. I don't know about others. I think it would be really important to involve some more people from the RLI (and from all other institutes) in oemof dev community to support the maintenance and development of the oemof packages.

The problem is that the meeting is already planned since May and if we move the meeting, there will be other appointments of other people. And, I think that rooms are already reserved in Magdeburg. So I guess it will be difficult to find an alternative.

**Comment by p-snft** [comment]
> Meanwhile, the FNE yearly network meeting is planned to take place on 8./9.11.22. Can and should the dev meeting be rescheduled?

We decided on the date one year ago. Also, we only have a partial conflict. I suggest to consider the FNE meeting in our schedule by putting topics to the the second or third day if there is urgent need for/by a FNE meeting visitor.

**Comment by jokochems** [comment]
Hi, oh shoot, I totally forgot to add the date in my calendar when we agreed on it, but that's clearly my bad.
I totally agree with what has been written on not rescheduling. Also, I like the idea of having not so very pressing or smaller group issues on the first day. I'll also attend the FN ESA annual meeting and thus most likely join on the 10th.

**Comment by jokochems** [comment]
Here is the (draft) agenda: https://github.com/oemof/oemof/wiki/Meeting-2022.11 
The draft was created by @p-snft. Thank you!

**Comment by jokochems** [comment]
I assume, we're collecting (further) topics for the agenda?
I want to add integration of the multi-period feature to solph: https://github.com/oemof/oemof-solph/pull/828
(Resolving integration issues I can address is on my TODO list for next week.)

**Comment by joroeder** [comment]
> I assume, we're collecting (further) topics for the agenda? 

Yes, it is as always possible to add topic, you want to discuss or work on, or maybe if decisions are required, the meeting should be used. Altogether, we are aiming for meeting with a strong focus on hands-on sessions to involve also new developers in the process (Tutored hackathlon).

> I want to add integration of the multi-period feature to solph: [oemof/oemof-solph#828](https://github.com/oemof/oemof-solph/pull/828) (Resolving integration issues I can address is on my TODO list for next week.)

I have added this as topic

**Comment by p-snft** [comment]
@sasa821: I really like the examples you give to motivate new features (see https://github.com/oemof/oemof-solph/pull/826, https://github.com/oemof/oemof-solph/pull/868). Will you join? I'd like to create a concept for an exercise script for teaching energy system modelling. It would make a lot of sense to base some of that on the examples you give.

**Comment by lensum** [comment]
I'm currently working on a way to implement cellular energy models (see [link](https://www.vde.com/de/etg/arbeitsgebiete/zellulare-energiesysteme)) into oemof, which requires some adjustment/extension of the existing oemof code. I'd like to participate on the dev meeting and if there's interest and time, I could also present what I have done so far. As mentioned, it is still a work in progress. But I would appreciate the input of other devs tremendously!

Also: is this comment enough to register me for the meeting or should I send an E-Mail as well?

**Comment by sasa821** [comment]
> @sasa821: I really like the examples you give to motivate new features (see [oemof/oemof-solph#826](https://github.com/oemof/oemof-solph/pull/826), [oemof/oemof-solph#868](https://github.com/oemof/oemof-solph/pull/868)). Will you join? I'd like to create a concept for an exercise script for teaching energy system modelling. It would make a lot of sense to base some of that on the examples you give.

Thank you! I'm glad you liked the examples. I am interested in collaborating, but I am not yet sure if I can manage to join the dev meeting. Since it is not far away from Berlin, maybe I can join for only half a day. Do you already know when you will discuss the new exercise script?

**Comment by p-snft** [comment]
@lensum: I just added you to the list in the Wiki. That should do.

@sasa821: Typically, we try to arrange everything based on the preferences of the attendees. The "Tutored hackathlon" slots are basically just "we do something practical and have experienced people around". So, we could meet in any of those slots. Alternatively, to reduce the need of travel, we could do something online. (Actually, I planned to have this as a dinner chat.)

**Comment by p-snft** [comment]
Documentation of the meeting:
* General: https://github.com/oemof/oemof/wiki/Meeting-2022.11
* Issue related: In issues.

**Comment by Bachibouzouk** [comment]
Are there any minutes of the meeting/sessions?

**Comment by Bachibouzouk** [comment]
Great news! Thanks for the update
