### ISSUE TITLE
Time-dependent self-(dis)charge for storages?

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#101]
My idea was to implement a time-depending self (dis)charge for storages instead of having a fixed value. By doing this, we can regard the ambient- or environment-depending losses/inflows of different storage types e. g. pumped hydro storages or thermal storages.

Idea: 

Passing a series of percental values with regard to the maximum storage capacity for all time steps instead of a fixed scalar. A positive value e.g. 0.05 in time step 5 means that the losses amount to 5% in this time step. Vice versa negative values represent occuring inflows.

@oemof/oemof-main : My idea might be (too) simple and naive, so any feedback is welcome!

**Comment by caro-rli** [comment]
I first had only battery storages in mind. I guess this feature makes no sense with battery storages :smile:

I think this must become clear when implementing this feature. Apart from that I find your idea good.

**Comment by simonhilpert** [comment]
I will implement this in solph and add a information to docstrings, that is possible to hand over a scalar or list/pandas Series. If we will dig deeper (e.g. additional gain for pump hydro) we might want to create a new class.

**Comment by simonhilpert** [comment]
pushed is on dev. I will close this issue. If we will have another enhancement we should open an new one.

**Comment by ckaldemeyer** [comment]
:+1

Actually I was going to do it but thanks :dancers:
