### ISSUE TITLE
Need to decide for a bank for the oemof association

### ISSUE THREAD

**Issue by c-moeller** [oemof/oemof#102]
Dear oemof community,

we need to decide for a bank for the oemof association. Does anyone have any good suggestions for ethical banks? I found these four alternatives:

- GLS Bank
- UmweltBank
- EthikBank
- Triodos Bank

In the last oemof board meeting, we were critical of GLS Bank, but we would like to hear your opinions before we decide. Also if you have experience with other banks and account management fees and so on. Thank you :-)

**Comment by simnh** [comment]
GLS is quite expensive in addition to critics based on anthroposophical stuff ...I have good experience with Triodos (not that there is also a connection to anthroposophy, however not as close as GLS).. EthikBank also sounds good...

**Comment by p-snft** [comment]
First of all, I like the idea to pick an ethical bank.

* The argument against GLS Bank unfortunately is valid for most ethical banks (and other companies): They frame esoteric ecology as a very positive thing. In the end, the argument isn't very selective.
* Umweltbank allows for new bank accounts only if you take a loan. So, they're out.
* EthikBank does something into the same direction as GLS, as they name Demeter as a positive example. Don't know if it's to the same extend, though. (In fact, Demeter is superior to "standard" organic farming, but it comes with unscientific nonsense.)
* Tridos Bank has the lowest costs but is not as transparent as the other institutes are.

**Comment by busiing** [comment]
As far as I am concerned is the esoteric level of demeter "optional" in most farms and thus I don't mind a couple of hippies burying a cow horn full of shit at mid-night with a full moon.

**Comment by p-snft** [comment]
I did not want to start a discussion on Dementer, but as I value truth: It is obligatory for a certification of Demeter to use "biodynamic preparations". (Those are comparable to anthropophilic globules, but for the soil.) However, this fact will lead us nowhere: No bank has "no esoteric BS" in their ESG guidelines.

Also, there are other examples for unscientific stuff in the ESG guidelines of both, GLS Bank and EthikBank, while Triodos Bank did not publish their ESG guidelines. So, it's hard to decide between the three based on company values.

**Comment by p-snft** [comment]
It is.
