### ISSUE TITLE
Definition of storages

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#102]
As I know it costs, C-values, etc. are related to the nominal capacity. As some storages do have a minimal and maximal soc the effective capacity is lower. In oemof cost, C-values are related to this effective capacity because we do not have a minimal and maximal soc.

@oemof/oemof-main : Did I misunderstand something or shall we add these attributes?

**Comment by simonhilpert** [comment]
we have: min / max soc = cap_min / cap_max attributes (absolut values)

**Comment by uvchik** [comment]
Sorry, missed it.

**Comment by caro-rli** [comment]
But for invest models I need a relative value like the DoD.

**Comment by caro-rli** [comment]
@uvchik is this still relevant for you, or now obsolete (as you have no investment models)?

**Comment by uvchik** [comment]
For me it is not important at the moment but we should keep that in mind for the cleaning up of solph:

Please help us to fill the [parameter table](../wiki/solph:-refactoring-attributes).

**Comment by caro-rli** [comment]
> Is this still relevant for you?

Yes for me it's still relevant and I would like to implement it.

> What speaks against working with absolute values?

Maybe I don't get the point, but for me it's not clear how it should be possible to set a minimum or maximum soc, when I don't know the storage capacity (because this is one of my results). That's why I would need a relative value like the DoD.

> @caro-rli : Please help us to fill the parameter table.

@uvchik Could you link the corresponding issue, if there is one?

**Comment by ckaldemeyer** [comment]
>> Is this still relevant for you?

>Yes for me it's still relevant and I would like to implement it.

>> What speaks against working with absolute values?

>Maybe I don't get the point, but for me it's not clear how it should be possible to set a minimum or maximum soc, when I don't know the storage capacity (because this is one of my results). That's why I would need a relative value like the DoD.

I see. So this would be an equation like `Cap_invest * Pecentual_Max_DoD => Filling_level[t] => C_invest * Pecentual_Min_DoD => 0`, right?

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/wiki/solph:-refactoring-attributes

**Comment by caro-rli** [comment]
> I see. So this would be an equation like Cap_invest * Pecentual_Max_DoD => Filling_level[t] => C_invest * Pecentual_Min_DoD => 0, right?

I'm not sure about this equation, as I don't now current solph equations in detail, but for example using a maximum and minimum SOC (like SOC_min = 10 %, SOC_max = 90 %) you could calculate a usable range of the storage and relate this to your investment capacity like:

_(SOC_max - SOC_min) * Cap_invest_

in every equation where _Cap_invest_ plays a role.

Using the DOD it could also be:

_(DOD_max - DOD_min) * Cap_invest_

but the SOC might be a bit more descriptive. But also I'm not sure if a SOC_max is really relevant and if DOD simply stands for DOD_max. But I think we can care later about this, when going into the details.

**Comment by uvchik** [comment]
@caro-rli : What about a new PR with "Revise parameter of storage model". You could make a consistent proposal and than we can discuss the details. That could cover this issue and #55.

**Comment by uvchik** [comment]
@caro-rli : Still valid?

**Comment by caro-rli** [comment]
I think yes. We don't have a parameter like DoD, do we? Or is this something we decided to calculate outside the model?

**Comment by uvchik** [comment]
We do have an upper/lower bound for the capacity (level).

**Comment by caro-rli** [comment]
Closing this. At the last developer meeting we decided to not include calculations like this in the model and leave it to the customer.
