### ISSUE TITLE
Attendance at 4th OpenMod Workshop in Stockholm

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#103]
Dear @oemof/oemof-main,

the open_eGo team is participating at the [4th OpenMod Workshop in Stockholm](http://wiki.openmod-initiative.org/wiki/Open_Energy_Modelling_Workshop_-_Stockholm_2016). Do you have participants from the omeof dev group? Do you present recent development of oemof or do you plan to initiate a breakout group?

If you like to coordinate things with us feel free to discuss here (or elsewhere ;) )!

**Comment by ckaldemeyer** [comment]
I am planning to go there as well! So far, there are no plannings on presentations but I could imagine a breakout group.

At the moment, I have the feeling that we are at the point that many people are willed to join the oemof project and a lot of code is produced (uncoordinated). In contrast some structures (core scope, documentation, stringent code, flexible interfaces for adaptions) are lacking, not clear or/and clean at the moment.

So one idea from my side would be to start breakout group with a title like "Creating coordinated, target-oriented structures in collaborative open source projects at the example of oemof".

This could serve as a coordination meeting between the different groups.

@oemof/oemof-main : What do you think?

**Comment by simonhilpert** [comment]
I will go there as well, not planning a presentation.

**Comment by cswh** [comment]
Unfortunately I cannot make it.

**Comment by beritRLI** [comment]
Eva just told me that noone of the oemof core-team will attend. I think it would be good to report about the state of oemof. for those who already know about oemof to know that it is developing and for the new openmods to hear about it.
I will just point out the GitHub and the releases and give a short explanation about the structure that was fixed at the last meeting.

**Comment by uvchik** [comment]
You could announce that we will have a 0.1 release in May (or June :blush:).
