### ISSUE TITLE
Adding Slack/Excess components instead of pure pyomo variables

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#104]
I created a feature branch features/slack_components where I implemented the two new components. 

Then slack will be inline with the the general structure because it will be represented as as component in the graph. It already works and I would like to merge soon. 
We only need to decide where to place the new classes. I think on the level below bus/component. 

For users nothing changes except the excess/shortage values will pop up in the result data frame aus bus output/inputs. 

Please comment @oemof/oemof-main

**Comment by uvchik** [comment]
To discuss changes on a feature-branch a pull request is easier than an issue.

**Comment by uvchik** [comment]
I don't know where we can continue the discussion after I accidentally merged the PR #107.

I'm quite unhappy with the actual structure. Couldn't we make `excess` and `shortage` to normal components. In my opinion they are sinks and sources and in my opinion it is clearer if they are not added automatically by the bus.

Actually the class `source.Commodity` can be used as a shortage variable. We could do the same for excess (`sink.Something`) and remove excess and shortage and the automatic creation. 

Of course we can keep it for a while to give people the chance to adapt there apps.

**Comment by uvchik** [comment]
see PR #133
