### ISSUE TITLE
[meeting] oemof user and developer meeting 2023

### ISSUE THREAD

**Issue by jokochems** [oemof/oemof#108]
Dear oemof users and developers,

at the last developer meeting in Magdeburg (#100), it has been decided that DLR is to host the next user and developer meeting.

Now here are the most important dates:
* Location: DLR **Stuttgart, Germany**; detailled venues and room infos to follow
* Time: **Wednesday, May, 24rd until Friday, May 26th**.
* Wiki page: https://github.com/oemof/oemof/wiki/Meeting-2023.05

Looking forward to seeing many of you there!

Best,
Johannes

[This is an edited posting summarizing the most important information on the meeting]

**Comment by jokochems** [comment]
Dear all,

I had some troubles with finding suitable rooms. I know the appointment announcement is out there on the website, but as long as there is no mailing, wiki page etc., I guess response rates are pretty much limited. Therefore, I suggest to change the appointment to May, 24th-26th where I can reserve some rooms. What do you think?

Thank you and best regards,
Johannes

**Comment by p-snft** [comment]
We should fix that soon so that not to many people plan based on the wrong date. I suggest to update the date if no-one objects today.

**Comment by jokochems** [comment]
> We should fix that soon so that not to many people plan based on the wrong date. I suggest to update the date if no-one objects today.

Totally agree. Let's do so once we have the feedback of the devs on the new proposed date.

**Comment by lensum** [comment]
I saw that the change is already announced, but would like to point out that the ETG-Congress will be on the 25th and 26th of May as well. Obviously, I don't know if it's a relevant conference for many other users, but I could imagine it to be. Just wanted to put that information out there.

**Comment by jokochems** [comment]
> I saw that the change is already announced, but would like to point out that the ETG-Congress will be on the 25th and 26th of May as well. Obviously, I don't know if it's a relevant conference for many other users, but I could imagine it to be. Just wanted to put that information out there.

Sorry to not respond earlier:
* As the responses were almost all in favor of moving to the current date, we decided to do so in the meantime.
* I'm sorry if you can't make it due to the conflicting appointment.
* To be honest, I heard of that congress for the first time (though I'm aware of the ETG in pricinple). So I hope, it won't affect too many people.

**Comment by jokochems** [comment]
I have created a draft Wiki page for the upcoming user & dev meeting in Stuttgart: https://github.com/oemof/oemof/wiki/Meeting-2023.05
I'll discussed the draft agenda with @srhbrnds next week and we'll fill in the schedule once we have the registrations.

**Comment by jokochems** [comment]
Dear all,
if you plan to attend the multi-period modelling tutorial in the course of the meeting, you can already find everything here:
https://github.com/jokochems/multiperiod_tutorial

It would be great, if you had at least your solver installation running beforehand and even greater if you already checked out the files and installed the dependencies.

I guess for @p-snft's tutorial on solph and TESPy, there are also already installation instructions which you could follow along upfront.

**Comment by p-snft** [comment]
It's this tutorial, by the way: https://oemof.github.io/heat-pump-tutorial/

(It was originally created for OSMSES 2023. We offer to present it a second time.)
