### ISSUE TITLE
Docstrings of the assembler methods do not show up in the documentation

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#109]
The docstrings of the assembler functions do not show up in the documentation. This might be caused by the atypical structure (all functions are named the same `_`).

@oemof/oemof-main : Does anybody has an idea?

**Comment by gnn** [comment]
Yeah, this is a known defficiency of using https://docs.python.org/3/library/functools.html#functools.singledispatch that I don't know how to fix. FWIW the whole assembler functions setup will hopefully eventually be redesigned, but that is part of a larger solph refactoring, which is better discussed in #93.

**Comment by uvchik** [comment]
Then we should await the oemof-meeting in April.

**Comment by uvchik** [comment]
We should spent the time on documenting solph v0.1 instead of the old version.
