### ISSUE TITLE
Convention for strings in python

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#113]
Dear @oemof/oemof-main  

I just realised that we are not really good in developing according to our own developer notes:

We handle python strings in a different way everywhere. Maybe we can clean that for the next release ? Or better may release? 
See:  
http://oemof.readthedocs.org/en/stable/developer_notes.html

I think the best way here is:

1. Decide if we stick to " " or use ' ' . (Maybe adapt the notes) 
2. Every developer fixes his/her code that he mainly developed on 

What do you think ?

**Comment by ckaldemeyer** [comment]
:+1: For me this could be done during the refactoring process.

**Comment by ckaldemeyer** [comment]
I think we should also look at the docstrings which are also not handled uniformly atm.

For this, we have agreed on the numpydoc style: http://oemof.readthedocs.org/en/stable/overview.html?highlight=docstring

In my opinion this part should be moved from "Overview" to "Developer Notes" as it only affects developers.

**Comment by ckaldemeyer** [comment]
Proposal:

Move the sections:

* Code commenting
* Code documentation
* General documentation

from "Overview" to "Developer Notes" and replace them through a section "Transparency" which roughly explains our documentation approach and then links to "Developer Notes".

**Comment by uvchik** [comment]
I added it to the topics in the [meeting-wiki](../oemof/wiki/How-to-release) yesterday (see issue #67).

I do not think we should decider whether to use " or '. I like the the way it is described [at stackoverflow](http://stackoverflow.com/questions/56011/single-quotes-vs-double-quotes-in-python).

**Comment by simonhilpert** [comment]
What I get from the discussion on stackoverflow: be consistent!

 and we aren't, so we have to decide " or ' , at least, when  
to use " and when '  in general.

**Comment by cswh** [comment]
For me the most important part is, that if we have a rule in our docs, we should stick to it or remove it from the docs.

> Proposal:
>   
>   Move the sections:
>   
>   * Code commenting
>   * Code documentation
>   * General documentation
> 
> from "Overview" to "Developer Notes" and replace them through a section "Transparency" which roughly   explains our documentation approach and then links to "Developer Notes".

I agree to the proposal. :+1:

**Comment by ckaldemeyer** [comment]
> For me the most important part is, that if we have a rule in our docs, we should stick to it or remove it from the docs.

:+1: Being consistent is also #1 for me. I don't really care whether we use "text" or 'text'..

**Comment by uvchik** [comment]
I totally agree. We should define all rules until the beginning of April. On the meeting we can adopt them and then we will make an announcement on github. What to do you think?

I think it is very important to announce new rules because people will read the rules once and otherwise they do not know about rules added afterwards.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by cswh** [comment]
:+1:

**Comment by uvchik** [comment]
@oemof/oemof : The new rule for quotes is now part of the developer rules. Please leave an okay-comment to ensign these changes.

**Quoted strings**

As there is no recommendation in the PEP rules we use double quotes for strings read by humans such as logging/error messages but single quotes for internal strings such as keys and column names. However one can deviate from this rules if the string contains a double or single quote to avoid escape characters. According to [PEP 257](http://legacy.python.org/dev/peps/pep-0257/) and numpydoc we use three double quotes for docstrings.

```python
logging.info("We use double quotes for messages")

my_dictionary.get('key_string')

logging.warning('Use three " to quote docstrings!'  # exception to avoid escape characters
```

**Comment by birgits** [comment]
okay!

**Comment by cswh** [comment]
ok for me.

**Comment by ckaldemeyer** [comment]
O.k. for me!

**Comment by caro-rli** [comment]
ok

**Comment by ckaldemeyer** [comment]
> @oemof/oemof : The new rule for quotes is now part of the developer rules. Please leave an okay-comment to ensign these changes.

> **Quoted strings**

> As there is no recommendation in the PEP rules we use double quotes for strings read by humans such as logging/error messages but single quotes for internal strings such as keys and column names. However one can deviate from this rules if the string contains a double or single quote to avoid escape characters. According to [PEP 257](http://legacy.python.org/dev/peps/pep-0257/) and numpydoc we use three double quotes for docstrings.

> ```python
> logging.info("We use double quotes for messages")

> my_dictionary.get('key_string')

> logging.warning('Use three " to quote docstrings!'  # exception to avoid escape characters
> ```

Just to get you right. Single quotes for internal strings such as keys and column names also refers to attribute names, plotting arguments, etc., right? 

WRONG:
`myplot.slice_unstacked(bus_uid="bel", type="output")`

RIGHT:
`myplot.slice_unstacked(bus_uid='bel', type='output')`

WRONG:
`bgas = Bus(uid="bgas",
           type="gas",
           price=70,
           balanced=True,
           excess=False)`

RIGHT:
`bgas = Bus(uid='bgas',
           type='gas',
           price=70,
           balanced=True,
           excess=False)`

I think this should be consistent in all code for the 1.0 May release.

**Comment by uvchik** [comment]
Correct, except that we should release 0.1 and not 1.0 in May :smile:
