### ISSUE TITLE
Who will take part in the 4th oemof developer days in Flensburg from May 9 to 11 2016 in Flensburg?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#115]
The 4th oemof developer days are from May 9 to 11 2016 in Flensburg.

I created a [wiki](../wiki/Issues-for-the-4th-oemof-developer-days) where you can add you Name if you will take part. You can also add topics, inputs, wishes, ... .

Please do not wait too long because people might want to book trains/accommodation early.

**Comment by cswh** [comment]
just adding for notifications: @oemof/oemof-main @oemof/feedinlib

**Comment by gplssm** [comment]
My potential participation depends on the agenda (and I guess the agenda partially depends on my input :wink: ). Thus, I'm interested if there will be sessions on open load flow modeling with oemof and similar.

**Comment by ckaldemeyer** [comment]
I'll be there as well.

> My potential participation depends on the agenda (and I guess the agenda partially depends on my input :wink: ). Thus, I'm interested if there will be sessions on open load flow modeling with oemof and similar. 

I think the main focus is a major clean-up and a rethinking/-designing of certain structures. From my point of view there is not too much time left for sessions such as OLF as time will be sparse.

Nevertheless, I think it's very valuable to pre-think future features such as OLF in the refactoring-process. Thus, your attendence would be great!

**Comment by ckaldemeyer** [comment]
I have added some outputlib-issues on the agenda: https://github.com/oemof/oemof/wiki/Issues-for-the-restructuring-meeting-from-6.4.-to-8.4.-in-Flensburg

Also see #85

**Comment by ckaldemeyer** [comment]
I have added two more topics to the wiki:

1. Inputlib
2. Marketing

Please make up your mind concerning all topics in advance so that we can make progress.

I am looking forward to the meeting!!

**Comment by uvchik** [comment]
> I am looking forward to the meeting!!

That's fine but it is still a month away.

See issue #67 for the April (remaster) meeting in Flensburg.

**Comment by ckaldemeyer** [comment]
Oops, wrong Issue..

**Comment by cswh** [comment]
Shall we start Monday afternoon and go until Wednesday noon? Or shall we already start Monday in the morning. For me as a Flensburg resident I can live perfectly well with both options. 

@oemof/oemof-main: Any preferences?

**Comment by ckaldemeyer** [comment]
I am also fine with both!

**Comment by cswh** [comment]
Proposal: We will start on Monday at 13:30. We will finish on Wednesday at 15:30.

@oemof/oemof : Any protests?

**Comment by caro-rli** [comment]
I'm fine with it.

**Comment by uvchik** [comment]
> I'm fine with it.

Me too :smile:

**Comment by gplssm** [comment]
Booked a ticket to Flensburg and will arrive at around 11 am. Looking forward to see you there! (:

**Comment by uvchik** [comment]
I booked a ticket from Köln. I will arrive at 12:43 with the RE from Hamburg (dep. 10:43). If the train is in time I will dispose my stuff at the hostel and will be at the Telekom building at 13:30.

**Comment by cswh** [comment]
So be it. Starting at 13:30 on Monday and finishing at 15:30 on Wednesday. I added the times to our [wiki](../wiki/Issues-for-the-4th-oemof-developer-days).

**Comment by gplssm** [comment]
Were do we actually meet?

**Comment by ckaldemeyer** [comment]
As far as I know we meet in the Telekomgebäude @ Eckernförder Landstr.!

**Comment by gplssm** [comment]
THX! See you there soon :)

**Comment by uvchik** [comment]
See the [wiki](../wiki) for some notes of the meeting.

Thank you for a nice and productive meeting :smile:
