### ISSUE TITLE
Sphinx warning caused by .rst ending

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#117]
With commit 80eb790b4f08 the file names of the whatsnew files were changed from `.txt` to `.rst`. This causes sphinx warnings. The files were original named with `.txt` to avoid these warnings.

@cswh Is there an important reason for `.rst`? If not, could you rename them again?

**Comment by cswh** [comment]
I changed them because they are written in rst-style and for example now get displayed properly at github. What causes the warning in sphinx? I would prefer to keep them as .rst.

**Comment by uvchik** [comment]
>I would prefer to keep them as .rst.

Me too, but for me it is more important to get rid of the warnings.

I think there are ways to fix it without renaming the files, but for me it did not have a priority because naming it with `.txt` fixed it. 

I would prefer using `.txt` rather than having the warnings all the times.

```python
/home/uwe/rli-lokal/git_home/oemof/doc/whatsnew/v0-0-1.rst:: WARNING: document isn't included in any toctree
/home/uwe/rli-lokal/git_home/oemof/doc/whatsnew/v0-0-2.rst:: WARNING: document isn't included in any toctree
/home/uwe/rli-lokal/git_home/oemof/doc/whatsnew/v0-0-3.rst:: WARNING: document isn't included in any toctree
/home/uwe/rli-lokal/git_home/oemof/doc/whatsnew/v0-0-4.rst:: WARNING: document isn't included in any toctree
/home/uwe/rli-lokal/git_home/oemof/doc/whatsnew/v0-0-5.rst:: WARNING: document isn't included in any toctree
```

**Comment by cswh** [comment]
Ok, new information for me: Resolves in commit message closes already the issue. Better use fix next time...

@uvchik Are you ok with the solution in the commit?

**Comment by uvchik** [comment]
Of course, that's even better. Thank you.
