### ISSUE TITLE
Invest

### ISSUE THREAD

**Issue by SanderNielen** [oemof/oemof#120]
Hi, I was wondering what the effect is of the boolean variable `invest`. Apparently it can be set via the `optimization_options` dictionary of each `Entity`. For some components, the effect is mentioned, but for the others the function of `invest` is not clear to me. 

Can someone explain this a little? Thanks in advance!

**Comment by simnh** [comment]
no its not binary it's really simple functionality (from an optimization model point of view). you can set the options for the class not instances of the class. so e.g. either all storages can be extended or none 

it basically changes the upper bounds of the flow between a bus and a component from

for output:

w_out <= out_max

to 

w_out <= out_max + add_out

when you create an object you can set out_max to 0 or any other value. This will be the capacity prior optimization. w_add_out is bounded by either by the values (attributes) add_out_limit (simpletransformer) or add_out_cap (storages). 
naming is not very nice, we will change that anyway...

see issue: #49 as well

**Comment by SanderNielen** [comment]
Thanks! 
Issue #49 is a whole lot of discussion, but I do understand the meaning of the variables now :D.
