### ISSUE TITLE
Oemof Thermal -StratifiedThermalStorage

### ISSUE THREAD

**Issue by therealtoby1** [oemof/oemof#125]
Hello everyone,

 i was attempting to use the StratifiedThermalStorage class the way it is shown in the [oemof-examples](https://github.com/oemof/oemof-thermal/tree/dev/examples/stratified_thermal_storage). I received an error message 
that indicated to me that the kwargs from the StratifiedThermalStorage class are causing this error in the facade.py file from oemof-thermal. 

There, the kwargs from the StratifiedThermalStorage are handed to the facade-class. The facade-class inherits from the Node-class and tries to pass the kwargs using 'super'. However, the Node-class cannot take any kwargs or args, so the attributes of the StratifiedThermalStorage class like diameter, bus, height... are causing the issue. 

I explained this with an example and a possible solution more thoroughly on my Github in [this file](https://github.com/therealtoby1/oemof_projects/blob/main/Stratified_Thermal_Storage.ipynb).

Any Feedback would be appreciated. Thank you in advance

**Comment by Bachibouzouk** [comment]
This looks like the same problem we have by oemof-tabular, you should be able to get your example running with the same oemof-solph and oemof-network version as in https://github.com/oemof/oemof-tabular/blob/dev/setup.py

**Comment by therealtoby1** [comment]
Thank you for the quick answer! 

I also managed to get the code to run by changing a line in the source code in the facade.py file, so the kwargs from the StratifiedThermalStorage class, that can't be handled by the Node class are not passed to the Node class.  Would it be reasonable to make a pull request or something like that so you can evaluate it?

**Comment by p-snft** [comment]
If I see it correctly, the corresponding code is already fixed but there has been no release since then: https://github.com/oemof/oemof-thermal/blob/08daa29146fd18f76666bc45d026ae63d0d8ea26/src/oemof/thermal/facades.py#L75

If you can verify by pip-installing the dev version and checking your code, I'd package a release.

**Comment by therealtoby1** [comment]
The change in the facade-file from the dev-version does indeed solve this issue. Packaging a release would  be really cool. Thank you for your help!

**Comment by p-snft** [comment]
Here is an updated release: https://pypi.org/project/oemof.thermal/0.0.7/

Note that it will set an upper limit for the version of solph (0.5.5) as oemof.thermal depends on other old libraries (pvlib and thus numpy < 2.0).

(I did not take the time to also fix the docs build. Content-wise, anyway nothing changed.)
