### ISSUE TITLE
new required packages ignored while updating with `git pull`

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#127]
On the example of newly added required package `dill` I discovered a potential misbehavior...

I expected pip to install all new required packages of `setup.py`. Recently someone added dill as new required package. After the pull to my local repo some file contains an import of dill, but dill isn't automatically installed by pip. Is it expected by the other @oemof/oemof-main that newly added required packages are automatically installed by pip?

I resolved the problem by half-way manually triggering the installation of `dill` with

`sudo pip3 install --upgrade -e oemof`

**Comment by gnn** [comment]
I was the one who added the `dill` dependency and unfortunately `pip` can't really know when dependencies change. So having to run `install --upgrade` manually on such occasions is expected behaviour and there's really not much we can do about it.

**Comment by gplssm** [comment]
What a pitty! Maybe we should improve pypi... ;)
Anyway, thanks for the explanation! I'll put the essence into the Developer Notes in the documentation.
