### ISSUE TITLE
Decision Making and Decision Documentation

### ISSUE THREAD

**Issue by ludee** [oemof/oemof#128]
What is your opinion on the "decision making rules"?
https://github.com/oemof/oemof/wiki/Rules-for-decision-making

Does it work? Improvements?
How does the decision documentation work? Wiki pages?
Do we have an "example decision", that shows the entire process?

**Comment by ckaldemeyer** [comment]
> What is your opinion on the "decision making rules"?
https://github.com/oemof/oemof/wiki/Rules-for-decision-making
>Does it work? Improvements?
So far I am fine with it.
> How does the decision documentation work? Wiki pages?
Lately, only major decisions have been fixed using the wiki pages. I think there's some space for improvements here.
> Do we have an "example decision", that shows the entire process?
You can search issues by label. I remember one Issue where we were discussing how to proceed with the outputlib and @uvchik , @s3pp , @caro-rli and me were involved.

**Comment by cswh** [comment]
I think we still need additional tools for the decision making for higher transparency and a better overview. As we discussed on the workshop in November.

**Comment by cswh** [comment]
@ludee : what is the background of your question?

**Comment by ludee** [comment]
The background of my question is a scientific paper with the title "Collaborative Modelling of Energy Systems – Best Practice and New Concepts for Successful Community Projects" for enviroinfo2016 (deadline 15.04.2016!).
We are analysing the oemof project with its challenges and problems (questionnaire) and give possible solutions from literature and other open source projects (expert interviews).
At this point the key sections are:
- Target definition and conception
- Exchange, feedback and decisions
- Information and documentation
- Planning and implementation

Now, the idea for an "example decision" is to agree on a "decision making strategy". With the aim of helping the oemof team and solving this "chicken-egg-situation" ;)

Thanks for your help @ckaldemeyer @cswh @uvchik

**Comment by ludee** [comment]
Why can't I add labels to this issues? 
Who can? 
Who is responsible to label issues?
Is it possible to create customised labels like "organisational decision"?

**Comment by uvchik** [comment]
No write access to oemof repository.
Everybody who is member with write access to oemof
Everybody who is member with write access to oemof and feels responsible
Technically it is possible but we should discuss how many lables we want.

**Comment by ckaldemeyer** [comment]
@ludee , I don't know whether you get notifications.

Anyway, I am interested in what you're planning in your paper: https://github.com/oemof/oemof/issues/88

**Comment by ludee** [comment]
@ckaldemeyer , I get notifications, thanks.
Paper is cancelled, decision making is continuing.

**Comment by beritRLI** [comment]
We  suggest the attached "decision making process". Along with this issue we'd like to go through the suggested process. We start with "decisions about organisational issues" when this is fixed the other decisions can follow (code,..)
Along with a process goes always the question of the responsibilities. As the roles in the oemof-organisation are not yet clear that is something which has to be discussed parallel (at least up to the point who is responsible for the decision making issues). Out of the expert interviews there is a starting chart with roles (not yet discussed) we will start another issue to discuss about that.
Please discuss along with the process also the responsibilities that we suggested.
We point out some points for the discussion here - please add your opinion on them and further points.

1. How to label "organisational decissions"?
 Suggestion: [decison wanted] and a new label [organisational]

2. Who is responsible for the execution of the process?
Suggestion: one person should be responsible; we suggest the leader of the core developer team is responsible to assign this person

3. should the 3 weeks discussion time be fixed or will the responsible person have the freedom to decide for a shorter period. (we suggest freedom to decide up to max. 3 weeks)

4.Is a voting always mandatory or can it be left out If the opinion seems to be clear? (we suggest that the responsible person is free to decide that (that can make decision processes much faster))

5. what are (other) mandatory points of the discussion
our point: there must be a location for the documentation of the decision 


[2016_04_18_oemof_decision_making.pdf](https://github.com/oemof/oemof/files/223971/2016_04_18_oemof_decision_making.pdf)

**Comment by ludee** [comment]
1. Suggestion for a first decision:
Do we want to create and use a label [organisational]?

2. At this point @cswh is the "decision assignee". Why is he/ are you responisble of the ticket?

3. Some decisions have to be made faster because other tasks depend on them.
On the other hand a hasty decision can lead to bad developments.
Is a minimum period needed? Like min. 1 week.
For this issue: Min: 25.04.2016 Max: 09.05.2016!

4. For a good decision a voting is not needed, for a good democracy it is.
What's the prefered voting tool, should it be defined or can the decision assignee decide which one to use?

5. Is there a minimum of people in he discussion?

**Comment by beritRLI** [comment]
4. I suggest to chose one voting tool that we use to make handling easier unless other functionalities are needed.
5. A decision which might be important for someone shouldn't be hindered because of non interest in it from others. If the responsible person thinks it is important to involve more people she/he should push that by contacting the group through to different media.

**Comment by uvchik** [comment]
By the way, I assigned @cswh, because he created the decision-making-wiki.

This discussion takes place at the oemof repository which is a repository of the oemof-core and oemof-solph group.

Who has write access to this issue? Everybody who is part of the oemof-core or oemof-solph group (at the moment also demandlib-group but this will change soon). 
Who is part of oemof-core or oemof-solph? Everybody who feels confident enough to review changes, features or bug fixes of solph or core.

We also have the oemof group with everybody who is part of the oemof organisation. But the oemof group cannot open issues, because the oemof group does not have a repository.

So we could add an organisation repository for all organisational issues. In this repository we do not need labels for bugs but for decision typs etc.. In this repo everybody could have write access who feels confident with the oemof organisation structure.

I vote for creating such a "fake" repository, to have a place for organisational issues concerning all oemof groups. I could do that.

@oemof/oemof : What do you think?

**Comment by uvchik** [comment]
...until we find a better way to organise our organisational stuff.

**Comment by beritRLI** [comment]
"So we could add an organisation repository for all organisational issues. In this repository we do not need labels for bugs but for decision types etc.."
I think that is a good idea to facilitate searching issues/having an overview

"until we find a better way to organise our organisational stuff."
what you mean by this? I think for the discussion of organisational stuff the issues are fine;
The question is where to store the organisational information; we should discuss if the documentation should be splitted into various parts or various documentations (user doc., developer doc.; then the organisational points of the oemof group would be part of the developers doc. and only some of them would belong to the users doc.)?

**Comment by uvchik** [comment]
>what you mean by this?

I did not mean something special. It is just not meant to use a repository like this. If we find something better we should use it.

**Comment by uvchik** [comment]
Okay, I created an [organisational repository](../../organisation) for test purpose. Everybody who is member of the oemof group can create [issues](../../organisation/issues), labels, milestones, assign people....

**Comment by cswh** [comment]
This issue was moved to oemof/organisation#1
