### ISSUE TITLE
Added parameter ww_incl to BDEW heat profile method

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#130]
I added the parameter ww_incl to the BDEW heat profile method to optionally exclude the warm water profile from the heat load profile. I pushed the changes to features/cleanup-demandlib and positively tested them with heat_demand_example.py. If it's alright with you @simnh, @caro-rli I will push the changes to the dev branch.

**Comment by simnh** [comment]
yes please! I will close this issue
Add information to "whats_new_v0.0.6.txt file in the docs,  please.
