### ISSUE TITLE
Fix docs at pythonhosted.org

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#132]

**Comment by uvchik** [comment]
As the documentation at [pythonhosted](http://pythonhosted.org/oemof/) is the documentation of version 0.0.4. So, for me it is more a bug than an enhancement because it is the wrong documentation for v0.0.5.

**Comment by ckaldemeyer** [comment]
@oemof/oemof : At the moment I am not a package owner of oemof@pypi (https://pypi.python.org/pypi/oemof/0.0.3)

But I think I need access to fix the documentation.

Could you add the rights for account (cordman)?

**Comment by uvchik** [comment]
Okay, Cordman (@ckaldemeyer) your're in :smile:

**Comment by ckaldemeyer** [comment]
@uvchik: Thanks!

I just created a basic html-page with a short text and a link to the documentation: http://www.pythonhosted.org/oemof/

**Comment by ckaldemeyer** [comment]
If that's not enough, just re-open the issue ;)

**Comment by uvchik** [comment]
What about the one, I already created? Is it lost?

**Comment by ckaldemeyer** [comment]
I have just uploaded a new zip-archive as explained in the PyPi backend. To me it seems as there is no direct access and documentation can only be replaced with the contents of a new archive.

So I guess it's lost. Is there something wrong with the new one?

I have also added the new template to the [wiki](https://github.com/oemof/oemof/wiki/How-to-release). If you still have your old one or want to change the new one, just replace it

**Comment by uvchik** [comment]
@ckaldemeyer : I added the previous version. If you like yours more I can revert it. Otherwise I could upload the code of this version for everybody.

**Comment by ckaldemeyer** [comment]
@uvchik: Looks better! I have corrected the HTML and added a body, header, title, ... and updated the wiki for the case that it gets lost again: https://github.com/oemof/oemof/wiki/Documentation-at-pythonhosted

**Comment by uvchik** [comment]
Cool. Thank you :smile:
