### ISSUE TITLE
solph: refactoring attributes

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#135]
Starting after proposal for new core structure. See: https://github.com/oemof/oemof/wiki/solph:-refactoring-attributes

**Comment by ckaldemeyer** [comment]
Hi everybody,

I have exported the current class hierachy into an UML diagram in yEd (using pyreverse and dottoxml) and added the ideas from the last meeting and some annotations concerning the refactoring.

Here's the first result (I only got finished with the core classes): https://gist.github.com/ckaldemeyer/516be346fe9e7d9df26f1d435a884ea5

Feel free to add your ideas which we can discuss in this issues!

Best
Cord

**Comment by ckaldemeyer** [comment]
I have updated the wiki by the attribute proposals: https://github.com/oemof/oemof/wiki/solph:-refactoring-attributes

**Comment by uvchik** [comment]
Oudated with version 0.1beta.
