### ISSUE TITLE
Internal consistency of solph 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#138]
Forgot to mention at the meeting: 

I think we should look at the code and be consistent with naming (e.g. functions names that generate constraints etc.) 

My first general question is: Do we want to keep naming inside solph generic oder specific? 

For example: 
```python 
def add_chp_relation(...):

####OR

def add_linear_output_output_relation(..):

```

My favorite is a more general naming approach. This is of course related to the attribute naming as well. (issue: #135)

**Comment by uvchik** [comment]
> My favorite is a more general naming approach. This is of course related to the attribute naming as well. 

I agree :+1:

**Comment by ckaldemeyer** [comment]
Me too :+1:

**Comment by uvchik** [comment]
No objections for half a year, so we will go on as suggested.
