### ISSUE TITLE
Write method to allow update of entity parameters in optimization model

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#141]
Make something like this possible: 

```python
sys.optimize()
sys2 = deepcopy(sys)
sys2.entities[0].shortage_costs = 100
sys2.optimize()
# new results in sys2....
```

**Comment by uvchik** [comment]
I tried it using our [storage example](../blob/dev/examples/storage_optimization/storage_invest.py). Below [line 135](../blob/dev/examples/storage_optimization/storage_invest.py#L135) I add two lines.
```python
[...]
storage = transformer.Storage(uid='sto_simple',
                              inputs=[bel],
                              outputs=[bel],
                              eta_in=1,
                              eta_out=0.8,
                              cap_loss=0.00,
                              opex_fix=35,
                              opex_var=10e10,
                              capex=1000,
                              cap_max=0,
                              cap_initial=0,
                              c_rate_in=1/6,
                              c_rate_out=1/6)
[...]
energysystem.optimize()
storage.eta_out=0  # change storage parameter
energysystem.optimize()  # optimise again with the change parameter
```
The first optimisation works and the second returns a "ZeroDivisionError: division by zero", which proves that the new eta_out is used (it shouldn't be zero).

**Comment by simnh** [comment]
yes this of course works, as energysystem.optimize() will create an new optimization model. So it is possible, but only if the whole opt-model is rebuild. I think it would be nice to only update corresponding parameters inside the optimization model.

**Comment by uvchik** [comment]
This would be nice, but to implement this I do not know enough about the inner pyomo structure. Actually you have to exchange a set of constraints. 

@simnh Do you have an idea how to do this?

**Comment by simnh** [comment]
A simple way to it could be to just only call the associated assembler method. But I think the refactoring will be a good start to think about it more generic. If it's just about cost, you can only update the objective function . I added a method on dev, that does this, this can be handy. 

now you can do:

```python
om = OptimizationModel(energysystem=energy_system)
#
energy_system.optimize(om)

pp_coal.opex_var = 340

om.update_objective()
energy_system.optimize(om)


```
We need to check how much work it is to have the max. generic solution in the future
