### ISSUE TITLE
roles and responsabilities

### ISSUE THREAD

**Issue by beritRLI** [oemof/oemof#143]
roles and responsabilities is a subject we also mentioned in the expert-interviews. In the attached google docs is a first summary for oemof.
Many of the roles can be joint but they should be formulated one by one so that it is easier to change the responsability for them or to puzzle them in different ways.

Feel free to comment.

https://docs.google.com/spreadsheets/d/1SMXyg7AzyGClsXqBxuRUm9RtbwOfirLsak6_Btq9V8A/edit?usp=sharing

**Comment by uvchik** [comment]
@beritRLI Shouldn't we move this to oemof-organisation? The milestone is outdated anyway.

**Comment by beritRLI** [comment]
yes you're right; do I have the right to move it? Is there an other way than to close it and open a new one in organisation?

**Comment by uvchik** [comment]
Just copy the text to a new issue in oemof-organisation.
