### ISSUE TITLE
The release of v0.0.6 is coming up soon

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#144]
**The deadline of the April release is April 29th.**

* Set the milestone to the next release if you are not able to close your issue until the deadline of the April release.
* Add all changes you made (fixes, enhancements,...) to the [whatsnew-file](../tree/dev/doc/whatsnew/v0-0-6.rst) and commit them. 
* Merge everything you want to release into the dev branch until the deadline. Later merges/commits will be ignored. Close the related issue.

*There should not be any open issues related to the April release milestone on the morning of the 29th!*

**Comment by birgits** [comment]
@oemof/oemof Only one more day :) Everybody please check all issues that are assigned to you and forward them to the next release if you are not able to fix them until tomorrow.

**Comment by birgits** [comment]
It's done, version 0.0.6 is up and running :) Thanks everybody for your help, especially @uvchik!

**Comment by ckaldemeyer** [comment]
@birgits: Thanks! :-)
