### ISSUE TITLE
Results output of the storage example changed and seem to be wrong

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#146]
In the storage_invest example (on dev branch) I have printed some results values like the sum of the generated energy from the gas power plant or annual and maximum demand with:

```python
pp_gas = myplot.slice_unstacked(bus_uid="bel", bus_type='el',
                                      type='input', obj_uid='pp_gas',
                                      date_from="2012-01-01 00:00:00",
                                      date_to="2012-12-31 23:00:00")

demand = myplot.slice_unstacked(bus_uid="bel", bus_type='el',
                                      type='output', obj_uid='demand',
                                      date_from="2012-01-01 00:00:00",
                                      date_to="2012-12-31 23:00:00")

print('pp_gas_sum: ', pp_gas.sum())
print('demand_sum: ', demand.sum())
print('demand_max: ', demand.max())
```

and get different results than there was in v0.0.3

It has been

```
pp_gas_sum:  val    112750260
dtype: float64
demand_sum:  val    2.255000e+09
dtype: float64
demand_max:  val    368693.14441
dtype: float64
```

Now it's

```
pp_gas_sum:  val    3.032659e+10
dtype: float64
demand_sum:  val    3.032659e+10
dtype: float64
demand_max:  val    10969817.87604
dtype: float64
```

@oemof/oemof Does anyone has any idea how this comes?

**Comment by simnh** [comment]
seems that their are other values for the demand timeseries. that might cause highte production etc.

**Comment by caro-rli** [comment]
No, time series values are the same in both cases, and also the energy system. I just checked this. I also came up with this problem with my personal scenario app (where I haven't changed anything concerning the input).

Differences in the storage invest app don't occure before dataframe creation, plottings and so on...
So the error could be there in the processing of the results, or even before..

I'm going to try to check the results object.

**Comment by caro-rli** [comment]
As far as I found out until now, the difference in the results first occur with d4710d9fb517e53389326887e3d737697b337bf5 and with that they might come from the branch 'features/slack_components'

**Comment by uvchik** [comment]
The plots look pretty much the same. There is an extra line for the excess in the actual version. I had to rename the components because the order is still alphabetic. I really should change that :blush:. 

Version 0.0.3

![figure_a](https://cloud.githubusercontent.com/assets/4760584/14826372/db9a267e-0bdd-11e6-9a7b-2786906d4b90.png)


Actual dev-branch

![figure_d](https://cloud.githubusercontent.com/assets/4760584/14826546/a44184aa-0bde-11e6-814c-e491d0f4718f.png)

**Comment by uvchik** [comment]
Same here. the demand is never above 400.000. And this is read from the DataFrame. 

The inputs are the same. Maybe there is something wrong in the way you read the values.
```
# demand in the actual dev-branch before(!) optimisation:
>>> print("sum:", demand.val.sum())
>>> print("max:", demand.val.max())
sum: 2255000000.0
max: 368693.14441
```

Version 0.0.3

![figure_f](https://cloud.githubusercontent.com/assets/4760584/14826939/60d5a05a-0be0-11e6-9bc8-24eafbf35636.png)

Actual dev-branch

![figure_g](https://cloud.githubusercontent.com/assets/4760584/14827190/765b4b04-0be1-11e6-9a15-395b3926ee19.png)

**Comment by caro-rli** [comment]
>Maybe there is something wrong in the way you read the values.

This seems to be the key. Using:

```python
es_df = tpd.ResultsDataFrame(energy_system=energysystem)

idx = pd.IndexSlice

pp_gas = es_df.loc[idx['bel',
                                    'el',
                                    'input',
                                    'pp_gas',
                                    slice(
                                        pd.Timestamp("2012-01-01 00:00:00"),
                                        pd.Timestamp("2012-12-31 23:00:00"))], :]

demand = es_df.loc[idx['bel',
                                    'el',
                                    'output',
                                    'demand',
                                    slice(
                                        pd.Timestamp("2012-01-01 00:00:00"),
                                        pd.Timestamp("2012-12-31 23:00:00"))], :]

print('pp_gas_sum: ', pp_gas.sum())
print('demand_sum: ', demand.sum())
print('demand_max: ', demand.max())
```

I get the results I want... but why?

For me

```python
pp_gas = myplot.slice_unstacked(bus_uid="bel", bus_type='el',
                                      type='input', obj_uid='pp_gas',
                                      date_from="2012-01-01 00:00:00",
                                      date_to="2012-12-31 23:00:00")
```

is the same logic. Intuitionally I have used it just like that.

**Comment by caro-rli** [comment]
Also, though different topic, somehow my plots look different in the current dev-branch:

![outputs_dev](https://cloud.githubusercontent.com/assets/8330132/14852264/8f78c7ca-0c85-11e6-96fa-f1f31fa60189.png)

![stack_plot_dev](https://cloud.githubusercontent.com/assets/8330132/14852269/97046f26-0c85-11e6-8437-3eade8a8076f.png)

**Comment by caro-rli** [comment]
Ok.. got it. If I use the method "slice_by" instead of "slice_unstacked" I get what I want :smile:

**Comment by uvchik** [comment]
The plots are the same but you have a different component order. That leads to different colours in the first plot and a different stack in the second plot. So the same results look different. I renamed the components to get the same order as in v0.0.3. To make it possible to change the order without renaming components I created PR #148.

@caro-rli : Are the results okay now?

We really should create a meta example that starts the examples and check the results.

```
storage_example:
    run: okay
    results: okay

another_example:
    run: okay
    results: failed

another_example2:
    run: failed
    results: empty

See logfile for more information.
```
But this is a new issue -> #149

**Comment by ckaldemeyer** [comment]
> Ok.. got it. If I use the method "slice_by" instead of "slice_unstacked" I get what I want :smile:

You could have a look at the dataframe objects respectively their structure. "slice_unstacked" should only unstack the index level "obj_uid". If this is confusing it might make sense to change the naming. 

What do you think?

Concerning the plotting: as @uvchik stated it is naming and matplotlib-related.

Concerning the tests: :+1: I'll continue in the right issue..

**Comment by caro-rli** [comment]
> I renamed the components

Finally got what you mean :smile:

> Are the results okay now?

Results are ok now. Thanks!

> "slice_unstacked" should only unstack the index level "obj_uid". If this is confusing it might make sense to change the naming.

I don't get this, but this must not mean anything :smile:
I think I will come up with this again, when it causes me trouble. So I'm closing here now.
