### ISSUE TITLE
feedback from user meeting 

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#15]
to be taken into account for next user meeting:
* split sessions for total newbies and more advanced users
* introduction to oemof - talk about what is possible so people get a quick overview if it is a good tool to use
* tutorial where to find the documentation and how to work with it

other:
* establish forum for users
* youtube video for installation of oemof for example (use the openmod channel, janet nagel will do it)

**Comment by busiing** [comment]
Moved to the Wikipage of[ Meeting May 2017](https://github.com/oemof/oemof/wiki/Meeting-May-2017)
