### ISSUE TITLE
Fix oemof for use of  latest pyomo version 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#150]
Atm oemof can not handle the latest pyomo version. This issue should fix this. (see: #147)

**Comment by gnn** [comment]
Not an oemof problem. Try doing `import pyomo.environ` in the python console after a clean install of the newest pyomo version. That should reproduce the error without oemof being involved. So all we can do is not depend on that particular pyomo version.

**Comment by uvchik** [comment]
We could keep this issue open as a reminder and check the next pyomo version before the next oemof release.

**Comment by simnh** [comment]
@gnn It might be a oemof problem because - as I already mentioned - we are using some internal methods, attributes etc of pyomo. As this is not intended by pyomo developers i guess, we should at least check if its related to these specific code pieces in oemof....

**Comment by ckaldemeyer** [comment]
According to the Pyomo-forum, there has been a new release now:

> A number of users have had issues with the latest release (4.3.11377), which we narrowed down to an issue with the wheel distribution file.

> I've generated a new Pyomo release, and the wheel file looks better.  Let me know if you have any problems installing Pyomo!

> --Bill

We should check if this fixes the error!

**Comment by uvchik** [comment]
Everything works fine for me using pyomo 4.3.11388. To get the newest version just type (linux):

```
pip3 install -e path/to/root/of/oemof --upgrade
```

I guess we keep the exclusion of version 4.3.11377 in the setup.py for a while.
