### ISSUE TITLE
Investment option for sinks possible?

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#151]
I set the investment option for a sink to _True_ with
```python
sink.Simple.optimization_options.update({'investment': True})
```
in my example app, and get the following error:

```
Traceback (most recent call last):
  File "/home/caro/rlihome/Git/eos/example/examples_households/NEW_CONCEPT_example_households_seperate_grid_10hh_11_to_20_COSTOPT_feedinlim.py", line 543, in <module>
    energysystem.optimize()
  File "/home/caro/rlihome/Git/oemof/oemof/core/energy_system.py", line 238, in optimize
    om = OM(energysystem=self)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/optimization_model.py", line 114, in __init__
    self.objective_assembler(objective_options=self.objective_options)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/optimization_model.py", line 210, in objective_assembler
    revenue_objects=revenue_objects)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/predefined_objectives.py", line 78, in minimize_cost
    expr += objexpr.add_opex_fix(self, block, ref=ref)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/objective_expressions.py", line 134, in add_opex_fix
    opex_fix[e] for e in uids_inv)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/objective_expressions.py", line 134, in <genexpr>
    opex_fix[e] for e in uids_inv)
AttributeError: 'SimpleBlock' object has no attribute 'add_out'
```

Can anyone give me a hint, why I get this error? Where is the add_out variable created?

Optimizing a sink maybe makes no sense at first sight, so this might be not implemented...

**Comment by simnh** [comment]
It is not possible for sinks at the moment. As you might notice for `add_out` it's only possible for components for that have outputs...

**Comment by caro-rli** [comment]
Seems also not to work with a transport object. I added the following lines in our storage invest example:

```python
bel_2 = Bus(uid="bel_2",
            type="el",
            excess=True)

transport = transport.Simple(uid='transport', inputs=[bel], outputs=[bel_2],
                             eta=np.ones(8760)*1,
                             out_max=np.zeros(8760))
```

No problem until here.. but adding this

```python
transport.Simple.optimization_options.update({'investment': True})
```

I run into trouble and get the following error message:

```
Traceback (most recent call last):
  File "/home/caro/rlihome/Git/oemof/examples/storage_optimization/storage_invest_two_regions.py", line 169, in <module>
    energysystem.optimize()
  File "/home/caro/rlihome/Git/oemof/oemof/core/energy_system.py", line 238, in optimize
    om = OM(energysystem=self)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/optimization_model.py", line 99, in __init__
    self.build_component_constraints(cbt)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/optimization_model.py", line 132, in build_component_constraints
    assembler.registry[cls](e=None, om=self, block=block)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/optimization_model.py", line 808, in _
    var.set_bounds(om, block, side="output")
  File "/home/caro/rlihome/Git/oemof/oemof/solph/variables.py", line 171, in set_bounds
    block.add_out[e].setub(add_out_limit[e])
AttributeError: 'SimpleBlock' object has no attribute 'add_out'
```


> Where is the add_out variable created?

Also still not understand this.. :-(
The place where this variable might be created seems to be only for investment options = False which confuses me even more.
https://github.com/oemof/oemof/blob/dev/oemof/solph/optimization_model.py#L182

Can someone easily explain this to me if it takes not too much time?

**Comment by simnh** [comment]
The last thing is ok as it's get() and the default if nothing is found is Flase, if the option is set the variable should be created. So this shoudl actually work...

**Comment by simnh** [comment]
But for transformer it does not work because this is not implemented as well. But it could be done easily. 
The problem here is the following: 

* Every class has a associated "assembler method" in the OptimizationModel() class
they are located below [Line 451](https://github.com/oemof/oemof/blob/dev/oemof/solph/optimization_model.py#L451)
* Theses methods are called when instantiating the Opt- Model. 
* Most "assembler_methods" only do some configuration stuff and then call the default_assembler [see line 148]((https://github.com/oemof/oemof/blob/dev/oemof/solph/optimization_model.py#L148) to actually build constraints, add variables etc.
* The transformer.Simple "assembler method" does not but there the constraints are directly added and the default_assembler method is not called. And thats the problem, because the creation of add_out is done inside the default assembler method. 

So what you need to do is basically make the assembler_method of transports.Simple look like the transformers.Simple (or the others where default assembler methods are called) 
Then it should work.

**Comment by simnh** [comment]
Actually having done this, you could as well adapt the sinks.Simple assembler method to generate a add_in variable. Then insert a constraint in linear_constraints.py that is similar to the add_out constraint but only for inputs. and then add the costs associated with add_input in the objective function. But maybe it s better to create a issue for a feature and a pull request, where we can discuss how to do it. And I think it would make more sense after the refactoring. But it should be possible with not too much effort...

**Comment by caro-rli** [comment]
> So what you need to do is basically make the assembler_method of transports.Simple look like the transformers.Simple (or the others where default assembler methods are called)
Then it should work. Hope this helps

Thanks a lot! This helps. I'm going to adapt this.

> Actually having done this, you could as well adapt the sinks.Simple assembler method to generate a add_in variable.

Going to try this, too. But this has more the character of a new feature. Will see if I need it urgently or if it can wait till the finishing of the refactoring.

> The last thing is ok as it's get() and the default if nothing is found is Flase, if the option is set the variable should be created.

ah, ok, I see... so it's exactly the opposite than I thought :smile:

**Comment by uvchik** [comment]
@caro-rli : Is this solved with the re-factored solph?

**Comment by simnh** [comment]
That should work, as the investment object is appended to the flow.

**Comment by uvchik** [comment]
@caro-rli : 

> Seems also not to work with a transport object.

For a bidirectional transport it is still a problem because so far it is not possible to connect the invest capacity for both directions. But this should be a new issue. The title of this issue is different.

**Comment by caro-rli** [comment]
>> Seems also not to work with a transport object.

> For a bidirectional transport it is still a problem

I tried this then as a workaround. So I think all tasks in this issue are obsolete now.
