### ISSUE TITLE
Webconference for V0.1 roadmap

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#156]

**Comment by birgits** [comment]
We decided to have a web conference to finalize the roadmap for the release of oemof version 0.1.0. @oemof/oemof please fill out the [doodle](http://doodle.com/poll/r98pugziegys5z9w) as soon as possible and decide together with your team on a realistic timetable when you will have finished the [necessary steps for the release](https://github.com/oemof/oemof/wiki/Release-Roadmap).

**Comment by uvchik** [comment]
:+1:

We definitely need somebody from the @oemof/oemof-core team.

**Comment by uvchik** [comment]
I think we can close it in favour of #207 and #216.
