### ISSUE TITLE
Class refactoring

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#162]
For V1.0 we restructure the classes into core and solph (external library) classes.This process also includes a new naming concept for classes and attributes.

Results of the last oemof developer days can be found here:

* New class structure (sketch in yEd): https://gist.github.com/ckaldemeyer/516be346fe9e7d9df26f1d435a884ea5
* New attribute names: https://github.com/oemof/oemof/wiki/solph:-refactoring-attributes

**Comment by ckaldemeyer** [comment]
I am human again and have edited the attibutes wiki page. Everything below "CHP" has been left untouched since we wait for the refactoring first

**Comment by uvchik** [comment]
Outdated. The new structure is already implemented.
