### ISSUE TITLE
documentation: add information about time series data format

### ISSUE THREAD

**Issue by Konsebast** [oemof/oemof#165]
I struggled some time with the input format of the time series until I found out, that the .csv file needs to be filled with relative values and not absolute value. Maybe it is possible to make this more clear in the documentation.
I am referring to the input data of fixed and dispath sources.

**Comment by uvchik** [comment]
Good point. We are cleaning up solph for version 0.1 so I will not change it directly but keep it in mind for version 0.1.

**Comment by uvchik** [comment]
All values are relative to the nominal_value (or invest value) in the re-factored version. I hope this is now quite clear in the documentation.
