### ISSUE TITLE
Building component constraints with new component classes inherited from oemof components

### ISSUE THREAD

**Issue by Jazzpilz** [oemof/oemof#169]
I am trying to inherit from an oemof component class, let's say "Bus", in order to add further functionality to this class (let's name this class "Bus_2"). When calling optimize() of the EnergySystem class with an instance of "Bus_2" as component of the latter, I get an KeyError. This is due to that assembler.registry holds no matching key to this new class.

Can you give me a good hint on how to best tackle this issue? 

Here is some explanatory code: 
```
from oemof.core import energy_system as es
from oemof.core.network.entities import Bus as oemof_bus

class Bus_2(oemof_bus):
    def __init__(self, **kwargs):
        # Some extra functionality
        super().__init__(**kwargs)
        # Some extra functionality

sys1 = es.EnergySystem(...)
bel1 = Bus_2(uid="bel1", type="el")
sys1.optimize()
```

The traceback:
```
Traceback (most recent call last):
  File "..../main.py", line 65, in <module>
    h.optimize()
  File "..../energy_system.py", line 238, in optimize
    om = OM(energysystem=self)
  File "..../anaconda3/lib/python3.5/site-packages/oemof/solph/optimization_model.py", line 107, in __init__
    self.build_bus_constraints(bbt)
  File "..../anaconda3/lib/python3.5/site-packages/oemof/solph/optimization_model.py", line 146, in build_bus_constraints
    assembler.registry[bls](e=None, om=self, block=block)
KeyError: <class '__main__.Bus_2'>
```

Somehow I need to make assembler.registry aware of the new component(s), but I so far lack the deeper understanding on what is going on under the hood in the Solph package.

**Comment by simnh** [comment]
You need to : 

- write your on constraints and add the to e.g. linear_constraints.py 
- create a assembler method for the new component/bus were you can add the created constraints. 

sorry for the short answer, we are refactoring solph atm and I think support development for the old version (i.e. except usage) is not possible. 
That's why I will a add wontfix for this issue. 

You are welcome to join the first_refactoring/solph/dev branch and created your apps based on this new structure. Then we will be able to support you in extension of the original functionalities" 

We try to release v. 0.1.0beta end of this month with this new structure.

**Comment by simnh** [comment]
I'll leave this open if somebody else can give support. Please close this once you decide how to proceed...

**Comment by Jazzpilz** [comment]
Thank you for the hints Simon. 

I guess it could be nice to consider for the new Solph the
possibility to inherit from basic component classes in order to
customize them according to the needs of individual projects.

So far as I see it you have to adapt classes within oemof in order to do
that, respectively you need to inherit from an basic oemof component
within an oemof package. Otherwise there will be ImportErrors.

**Comment by Jazzpilz** [comment]
Thank you Simon for the prompt support. 

So far I can not see an oemof-dev branch in the repository, but I will
join as soon as it is there. Of course it is best to build upon the new
structure of Solph you want to introduce.

**Comment by uvchik** [comment]
Use this branch: `remotes/origin/first-refactoring/solph/dev`.

The new [storage_invest example](../blob/first-refactoring/solph/dev/examples/storage_optimization/storage_invest.py) is a good start to understand how the re-factored Solph works.

**Comment by Jazzpilz** [comment]
Thanks a lot for the hint!

**Comment by Jazzpilz** [comment]
One more question:

While trying to add custom components and custom constraints
respectively to oemof solph (optimization_model.py) I saw that as you
are testing for oemof components, custom objects will be ignored. Will
this be also the case for the refactored solph?

An example out of optimization_model.py (Line 273):
---------------------------------------
        for entity in self.entities:
            if (isinstance(entity, cp.Transformer) or
                    isinstance(entity, cp.Transport) or
                    isinstance(entity, cp.Source) or
                    isinstance(entity, ShortageSlack)):
---------------------------------------

Would be great to know, otherwise I need to write a customized
optimization_model.py

Thank you.

**Comment by simnh** [comment]
This is one of the drawbacks of the current implementation. With the refactored version you can 'tell' 
solph about new constraints, variables and objective expressions. 
For  the results functionality this will be a little hard. As long as you just have multilple flows, these will be added automatically. 
For new variables etc. we do not provide a extension functionality. But you can easily access e.g. variables in the new structure like: 

`om.YourNewTransformer.your_variable[index2, index2].value`

The storage capacity can be accessed (indexed by storage objects and timesteps): 

`om.Storage.capacity[n,t]`

**Comment by Jazzpilz** [comment]
Thank you for the explanation, I think I get your point.

I will check out the new solph version as soon as it is there.

**Comment by uvchik** [comment]
I just updated the release branch. You could checkout the `release/v0.1beta` branch and try the examples. The examples are in the .../oemof/examples/solph directory and at least the "storage_optimisation" and the "simple_least_cost" example should work. 

To install the git version just use ```pip3 install -e /path/to/your/git/oemof````.
