### ISSUE TITLE
Usage of `get` without supplying a default value

### ISSUE THREAD

**Issue by gnn** [oemof/oemof#171]
There's possibly unwanted behaviour in [`oemof.solph.network`](https://github.com/oemof/oemof/blob/3d3ba2aa9ede7baee5c4307b2172a2085e9ccfa7/oemof/solph/network.py#L112) introduced in commit [f68b26b](https://github.com/oemof/oemof/blob/f68b26b3c75cf1ba7ce50003f77388912c07dc1a/oemof/solph/network.py#L106). The problem is that `a_dictionary.get(a_key)` returns `None` if `a_key` is not found and since the return value is used immediately as the target of `.items()` one gets a weird attribute error if no `conversion_factors` are supplied when a `LinearTransformer` is constructed. We should either use `a_dictionary[a_key]`, to error out early with a more informative message, or `a_dictionary.get(a_key, a_sensible_default)`, to carry on and error out when the `conversion_factors` are used without being set.
I'm opening this bug because @ckaldemeyer and me [stumbled over this](https://github.com/oemof/oemof/blob/195133ca3450395b623ca1f6c0096093269f6808/oemof/solph/options.py#L178).
I also already pushed a [fix](https://github.com/oemof/oemof/commit/195133ca3450395b623ca1f6c0096093269f6808), which carries on so that conversion factors can be set later at a later stage before they are used. Your mission @uvchik , should you decide to accept it, is to check whether you're OK with that fix.

**Comment by uvchik** [comment]
The changes in commit f68b26b were just changes to satisfy pylint. I added a newline to fix the "continuation line under-indented for visual indent" warning". I think I did not change the syntax. If I did change anything by accident, feel free to fix it. But your change seems to be something different. Here are the changes I did:

```diff
-        self.conversion_factors = {k: Sequence(v)
-            for k,v in kwargs.get('conversion_factors').items()}
+        self.conversion_factors = {
+            k: Sequence(v)
+            for k, v in kwargs.get('conversion_factors').items()}
```

If everything works fine I am okay with your changes.

**Comment by uvchik** [comment]
This fix is already part of the solph refactoring branch.

**Comment by gnn** [comment]
Yeah. For the sake of completeness: the actual change introducing the error was [this line](https://github.com/oemof/oemof/blob/b9bd24c24411a5beeb532ed39d3b61dd77e7786e/oemof/solph/network.py#L101) in commit b9bd24c24411a5beeb532ed39d3b61dd77e7786e.
