### ISSUE TITLE
Storage invest bug fixed

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#172]
Commit 1aadf70c0 fixes a bug for investment storages in solph.

Users of version 0.0.7, who uses the storage with the investment option should be aware of this bug. 

@oemof/oemof: Maybe anybody of these users could release the fixed version. There are already three fixes since the last release.

**Comment by uvchik** [comment]
Done (https://github.com/oemof/oemof/releases/tag/v0.0.8) but not uploaded to pypi. Feel free to do this.

**Comment by ckaldemeyer** [comment]
I have added a post to the blog as well to show some activity (even if I am unactive in terms of oemof atm): https://oemof.wordpress.com/

**Comment by uvchik** [comment]
I just included the v0.1-beta link to the post.

**Comment by ckaldemeyer** [comment]
:+1:
