### ISSUE TITLE
update your oemof examples

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#174]
For the refactoring release we will need to update all examples. Please make sure that examples you want to keep do work with the refactored solph and core version. Otherwise these examples will be dropped with the next release. 

Plese do it on firstrefactoring/solph/dev branch (#168)

**Comment by uvchik** [comment]
Now there is still a `multiple_energysystems.py` example. Everything else is removed or adapted.

Shall the `nodes_from_csv` example also be a part of the example test?

**Comment by ckaldemeyer** [comment]
I will move the "renpass-gis" development example into the ZNES repository and write a documentation, etc. for it so that all RLI-people and interested others can use/adapt it.

As soons as our projects is finished...

**Comment by ckaldemeyer** [comment]
Currently the example is in the folder "nodes_from_csv" an runs with the csv builder

**Comment by uvchik** [comment]
> Currently the example is in the folder "nodes_from_csv" an runs with the csv builder

I know but so far it is not a part of the tests. Shall it be a part of the example test? Than you should write a block in the example_test file. By the way, you should create some test otherwise sombody could break it and nobody will notice it until you use it the next time.

**Comment by ckaldemeyer** [comment]
>> Currently the example is in the folder "nodes_from_csv" an runs with the csv builder

> I know but so far it is not a part of the tests. Shall it be a part of the example test? Than you should write a block in the example_test file.

No, I would remove it from oemof and maintain it in the ZNES repository.

> By the way, you should create some test otherwise sombody could break it and nobody will notice it until you use it the next time.

Fair enough, but I don't have the time right now. Would be a workpackage for September/October.

But as it is quite central someone should notice if it doesn't work and for the first step I will leave something like a minimal-validation

**Comment by uvchik** [comment]
I think the easiest (least time) variant is to keep a simple example in the example section, create a dictionary with some expected results and create a check-block in the example test-file. See the other two examples to see how to do it.

**Comment by ckaldemeyer** [comment]
> I think the easiest (least time) variant is to keep a simple example in the example section, create a dictionary with some expected results and create a check-block in the example test-file. See the other two examples to see how to do it.

Sounds reasonable. Thanks for the hint

**Comment by uvchik** [comment]
@simnh What about the `multiple_energysystems.py` in the examples/core folder. This is the last example that does not work. Could you repair it or remove it. Is it a core or a solph example?

**Comment by uvchik** [comment]
@simnh I removed the example with commit 5fe4af97538. You will find it there, if you still need it.
