### ISSUE TITLE
New solph: storage_invest does not run with gurobi

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#181]
Is this a known issue?
I'm on first-refactoring/solph/dev and it just doesn't run trough. It stops at "Solve the optimization problem".

**Comment by uvchik** [comment]
I cannot reproduce the error. Did you try another solver (e.g. cbc) to exclude, that it is caused by gurobi? Did you check the gurobi license? 
Is there any message beyond the logging message?

By the way. In future you should use the release branch but at the moment they are pretty much the same.

**Comment by caro-rli** [comment]
Yes, cbc and glpk work. Ok, I'll try this again next week.. my computer is anyway full of worms today :-( might be the heat.

**Comment by caro-rli** [comment]
This was a license problem. My license expired on that day.
