### ISSUE TITLE
Re-factoring of the documentation

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#183]
In my honest opinion the actual documentation is not very clear for new users/developers and secondly it has to be adapted to the new structure.

A proposal based on the actual documentation can be found in the wiki:

[Proposal-for-a-new-documention-structure](../wiki/Proposal-for-a-new-documention-structure)

I definitely need a feedback what you think about the new structure and then I need help writing/adapting the text.

**Comment by uvchik** [comment]
@oemof/oemof : I need a feedback and help. You do not have to deeply understand the code to help with the documentation!

**Comment by simnh** [comment]
I like your suggestion! Only thing I propose is to remove the  the 'installing the developer version' from
 the section 'Using oemof'! 
Thanks for the start! Do you just want to create the new structure to the release/v.01.beta branch? 

Then we could start copying stuff that is still good and insert new things.

**Comment by uvchik** [comment]
> Only thing I propose is to remove the the 'installing the developer version' from
> the section 'Using oemof'! 

Of course! This was a mistake!

> Do you just want to create the new structure to the release/v.01.beta branch?
> Then we could start copying stuff that is still good and insert new things.

Yes. Even though the release date of the beta version is already in the past I would release it without a new documentation structure. Anyhow, everybody who wants to test the re-factored oemof can use the release branch.

**Comment by uvchik** [comment]
I think the structure is better now. I think we should revise the `about oemof` section and fill the description of the libraries.

@oemof/oemof We really need some help. If everybody would spend an hour or two a week the documentation will improve quickly.

**Comment by uvchik** [comment]
@oemof/oemof The actual documentation can be found here: http://oemof.readthedocs.io/en/release-v0.1

**Comment by ckaldemeyer** [comment]
I think the complete Flow-concept has to be integrated here: http://oemof.readthedocs.io/en/release-v0.1/about_oemof.html

**Comment by uvchik** [comment]
For me the flow concept should be part of the 'network' section. In my opinion 'About oemof' should contain infos about the oemof group, the basic idea (philosophy) and the structure of the whole project.

**Comment by ckaldemeyer** [comment]
Oh, I missed that section. I agree as this would be a cleaner solution.

**Comment by simnh** [comment]
What is still missing? The release version is already tagged...

**Comment by uvchik** [comment]
:exclamation:  @oemof/oemof We really do need help to publish the documentation :exclamation:

@oemof/oemof Everybody could read the documentation and correct typos or incomprehensible parts. Do like the new structure? Do you miss anything in the README as it is the first entry to oemof?

@caro-rli @ckaldemeyer @birgits The section [The idea of an open framework](http://oemof.readthedocs.io/en/release-v0.1/about_oemof.html#the-idea-of-an-open-framework) needs to be revised. The picture seems deprecated to me and the text could be little more precise in explaining APP and LIB. There are different LIBs everybody can add a LIB and one can write an APP and use the LIBs... . Or what do you think is the main point of this section???? [Look here for ideas of a new graph](https://github.com/simnh/addressing_challenges_oemof/issues/3#issue-165310025).

@simnh What do you think about the structure of the [solph documentation](http://oemof.readthedocs.io/en/release-v0.1/oemof_solph.html). Could give feed-back, correct typos, add content. What about the [mathematic notation](http://oemof.readthedocs.io/en/release-v0.1/oemof_solph.html#mathematical-notation-for-solph)? How do you want to use it. Or is it obsolete in favour to the docstrings. Or should we give an overview where to find the equations in the docstrings?

@gnn @cswh What about the [oemof network documentation](http://oemof.readthedocs.io/en/release-v0.1/oemof_network.html)? I copied some old stuff into it. Can you remove it, revise it or do what ever to makle this section suitable for v0.1! What about the network section in [Using oemof](http://oemof.readthedocs.io/en/release-v0.1/using_oemof.html#oemof-network). Is it okay like this?

**Comment by uvchik** [comment]
I added a lot of content to the documentation but I did not reread it. Pleeeeaaaase proofread it.

**Comment by uvchik** [comment]
@cswh, @gnn Does it makes sense to keep the network section as nobody can do anything with it. By now it is only a base for solph and for this we can describe how to use it with solph and remove the network part from the documentation.

What do you think?

**Comment by simnh** [comment]
I think we should keep it and just mention a few words. With oemof core, it's also possible to create a system (graph), group the nodes with grouping etc. So, a simple example and a short description cloud help understanding all depend moduls (e.g. solph). 
Remains: Who does it, I know @cswh if 'offline' until Feb. 2016. So Me or @gnn  need to do it. Maybe I'll be able to write some stuff this week....

**Comment by ckaldemeyer** [comment]
>> I added a lot of content to the documentation but I did not reread it. Pleeeeaaaase proofread it.
 I'll have a look at it this week

**Comment by ckaldemeyer** [comment]
I have opened a pull request for my changes: https://github.com/oemof/oemof/pull/224

**Comment by ckaldemeyer** [comment]
One terminilogy question as I just stumpled upon it in the oemof-article:
Are we talking about libraries or packages (containing modules) when we talk about the parts an app is based on?

In other words:
Are we generic (platform-independent) or python specific?

From my point of view we could use the generic formulation as it leaves us more degrees of freedom.

**Comment by uvchik** [comment]
If we talk about code issues, we should use package, subpackage, module,...

As we do have a demandlib, feedinlib etc. we should talk about libraries :smirk: But I do not care as long as we think, that readers will understand what we are talking about.

**Comment by ckaldemeyer** [comment]
:+1: I'll adapt the paper then where it's suitable and only speak about packages when python packages are meant.

**Comment by simnh** [comment]
I think inside the paper (and outside everything code related) we should keep it python unspecific. 

But it should be possible to differentiate between libraries of type  'solph'  and of type 'feedinlib'. Maybe the layer structure is good enough for this..?

**Comment by ckaldemeyer** [comment]
I think inside the paper (and outside everything code related) we should keep it python unspecific.

:+1: 

But it should be possible to differentiate between libraries of type 'solph' and of type 'feedinlib'. Maybe the layer structure is good enough for this..?

In the first version of the documentation we once started with "packages" and "modules" even of everything wasn't aligned straight to the standard python definition of these terms. I think we need an extra "unspecific term" apart from the python terminology for this. Otherwise potential new users with python knowledge might become confused..

**Comment by uvchik** [comment]
Thanks to @ckaldemeyer and @simnh for your help. We will release now.

@oemof/oemof Would still be nice if you take a look at the documentation and fix typos or add content for the next release.
