### ISSUE TITLE
Fix regression test

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#185]
@gnn : According to  your TODO in the code, please adapt or remove the tests.

**Comment by gnn** [comment]
Ouch. No idea where this is exactly, but I'll check it out for the next release.

**Comment by uvchik** [comment]
https://github.com/oemof/oemof/blob/dev/tests/regression_tests.py#L21

**Comment by gnn** [comment]
Actually stumbled upon these while checking tests for #269. Next release should be possible.

**Comment by gnn** [comment]
Started working on this with on [fixes/185](https://github.com/oemof/oemof/tree/fixes/185). Shouldn't be too hard and easily doable for v0.2.0

**Comment by gnn** [comment]
Still easy to do, and I'll do it as fast as I can, but might still be a week or so. Doesn't really change the API, so in order to not block `0.2.0`, I'm moving it to `0.2.1`.

**Comment by jnnr** [comment]
May this be in for the coming release v0.2.1?

**Comment by uvchik** [comment]
This is a really funny issue. 

@gnn Please remove the tests. You will never fix them :smirk:  They are not important, they were left over from v0.0.7 (2 years old)!

**Comment by p-snft** [comment]
I reject to postpone this issue further. If it is not resolved before the 0.3.0 release, I will remove the tests and close the issues.

**Comment by uvchik** [comment]
I removed the test with commit 98f9d682c917.

@gnn If you want to fix the test you can revert the commit and fix it.
