### ISSUE TITLE
Missing core module in oemof

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#189]
I'm using oemof 0.0.8.dev0 and installed it via pip3 from the sources (used the flag `-e`). Since some time (I cannot exactly say what happend in between) I have an import error related to oemof.

When I try to do `import oemof.core` I get an the error 

> AttributeError: 'module' object has no attribute 'core'

My guess is that oemof.db somehow overrides oemof in the pip index on my computer (this is very vague). How do I assume this?

`import oemof` followed by `oemof.__path__` yields 

> ['.../git-repos/oemof.db/oemof']

whereas `import oemof.db` followed by `oemof.db.__path__` yields 

> ['.../git-repos/oemof.db/oemof/db']

Does someone has any clue on that?

**Comment by uvchik** [comment]
Reinstall oemof and oemof.db and make sure there is nothing left of an old installation without  `-e`. Check if there is something like `/usr/local/lib/python3.4/dist-packages/oemof`.

**Comment by gplssm** [comment]
Thanks for your input!

I tried it like this: try to remove it by pip3 (which failed), then delete the eggs inside the repo and finally removed egg-links from `/usr/local/lib/python3.4/dist-packages/`.
Afterwards re-install oemof+oemof.db with flag `-e`. Sadly, no luck :( Still exactly the same issue...

If there are more suggestions, I'm open for them.

**Comment by uvchik** [comment]
By the way, oemof.core will not exist since version 0.1.

**Comment by gplssm** [comment]
I guess I figured out the actual problem: oemof.db was appended to the PYTHONPATH and thus overwriting oemof, due to the same namespace. Removing oemof.db from PYTHONPATH solved the issue.

Thanks for support!
