### ISSUE TITLE
Use dev-branch (and soon the master) for the new version

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#193]
@oemof/oemof I just marked the actual state of the "old" oemof as version 0.0.8 and the actual state of the new oemof as 0.1beta.

I would like to use the `dev` branch for the new developer version very soon and the `master` branch since v0.1 is out.

The question would be how to call the branch where possible bug fixes for the "old" version can be pushed (v0.0.9, v0.0.10 etc.).

I think the new oemof is already used by most of the developer and we should change the structure to make that obvious for new developers.

**Comment by ckaldemeyer** [comment]
What about dev-v.0.0.X or something similar?

**Comment by ckaldemeyer** [comment]
Btw: Thanks for all your effort on the release!!!

**Comment by uvchik** [comment]
I like the idea of @gplssm mentioned [here](https://github.com/oemof/oemof/pull/213#issuecomment-254585707) for the old version (`deprecated/dev`, `deprecated/master`, `deprecated/something`).

I will make sure that these branches exist until I will merge the v0.1 to `master` and `dev'.

**Comment by uvchik** [comment]
If you want to use the old API you should add changes to the `deprecated/dev` and `deprecated/master` branch.

The new API will now be developed using `dev` and `master` again.
