### ISSUE TITLE
Variable domain specifications

### ISSUE THREAD

**Issue by Jazzpilz** [oemof/oemof#195]
I would like to be able to specify the domain for certain variables on my own. For example, I would like to specify the sizing of a flow to be positive integer based. I know that for a Storage component to be restricted to e.g. positive integers, I simply need to create a copy of the Storage class in blocks.py. For a flow I can see no way at the moment to do this, hence I am interested on whether and if so, when a domain specification for flows, for example, will be available?

Thank you for the help and congratulations for the good work on this nice library so far.

**Comment by simnh** [comment]
Hi there, 

You are right, that it is not as 'easy' for flows as it is for a say, storage object. We can try to add an interface for such specific modelling purposes, actually, it should be straightforward. But I think that this might still take a while (maybe 1-2 month)? I will add it to the lists of nice future features.

I think i mentioned it already, if you are going to restrict variables to integers, you runtime will increase significantly, and you won't be able to solve 1 Year hourly stepsize anymore...(i suppose)

**Comment by simnh** [comment]
Ok I just looked at the code, and it might be a bit more complicated as I assumed. So, I guess it will not happen this year...
