### ISSUE TITLE
Investment Optimization of Dispatch Sources

### ISSUE THREAD

**Issue by Konsebast** [oemof/oemof#197]
I have again a problem that I can not solve on my own...

Is there a possibility to optimize the output of a dispatchSource concerning the minimization of the costs?

If I set the optimization_options on true like this:
```python
source.DispatchSource.optimization_options.update({'investment':True})
```
I get the following error:
```python
Traceback (most recent call last):
  File "modell3.py", line 2460, in <module>
    energysystem.optimize()
  File "C:\Python34\lib\site-packages\oemof\core\energy_system.py", line 238, in optimize
    om = OM(energysystem=self)
  File "C:\Python34\lib\site-packages\oemof\solph\optimization_model.py", line 99, in __init__
    self.build_component_constraints(cbt)
  File "C:\Python34\lib\site-packages\oemof\solph\optimization_model.py", line 132, in build_component_constraints
    assembler.registry[cls](e=None, om=self, block=block)
  File "C:\Python34\lib\site-packages\oemof\solph\optimization_model.py", line 708, in _
    raise ValueError("Dispatch source + investment is not possible!")
ValueError: Dispatch source + investment is not possible!
```

Thank you again for your great support!

**Comment by uvchik** [comment]
In this case the error message is very clear.
```python
ValueError: Dispatch source + investment is not possible!
```
This feature is just not implemented and as I see the situation nobody will do that. Of course you could do it, if you want but we already working on the next generation of solph (0.1).

Why do you use a DispatchSource and not a FixedSource? I think a FixedSource will work with the Investment mode.

**Comment by Konsebast** [comment]
Thank you for the reply.
I solved it in a different way, with a shortage object. 

I needed a source which only has a output as long there is no cheaper alternative. In a later version I wanted to cut the source for some time in the simulation.

I am modelling a energy cell that is connected to the external grid. The cell should produce the necessary energy by itself and should only rely on the external grid in exceptional cases. (cutting the source whould be some kind of breakdown of the external grid)
