### ISSUE TITLE
Renaming of 'BUS' to 'HUB'

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#199]
The oemof-core paper introduces a new nomenclature for our Bus-Component concept. There, to bus 
is referred as hub.  I personally think hub is a more precise wording and we do not get confused with the definition of buses in load flow models. Additionally, I think it is easier to understand what it means in oemof energy system modelling context.  Now, we have to decide, whether to rename bus to hub. If so, we should do this before the release of version 0.1 and the upcoming paper. 

Although it might be some work, I vote yes! 
(It's basically replacing texts in all documents as we do not need to keep depreciated warnings etc with the new version...)

**Comment by simnh** [comment]
Does anyone care, otherwise I would start a branch with a pull request for the renaming process...?

**Comment by uvchik** [comment]
I do not have the impression that hub is more precise than bus but I am not a native speaker.

 I think we have better things to do than starting a renaming process (e.g. documentation).

I would postpone the discussion to v0.2.

**Comment by uvchik** [comment]
> ...as we do not need to keep depreciated warnings etc with the new version...

As we already released a beta version and encouraged people to use the upcoming version, a warning might be still necessary. Normally fundamental changes shouldn't be done after releasing the beta version.

**Comment by simnh** [comment]
well, I think it is indeed quit important to do that before the release because otherwise we won't do it until 1 or 2 years. The upcoming and even existing papers (at least partly) introduce that naming and its rather coming from the oemof-core concept, which i guess has been finalized with the paper at the EnvironInfo. So we should, in my opionen, stick to a finalitzed concept with a certain taxonomy with version 0.1 which will be the naming for quit a while i think. 

And it is a better word as it can not be confused as  'bus' can with the load flow / grid terms and depicts the more general form. As it's not a lot of work I think we should do

**Comment by simnh** [comment]
I guess this will not be happening, so it 'll be bus until v0.2  :)
