### ISSUE TITLE
Add mathematical descriptions/notations for solph

### ISSUE THREAD

**Issue by simonhilpert** [oemof/oemof#2]
The mathematical description in solph is not 100 % in line. For this a static rst. file should be created. This file will contain general informations and notations for the mathematical description. 

The following infos should be given in a structured(table-like) format: 

variable names, 
math. sets, 
math. parameter

Docstrings in solph should be in line with these general informations.

**Comment by uvchik** [comment]
Please use the comment function to make the progress transparent. Reset the milestone in time.

**Comment by simonhilpert** [comment]
There is a feature branch for this issue, if someone has ideas feel free to add something. 
Maybe this is something that can be done when new class names and attributes etc and solph is 'fixed'

**Comment by simonhilpert** [comment]
I added the math notation, it is not fully complete and might have some `bugs`. I will close this issue and
open a new feature branch for refactoring solph including a mathematical description, or rather starting with it....
