### ISSUE TITLE
Project management on GitHub

### ISSUE THREAD

**Issue by beritRLI** [oemof/oemof#2]
Organison des Projektmanagements von Collaborativen Projekten
als neuer Issue, damit das decision making nicht mit Randdiskussionen überladen wird

@cswh : danke für den App-Hinweis
@ludee : ich habe die PM Apps mal raussortiert. Da sollten wir möglichst zeitnah reingucken um zu sehen ob das hilfreich ist (möglichst mit Martin, von dem ich das Kürzel jetzt nicht weiß)
https://github.com/integrations/zenhub
https://github.com/integrations/huboard
https://github.com/integrations/waffle
https://github.com/integrations/overv-io

**Comment by busiing** [comment]
Can someone update the current situation? Or is this issue not relevant anymore?

**Comment by uvchik** [comment]
I think we can just close it, as for four years nobody has cared about it.
