### ISSUE TITLE
Implement 'plugin' rolling optimization

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#200]
We already head a functionality for rolling optimization inside the old solph. It is of interest for several projects, to have such a functionality inside the new oemof-solph v.0.1 / v.0.1.1...

**Comment by uvchik** [comment]
I agree but I would assign it to 0.1.1 to not delay the release.

**Comment by gnn** [comment]
It's a nice to have, but I don't think even 0.1.3 is realistic.

**Comment by uvchik** [comment]
I added a [wiki for good ideas](https://github.com/oemof/oemof/wiki/ideas). You may want to move your approach there? :smile:

**Comment by simnh** [comment]
I guess this will not happen so soon...for now I will close this
