### ISSUE TITLE
ResultsDataFrame fails on restored energysystem if storages are involved

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#203]
Using [a results script](https://github.com/gplssm/europepstrans/blob/8973d059984bf2ab93174f5e40501959f61e5d1b/examples/3regions_invest/plot_3regions_results.py) on results obtained from [this example app](https://github.com/gplssm/europepstrans/blob/8973d059984bf2ab93174f5e40501959f61e5d1b/examples/3regions_invest/3regions_invest_example.py) I discovered odd behavior of `ResultsDataFrame` which is probably a bug.

Whenever `energy_system` obtained from solver is stored via `energy_system.dump()` and `energy_system` contains storage objects `__init__` of  `ResultsDataFrame()` fails to build a DataFrame of results.

```
19:35:55-INFO-Restoring attributes will overwrite existing attributes.
Traceback (most recent call last):
  File "/home/guido/rli_local/oemof/examples/solph/storage_optimization/storage_invest.py", line 235, in <module>
    pp.pprint(get_result_dict(esys))
  File "/home/guido/rli_local/oemof/examples/solph/storage_optimization/storage_invest.py", line 142, in get_result_dict
    myresults = outputlib.DataFramePlot(energy_system=energysystem)
  File "/home/guido/rli_local/oemof/oemof/outputlib/__init__.py", line 208, in __init__
19:35:55-INFO-Check the results
    super(DataFramePlot, self).__init__(**kwargs)
  File "/home/guido/rli_local/oemof/oemof/outputlib/__init__.py", line 90, in __init__
    row['bus_label'] = list(k.outputs.keys())[0].label
IndexError: list index out of range

Process finished with exit code 1
```

This can be reproduced using [storage invest example](https://github.com/oemof/oemof/blob/7b18580402758745eef5d42c7a46917ad96f17b5/examples/solph/storage_optimization/storage_invest.py) when changed to dump `energy_system` between solver and results plotting [as illustrated here](https://gist.github.com/gplssm/0be4c86e67dbb4c159deeac15b89502b).

**Comment by uvchik** [comment]
Might be connected with issue #186.

**Comment by simnh** [comment]
Is this solved?

**Comment by gplssm** [comment]
No, maybe we should move to next release

**Comment by uvchik** [comment]
@gnn is about to fix it.

**Comment by gplssm** [comment]
@gnn please close this one when merging #231
