### ISSUE TITLE
Add possiblity to restrict flows to discrete values

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#204]

**Comment by simnh** [comment]
The options is provided now. At least if its about forcing the variable to integer values. 
```
Flow(..., discrete=DiscreteFlow(integers=True)
```
In the future we might add the possibility to use arbitrary set of discrete values but i guess this will 
be a little bit more work as we probably need to use binary variables / SOS sets for that...or look deeper into pyomo.

**Comment by uvchik** [comment]
Is this related to #195?

**Comment by simnh** [comment]
yes indeed...

**Comment by simnh** [comment]
#195

**Comment by simnh** [comment]
It has been done, but can be improved as a feature. in next versions . closing it for now...

**Comment by uvchik** [comment]
@simnh Could you add just a few lines to the documentation?

> It has been done, but can be improved as a feature. in next versions . 

I do not understand. If it is done, it is a new feature, isn't it?

**Comment by simnh** [comment]
It's possible to restrict a Flow to Discrete domain. So that vlue of Flow a flow may only be flow_min <= flow <= flow_max and flow is inside {0, 1, 2, .., flow_max} 
So yes its a new feature...

**Comment by uvchik** [comment]
@simnh Could you add just a few lines to the documentation?
