### ISSUE TITLE
Add Investment options to csv-reader

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#205]
At the moment discrete/binary objects may be added for MILP from the csv file, but investment not. 
It can be easily added in analogy to the discrete (renamed to binary) objects. 
We only need to make sure that attributes in the csv file are unique among normal flow attributes, binary attributes, discrete attributes and investment attributes....But I think its possible.

**Comment by simnh** [comment]
I added this functionality, its a little hacky, but as it is does not affect the API we can change it later.
Although, the storage component is always kind of annoying...

**Comment by ckaldemeyer** [comment]
So it can be closed?

**Comment by simnh** [comment]
We should test this one before closing it...I think a pull request would have been better anyway, but right now its kind of annoying with the release branch pending...

**Comment by ckaldemeyer** [comment]
I won't be able to check for investment options atm.

**Comment by ckaldemeyer** [comment]
I still won't be able to check it atm. will you or have you already @simnh ?

**Comment by simnh** [comment]
I implemented it ...should work fine
