### ISSUE TITLE
Clearfiy API oemof core: EnergySystem attribute time_idx -> time_index

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#206]
We should fix this at is kind of confusing because inside the examples and the OperationalModel class we use 'time_index' whereas inside EnergySystem class we use 'time_idx'...

**Comment by simnh** [comment]
I think we should definitely do this before the release!!!!

**Comment by uvchik** [comment]
@simnh Cloud you make a PR?

**Comment by simnh** [comment]
I can, but I actually assigned @gnn . I see if I can do it this week...

**Comment by simnh** [comment]
I created a feature branch for the pull request. so please work on this: features/clearify-energysystem-api

**Comment by uvchik** [comment]
-> #217
