### ISSUE TITLE
Webconference: "Quo vadis oemof"

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#207]
I think after the summer break, we should have a Webconference for all oemof developers. Do you 
agree? How to find a date? 

Who is interested in such a meeting: 

@uvchik, @gplssm, @caro-rli, @ckaldemeyer , @s3pp , @cswh, @gnn ???

**Comment by ckaldemeyer** [comment]
I am interested and would have time after next week, so from the 24th on!

**Comment by uvchik** [comment]
Thank you for your initiative. I am highly interested.

What about the 24th or another day within that week.

One topic could be the next oemof meeting? Do we want a meeting this year? How long?

**Comment by gplssm** [comment]
I would join the WebCo. 24th of October is fine for me.

**Comment by caro-rli** [comment]
For me also October 24th is fine.

**Comment by simnh** [comment]
Ok great, i suggest: 15:00 - 17:00, what about you guy @ckaldemeyer , @gnn?

**Comment by uvchik** [comment]
Time is okay for me.

**Comment by birgits** [comment]
I will join as well!

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by ckaldemeyer** [comment]
:)

**Comment by gplssm** [comment]
:+1:

**Comment by gnn** [comment]
Ooohh, nice. 24th of October, 15:00 - 17:00 still free and duly noted. :+1:

**Comment by uvchik** [comment]
Could we also talk about "Quo vadis v0.1?" (#216)?
