### ISSUE TITLE
Documentation of the NodesFromCSV structure

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#209]
Provide a deschription on how to use the nodes from csv reader. Maybe we can use some of the user experiences from renpassG!S and play it back to oemof.

**Comment by ckaldemeyer** [comment]
yep. next week!

**Comment by ckaldemeyer** [comment]
I have documented the functionality in the CSV-file itself: https://github.com/oemof/oemof/pull/223

Feedback welcome!

**Comment by uvchik** [comment]
I would appreciate if you could add a section to the [solph documentation](http://oemof.readthedocs.io/en/release-v0.1/oemof_solph.html).

**Comment by ckaldemeyer** [comment]
O.k.. I am just wondering which would be the right place.

What about a section "Using the CSV reader" under "The Grouping module (Sets)". My idea would be to write 3 sentences about the general idea and than cross-link to the example.

**Comment by uvchik** [comment]
Fine.

**Comment by ckaldemeyer** [comment]
I have added some lines to https://github.com/oemof/oemof/pull/224 together with some obvious typos, etc. and some line breaks.

@uvchik : The solph documentation looks really nice!

**Comment by ckaldemeyer** [comment]
By the way: Might it make sense to agree on terms for different model types?

Investment model = clear for everybody
Least cost energy system model with fixed capacities for longer time periods = dispatch model / operational model / central planner model / economic dispatch model

As far as I know the "official term" is "Economic Dispatch Model" according to:

1. https://www.amazon.de/Economics-Electricity-Markets-Wiley-IEEE/dp/1118775759/ref=sr_1_1?ie=UTF8&qid=1477481437&sr=8-1&keywords=biggar+economics
2. https://www.amazon.de/Generation-Operation-Control-Wollenberg-January/dp/B00QAS5QKU/ref=sr_1_1?ie=UTF8&qid=1477481451&sr=8-1&keywords=wood+and+wollenberg

But I don't mind with the term and just think it should be consistent ;)

**Comment by ckaldemeyer** [comment]
I just brought this up because I read the solph documentation (dispatch model) and created an example (operational model)..

**Comment by uvchik** [comment]
> @uvchik : The solph documentation looks really nice!

Thank you :smile: 

In my opinion an investment model is also a least cost model. A dispatch model is something like a least marginal cost model.

@ckaldemeyer : I agree that it should be consistent and if there are "official" terms we should use them. Do you have a proposal?

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer : I agree that it should be consistent and if there are "official" terms we should use them. Do you have a proposal?

I'll look it up again and post the definitions here. We can decide then!

**Comment by ckaldemeyer** [comment]
Biggar (Definition: "Optimal Least Cost Dispatch (with Inelastic demand for Generators with Constant Variable Costs"):
http://pasteboard.co/jVpCPuTzM.png
http://pasteboard.co/1ZxB1RDWL.png

Wood & Wollenburg (Definition "Economic Dispatch(ED) / Unit Commitment(UC)"):
http://pasteboard.co/jVrcBcQ2m.png
http://pasteboard.co/jVrpNTPC2.png
http://pasteboard.co/jVrFw3laC.png

Adam Greenhall ("ED/UC"):
http://adamgreenhall.github.io/minpower/economic-dispatch.html
http://adamgreenhall.github.io/minpower/unit-commitment.html

My bottomline:

I confused it and had already forgotten the terms -> ED is a subset of UC and generally we are using Optimal Least Cost Dispatch models in many cases (not mandatory) with and inelastic demand and generators with constant variable costs.

I would vote for "Optimal Least Cost Dispatch" or just "Dispatch" Models for operational models and ""Optimal Least Cost Dispatch with Investment" or just "Investment" Models for models that include investment.

**Comment by simnh** [comment]
from what i know ED describes scheduled unit (on) in their operational range while UC includes the definition of finding unit to be on or off. So I think disptach (linear(ED)/milp(UC)) and investment models are fine terms for me....But using an UC approach could also be profit maximization (which of course is equivalent to cost minimization)....So overall I think we should not bother too much but rather use extensive naming and description to clearfiy differencens...

for the example of simple_least_cost oder nodes from csv we could also write: 'welfare_max_inelastic_demand'...which would also be correct...

**Comment by simnh** [comment]
or we just use numbering and solph_1, solph_example_2, .... and describe in the docstring what this example is about...

**Comment by ckaldemeyer** [comment]
> from what i know ED describes scheduled unit (on) in their operational range while UC includes the definition of finding unit to be on or off. So I think disptach (linear(ED)/milp(UC)) and investment models are fine terms for me....But using an UC approach could also be profit maximization (which of course is equivalent to cost minimization)....So overall I think we should not bother too much but rather use extensive naming and description to clearfiy differencens...

> for the example of simple_least_cost oder nodes from csv we could also write: 'welfare_max_inelastic_demand'...which would also be correct...

:+1: 

> or we just use numbering and solph_1, solph_example_2, .... and describe in the docstring what this example is about...

I'd rather use a catchy name than loosing myself in extensive descriptions.

**Comment by simnh** [comment]
ok lets say : sufficient...

**Comment by ckaldemeyer** [comment]
I'd still do it in the folder and file names with descriptive names. Otherwise one has to go and look inside every folder/file

**Comment by ckaldemeyer** [comment]
Since we are planning to release tomorrow: Should be just postpone the example-renaming to the next version?

**Comment by ckaldemeyer** [comment]
I'd then just adjust this issue..

**Comment by uvchik** [comment]
You better should open a new issue with a more precise topic and close this one.

**Comment by ckaldemeyer** [comment]
> You better should open a new issue with a more precise topic and close this one.

The idea was not to loose the historical in this issue when it gets closed. But I have just linked in in a new one now ;)
