### ISSUE TITLE
Implement type-days clustering for input data

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#210]

**Comment by ckaldemeyer** [comment]
Is this solve specific? I guess it is more a matter of preprocessing.

**Comment by simnh** [comment]
No, but I thought we can implement to suit our csv-datastructure  for facilitating modelling? But we can start with general dataprocessing tool and then write an adapter for our structure..I remove the solph tag.

**Comment by ckaldemeyer** [comment]
postponed as other stuff has priority first

**Comment by ckaldemeyer** [comment]
Closed in favor of the following package which I have already used succesfully: https://github.com/FZJ-IEK3-VSA/tsam

**Comment by uvchik** [comment]
Is it pure preprocessing to had to adapt something in order to combine it with oemof? If that is the case it would be nice to share this knowledge (someday 😏).

**Comment by simnh** [comment]
Rigth now this is only preprocessing..as far as i now

**Comment by ckaldemeyer** [comment]
> Is it pure preprocessing to had to adapt something in order to combine it with oemof? If that is the case it would be nice to share this knowledge (someday ).

Yes, it is purely preprocessing. You put some time series (e.g. demand or VRE in), select your cluster method and get your clusters. I have some code snippets including test I could share or show you how to use it if you are interested! I had contact with the developer and also discovered a couple of bugs/improvements.

> It's always cool to use existing packages. We could even link to this package if it is good (e.g. a list of packages that can be used in combination with oemof).

I told him that he could promote it in the openmod group and link it in the wiki. From my opinion we could rather link to openmod and collect recommendable software/packages/... there as it is of general interest and a central place.

**Comment by ckaldemeyer** [comment]
And I suggested that he can move it to the oemof cosmos if no support from others comes arround as he is the only developer :smile:

**Comment by ckaldemeyer** [comment]
He was quite excited of some feedback, etc..

**Comment by uvchik** [comment]
> I told him that he could promote it in the openmod group and link it in the wiki. From my opinion we could rather link to openmod and collect recommendable software/packages/... there as it is of general interest and a central place.

If you know where this can be done, it is a good idea to use a more central place.

**Comment by ckaldemeyer** [comment]
> I told him that he could promote it in the openmod group and link it in the wiki. From my opinion we could rather link to openmod and collect recommendable software/packages/... there as it is of general interest and a central place.
> If you know where this can be done, it is a good idea to use a more central place.

I have asked on openmod.
