### ISSUE TITLE
Include example when oemof is installed using pip

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#212]
If someone installs oemof using pip the examples are not included. 

@gplssm tries to find a way to do this for the demandlib. I will transfer it to oemof afterwards.

**Comment by uvchik** [comment]
Reminder!
In the chapter Installation and Setup of oemof's documentation is a paragraph about the example. We should add the place where it can be found afterwards.

**Comment by uvchik** [comment]
@gplssm created scripts for the demandlib that makes it easy to run the examples right after the installation. He will do that for oemof as well. thanks in advance.

- [ ] Creating scripts to execute examples
- [ ] Update setup.py to copy example during installation
- [ ] Explain how to execute the examples in README.rst section "Examples"
- [ ] Add yourself to whatsnew as contributor and add a line (feature) if you like

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by gplssm** [comment]
Progress can be seen here #227

**Comment by gplssm** [comment]
done. further discussion #227
