### ISSUE TITLE
oemof developer meeting - Berlin, December 6, 2016

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#218]
Hi everybody,

here's the doodle link: http://doodle.com/poll/wyeimg84nh48yd5v

Should we assign a deadline of X days?

**Comment by uvchik** [comment]
Until next Monday ?!

**Comment by ckaldemeyer** [comment]
Wow, there is a vote option now ;)

**Comment by gplssm** [comment]
As I already posted as comment below the doodle. I maybe join to discuss things regarding oemof.db/ demandlib if the meeting takes place in Berlin and if I'm available.

**Comment by ckaldemeyer** [comment]
@gnn: Are you also planning to attend?

So far, I would put as a Nikolaus-meeting in on the 6th of December if everybody is fine with that since I don't like heavy Friday/Monday traffic..

@uvchik suggested to have an additional day specificly on oemof application development for everybody who's interested which could be on the 7th. The idea would be so present research/PhD projects and discuss ways how to tackle questions with oemof in terms of modelling techniques. This could also be a starter for collaborative app development, etc.

What do you think?

**Comment by uvchik** [comment]
Where do we meet? I f we follow the regular cycle it will be in Berlin. We could also meet in Magdeburg, but as @gnn did not answer and @gplssm / @caro-rli mentioned that they will party be there if it is Berlin I would say, that we meet in Berlin. Objections :question: 

As I understand it @simnh, @ckaldemeyer, @uvchik and anybody who is interested will meet on the 7th!? I move this to issue #241.

As nobody objected the developer meeting will take place December 6.

**Comment by uvchik** [comment]
Topics (please add yout topics):

 * The new home page
   - Content (Welcome Page, App Page)
   - Wordpress? (limitations, advertisement on the free page)

 * Further development
   - Who? What?
   - Where shall we place new modules, functions, classes....?

**Comment by gnn** [comment]
I don't know whether I'm able to make it on the 6th. The 7th is fine, but on the 6th I have to give a talk in MD. I've got to check whether I can reschedule that, but I won't be able to do so until next tuesday.

**Comment by uvchik** [comment]
At the web conference we decided that the meeting will start at 9.30 and end at about 18.00 (+- 1h) depending on the energy of the participants.

**Comment by simnh** [comment]
I will not be able to make it to the meeting next week. But if maybe I can you for some blocks via the web...we can check if this works e.g. AdobeConnect and the beamer ;) Would be an interesting experience. 
Sorry about that! I hope next time will be possible for me again.

**Comment by birgits** [comment]
Transcript from license break out group:

- Decision: Authorship lies with the "oemof developer group"
- Each contributor must agree to the „contributor agreement“ which states that all rights must be passed over to the oemof developer group. This ensures that changing the license of oemof can be decided by the oemof developer group. The agreement should also contain a passage stating that oemof will always be released under an open source license.  
- Each file should contain the following header :
  - Python files:
#!/usr/bin/env python3
"""one line to give the program's name and a brief idea of what it does"""
__copyright__ = "Copyright oemof developer group"
__license__ = "GPLv3"
  - SQL und andere:
/*
one line to give the program's name and a brief idea of what it does
__copyright__ = "Copyright oemof developer group"
__license__ = "GPLv3"
*/
- The following will be added to the LICENSE FILE:
  - This programOemof is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.
  - Oemof is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
- @Ludee will implement the above changes (put the header in each file and modify the license files to include the correct name and exchange "this software" with oemof)

**Comment by uvchik** [comment]
Panel discussions about organisation and decisions: https://github.com/oemof/organisation/issues/11

**Comment by uvchik** [comment]
@birgits Didn't we decide to create the header in the following way:

```python
""" One line to give a brief idea of what this module is a about.

A description of the module (short but could be more than one line). 
This the module header as described in numpydoc and we decided to use 
numpydoc for docstrings.
"""

__copyright__ = "Copyright oemof developer group"
__license__ = "GPLv3"

import ...

your code
```

**Comment by birgits** [comment]
I don't see the difference... But I just copied it from the pirate pad. We can change it if something is missing or wrong!

**Comment by uvchik** [comment]
Sorry, the markdown of github changed `__copyright__` to __copyright__ . That's why I misunderstood it.

**Comment by birgits** [comment]
Oh, right! I changed it in the transcript, thank you!

**Comment by Ludee** [comment]
another difference are the empty lines between the sections.
In order to keep it short I didn't use them. Are they important and needed?
I'm ok with and without blank lines.

**Comment by birgits** [comment]
Panel discussion about wordpress page: https://github.com/oemof/oemof/issues/221

**Comment by Ludee** [comment]
After feedback from @birgits we follow @uvchik comment and use black lines. It uses more space but is easier to read.
I wasn't sure where to document it so I created a new [wiki page](https://github.com/oemof/oemof/wiki/Header-and-License)
Didn't manage to make a simple line break. needs 2 [add linebreak]

**Comment by uvchik** [comment]
I fixed it. For the future: https://guides.github.com/features/mastering-markdown/ :smile:

**Comment by uvchik** [comment]
I'm not sure about the `#!/usr/bin/env python3` line. 

Do we need it? Is it recommended?

**Comment by Ludee** [comment]
http://stackoverflow.com/questions/7670303/purpose-of-usr-bin-python3
> A shebang line defines where the interpreter is located at. In this case, the python3 interpreter is located in /usr/bin/python3. It could be a bash, ruby, perl or any other scripting languages' interpreter. The operating system does not know it's a python script if you set the execution flag on the script and run it like ./script.py, unless you run it like python3 script.py or set the shebang line.
You can use /usr/bin/env python3 for portability across different systems if they have the language interpreter installed in different locations.

It is not mandatory but is recommended for portability reasons. [see link](https://en.wikipedia.org/wiki/Shebang_%28Unix%29#Portability)

I could not find a negative impact besides copying one more line, so why not?

**Comment by uvchik** [comment]
I know, but I wonder why we should have it inside a package, where it is not intended to execute the files directly. I might be wrong but I think it is useless within a package and we should not add useless lines. It is only useful for examples or applications.

But if it does not interfere with sphinx I am okay with it.

**Comment by ckaldemeyer** [comment]
> I know, but I wonder why we should have it inside a package, where it is not intended to execute the files directly. I might be wrong but I think it is useless within a package and we should not add useless lines. It is only useful for examples or applications.

:+1: 

> But if it does not interfere with sphinx I am okay with it.

I'd rather leave it for examples and applications.

**Comment by Ludee** [comment]
While there is no good reason to keep the line let's remove it. I removed it from the wiki.

On the other hand the open_eGo team added an additional info "author"
```python
__author__ = "author1, author2"
```
Use the GitHub or real name, first author is contact person and responsible for maintenance.
What do you think?
