### ISSUE TITLE
Webconference: "How to find new developers?"

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#219]
At the web conference yesterday we decided to have another web conference on the topic of oemof's future and how to acquire new developers. Since we at the RLI wanted to have a team meeting about that on Nov. 17th I would suggest having the webco sometime during the week after, so Nov. 21-25.  I'm available at the 22nd, 24th and 25th. 
@oemof/oemof Who else wants to join the webco and would any of those days work for you?

**Comment by uvchik** [comment]
All these days are fine for me.

**Comment by caro-rli** [comment]
I'm available at 21st and 25th.

**Comment by uvchik** [comment]
November 25 would be the day for all of us.

**Comment by birgits** [comment]
Alright, the 25th it is! I'll have time until 3 p.m. and would suggest having the webco from 10-12. @oemof/oemof is that good for everybody?

**Comment by uvchik** [comment]
@oemof/oemof Who else will take part? If it is only the three of us, it does not have to be a web conference.

**Comment by ckaldemeyer** [comment]
I'm in!

**Comment by simnh** [comment]
me too

**Comment by birgits** [comment]
So @oemof/oemof November 25, from 10-12 it is!

**Comment by birgits** [comment]
REMINDER: The webconference will be tomorrow from 10-12!

**Comment by birgits** [comment]
This is the transcript from the webco:

* Wie bekommen wir neue Entwickler/Entwicklerinnen?
- ZNES/RLI
   ** Es gibt ein klares Bekenntnis zum Framework, welches auch nach außen komminiziert wird
   ** oemof-Weiterentwicklung wird in Forschungsprojekten "eingepreist" und somit gewährleistet
- Externe Institute
  ** TH Köln (Doktorand) -> will entwickeln
  ** Uni Kassel (Thermische Energiesystem, IdE Institut dezentrale Energietechnologien gemeinnützige GmbH) -> Anwender von renpassg!s
  - Hochschule Osnabrück
  -> Bei Ansprache externer Institute: Nicht bestehende Modelle für eigenes Institut "claimen", sondern auf kollaborative Charakter aufmerksam machen
  -> oemof kann auch "ready to use" sein -> oemof.Apps(c)
* Doktoranden, WMs, Wissenschaftler/innen
* Hochschulen?
  - Summer Seminar/School 2017!? (Cord)
  - Vorschlag:
   1.) Summer School als Seminar an der EUF (hauptsächlich für Studierende)
   2.) Winterschool (mit openmod Workshop gelinkt, auch für externe)
   3.) Oemof-User Treffen am RLI (evtl. Mai) -> Wie baue ich ein App? Wie beteilige ich mich an oemof?
- Treffen im Dezember (Rahmen abklären)
* Kleingruppe "Konzept oemof-Öffentlichkeitsarbeit"
  - Bei Releases: Netzwerke als Multiplikator nutzen (openmod-Verteiler/Strommarktgruppe)
  - oemof-Homepage (Wordpress): Kleingruppe erarbeitet Konzept (Landing-Page nicht app-spezifisch, Domain, allgemeine Struktur, schicke App-Bilder, ...)
* Zeitrahmen:
 - Developer:
  -> Anfang: 9.30 klärt Cord mit Simon
  -> Ende: je nach Beginn
  -> Birgit holt Miriam für oemof Öffentlichkeitsarbeit dazu
 - User:
  -> Anfang: 9.30
  -> Ende: 17.00

**Comment by birgits** [comment]
Ticket for oemof user meeting in spring 2017: https://github.com/oemof/oemof/issues/261
What about the summer school and the other ideas? Should we write separate tickets or leave this ticket open as a reminder?

**Comment by ckaldemeyer** [comment]
> What about the summer school and the other ideas? Should we write separate tickets or leave this ticket open as a reminder?

I think this one should be enough for now.
