### ISSUE TITLE
Find a way to represent the availability of the main contributors

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#220]
Sometime issues are assigned to contributors, that are not available for a longer period. This might be frustrating for others waiting for a response. If others know about the (longer) absence of a contributor they will not assign an issue to him/her or will be aware that will take some time.

**Comment by cswh** [comment]
As an idea or interims solution on that I added a [wiki page](wiki/Availability-of-developers) for that reason. Feel free to change.

**Comment by ckaldemeyer** [comment]
I have asked this on github since I couldn't find an easy way (despite the wiki idea): http://stackoverflow.com/questions/40239420/easy-way-to-track-and-show-user-availability-on-github-e-g-if-users-are-on-hol

Let's see if we get an answer.. ;)

**Comment by ckaldemeyer** [comment]
No answer yet. I suggest we handle it as the doodle. If no solution has come up until next Monday, we go with the wiki.

**Comment by ckaldemeyer** [comment]
#275  fixes this if we just add a flag [currently inactive (until xx.xx.xxxx)] on www.oemof.org/contact
