### ISSUE TITLE
Improve wordpress page

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#221]
At the web conference yesterday we decided to improve our wordpress page and start with adding applications that use oemof. I talked to our PR specialist today and she will help me with wordpress. I'll have a meeting with her sometime next week and will keep you up to date.

**Comment by simnh** [comment]
nice!

**Comment by uvchik** [comment]
I created a test page, where new layouts can be tested. https://newoemof.wordpress.com/

However, the design options of the free version is very limited.

**Comment by uvchik** [comment]
Please write a post with just two or three sentences and a link if you talked about oemof or oemof apps at conferences, meetings etc. That will keep the page alive and more interesting.

**Comment by ckaldemeyer** [comment]
- Boysen, Cynthia; Kaldemeyer, Cord; Tuschy, Ilja "Druckluftspeicherkraftwerk Schleswig-Holstein". Energiespeicherinitiative Schleswig-Holstein, Reußenköge, 24. Juni 2015 [Presentation]
- Kaldemeyer, Cord; Boysen, Cynthia; Tuschy, Ilja "Compressed Air Energy Storage in the German Energy System - Status Quo & Perspectives". 10th International Renewable Energy Storage Conference (IRES 2016), Düsseldorf [Poster]
- Kaldemeyer, Cord; Boysen, Cynthia; Tuschy, Ilja "Compressed Air Energy Storage in the German Energy System - Status Quo & Perspectives". Energy Procedia. 2016 [accepted and in review]

**Comment by ckaldemeyer** [comment]
> I created a test page, where new layouts can be tested. https://newoemof.wordpress.com/
> However, the design options of the free version is very limited.

I still like the old design as it is lean and clean. From my point of view, adding some styled figures of applications, etc. (as on the new wordpress page) would be absolutely sufficient!

**Comment by ckaldemeyer** [comment]
Thanks for your effort!

**Comment by uvchik** [comment]
@ckaldemeyer No, this is not the new layout. It is just a page to test new layouts.

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer No, this is not the new layout. It is just a page to test new layouts.

Yes, o.k., but in my opinion we do not need a new one and could only update the content. Just in terms of time management.. But go ahead if you want ;)

**Comment by simnh** [comment]
I like the new design better! (Except the red stuff at the top ;) 
From my opinion there should be a side: applications on the same level as libraries, where we can add apps and associated literature, or we will have a separated publication section. With paper, conference paper, presentations.

**Comment by simnh** [comment]
> 
    Boysen, Cynthia; Kaldemeyer, Cord; Tuschy, Ilja "Druckluftspeicherkraftwerk Schleswig-Holstein". Energiespeicherinitiative Schleswig-Holstein, Reußenköge, 24. Juni 2015 [Presentation]
    Kaldemeyer, Cord; Boysen, Cynthia; Tuschy, Ilja "Compressed Air Energy Storage in the German Energy System - Status Quo & Perspectives". 10th International Renewable Energy Storage Conference (IRES 2016), Düsseldorf [Poster]
    Kaldemeyer, Cord; Boysen, Cynthia; Tuschy, Ilja "Compressed Air Energy Storage in the German Energy System - Status Quo & Perspectives". Energy Procedia. 2016 [accepted and in review]

Maybe we should restrict our citations. If we use paper, posters, presentatiosn from all related topic, the list might get quit long. So maybe we should carefully select. Especially, if literature is only related not that closely to the framework.

**Comment by ckaldemeyer** [comment]
> Maybe we should restrict our citations. If we use paper, posters, presentatiosn from all related topic, the list might get quit long. So maybe we should carefully select. Especially, if literature is only related not that closely to the framework (and some literature is almost the same (for exampel paper and poster as above ;) )

Yep, these are quite redundant but I thought we can still pick subsets. In this case, I would only select the Energypedia publication, even if it only mentions oemof.

**Comment by ckaldemeyer** [comment]
Maybe we should rebuild the CAES model in oemof ;)

**Comment by ckaldemeyer** [comment]
I misunderstood @uvchik's post. The idea was to publish a news post on the blog, everytime something oemof-related like articles, etc. has been created.

**Comment by simnh** [comment]
> Maybe we should rebuild the CAES model in oemof ;)
Great!

**Comment by birgits** [comment]
I would go with @ckaldemeyer - I like the old page and would rather put effort into the content than the layout. I think that a good static "Home" page explaining what oemof is is important, since we want the wordpress page to be the landing page for people trying to find out about oemof. Thank you @uvchik for implementing that!
I made a new page called Applications where all our apps can be collected. I also included an example app showing you how I would introduce an app. I would try to keep it short, explaining in a few sentences the motivation, the methodology and major results and add one or two pictures/plots. It's very hard to keep it short though, so maybe we should rather use bullet points? I didn't publish the page yet so you'll have to be in the editing mode to see it. 
If you don't have any further suggestions we can each add another app and then publish the page.

**Comment by simnh** [comment]
I thought it would not be a great deal to change the design. I think the new design of the OSeMOSYS page can be quite inspirational, as they have also various projects based on the core of there framework:  

http://www.osemosys.org/

I like the tabs at the top...we think we should move in this direction. BTW I believe that a static page or blog should rather be there to hold static content for new/intereseted etc. users/people. I think we should not focus on the 'news' in the middle of the page, rahter somewhere on the side...thats why i like the new design better.

**Comment by uvchik** [comment]
@birgits wrote:
> At the web conference yesterday we decided to improve our wordpress page and start with adding applications that use oemof. I talked to our PR specialist today and she will help me with wordpress. I'll have a meeting with her sometime next week and will keep you up to date.

I thought after this meeting you might want to test a different layout. And **if** you want to test a new layout you should not do it at the published oemof page but on an extra page. Therefore I added a new page for testing purposes. From my side it was not intended to replace the old design as it is now.

**Comment by uvchik** [comment]
I like the idea of adding more pictures to the page so I put some images related to oemof together, but this does not depend on a specific layout.

![cropped-oemof_gallery31](https://cloud.githubusercontent.com/assets/4760584/20052656/3b25638e-a4d5-11e6-811d-7294c43ae5ea.png)

It's just a proposal and we can change the color, the images and the way they are connected but I would like to have something like this to make oemof less abstract. 

What do you think?

**Comment by simnh** [comment]
like it

**Comment by simnh** [comment]
still i like the new design better, altough i think that the things i do not like are not related to the general layout but rather to some specific sidebar etc. configuration...

**Comment by uvchik** [comment]
Thanks @birgits for the new page. I wonder whether it will be too long once we added all apps. Should we move the long description to an extra page and let the app-page be more like a gallery or an overview (one sentence and an image).

Furthermore I would like to create a welcome page:

`Welcome to oemof, the flexible tool to model energy supply systems. Go to the app-page to get an overview what kind of energy models are blabla. If you want to stay in touch with us follow this blog or have a look at the news page blabla. Get in touch go to contact page blabla`.

The contact page should contain our oemof research fields.

**Contacts**
* Peter Meyer (mobility)
* Lucy Smith (heat and power systems, MILP)
* .....

**Comment by uvchik** [comment]
@simnh 

You can change the layout from the new page to the same layout of the old page and then change or remove the menus and/or page order as you like. If looks as you want, you can present it as an alternative. If you need help just let me know.

**Comment by ckaldemeyer** [comment]
Here's a draft of @birgits page for all people without wordpress login: http://pasteboard.co/ojVUGkYsX.png

**Comment by ckaldemeyer** [comment]
1. Concerning the content:

I like @simnh proposal of having a look at the Osemosys page: http://www.osemosys.org/projects.html

We could also keep it like this and post a general project descriptions with contact details and some exemplary results that are produced with oemof (or later the real results).

With this we keep the effort quite low..

2. Concerning the design/template:

I rather like minimal designs such as the one when I scroll the content of the new layout (https://newoemof.wordpress.com/) and would add @uvchik s example figures -which I like- from (https://github.com/oemof/oemof/issues/221#issuecomment-258787626) as content.

**Comment by birgits** [comment]
At the oemof developer meeting we decided on the following:
- We will keep the general design of the wordpress page.
- Site will have the following pages:
  - HOME
    - Logo
    - Catchphrase
      - modular energy system modelling - no wishes remain open
      - open modeling - no wishes remain open
      - (renewables?)
      - A modular open source framework to model energy supply systems
      - Answer questions around energy supply systems
      - Tool to model the Energiewende
      - Decision support tool for the Energiewende
      - Numerical evidence for the Energiewende
    - Showoff
      - Open Source - free, transparent and well documented (contribution?)
      - Modular - provides various python packages (libraries) with well defined interfaces for modelling and optimisation. /select or create libraries 
      - Versatile - create applications and adapt components to your scope and purpose
      - Cross-Sectoral - include and link heat, power and mobility sectors
      - Multiregional - flexibly connect multiple regions
      - different temporal resolution
    - Picture
      - tiles, jigsaw puzzle, building set
      - Sectors (Power, Heat, Mobility, Grids?)
      - (RLI)-Icons 
    -  Gallery: Answer questions around energy supply systems - gallery with questions and picture 
  - ABOUT
    - History/Background
    - Motivation/Goals
    - Community
    - Documentation
  - NEWS
    - Blog entries
  - LIBRARIES
    - Names, short description and link to GitHub
    - also link to "friend" libraries (PVlib, Windpowerlib)
  - APPLICATIONS
    - Name, short description (1-2 sentences), picture and link to GitHub
    - should show the variety of oemof (heat, power, mobility)
  - CONTACT / PARTNERS
    - Logos

I will make a suggestion for the landing page with contents from above. Uwe made a suggestion for a cool picture for the landing page. @oemof/oemof-developer-group who else would be willing to design/help design a picture? Also, we need people who will add their app to the Applications page. Who has an app he/she can add?

**Comment by uvchik** [comment]
This picture is just a proposal!

<img src="https://cloud.githubusercontent.com/assets/4760584/21008990/951a3392-bd44-11e6-98d3-98383d148508.png" width="400">

Comments so far
1. use only middle pieces and no edge pieces (okay)
2. use a typical heat symbol (okay)
3. use LEGO bricks not puzzle pieces (Do not know how to do it. Will not have the time to find out.)
4. use other symbols (I will not have the time to search for.)

If you want to make a proposal with LEGO or other symbols - go ahead. I could follow 1 and two and make a clean proposal of a puzzle. This is realistic for me.

**Comment by ckaldemeyer** [comment]
:+1: If anyone wants to do a Lego suggestion I'd also be interested. But I also like the puzzle!

**Comment by uvchik** [comment]
Second proposal.

<img src="https://cloud.githubusercontent.com/assets/4760584/21028425/5ff25d42-bd95-11e6-9f04-e6b9f50da656.png" width="500">

**Comment by ckaldemeyer** [comment]
I like the overall style and the symbols. Looks quite dynamic!

The only thing I would change is the color/surface of the pieces. I don't know if multiple colors for the pieces look to restless or if is a combination that looks nice. Another option would be so use some sort of blue/grey combination as a combination of providing a "serious" and "vivid" impression.

**Comment by beritRLI** [comment]
I really like it, too! And I tend to Cords secont proposal of colours (combination of serious and vivid (=> variing blue background?))

**Comment by uvchik** [comment]
<img src="https://cloud.githubusercontent.com/assets/4760584/21046519/65badfb8-be05-11e6-9a16-6c52578f68a3.png" width="400">

Like this (just the colours not the perspective)? If not please define a colour set, because I do not want to guess your ideas and to spend too much time on this.

`car: #ffffff, winturbine: #000000, pv: #23aa12, ....`

**Comment by ckaldemeyer** [comment]
> Like this (just the colours not the perspective)? If not please define a colour set, because I do not want to guess your ideas and to spend too much time on this.

Looks pretty purple on my screen ;) I'll define one on Monday!

**Comment by uvchik** [comment]
Thank you. You may draw 9 squares to test the colours.

**Comment by ckaldemeyer** [comment]
Based on http://colorbrewer2.org/#type=sequential&scheme=Blues&n=6 , these are the codes (blue palette):

#eff3ff
#c6dbef
#9ecae1
#6baed6
#3182bd
#08519c

And this could be the result: http://pasteboard.co/T51SF43e.png

By the way [Pinta](https://pinta-project.com/pintaproject/pinta/) is a nice Paint/Paint.NET replacement ;-)

**Comment by uvchik** [comment]
Thank you. Looks pretty good, but a white piece is not possible on a white background. In the "dynamic" picture all pieces will have contact to the background. We could use the colour of the "pv" piece or we could brew a seventh colour.

**Comment by ckaldemeyer** [comment]
> Thank you. Looks pretty good, but a white piece is not possible on a white background. In the "dynamic" picture all pieces will have contact to the background. We could use the colour of the "pv" piece or we could brew a seventh colour.

I would brew a seventh or we go for nine/ten (-white) colors and have everything unique.

**Comment by uvchik** [comment]
![oemof_puzzle_dynamic](https://cloud.githubusercontent.com/assets/4760584/21589513/ce7e2294-d0f2-11e6-9851-bd5448193a28.png)

**Comment by uvchik** [comment]
![oemof_puzzle_dynamic_black_white](https://cloud.githubusercontent.com/assets/4760584/21589522/dc076556-d0f2-11e6-9539-6e447633e0bc.png)

**Comment by uvchik** [comment]
![oemof_puzzle_dynamic_fabric](https://cloud.githubusercontent.com/assets/4760584/21589526/e577d9d6-d0f2-11e6-8f47-3abd3af15821.png)

**Comment by uvchik** [comment]
Last changes. Please vote.

**Comment by ckaldemeyer** [comment]
I would prefer the first or second depending on how it integrates in the wordpress-template due to the colors.

**Comment by ckaldemeyer** [comment]
And thanks for your effort!!

**Comment by uvchik** [comment]
I updated the [libraries page](https://oemof.wordpress.com/libraries/).

@birgits What about the landing page? I remember that you already wrote a text?

**Comment by ckaldemeyer** [comment]
"It can be used to flexibly create energy systems which are internally represented as a bipartite directed graph."

"Besides this, .."

Thanks!

**Comment by uvchik** [comment]
Nice. Thanks.

**Comment by birgits** [comment]
I like the first one the best followed by the second one!
I will implement the landing page at the end of this or the beginning of the next week.

**Comment by uvchik** [comment]
Thanks in advance @birgits. You can just use the image from above. If the quality is not good enough I will replace the image once the page is designed.

**Comment by simnh** [comment]
I am without an opinion ;)

**Comment by birgits** [comment]
I added a new draft page for the new landing page:
https://oemof.wordpress.com/wp-admin/post.php?post=377&action=edit

Feedback wanted! If you look at my post from Dec 8 you'll find the rest of the ideas we collected at the developer meeting. I had to choose between some of them, but if you like some of the others better just let me know.
I very much like the jigsaw on the landing page btw :)

**Comment by ckaldemeyer** [comment]
> Feedback wanted! If you look at my post from Dec 8 you'll find the rest of the ideas we collected at the developer meeting. I had to choose between some of them, but if you like some of the others better just let me know.

Thanks! It looks great already!

I find the "open modeling - no wishes remain open" slogan a bit over the top to be honest ;-)

Could you imagine alternatives like "The swiss army knife for open energy system modelling" (haha) or "A flexible tool for open energy system modelling"?

> I very much like the jigsaw on the landing page btw :)

Me too :+1:

**Comment by uvchik** [comment]
I would reorder the list because oemof is made for energy modelling.

- Cross-Sectoral – Include and link the heat, power and mobility sector.
- Multiregional – Flexibly connect multiple regions.
- Time-step-flexible
- Open Source – It’s free, transparent and well documented.
- Modular – Choose from various python packages (libraries) with well defined interfaces for modelling and optimisation.
- Versatile – Create applications and adapt components to your scope and purpose.

I would cross out the title ("about").

I would publish it today because it is better as the actual state.

If you agree I can implement the changes.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group : Please add images for the gallery to wordpress or send them to me. At the moment the gallery is too messy.

**Comment by uvchik** [comment]
I added a gallery page and removed some images. Please add new ones.

**Comment by ckaldemeyer** [comment]
> I added a gallery page and removed some images. Please add new ones.

+1

**Comment by ckaldemeyer** [comment]
If you like you could add some figures from the renpassG!S page: https://github.com/znes/renpass_gis

**Comment by ckaldemeyer** [comment]
Or I could also add them..

**Comment by uvchik** [comment]
> If you like you could add some figures from the renpassG!S page: https://github.com/znes/renpass_gis
> Or I could also add them..

No problem, took me 5 minutes.

Shall we publish the landing page?

**Comment by ckaldemeyer** [comment]
> No problem, took me 5 minutes.

Thanks!

> Shall we publish the landing page?

:+1:

**Comment by birgits** [comment]
> Shall we publish the landing page?
Yes, please! Thank you :)

**Comment by uvchik** [comment]
Done.

Are you okay with the new order?

Shall we talk about the headline? (@ckaldemeyer: "over the top")
https://oemof.wordpress.com/

**Comment by ckaldemeyer** [comment]
> Are you okay with the new order?

Currently on my laptop (1920*1280) the puzzle pushes the content out of the viewport. 

I would change the order and begin with the facts "oemof addresses challenges in energy system modelling by being" (without colon) and the bullets and then show the puzzle.

The slogan "open modelling – no wishes remain open" makes me smile but in my opinion could be left out or be replaced to be a bit more serious ;-)

**Comment by ckaldemeyer** [comment]
But if everybody is fine with it we can also leave it. It's just my point of view..

**Comment by birgits** [comment]
I liked your swiss army knife slogan too, Cord! You can change the slogan, I have no strong opinion on it!

> "oemof addresses challenges in energy system modelling by being" (without colon) 

I like that! 
I think the picture first looks nicer. Maybe we could make it smaller so the content also shows on smaller screens?

**Comment by ckaldemeyer** [comment]
> I think the picture first looks nicer. Maybe we could make it smaller so the content also shows on smaller screens?

Could the picture also be placed beside the bullets and a bit smaller?

Anyway, reducing the size might already fix the viewport problem @birgits !

**Comment by ckaldemeyer** [comment]
So: Bullets left and picture to the right?

I am not sure how it looks then. Maybe it looks a bit messy and the one after another a bit cleaner ;)

**Comment by uvchik** [comment]
We could also remove the title and replace  "oemof is" with the slogan:

![bildschirmfoto - 26 01 2017 - 11 31 13](https://cloud.githubusercontent.com/assets/4760584/22328200/376fa982-e3bb-11e6-9c16-7f4cf71c40ed.png)

**Comment by uvchik** [comment]
This is how it looks on my screen.

**Comment by ckaldemeyer** [comment]
> We could also remove the title and replace "oemof is" with the slogan:

You mean removing "A modular open source framework..." from the title logo and putting it into the text?

I quite like it in the title logo and would prefer "oemof addresses challenges in ..." instead of "oemof - powerful and flexible" on top of the bullets and under the (smaller) puzzle.



> This is how it looks on my screen. I like it this way. Without the admin line another two bullets are visible.

I also like it already but would reduce the puzzle just a little bit so that all bullets are visible without the ADM panel on a 1920*1280 resolution

**Comment by ckaldemeyer** [comment]
Concerning the figures for the gallery: maybe some can be taken also from the open-eGo project?

**Comment by ckaldemeyer** [comment]
By the way I have edited the "libraries" page and named all libraries with a dot e.g. "oemof.outputlib" instead of "oemof - outputlib" as it was before. This way it looks uniform.

**Comment by uvchik** [comment]
In the picture above the title is already removed. I would NOT remove the subtitle of the logo ("A modular open source framework...")

I would like to have a slogan above the bullets. I do not like "oemof addresses challenges in..., it sounds too academic to me. But it's a matter of taste.

@ckaldemeyer: In my opinion you can reduce the size and we see how it looks. No problem to resize it again, if it does not look good.

The best way would be to reduce the space between the oemof-logo and the main content but we have to pay to do so.

**Comment by ckaldemeyer** [comment]
> I would like to have a slogan above the bullets. I do not like "oemof addresses challenges in..., it sounds too academic to me. But it's a matter of taste.

Yes, you're right it sounds academic. But I think oemof is mostly used in the academic sector and this also was the (from my opinion justified) punchline in our common paper. So far it's @birgits and my favourite for the slogan. What about @simnh and the others?

Another idea would be "Enhancing energy modelling [by being]"



> @ckaldemeyer: In my opinion you can reduce the size and we see how it looks. No problem to resize it again, if it does not look good.

I have played around a bit now and also shortened the slogan and just put it in the title of the page. Now all bullets fit in the viewport: http://pasteboard.co/qHy6xZryN.png

We can of course change the slogan but I quite like to just put it as page title followed by the puzzle and the bullets.



> The best way would be to reduce the space between the oemof-logo and the main content but we have to pay to do so.

I think we're fine with the standard template.

**Comment by ckaldemeyer** [comment]
But maybe the bullets first look even better. For me the main thing would be that everything (bullets and puzzle) fit on the page

**Comment by ckaldemeyer** [comment]
To be honest I would even prefer this variant: http://pasteboard.co/qHJ3walmQ.png

**Comment by ckaldemeyer** [comment]
Because it come with facts first and underlines this visually with the puzzle. But it's all a matter of taste and we could discuss for days here ;-)

**Comment by uvchik** [comment]
Open Questions:

* bullet first or jigsaw first
* slogan above jigsaw or above bullet list (if jigsaw first)
* slogan?
  * oemof - flexible and powerful
  * oemof addresses challenges in
  * The swiss army knife for open energy system modelling
  * open modeling - no wishes remain open
  * oemof - enhancing energy modelling

I think we agree already that we do not want to have a title AND a solgan on top the bullets, right?

@ckaldemeyer : Just edit this post if your slogan is not right or add a slogan.

@oemof/oemof-developer-group : Please vote!

**Comment by uvchik** [comment]
As the result is not written in stone I would say people can vote until tomorrow morning. Otherwise this will take to much time at all.

**Comment by uvchik** [comment]
BTW: 

```diff
- Open Source – It’s free, transparent and well documented.
+ Open Source and community driven – It’s free, transparent and well documented.
```

**Comment by ckaldemeyer** [comment]
I have edited your post and added the alternative to have a slogan AS title.

Here's my vote which basically looks like [this](http://pasteboard.co/qHJ3walmQ.png):

Open Questions:

* bullet first or jigsaw first -> bullets first and sentence "oemof addresses challenges in energy system modelling by being" above bullets
* slogan above jigsaw or above bullet list (if jigsaw first)
* slogan (if no title)
  * oemof - flexible and powerful
  * oemof addresses challenges in
  * The swiss army knife for open energy system modelling
  * open modeling - no wishes remain open
  * oemof - enhancing energy modelling
  * enhancing energy modelling
* slogan (as title)
  * oemof - flexible and powerful -> also o.k. but so long that it induces a line break
  * oemof addresses challenges in
  * The swiss army knife for open energy system modelling -> also o.k. but so long that it induces a line break
  * open modeling - no wishes remain open
  * oemof - enhancing energy modelling -> also o.k. but so long that it induces a line break
  * Enhancing energy modelling -> preferred title

**Comment by uvchik** [comment]
I'm fine with the actual state but if we have the bullets first we could enlarge the image again. All variants are definitely better than before.

I added an applications page. Following the form:

**Title**

http://link.de

Small description.

Image with a maximum of 636x477 (typical worpress scale).

What do you think?

**Comment by uvchik** [comment]
https://oemof.wordpress.com/applications/

**Comment by uvchik** [comment]
I think the page is much better now we do have 10 Followers already :smile: and I would like to close this issue tomorrow. If there are still things to do we should open specific issues.

Everybody can add his/her application and/or image to the gallery all the time. We do not need an open issue to do that.

**Comment by ckaldemeyer** [comment]
> I'm fine with the actual state but if we have the bullets first we could enlarge the image again. All variants are definitely better than before.

:+1: 



> What do you think?

Looks very nice! Thanks.

I have edited one sentence to "Following you find a collection of different oemof applications that can be used to answer questions arround energy systems." and put the sentence "The application is currently under development." in the reegis paragraph.

> I think the page is much better now and we do have 10 Followers already

I also think that this added a lot of value for external people. Thanks again for you puzzle-effort.

 

> I would like to close this issue tomorrow. If there are still things to do we should open specific issues.

I am fine!
