### ISSUE TITLE
Matplotlib as dependency of oemof in order to get examples running?

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#225]
AFAIK oemof should be designed with less dependencies. But first-time users running example scripts stumble upon an ugly error message matplotlib is not installed.

```
Traceback (most recent call last):
  File "simple_least_costs/simple_least_costs.py", line 12, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named 'matplotlib'
```

Sould we add matplotlib as dependency? Is there any other option available?
@birgits how does `extra_requires` work? Would it be possible to apply this concept here?

**Comment by gplssm** [comment]
In order to make a quick decision until release, let's up-/downvote this comment. I check on Monday 11 pm - sharp.

**Comment by gplssm** [comment]
Note, current implementation of entry point creation requires to matplotlib as dependency otherwise travis-ci is complaining. I added it to requirements in 0554213b7b10c8c2f4f4bf3e9f0a98251b41cfaf, be aware when disussing #227

**Comment by simnh** [comment]
I think it's ok to have it as dependency...even if most plotting is done with pandas (based on matplotlib) 
it's good to have it in there for advanced settings, saving of figures etc.

**Comment by ckaldemeyer** [comment]
I agree to simon. But shouldn't matplotlib be installed with pandas anyway?

**Comment by ckaldemeyer** [comment]
Ah no, it's optional.. http://pandas.pydata.org/pandas-docs/version/0.18.0/install.html

**Comment by uvchik** [comment]
I think it is not that important because most people uses matplotlib anyway. However it is not clean and we should think about a better way in the future. We could also just print out the results if matplotlib is missing. This is even better if the plotting is wrapped into a function:

```python
try:
    from matplotlib import pyplot as plt
except ImportError
    plt = None

# the example code....

if plt is not None:
    results_data_frame.plot()
    plt.show()
else:
    print(results_data_frame.sum())
```

I could do it for our examples but I am also fine with matplotlib as a requirement.

**Comment by gplssm** [comment]
Thanks for your feedback! There is a tendency to keep current work load small and keep matplotlib as dependency.
With @uvchik last post, a "new" idea popped up. If you @oemof/oemof prefer to have matplotlib not in the dependency list and handle missing matplotlib installation as illustrated above, please upvote the above post.

Mid or long-term discussion about this topic should be continued until v1.1. Please use this issues #229

**Comment by uvchik** [comment]
I agree to postpone the discussion and add matplotlib to the requirments for v0.1.0.

**Comment by gplssm** [comment]
We decided to keep matplotlib in the dependency list.
