### ISSUE TITLE
Examples may override existings exemples folder from other site-packages

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#226]
Current concept of including example files (.py and .csv) to the package is to install it somehow as a site-package. This could cause issues if other packages using some concept and are installed to the same environment (think of virtualenvs here). One plausible example would be having demandlib and oemof installed in the same virtualenv.

I'm looking for a setuptools from who has advice :eyes: @gnn

**Comment by uvchik** [comment]
Could you do something like `example/demandlib` and `example/oemof` or `example_oemof` to avoid overriding?

**Comment by gplssm** [comment]
For some reason I feel responsible. But I can't make it right now and have to postpone it :(

**Comment by uvchik** [comment]
Is it still valid? Or is it solved by using the new "oemof_installation_test" script and nothing else.

https://github.com/oemof/oemof/blob/dev/setup.py

**Comment by gplssm** [comment]
I think this issue is resolved independently from the "oemof_installation_test". Nevertheless, it's a nice installation check :smile: 

The issue was actually resolved by moving the examples to a separate repo. The actual problem was the folder "examples" at top-level that was included in "package_data". This way of package management could lead to conflicts of two or more packages that use this concept of providing examples.

Feel free to close this issue!

**Comment by uvchik** [comment]
Thank you.
