### ISSUE TITLE
Should matplotlib be a dependency of oemof?

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#229]
We earlier discussed this (#225) but it's a difficult topic...

Let's take some to discussed not just a few days before release.

**Comment by uvchik** [comment]
In the feedinlib we did the following to avoid a dependency.

```python
try:
    from matplotlib import pyplot as plt
except ImportError
    plt = None

# the example code....

if plt is not None:
    results_data_frame.plot()
    plt.show()
else:
    print(results_data_frame.sum())
```

**Comment by uvchik** [comment]
At the moment it is a dependency so we might want to keep it like this until anybody complains.

**Comment by ckaldemeyer** [comment]
> At the moment it is a dependency so we might want to keep it like this until anybody complains.

Isn't it an implicit dependency anyway because pandas needs matplotlib for its plotting API?
