### ISSUE TITLE
Rename Examples Consistently with Speaking Names and Check for Explicit Modelling

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#230]
So far some of the examples have non-speaking and inconsistent names for dispatch/operational or investment models. The idea was to find a uniform naming and rename either the folders itself or provide a small description within the example itself.

For definitions and a discussion with different opinions, see: https://github.com/oemof/oemof/issues/209

**Comment by ckaldemeyer** [comment]
We should adapt all examples to explicit modelling in order to prevent misundertstandings such as https://github.com/oemof/oemof/issues/240#issuecomment-258832589

**Comment by uvchik** [comment]
@simnh already opened a PR (#238). Let's continue there....

**Comment by simnh** [comment]
So, I took a look at the examples and I think they are quite ok actually. I would change two thins:

- storage_optimization -> storage_capacity_optimization (?)
- simple_least_costs -> simple_operational_optimization (?)

I do not care, please propose something or I will just change it ...

**Comment by uvchik** [comment]
* simple_least_costs -> simple_dispatch_optimization (?)

Shall we add a comment to this example, according to #240?

```
    # It is possible to create a resource bus without connecting a source to
    # this bus. In that case 'balanced' has to be set to 'False'. The costs of
    # the fuel has been added to the 'variable_costs' of the transformers.
    # Be careful: This is an source of error, because changes such as 
    # lowering the conversion factor will increase the amount of fuel but not 
    # the costs.
```

**Comment by ckaldemeyer** [comment]
> So, I took a look at the examples and I think they are quite ok actually. I would change two thins:

> storage_optimization -> storage_capacity_optimization (?)
> simple_least_costs -> simple_operational_optimization (?)

> I do not care, please propose something or I will just change it ...

I think the consens was "dispatch (ED/UC)" and "investment" models here: https://github.com/oemof/oemof/issues/209

So my proposal would be:

storage_optimization -> storage_investment_optimization/storage_investment
simple_least_costs -> simple_dispatch_optimization/simple_dispatch

Maybe leaving the "optimization" is a bit leaner since all examples are in the folder "solph" anyway..

**Comment by ckaldemeyer** [comment]
> Shall we add a comment to this example, according to #240?

Nice idea!

**Comment by simnh** [comment]
I recently often had the discussion about optimization, and many people tend to think of 'optimizing' energy systems as optimizing capacities etc. So I think using dispatch is very good.. I think I know what to do now ;)

**Comment by uvchik** [comment]
see PR #247
