### ISSUE TITLE
Announcements after the v0.1.0 release 

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#233]
According to the [comment](https://github.com/oemof/oemof/issues/216#issuecomment-257319700) from @gplssm.

I hope you find finally some energy to talk about what achieved @simnh and @uvchik and others! Just a side-note here, @ludee reported from Milano that people where asking about oemof and further development.
In order to keep an overview on post-release communication channels, I create a checklist for release announcements (feel free to extend and change responsibilities)

- [x] oemof.wordpress.com (should be a medium-long more explanatory post) @uvchik @simnh 
- [ ] openmod mailing list @simnh 
- [ ] strommarktgruppen mailing list @simnh 
- [x] news on [RLI page](http://reiner-lemoine-institut.de/) @gplssm @uvchik 
- [ ] mail to personal mail addresses of potential interested people @gplssm
   - [ ] people that talked to @ludee in milano
   - [ ] HTW research group
   - [ ] personal contacts

**Comment by gplssm** [comment]
We currently work on a news past for the RLI-Website. Furthermore, we have collected some peoples's mail address who are potentially interested in oemof and should be notified about the release. I would like to write them quite the same mail we will send to the openmod/strommarktgruppe mailing list.
@simnh do you have created a draft for a mail the openmod/strommarktgruppe mailing list?

**Comment by simnh** [comment]
No I did not make it yet, although I think we can maybe join whats on wordpress and some elements from your website post?

**Comment by uvchik** [comment]
Good idea. Do you want to write the mail. If you are unsure you can post it here but I am okay with posting it directly. Anyway I think we should answer to the post, so that it gets more attention :smile:

**Comment by simnh** [comment]
who is you?

**Comment by uvchik** [comment]
@simnh

**Comment by uvchik** [comment]
@simnh Are you going to write it? It's just though, that you offered to do it at the web conference but I might be mistaken.

I just wrote mails to oemof users I know.

**Comment by simnh** [comment]
I will not be able to do it before next week and even then someone might probably need to remind me....So if there is anybody out there willing to do it, do not hesitate...
