### ISSUE TITLE
Oemof on Windows, Error: "Solver did not exit normally"

### ISSUE THREAD

**Issue by Benedikt4** [oemof/oemof#237]
I tried to run storage_invest.py with Spyder on Win7 64bit, i get this error message:
"ApplicationError: Solver (glpk) did not exit normally" 

I tried to use the new example storage_invest.py (with the cbc solver), i got the same error message
 "ApplicationError: Solver (cbc) did not exit normally"

My Installation procedure: 
Anaconda3-4.2.0-Windows-x86_64 installed, then in Windows Comand:
1. pip install package_name
2. pip install oemof
3. conda install -c conda-forge glpk=4.60 
4. pip install virtualenv

How can i solve this problem ?

Best Regards from Germany, Benedikt

**Comment by ckaldemeyer** [comment]
Hi Benedikt,

could you give us some further details like the solver output/log. Thank might lead us to the problem!

Best
Cord

**Comment by Benedikt4** [comment]
If a run the file - i got these messages in the IPython console, after glpsol.exe opens just a black empty Window.

17:48:30-INFO-Building component constraints.
17:48:32-INFO-Building bus constraints.
17:48:33-INFO-Building objective function.
17:48:34-INFO-Handing problem to solver and solving.
Traceback (most recent call last):

  File "<ipython-input-1-2684945c75f8>", line 1, in <module>
    runfile('C:/Users/xxxxxxxxxx/storage_invest.py', wdir='C:/Users/Bene/xxxxxxxxxx')

  File "C:\Users\Bene\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Bene\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Bene/Documents/xxxxxxxxxx/storage_invest.py", line 250, in <module>
    esys = optimise_storage_size(esys)

  File "C:/Users/Bene/Documents/xxxxxxxxxx/storage_invest.py", line 151, in optimise_storage_size
    energysystem.optimize()

  File "C:\Users\Bene\Anaconda3\lib\site-packages\oemof\core\energy_system.py", line 243, in optimize
    solve_kwargs=self.simulation.solve_kwargs)

  File "C:\Users\Bene\Anaconda3\lib\site-packages\oemof\solph\optimization_model.py", line 408, in solve
    results = opt.solve(self, **solve_kwargs)

  File "C:\Users\Bene\Anaconda3\lib\site-packages\pyomo\opt\base\solvers.py", line 584, in solve
    "Solver (%s) did not exit normally" % self.name)

ApplicationError: Solver (glpk) did not exit normally

**Comment by ckaldemeyer** [comment]
Hm, this doesn't give us more information..

Is this the original storage invest example without any changes? Did you have a look into the lp-file?

**Comment by Benedikt4** [comment]
Its the original storage invest example, i changed nothing. What is the lp-file ?

**Comment by simnh** [comment]
You may somewhere inside the code before the om.solve() method is called insert a line: 

`om.write('path/to/file.lp',  io_options={'symbolic_solver_lables':True})`

This will write the lp file to the path you provide...But you should maybe reduce the timesteps (timeindex) to avoid a very large file ....maybe only 4 hours or so...

**Comment by simnh** [comment]
How much RAM do you have on your machine? 
Can you try an other / smaller example, e.g. the simple_least_cost, or (as I said reduce the timesteps)

**Comment by Benedikt4** [comment]
Thank you for your answer :) 
16GB RAM and an Intel i5-4670K processor - i cant believe that the computer is the problem. But i can try it, where can i find this example ?

**Comment by simnh** [comment]
No, 16 GB is more then enough for the examples, sometimes the solver might crash if resources are exceeded...

All examples your are looking for are located inside the oemof/examples/solph directory

**Comment by simnh** [comment]
Well actually, I just noticed inside your posted message energysystem.optimize is called, this means you are on the old meaning drepreciated oemof version. If you just installed oemof and just starting you should definitely use v0.1 that we released just now. 

On windows I do not know how to do this. 

@uvchik @gplssm : Should the pip installation not yield the version 0.1 ?

**Comment by Benedikt4** [comment]
thats right, oemof 0.0.7 is installed on my computer.
i tried the same installation procedure on my notebook also win7 64bit and i installed the same packages. but there omeof 0.1 is installed --- but there is the same error with cbc solver and not glpk solver.

**Comment by simnh** [comment]
you could try to run an normal pyomo example and see if this works on your machine. 

https://github.com/Pyomo

**Comment by Benedikt4** [comment]
Please send me a link, i can find examples, but i dont know where or if  i can download it and what exactly.  its not easy to have an overview here. the structure is expendably and additional is my english is not good enough by half.
but of course - i am very happy about your help

**Comment by ckaldemeyer** [comment]
You could try to run the transport problem: https://github.com/Pyomo/PyomoGallery/tree/master/transport

**Comment by ckaldemeyer** [comment]
Just call it with `python3 transport.py`

**Comment by Benedikt4** [comment]
IPython console:

runfile('C:/Users/Bene/Desktop/transport.py', wdir='C:/Users/Bene/Desktop')
# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem: 
- Name: unknown
  Lower bound: 153.675
  Upper bound: 153.675
  Number of objectives: 1
  Number of constraints: 6
  Number of variables: 7
  Number of nonzeros: 13
  Sense: minimize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver: 
- Status: ok
  Termination condition: optimal
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.031200170516967773
# ----------------------------------------------------------
#   Solution Information
# ----------------------------------------------------------
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Displaying Solution
------------------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-1-8c151f68905d>", line 1, in <module>
    runfile('C:/Users/Bene/Desktop/transport.py', wdir='C:/Users/Bene/Desktop')

  File "C:\Users\Bene\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Bene\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Bene/Desktop/transport.py", line 94, in <module>
    pyomo_postprocess(None, instance, results)

NameError: name 'instance' is not defined

-

But in line 80 instance is defined

**Comment by ckaldemeyer** [comment]
There is an error in the code as instance is not created but passed to the result-function..

Change the last line to:

`pyomo_postprocess(None, None, results)`

Then it should deliver something like:

	Displaying Solution
	------------------------------------------------------------
	x : Shipment quantities in case
	    Size=6, Index=x_index, Domain=Reals
	    Key                       : Lower : Value : Upper : Fixed : Stale
	     ('san-diego', 'chicago') :   0.0 :   0.0 :  None : False : False
	    ('san-diego', 'new-york') :   0.0 : 325.0 :  None : False : False
	      ('san-diego', 'topeka') :   0.0 : 275.0 :  None : False : False
	       ('seattle', 'chicago') :   0.0 : 300.0 :  None : False : False
	      ('seattle', 'new-york') :   0.0 :   0.0 :  None : False : False
		('seattle', 'topeka') :   0.0 :   0.0 :  None : False : False

If it does, your solver is working and we have to look further.. ;)

**Comment by ckaldemeyer** [comment]
Have you also tried other examples?

**Comment by Benedikt4** [comment]
The solver seems to be working:

x : Shipment quantities in case
    Size=6, Index=x_index
    Key                       : Lower : Value : Upper : Fixed : Stale : Domain
     ('san-diego', 'chicago') :   0.0 :   0.0 :  None : False : False :  Reals
    ('san-diego', 'new-york') :   0.0 : 325.0 :  None : False : False :  Reals
      ('san-diego', 'topeka') :   0.0 : 275.0 :  None : False : False :  Reals
       ('seattle', 'chicago') :   0.0 : 300.0 :  None : False : False :  Reals
      ('seattle', 'new-york') :   0.0 :   0.0 :  None : False : False :  Reals
        ('seattle', 'topeka') :   0.0 :   0.0 :  None : False : False :  Reals

**Comment by uvchik** [comment]
There seems to be a problem with pyomo or anaconda. Try to update all packages needed with `pip install oemof --upgrade` or directly `pip install pyomo --update`. Do have the right Anaconda version (32 or 64 bit)? Do you have the right solver version (32 or 64 bit)?

That's what I did (Windows 8, 64bit):

1. Installed latest Anaconda from [here](https://www.continuum.io/downloads#windows) (64 or 32 bit)
2. Downloaded CBC from [here](http://ampl.com/dl/open/cbc/cbc-win64.zip) (32 bit [here](http://ampl.com/dl/open/cbc/cbc-win32.zip) )
3. Unpack CBC to any folder (e.g. `C:/Users/Somebody/my_programs`)
4. Set the PATH to that folder using this [tutorial](http://www.computerhope.com/issues/ch000549.htm)
5. Restart Windows
6. Open Anaconda terminal and type `pip install oemof`
7. Type `oemof_examples storage_invest`
8. Plots appeared after a while....

Please compare what you did with that or try it again.

**Comment by uvchik** [comment]
To get the glpk example work:

9. I downloaded glpk from [here](https://sourceforge.net/projects/winglpk/https://sourceforge.net/projects/winglpk/)
3. Unpacked GLPK to any folder (e.g. `C:/Users/Somebody/my_programs`)
4. Set the PATH to that folder using this [tutorial](http://www.computerhope.com/issues/ch000549.htm)
5. Restarted Windows
7. Typed `oemof_examples simple_least_cost`
8. Plots appeared after a while....

**Comment by ckaldemeyer** [comment]
I think @uvchiks steps are as detailed as possible.

If you just want to check the right version of the Python packages (oemof/pyomo) you could also do:

    pip show <package_name>

But normally, if you install Anaconda and then oemof via pip, it should get you the right packages due to the dependencies.

**Comment by Benedikt4** [comment]
@uvchik  I installed anaconda from the same website. I updated pip, pyomo and oemof 0.1.1. Now the console shows the error message:

File "C:/Users/Bene/Documents/xxxxxxxxxx/storage_invest.py", line 41, in <module>
    from oemof.outputlib import to_pandas as tpd

ImportError: cannot import name 'to_pandas' 

After copying this (and also some other) missing folders from oemof 0.0.8 into the oemof 0.1.1 folder - i am back at the old error message:
File "C:\Users\Bene\Anaconda3\lib\site-packages\pyomo\opt\base\solvers.py", line 584, in solve
    "Solver (%s) did not exit normally" % self.name)

ApplicationError: Solver (glpk) did not exit normally
-

**Comment by uvchik** [comment]
> File "C:/Users/Bene/Documents/xxxxxxxxxx/storage_invest.py", line 41, in
from oemof.outputlib import to_pandas as tpd

You do have the wrong version of the example! Open the Anaconda Prompt and type `oemof_examples storage_invest`.

Did you check whether you installed the right bit-version (32/64) for anaconda and the solver?

**Comment by Benedikt4** [comment]
i installed the 64bit version, thats right. i have an older version (with glpk solver) of storage_invest on my computer and i tried a new version of storage_invest (with the cbc solver) and i get the same error message, just with cbc instead of glpk.
@uvchik What is "Anaconda Prompt" ? You can also answer me in german ;)

**Comment by uvchik** [comment]
This discussion might be interesting for other users (in the future) having the same problem, so I keep on writing in English.

I installed Anaconda and found different programs within the Anaconda menu folder (Spyder, Ipython, Anaconda Prompt....). I used the Anaconda Prompt to install oemof and to execute the example as described above.

![anaconda_prompt](https://cloud.githubusercontent.com/assets/4760584/19972238/a7af158c-a1e1-11e6-84a5-b3468450ca51.png)

![anaconda_prompt2](https://cloud.githubusercontent.com/assets/4760584/19972059/3eb10fb8-a1e1-11e6-8cf3-31a806ed8918.png)

**Comment by ckaldemeyer** [comment]
@Benedikt4 : Did you delete all old files and do a plain installation as described in the steps of @uvchik ?

There might be some old files, etc. as Windows still remembers things at different places like the regedit and user specific app folders..

**Comment by ckaldemeyer** [comment]
Anyway your experiences are valuable and we will include some windows best-practices in the documentation afterwards!

**Comment by Benedikt4** [comment]
I will try to use the new storage_invest.py with the cbc solver on the computer
@uvchik  "4. Set the PATH to that folder using this tutorial":
4. In the Environment Variables window (pictured below), highlight the Path variable in the "System variables" section and click the Edit button. Add or modify the path lines with the paths you want the computer to access. Each different directory is separated with a semicolon as shown below. 

I dont really understand what i have to chainge with the path.

if this doesnt run, i will uninstall everything and start with installing anaconda

**Comment by ckaldemeyer** [comment]
> I dont really understand what i have to chainge with the path.

The PATH variable contains the paths (folders) to programs in order to use them on the windows command shell (cmd.exe) and the solvers have to be executable from it. If this works, pyomo can also access them with its solver-interface.

**Comment by Benedikt4** [comment]
Thanks, but i still do not understand what i have to do and why, can someone explaine it in german ?

**Comment by uvchik** [comment]
You can [mail](http://reiner-lemoine-institut.de/en/about-us/team/uwe-krien/) me your number and I will call you tomorrow.

**Comment by Benedikt4** [comment]
Thank you for your help, its working now with the cbc solver. I followed just the tutorial under Point 4 @uvchik posts.

**Comment by uvchik** [comment]
Then the GLPK should also work if you use [this tutorial from above](https://github.com/oemof/oemof/issues/237#issuecomment-258136140).

I'm glad, that it works now. I guess we can not reconstruct what went wrong before or do you have an idea.

If everything works fine you can close this issues. I wish you a lot of success using oemof...

**Comment by Benedikt4** [comment]
I downloaded glpk from from the anacondacloud. there was no notice to embed this solver like under point nr.4 in your instruction. because after downloading this glpk solver from anacondacloud, ipython changed his error message, i thought the solver is running now. i think that was my mistake
thank you for you help @uvchik @ckaldemeyer :)

**Comment by uvchik** [comment]
@oemof/oemof-solph I add the instruction from [above](https://github.com/oemof/oemof/issues/237#issuecomment-258133923) to the documentation.

**Comment by ckaldemeyer** [comment]
:+1:  Thanks!
