### ISSUE TITLE
oemof user meeting (heat and power) - Berlin, December 7, 2016

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#241]
Topics?

**Comment by ckaldemeyer** [comment]
* Detailed Modelling of District Heating Systems
   * Market Driven (Investor Centered) Dispatch
   * Mathematical modelling
     * Modelling of heat storages
     * Modelling of heat pumps
     * Modelling of transmission networks
* Coordinated development of renpassG!S?
   * Integration of CHP
   * Other TODOs (@ckaldemeyer has a list)

**Comment by ckaldemeyer** [comment]
@fwitte : Are you also interested?

**Comment by simnh** [comment]
Sounds  interesting, I will need to check wheter there's money for travelling because i'am currently working on a different project that does not deal with power/heat modelling...

**Comment by uvchik** [comment]
@simnh We could open it to other topics. Would be interesting to have you there.

**Comment by beritRLI** [comment]
is it an internal meeting or is it also thought for users who are in the decision phase if they want to use oemof in future for their purposes?

**Comment by uvchik** [comment]
At the web conference we decided that the meeting will start at 9.30 and end at 17.00.

**Comment by uvchik** [comment]
@elisagaudchau Would you talk about heat and power approaches in the smenos application. Especially how you deal with the missing heat parameters in the power plant data base.

**Comment by simnh** [comment]
Unfortunately, I will not be able to make it next week, as there are just to many other things that need to be finished in the first two weeks of december.
