### ISSUE TITLE
Introduce checks for flow attributes inside the csv-reader

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#243]
Either externally or internally within the flow class.

**Comment by simnh** [comment]
We can do it with @property inside flow (at least  @gnn said so)

**Comment by ckaldemeyer** [comment]
> We can do it with @property inside flow (at least @gnn said so)

Actually I don't remember this one anymore and its postponed now

**Comment by simnh** [comment]
As we remove the csv-reader this one is obsolete...
