### ISSUE TITLE
Add inputlb documentation

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#245]
We moved some code around and created the inputlib which needs documentation / adaption of documentation. We will do this in the pull request #242

**Comment by ckaldemeyer** [comment]
I think this is fine @simnh , isn't it?

**Comment by simnh** [comment]
No I don't think so...

**Comment by simnh** [comment]
As we discussed today, the inputlib is hard to maintain and there will be no further documentation for now, as we will check how this this evolve in future
