### ISSUE TITLE
oemof pyPSA integration

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#246]
We will now (finally) integrate pyPSA into oemof. We will use the feature branch features/pyPSA-integration, and create a pull request for this branch.

**Comment by simnh** [comment]
This will be discussed in #250

**Comment by gnn** [comment]
No idea why this was moved to v0.1.2. It'll definitely not be done then, so v0.1.3 is a more realistic approach.

**Comment by uvchik** [comment]
in #250 @simnh said that this approach is on hold. Does not sound like 0.1.3 though.

@simnh in #250 
> Due to limited project time we agreed to use pyPSA right away for now. Therefore this one is on hold. If somebody wants to take over, feel free.
> 
> I might be easy though to add linear optimal power flow to solph with minimal effort. As mathematically this is straight forward...

I added a [wiki for good ideas](https://github.com/oemof/oemof/wiki/ideas). You may want to move your approach there? :smile:

**Comment by simnh** [comment]
we wont do it I guess, so I close it for now...
