### ISSUE TITLE
Improve ResultDataFrame

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#251]
- Unique column names e. g. for Storages (input/output/level)
- "Unstack-all-method"

**Comment by ckaldemeyer** [comment]
#252 is related

**Comment by ckaldemeyer** [comment]
https://github.com/znes/renpass_gis/issues/19 is related, too.

**Comment by ckaldemeyer** [comment]
Memo: Maybe we directly replace the Result-Dict?

**Comment by simnh** [comment]
I think the result dict was our standard interface between different oemof packages? Do you think pandas should be this ? Maybe if the standard ResultsDataframe will be a dict of frames as well...of course we would need to rename it then ;)

**Comment by ckaldemeyer** [comment]
> I think the result dict was our standard interface between different oemof packages?

Was it? I think @gnn told me once that it was just something that "was there" and became standard like the RDF. And either way if it was the standard interface, it shouldn't be located in solph from my point of view. Nevertheless, the structure is quite nice, I think.

> Do you think pandas should be this ?

Thinking only from the solph perspective (if we leave it in solph) this would be an option for me. What's the benefit of a solph-result-dict if it's always converted into a dataframe anyway?

> Maybe if the standard ResultsDataframe will be a dict of frames as well...of course we would need to rename it then ;)

That was the plan or at least we had a similar plan:  

- we keep the current dataframe with the multiindex as it holds all information and is quite flexible
- a new class e.g. "oemofResults" is created and holds the multiindex dataframe and the investment results as an attribute. addtionally it holds the plotting and slicer methods for the multiindexed dataframe (in a similar fashionas as it is realized now)
- own ideas like the "dict of flat dataframes arround busses" can be added as slicer methods

So the slicer method could be the "dict of frames" since @uvchik and others seem to like the MultiIndex dataframe. From my point of view we could also replace it through a dict of flat frames. But either way the "flat option" should be implemented.

**Comment by ckaldemeyer** [comment]
But just a lean, nested dict instead of a new class "oemofResults" would also be appealing ;)

**Comment by simnh** [comment]
I think there are many good ways. Using a dict of frames is great. Maybe a 'flatten' method can be used to append the flattened frames to the dict if needed (or it just returns a 'sub-dict' with only flattened frames). 

> Thinking only from the solph perspective (if we leave it in solph) this would be an option for me. What's the benefit of a solph-result-dict if it's always converted into a dataframe anyway?

That's why it I thought is was not a 'solph-dict' but the oemof dict... so that we have standard output format cross a  oemof modules. But lets start with solph and see what happens

**Comment by ckaldemeyer** [comment]
> That's why it I thought is was not a 'solph-dict' but the oemof dict... so that we have standard output format cross a oemof modules. But lets start with solph and see what happens

I am just thinking about how to use it as an oemof-dict.

Would the structure of the dict be defined somewhere as mandatory and all apps build their result-dicts accourding to his?
Or would it be a class (subclass of userdict with a certain structure) that can be used to store the results?

Either way, thinking about a generic result structure will bring us closer..

**Comment by ckaldemeyer** [comment]
Memo:

* Keep "old" results in the energy sytem
* Add new result object

API example:

* my_energy_system.old_results -> ResultDataFrame
* my_energy_system.results -> MultiIndex Dataframe with new structure (not inheriting from pd.DataFrame)

**Comment by ckaldemeyer** [comment]
my_view = oemofViews(my_energy_system.results)
    my_view.get_bus_balance(['bus1', 'bus2', ...])

**Comment by ckaldemeyer** [comment]
my_view = oemofViews(my_energy_system.results)
    my_view.get_bus_balance(['bus1', 'bus2', ...])

**Comment by ckaldemeyer** [comment]
To check/discuss: How to Index the DataFrame:

Using oemof objects (slicing with string reprs. or only string reprs.)?

**Comment by uvchik** [comment]
We should add a method to slice using the string representation. This is easier for some users. At the moment I think the DataFrame index should contain the objects but I am not really sure about that.

**Comment by ckaldemeyer** [comment]
> We should add a method to slice using the string representation. This is easier for some users. At the moment I think the DataFrame index should contain the objects but I am not really sure about that.

I'll start next week and keep you up to date!

**Comment by ckaldemeyer** [comment]
Whiteboard contents as memo: https://www.dropbox.com/sh/ga899x6tywdk5bn/AABzXHoDgpCkt7tt89B7t0IZa?dl=0

**Comment by uvchik** [comment]
I changed the milestone. Is this realistic now?

**Comment by ckaldemeyer** [comment]
> I changed the milestone. Is this realistic now?

:+1:

**Comment by ckaldemeyer** [comment]
Just as a reminder:

On the IRES I had a longer talk with Tom Brown (main developer of [PyPSA](https://www.pypsa.org/)) about flexible data structures and they also had some re-factoring of their result structures.

He said that they had some looks into [PLEXOS](http://energyexemplar.com/software/plexos-desktop-edition/) and [TIMES/MARKAL](http://iea-etsap.org/index.php/etsap-tools/model-generators/times) as an inspiration for their [IO solution](https://www.pypsa.org/doc/import_export.html).

Interestingly, they have moved away completely from using (objects of own) classes in the new versions due to runtime efficiency and now only rely on pandas dataframes for all input and output data..

**Comment by ckaldemeyer** [comment]
I went through the minutes, again trying to remember our final idea for a structure. I remember that we all agreed that the structure should fit for everything but now I somehow do not get it right, again..

Here's what I have restructured from the whiteboard:

* Create a common DataFrame using MultiIndex that holds all results and replaces the result-dict
* The DataFrame is a Pandas DataFrame with a MultiIndex and does not inherit from pandas
* Provide views that handle and edit this DataFrame e.g. `MyView = outputlib.view_unstack_per_bus(MyNewRDF)`
* Have a common API (Index) to access results: `('object', 'attr', 'type')` e.g. `index=('storage', 'soc', 'timeseries')` or `index=('storage', 'soc', 'invest')` and then `MyNewRDF[index]`

I wasn't sure about the index.. Was it like this or `index=('storage', 'soc', scalar)` and `index=('storage', 'soc', timeseries)`?

I should have made better notes... :/

**Comment by ckaldemeyer** [comment]
O.k., after talking to @uvchik things got a bit clearer!

* We were discussing a common pandas dataframe with a MultiIndex that holds all results and replaces the result dict
* The index is
   * `(Source, 'target')` for all flow sequences as it is realized now in the result dict
   * `(Source, 'investment') for all investment scalars
   * `(Source, 'my_component_attr') for all component scalars (which could occur) or sequences such as storage levels
* It is to be discussed if `Source` is the oemof object itself or a respective string representation. The best would be to have the possibility to slice by strings and have a "fallback" slicing possibility by objects
* For logical reasons it should be realized within a single responsible unit e.g. the OM is passed and the results are being processed

**Comment by ckaldemeyer** [comment]
Correct me if I have missed something!

**Comment by simnh** [comment]
So how do I know that the investment is associated with a specific flow ? If there is more than one output? For a demand this would bei ('bus_el', 'investment'), which is kind a strange? 

To me it seems the concept of storing result in a generic cross level. manner is still not solved sufficiently...maybe for now we should leave it like this or rather use:

* The index is
   * `(Source, 'target', 'flow')` for all flow sequences as it is realized now in the result dict
   * `(Source, 'target', 'investment')` for all investment scalars
   * `(Source, 'target' 'my_component_attr')` for all component scalars (which could occur) or sequences such as 

For components like the storage just keep ('storage', 'storage', 'investment')...

**Comment by ckaldemeyer** [comment]
> So how do I know that the investment is associated with a specific flow ? If there is more than one output? For a demand this would bei ('bus_el', 'investment'), which is kind a strange?

You're right, the f***** investment object again has to be thought of and for this the identifier is not sufficient if I see it right.

> To me it seems the concept of storing result in a generic cross level. manner is still not solved sufficiently...maybe for now we should leave it like this or rather use:
> 
> The index is
> (Source, 'target', 'flow') for all flow sequences as it is realized now in the result dict
> (Source, 'target', 'investment') for all investment scalars
> (Source, 'target' 'my_component_attr') for all component scalars (which could occur) or sequences such as
> For components like the storage just keep ('storage', 'storage', 'investment')...

I could live with the extra identifier `'target'` but not with waiting for a "some-day generic structure" ;)

Let's just discuss it here and find such a structure that holds for all objects!

**Comment by ckaldemeyer** [comment]
At the moment the identifier

    (Source, Target, [flow/investment/attr])

should hold, or doesn't it?

**Comment by uvchik** [comment]
Nodes?

We could use the object instead but than we have the problem that it is quite awkward to define a flow object. And it will be more difficult to slice by buses. 

```python
(object, [flow/investment/attr])
```

The other way is to use the id twice (source and target) as we do it at the moment.

**Comment by ckaldemeyer** [comment]
Obsolete!
