### ISSUE TITLE
Accessability of Investment Results

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#252]
At the moment the results of an investment problem are not appended to the ResultDataFrame and can only be accessed via the result-dictionary as in the storage invest example:

	    return {'pp_gas_sum': pp_gas.sum(),
		    'demand_sum': demand.sum(),
		    'demand_max': demand.max(),
		    'wind_sum': wind.sum(),
		    'wind_inst': wind.max()/0.99989,
		    'pv_sum': pv.sum(),
		    'pv_inst': pv.max()/0.76474,
		    'storage_cap': energysystem.results[storage][storage].invest,
		    'objective': energysystem.results.objective
		    }

As I am only working with the csv-functionality at the moment, I stumbled upon this problem because I have no nodes to pass.

I know there are workarrounds like looking for the maximum of the flows or the maximum filling level. Nevertheless this kind of breaks the logic because of the "special handling" directly on the result-dict.

So my idea was to integrate it in the result RDF somehow. The first guess would be to just include fixed values of the (flow) capacity similarly to the handling of the filling level.

Another idea was to get rid of the MultiIndex and work with Pandas Panels. So each panel either represents everything arround a bus or information like investment, etc.

But this would only be possible parallely to the current RDF as it would break the API.

Do you have any opinions/hints/suggestions?

**Comment by uvchik** [comment]
We could create an investment results dictionary for all investment nodes. I think a DataFrame makes not sense, because we do not have time series but only scalars.

**Comment by ckaldemeyer** [comment]
> We could create an investment results dictionary for all investment nodes. I think a DataFrame makes not sense, because we do not have time series but only scalars.

Hm, the simplest and quickest idea would be to add a nested dictionary of investment component results as an attribute to the RDF. But somehow I don't like having different data structures combined..

I think the problem with [panel data](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel) is the dimension of the panel objects. If a series would be allowed, it would be no problem to store investment objects as a panel object.

Another proposal from my side would be to just create one dictionary of flat (only datetime indexed) dataframes arround busses / bus balances. This could also contain you abovementioned dict as a value or we chose a pandas series for the investment components.

Dataframes of dictionaries can be converted easily and also the "standard" dataframe objects (with its plotting methods) could be accessed via:

    my_result_dict_of_dataframes['bus_xy']

Just another idea which in my opinion would be a bit more straight.

**Comment by ckaldemeyer** [comment]
> I think the problem with panel data is the dimension of the panel objects. If a series would be allowed, it would be no problem to store investment objects as a panel object.

I think I actually tested this last year and also if the dataframes are of different dimensions, the highest dimension is taken for the slices meaning that if I slice on a frame with less cols/rows all "non-existing" cells are shown as NaNs which I found not self-explaining and suitable for further processing.

**Comment by uvchik** [comment]
> But somehow I don't like having different data structures combined...

We do have different data structures and I think it should not be the aim to press them together.

The results of the flows are time series and the results of the nodes are scalars. I might want to plot time series but I rarely plot a scalar. That means that I will process the data differently and therefore it is okay for me to have a different structure even a different class with different methods in the outputlib to process them. I also think for new users it is easier to handle two objects than a very special integrated all covering object.

**Comment by ckaldemeyer** [comment]
> We do have different data structures and I think it should not be the aim to press them together.

No, that "pressing" was never the goal. But storing them together in an understandable structure should be the goal from my point of view, which is not the case at the moment.

> The results of the flows are time series and the results of the nodes are scalars. I might want to plot time series but I rarely plot a scalar. That means that I will process the data differently and therefore it is okay for me to have a different structure even a different class with different methods in the outputlib to process them. I also think for new users it is easier to handle two objects than a very special integrated all covering object.

This would be in line with my "dict of flat dataframes + dict/some object of investment components" suggestion. Or don't you think?

**Comment by uvchik** [comment]
Then it will be more difficult to plot all time series you like in one plot, won't it?

I would add a new class with a dict/DataFrame and the labels of the nodes as keys/columns/index.

**Comment by ckaldemeyer** [comment]
I just talked to @uvchik and we would propose the following structure (correct me if not):

- we keep the current dataframe with the multiindex as it holds all information and is quite flexible
- a new class e.g. "oemofResults" is created and holds the multiindex dataframe and the investment results as an attribute. addtionally it holds the plotting and slicer methods for the multiindexed dataframe (in a similar fashionas as it is realized now)
- own ideas like the "dict of flat dataframes arround busses" can be added as slicer methods

TODO: How to deal with the API changes?

**Comment by ckaldemeyer** [comment]
I just read the release notes for the new PyPSA version on the openmod mailing list and they also went for a dict of dataframes in the new version (before, they had used panels):

* network.generators_t are no longer pandas.Panels but dictionaries of
pandas.DataFrames, with variable columns, so that you can be flexible
about which components have time-varying attributes; please read
http://pypsa.org/doc/design.html#time-varying carefully. 

Interesting ;-)

**Comment by uvchik** [comment]
If it is a new class we could keep the old class and add a 'deprecated warning`. With v0.2 we can delete the old class if the new way works fine.

I do not understand why the API change of PyPSA is important for us. Do they have methods, plots or anything else we can use? Should we try to have the same API in your opinion?

**Comment by ckaldemeyer** [comment]
> If it is a new class we could keep the old class and add a 'deprecated warning`. With v0.2 we can delete the old class if the new way works fine.

yes!

> I do not understand why the API change of PyPSA is important for us. Do they have methods, plots or anything else we can use? Should we try to have the same API in your opinion?

No, I just found it interesting because we had some discussion with the developers (panel vs. multiindex) some time ago.

**Comment by simnh** [comment]
should come with the new result API
