### ISSUE TITLE
Logging: Default message that highlights license (GPL3)

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#256]
At the moment we are working on the first release of renpass-gis by this week and yesterday I added a small documentation: https://github.com/znes/renpass_gis/tree/dev

@simnh suggested to also add a license and we chose the GPL3 which I just copied from the oemof repo.

I have added a license file for GPL3 on dev now and just stumbled upon this in the license:

	    {project}  Copyright (C) {year}  {fullname}
	    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
	    This is free software, and you are welcome to redistribute it
	    under certain conditions; type `show c' for details.

Should we add a default message to the logger like this one?

This might highlight the legal aspects of oemof respectively free and open software a bit more.

**Comment by ckaldemeyer** [comment]
It could also be a one liner with a link to the license (show c' for details doesn't make sense) but I think I would be and improvement.

**Comment by uvchik** [comment]
Looks really nice :smile: 

You can install renpassg!s directly from the repository without cloning or releasing it (see [geoplot readme](https://github.com/rl-institut/geoplot)).

I am still kind of struggling with the GPL, so I would not focus it. But it does not matter much to me.
