### ISSUE TITLE
Announcement on mailing lists

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#257]
Basic text from wordpress:

> We proudly present the totally revised version of oemof
> 
> Now oemof is more flexible, better documented and ready to join for new contributors and users.
> 
> The framework provides the basis for a great range of different energy system model types, ranging from LP bottom-up (power and heat) economic dispatch models with optional investment to MILP operational unit commitment models.
> 
> With v0.1.0 we re-factored oemof (not backward compatible!) to bring the implementation in line with the general concept. Hence, the API of components has changed significantly and we introduced the new ‘Flow’ component. Besides an extensive grouping functionality for automatic creation of constraints based
> on component input data the documentation has been revised.
> 
> We provide examples to show the broad range of possible applications and the
> frameworks flexibility.
> 
> See the [documentation](http://oemof.readthedocs.io) for more information.

**Comment by ckaldemeyer** [comment]
Here's my proposal for an e-mail on openmod/strommarktgruppe:

#####################

Hi everybody,

we proudly present the totally revised version version 0.1.0 of the Open Energy Modelling Framework (oemof) which has been released on github and PyPI.

oemof is now more flexible, better documented and ready to join for new contributors and users!

This release brings some major improvements:

* Different energy system model types, ranging from LP bottom-up (power and heat) economic dispatch models with optional investment to MILP operational unit commitment models.
* The implementation is in line with the general graph-based concept. Hence, the API of components has changed significantly and we introduced the new ``Flow`` component.
* An extensive grouping functionality for automatic creation of constraints based on component input data the documentation has been revised.
* Energy systems can be modelled based on spreadsheets (csv) which lowers the entry barrier for new users.
* Provided Examples show the broad range of possible applications and the frameworks flexibility.

See the full release notes in the documentation for more information: http://oemof.readthedocs.io/en/stable/whats_new.html#v0-1-0-november-1-2016

Thanks to all people who contributed!

Best wishes,
The oemof Development Team

**Comment by ckaldemeyer** [comment]
I think there's some stuff (csv-reader, ...) missing in the release notes which we should add before we send the mail

**Comment by uvchik** [comment]
Thank you @ckaldemeyer. I will send it to `openmod` tomorrow if nobody objects. 

Do you want to change the release notes as well?

Will you send it to the `strommarktgruppe`?

**Comment by ckaldemeyer** [comment]
> Thank you @ckaldemeyer. I will send it to openmod tomorrow if nobody objects.

:+1: 

If you wait until Thursday, we will have released renpassG!S and someone of us can "answer" and post existing applications.

@simnh: Should we just add some screenshots to the HESYSOPT documentation as well to post it?

> Do you want to change the release notes as well?

I don't have time right now. Maybe we just remove the link and only say "See the full release notes in the documentation for more information." as a workarround?

> Will you send it to the strommarktgruppe?

I don't know if @simnh wants to because of your effort. In case he doesn't, I'll do it!

**Comment by ckaldemeyer** [comment]
By the way, the repo title says "Open Energy Modelling Framework - Base packages for energy system modeling and optimization https://oemof.wordpress.com" and the Wordpress-Header as well

Are we now with BE or AE (modeling/modelling)?? I thought BE but the "l" seems to pop up again after some time :-)

**Comment by uvchik** [comment]
As I understand it:

BE: `modelling`
AE: `modeling`

As we decided to use BE we should us `modelling`, don't we?

**Comment by caro-rli** [comment]
> An extensive grouping functionality for automatic creation of constraints based on component input data the documentation has been revised.

Is there a word missing in this sentence? Or do I just don't understand?

**Comment by ckaldemeyer** [comment]
>> An extensive grouping functionality for automatic creation of constraints based on component input data the documentation has been revised.
> Is there a word missing in this sentence? Or do I just don't understand?

I think so and missed it.

Suggestion:

* An extensive grouping functionality for automatic creation of constraints based on component input data with a revised documentation.

**Comment by ckaldemeyer** [comment]
> As I understand it:
>
> BE: modelling
> AE: modeling
>
> As we decided to use BE we should us modelling, don't we?

You're right. I'll fix it!

**Comment by ckaldemeyer** [comment]
It's now: "Open Energy Modelling Framework - Base packages for energy system modelling and optimisation"

**Comment by uvchik** [comment]
I think we should not link to the release notes because the mail says as much as the release notes. We should better link to the documentation at all. Therefore we could mention the 'total revision of the documentation, especially solph's documentation.

~~See the full release notes in the documentation for more information: http://oemof.readthedocs.io/en/stable/whats_new.html#v0-1-0-november-1-2016~~

See the fully revised documentation for more information http://oemof.readthedocs.io/en/stable.

For LP/MILP problems have a look at the solph package http://oemof.readthedocs.io/en/stable/oemof_solph.html

**Comment by ckaldemeyer** [comment]
:+1:
