### ISSUE TITLE
Domain for wordpress website

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#259]
https://oemof.wordpress.com/ should be reachable via https://www.some-domain.com e.g. https://www.oemof.org

**Comment by ckaldemeyer** [comment]
We still have to agree on a domain.

Suggestions:

www.oemof.[TLD]
www.open-energy-modelling-framework.[TLD]

TLD (Top Level Domain): .org, .com, .net?

**Comment by Ludee** [comment]
oemof.org

**Comment by birgits** [comment]
I'd go for oemof.org as well!

**Comment by ckaldemeyer** [comment]
My favorite would be oemof.org as well!

**Comment by simnh** [comment]
yes org

**Comment by uvchik** [comment]
oemof.org :+1:

**Comment by ckaldemeyer** [comment]
O.k.. I'll ask for the financing tomorrow and will report it here

**Comment by ckaldemeyer** [comment]
It should now be discussed on the meetings of the EUF guys on a Wednesday together with their Professor.

@s3pp : Can you report the progress here?

**Comment by wolfbunke** [comment]
ok, I will ask.  -> oemof.org :+1:

**Comment by ckaldemeyer** [comment]
> ok, I will ask. -> oemof.org :+1:

Thanks!

**Comment by ckaldemeyer** [comment]
Linked to #221 and still in progress. @s3pp and @wolfbunke are in charged and it will be discussed and decided next Wednesday. Funding looks good!

**Comment by uvchik** [comment]
Any feedback from the "Wednesday meeting".

**Comment by ckaldemeyer** [comment]
> Any feedback from the "Wednesday meeting".

Yes, but meanwhile from another meeting ;)

There is money and we can buy the domain! I will talk to @s3pp and @wolfbunke and manage the entry.

**Comment by wolfbunke** [comment]
Sorry @uvchik for the late answer! Unfortunately we didn't talked about the homepage  last  Wednesday :( Tomorrow @s3pp and me place this topic at our meeting.

**Comment by ckaldemeyer** [comment]
> Sorry @uvchik for the late answer! Unfortunately we didn't talked about the homepage last Wednesday :( Tomorrow @s3pp and me place this topic at our meeting.

We talked a about it in the MoVe meeting and there was a YES for the money. Now the only question is how to pay. There are only two options to pay on an annual basis (~35 USD): 1. Credit card and 2. PayPal

**Comment by wolfbunke** [comment]
ok, thanks. I hope this was discussed after I left the meeting :wink:

**Comment by ckaldemeyer** [comment]
> ok, thanks. I hope this was discussed after I left the meeting

Yep :D

**Comment by s3pp** [comment]
Presumably we will switch from free to personal plan on Friday. Update on Friday : ).

**Comment by s3pp** [comment]
We are now on a personal plan and could switch the domain name. Not sure if there is anything to consider beforehand?

**Comment by uvchik** [comment]
:+1: :smile: :tada: Very cool. Thank you.

I think we decided to use `oemof.org`. If the old URL will be available afterward you can switch right away.

**Comment by ckaldemeyer** [comment]
> Very cool. Thank you.
> 
> I think we decided to use oemof.org. If the old URL will be available afterwards you can switch right away.

We are still trying to figure out how to register the domain since now there seems to be an additional charge of 18 $/y for the registration :/

**Comment by ckaldemeyer** [comment]
If you find the button, go ahead! ;)

**Comment by s3pp** [comment]
Nice, it's already there. Thanks @uvchik

**Comment by ckaldemeyer** [comment]
Nice! Thanks @uvchik 

Here are some things we could/should adapt:

* Change documentation entry to new domain
* Change openmod entry to new domain
* Create a news entry for the facelift and new domain in the blog

**Comment by ckaldemeyer** [comment]
I'll change the first two points tomorrow

**Comment by ckaldemeyer** [comment]
And add a news entry

**Comment by ckaldemeyer** [comment]
I have now changed the documentation, the [openmod website](https://wiki.openmod-initiative.org/wiki/Oemof) and added a [news enty](https://oemof.org/news/).

There seem to be a lot of new fields about the model itself (which is difficult for a framework) on the openmod website. So far, I have only changed the domain, ordered the list of contributors alphabetically and checked some of the boxes.

Feel free to add more content and change the site!

**Comment by uvchik** [comment]
I fixed and extended your changes in the dev-branch 027cda8f.

**Comment by ckaldemeyer** [comment]
I have fixed a part of your changes (project side -> project site):

https://github.com/oemof/oemof/commit/fb60d6bccd4bbd6c13ba7fd17ea12c9c77660f36
https://github.com/oemof/oemof/commit/79e4d8b065ed61b05275499a43322128d006aca2

**Comment by uvchik** [comment]
Thank you. Guess this was an old typo.
