### ISSUE TITLE
oemof user meeting spring 2017

### ISSUE THREAD

**Issue by birgits** [oemof/oemof#261]
We decided on having a user meeting in spring 2017 in Berlin. We should find a date soon. Did we decide on a month yet? I could set up a doodle.

**Comment by uvchik** [comment]
I would vote for May. 

I think we should find a date together with the developer meeting, so that people who are developer and user do not have to travel twice.

**Comment by ckaldemeyer** [comment]
I am on holiday for one week in May. I'll figure out when and post it here ;)

**Comment by birgits** [comment]
Alright, I made a dudle for May.
https://dudle.inf.tu-dresden.de/oemof_meeting/

**Comment by ckaldemeyer** [comment]
I took part

**Comment by uvchik** [comment]
Me too.

**Comment by uvchik** [comment]
I think four persons are a good base to plan this event.

I would block May 8 to May 10 (Monday to Wednesday).

Monday noon to Tuesday noon (Developer meeting)
Tuesday (after)noon to Wednesday afternoon with an optional dinner (User Meeting)

We should fix it soon to start inviting the people for the user meeting (save the date).

@oemof/oemof-developer-group: What do you think?

**Comment by uvchik** [comment]
@oemof/oemof-developer-group: I would feel better, if this would not be a silent consent.

I would like to start to invite people next week.

**Comment by ckaldemeyer** [comment]
I already took part

**Comment by gplssm** [comment]
I put 8th to 10th May in my calendar. My participation is not sure for now, depends on how much my work then depends on oemof.

**Comment by caro-rli** [comment]
I blocked the date, too. Would like to take part in the user meeting.

**Comment by uvchik** [comment]
Thanks to @beritRLI we have a proposal for the invitation. Any remarks?
**************************************************

**oemof – exchange, learn how to use, experience what is new user meeting 2017**

_May 9/10 – Berlin_

The oemof core group invites you to the 2017 user meeting, hosted on May 9th and 10th at the Reiner Lemoine Institut in Berlin.

The objective of this meeting is to bring together advanced users, new users and future users of oemof to exchange about the possibilities to use the framework.

Seeing the community of users growing with a lot of different use cases we like to bring you together to know each other and to get inspired by the already existing applications and to discuss new ideas.

- If you use oemof in various applications….
- If you start using oemof and you are working on your first application…..
- Or if you just want to know if oemof could work for your studies…
… you are invited to come and meet up with other oemof users!

In the last year oemof did some jumps of development that we want to share with you. Not only concerning appearance and documentation (see https://oemof.wordpress.com/) but also regarding modelling possibilities and applications. Questions along energy system analyses require more or less complex models. In some cases it is important that the model is simple and can be built up without big efforts others need to include quite a number of possibilities of configuration. For both requirements you can find examples in oemof. 

At the oemof user meeting you will also have the possibility to get in contact with oemof developers to find out what is under construction and which future applications are discussed. 

Key subjects to be highlighted in the 2017 meeting are … 
* creating your own application
* sector coupling (power, heat mobility)
* add non-existing components within you application

You are invited to contribute to the meeting with an insight into your application or with a discussion about your plans to develop an application. Please send us a line or phone us to discuss your input or request of content for the meeting. You can also raise topics beyond the mentioned key subjects.

Please consider the following timeline:

|  Please consider the following timeline  | Date  |
|:-------------|:--------------------------|
| Distribution of first invitation | 17.02. |
| Deadline for contributions (presentation of applications, discussion of special issues,…) | 26.03. |
| Distribution of invitation with preliminary program        |     10.04. |
| Final deadline registration (please try to register before to ease organisation)      |      22.04.|


For any questions contact xyz.zxx@rl-institut.de. (Tel:....)

We are looking forward to know more about your modelling questions and answers.
…. 
On behalf of oemof …. Group…

**Comment by gplssm** [comment]
@beritRLI thanks a lot for the draft!

In order to make editing on the text easier and provide change tracking, I put the text in a [gist](https://gist.github.com/gplssm/38f0f21008f26a65b7dde21cc238f1d3)
... and made some changes there.

Would you agree that it makes sense to set up a permanent page providing info about the meeting and link to the page already in the first invitational mail. It does not have to contain more than the information provided by the invitation. maybe miriam could take care of it... @beritRLI could you take about this with her?

If this is planned to be a workshop
> creating your own application

I would recommend to say this clearly, maybe by

> Workshop: How to build an app from scratch?

**Comment by ckaldemeyer** [comment]
> Would you agree that it makes sense to set up a permanent page providing info about the meeting and link to the page already in the first invitational mail. It does not have to contain more than the information provided by the invitation. maybe miriam could take care of it... @beritRLI could you take about this with her?

Would it make sense to make this on the (new) oemof-page (www.oemof.org)?

**Comment by ckaldemeyer** [comment]
I have already mentioned it in the last post: https://oemof.org/news/

**Comment by uvchik** [comment]
> If this is planned to be a workshop
> 
>     creating your own application
> 
> I would recommend to say this clearly, maybe by
> 
>     Workshop: How to build an app from scratch?

I would leave it open depending on the number of attendees.

I created a draft, but you have to be logged in.

https://oemof.wordpress.com/?p=475&preview=true

**Comment by ckaldemeyer** [comment]
> I would leave it open depending on the number of attendees.
> 
> I created a draft, but you have to be logged in.
> 
> https://oemof.wordpress.com/?p=475&preview=true

I am fine with it
