### ISSUE TITLE
Header and License

### ISSUE THREAD

**Issue by Ludee** [oemof/oemof#262]
The open_eGo project will use the oemof [standard header](https://github.com/oemof/oemof/wiki/Header-and-License) as well.
A big thank you and a small add-on:

```python
__author__ = "some_name, another_name"
```
it can be a real name or preferable the GitHub username.
It has the function of a "contact persons" and the first one is responsible for maintenance.

**Comment by birgits** [comment]
The header we decided on is documented in the wiki:
https://github.com/oemof/oemof/wiki/Header-and-License

@Ludee can you make a PR where you add the header to each file?

**Comment by uvchik** [comment]
Okay, I added the header to (hopefully) all files.

**Comment by ckaldemeyer** [comment]
> Okay, I added the header to (hopefully) all files.

Thanks a lot for this!
