### ISSUE TITLE
Visualization of Network

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#263]
Hi, is there somewhere code for visualizing the network structure of say `es.nodes` ? 

Maybe inside some apps, somewhere?

**Comment by ckaldemeyer** [comment]
Wasn't there some approach by @cswh in the first version of renpass-gis using *networkx*?

..on the VN server.. :-)

**Comment by simnh** [comment]
Yes that I remember, but it was really a simple approach...I was looking for something finished and really cool. I think for smaller apps (heat modelling) this might totally make sense....

**Comment by ckaldemeyer** [comment]
> Yes that I remember, but it was really a simple approach...I was looking for something finished and really cool. I think for smaller apps (heat modelling) this might totally make sense....

I agree but I won't make it since it has less priority for me and I have other stuff I find more interesting and important first.

**Comment by ckaldemeyer** [comment]
May be we should add a flag "wishlist" during christmas time ;-)

**Comment by simnh** [comment]
![g](https://cloud.githubusercontent.com/assets/2633688/21220779/c86dbb94-c2ba-11e6-98e6-cea70b4f0a7c.png)

**Comment by simnh** [comment]
Graphviz seems to work better...for simple ones thats the code

```
    import graphviz as gv
    import oemof.network as ntwk
    G = gv.Digraph(format='png')
    for n in es.nodes:
        if isinstance(n, ntwk.Component):
            color='black'
            shape = 'box'
        else:
            color = 'blue'
            shape = None
        if 'heat' in n.label:
            color = 'red'
        if 'GL' in n.label:
            color='brown'
        G.node(n.label, color=color, shape=shape)
    for s,t in om.flows:
        G.edge(s.label, t.label)
    G.render('G')


```

**Comment by ckaldemeyer** [comment]
> Graphviz seems to work better...for simple ones thats the code

Nice!

One contra point:

networkx can export to .graphml which can be used within yEd and from there you can group automatically and edit the graph: https://thirld.com/blog/2012/01/31/making-yed-import-labels-from-graphml-files/

graphviz doesn't seem to provide this possibility: http://www.graphviz.org/doc/info/output.html

**Comment by ckaldemeyer** [comment]
But maybe some of the xml based formats work with yEd, too. I haven't checked...

**Comment by cswh** [comment]
there is some work on that in: [energy_system.py in branch feature/pypower](https://github.com/oemof/oemof/blob/features/pypower/oemof/core/energy_system.py)

just see the `plot_as_graph` method

**Comment by simnh** [comment]
ok this does not work :D 
![g](https://cloud.githubusercontent.com/assets/2633688/21221740/dd864d94-c2be-11e6-90c9-7b80bdfb766e.png)

**Comment by ckaldemeyer** [comment]
> ok this does not work :D

I think for big graphs/networks the yEd import and autogroup functionality might be really helpful. It aligns graphs depending on given criteria, etc.
