### ISSUE TITLE
oemof-Workshops @ openmod conference

### ISSUE THREAD

**Issue by beritRLI** [oemof/oemof#266]
To attract new developers/users for oemof introduction-workshops would be a good way. There is a good opportunity at the next openmod Meeting in April. The google doc with organisational details is here:
https://docs.google.com/document/d/1_F6n9ePO2apa7V7XzE3KO6Ii0VASel-inIW_3i-n1EM/edit#heading=h.ojqn8etuudzn
An organizational call is organized bei tim (tt397@cam.ac.uk); at the moment the envisaged date is: 
Tuesday, 17 January 2016 3pm CET, 2pm GMT
If one or more of you are able to give an introduction to oemof would be good. Please find together here and note at the google doc and inform Tim.

**Comment by beritRLI** [comment]
@oemof/oemof-developer-group 
bitte guckt doch mal oben auf die Anfrage aus meinem ersten Post in diesem issue

**Comment by simnh** [comment]
I talked to @ckaldemeyer  and as we would attend the meeting we would also prepare a oemof tutorial for this workshop. If someboy wants to join, feel free to add your name to the googledocs document..

**Comment by beritRLI** [comment]
great, thanks!

**Comment by birgits** [comment]
I could help as well and added my name to the doc.

**Comment by simnh** [comment]
> I could help as well and added my name to the doc.

very much appriacated!

**Comment by uvchik** [comment]
I think it is a good opportunity to show oemof, so I would like to help. But due to time restrictions I cannot promise anything.

**Comment by birgits** [comment]
Hey, I wanted to ask how the preparation for the oemof tutorial is coming along and if you would like me to help with anything? We also signed up for an oemof short talk to let people know about what's happening in the oemof cosmos. I put my name there for now but if anyone else would like to do it, as I am not very much up to date, you can just let me know and I'll change the name.

**Comment by ckaldemeyer** [comment]
> Hey, I wanted to ask how the preparation for the oemof tutorial is coming along and if you would like me to help with anything?

So far, nothing has happened here. If I get it right @simnh and me started the whole thing and you, @gplssm wanted to contribute.

Should we hold a small webco for the preparation?

**Comment by simnh** [comment]
I am already getting some expierence from the pyomo tutorial. The first important step will be to provide installation instructions upfront, which we should add to the wiki as soon as possible. We can than decide what content...

For pyomo we use anaconda which is great, we could use that as well. We only would need to provide the link to the repository for oemof as a link

```
```

**Comment by ckaldemeyer** [comment]
> I am already getting some expierence from the pyomo tutorial. The first important step will be to provide installation instructions upfront, which we should add to the wiki as soon as possible. We can than decide what content...
> 
> For pyomo we use anaconda which is great, we could use that as well. We only would need to provide the link to the repository for oemof as a link
> 
> name: oemof-tutorial
> channels: 
>     - conda-forge
>     - defaults
> dependencies:
>     - python=3.5
>     - glpk=4.61
>     - pip:
>      - "oemof"
> I think something like this should work, or we leave the pip part from the yml file and just add:
> 
> 'Activate your environment and run pip install oemof'
> 
> Or we could just refer to our great installation page inside the docs

:+1: I think the installation page has been tested enough, or not?

> Regarding the telco, I could do it on friday, but we should already put some information for installing oemof on the wiki page for the workshop as I said. And if we need files we could also add them there, e.g. we want to use the csv-reader?

If I look at the [program and shedule](https://wiki.openmod-initiative.org/wiki/Open_Energy_Modelling_Workshop_-_Frankfurt_2017#Energy_Model_Introductions) I am not sure if it is supposed to be in tutorial style anymore as all models are currently planned sequentially:

Room: Main Auditorium 0.100
This stream contains lectures introducing energy models.
16:30 - 17:00 -- Calliope
17:30 - 18:00 -- OSeMOSYS
18:00 - 18:30 -- Oemof
18:30 - 19:00 -- PyPSA

At first, I thought it's a break out group and we have some "hands on" but now it looks like a classic presentation.

Should we ask Tom or someone else how it is planned?

**Comment by ckaldemeyer** [comment]
I'll ask him..

Concerning the telco I could join from Friday 2 pm.

**Comment by birgits** [comment]
I agree with Cord, the installation instructions in the wiki are well tested.
I could also join a webco at 2 pm, though 3 pm would work better for me.

**Comment by ckaldemeyer** [comment]
> I agree with Cord, the installation instructions in the wiki are well tested.
> I could also join a webco at 2 pm, though 3 pm would work better for me.

3 pm would also be fine for me. Can someone then add the installation instructions (the link) to the openmod wiki?

I have already mailed Tom and Jonas concerning the planned structure and wait for an answer..

**Comment by uvchik** [comment]
> At first, I thought it's a break out group and we have some "hands on" but now it looks like a classic presentation.
> 
> Should we ask Tom or someone else how it is planned?

If people are interested in more details the might get a last-minute-ticket for the user meeting ;-)

I will not be able to take part in the webco, but I am interested in the results as I will hold a presentation about oemof in Bremen next week.

**Comment by ckaldemeyer** [comment]
Here is Toms answer:

> Hi Cord,
> 
> We were thinking just a straightforward presentation of the model and
> its applications - the time slots are unfortunately too short (30 mins)
> for a "hands on" approach and probably people are too tired after the
> tutorials anyway .
> 
> Best,
> Tom

So it's basically a normal presentation with the ideas behind, an outline of the structure, some applications, a conclusion and an outlook.

**Comment by birgits** [comment]
Is anyone joining the webco now?

**Comment by birgits** [comment]
Cord and I decided to have another try for a webco at the beginning of next week since Simon should join as well if possible. I would suggest Tuesday afternoon (between 14-17 o'clock) or sometime on Wednesday?

**Comment by ckaldemeyer** [comment]
> Cord and I decided to have another try for a webco at the beginning of next week since Simon should join as well if possible. I would suggest Tuesday afternoon (between 14-17 o'clock) or sometime on Wednesday?

We had the idea of a classic starter (idea behind, toolboxes, graph logic, ...) and then going into practical application by showing oemof's flexibility using different examples or even live-developing/extending an application. I would find that quite cool ;)
