### ISSUE TITLE
Web-Conference

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#271]
@oemof/oemof-developer-group - There are some topics to talk about:

 * citing oemof (group and order of authors)
 * next release
 * spring meeting
 
**Possible dates:** Tuesday (21.2), Wednesday (22.2) or Thursday (23.2) at 16:00.

**Comment by ckaldemeyer** [comment]
For me all dates would be fine

**Comment by birgits** [comment]
For me, too!

**Comment by gplssm** [comment]
I'll join on any date.

**Comment by uvchik** [comment]
I would prefer Thursday. Tuesday is possible but difficult for me.

**Comment by birgits** [comment]
What about Wednesday? Thursday would only work until 17:00 for me.

**Comment by simnh** [comment]
All dates possible...if I do not show up, calll me as a reminder ;)

**Comment by ckaldemeyer** [comment]
> I would prefer Thursday. Tuesday is possible but difficult for me.
>> What about Wednesday? Thursday would only work until 17:00 for me.
>>> All dates possible...if I do not show up, calll me as a reminder ;)

What about Thursday at 2 pm right after the lunch coma?

**Comment by uvchik** [comment]
For me, it is not possible before 4pm (see first post). What about Wednesday at 4pm?

**Comment by ckaldemeyer** [comment]
> For me, it is not possible before 4pm (see first post). What about Wednesday at 4pm?

Oh, I missed that. I am fine with it!

**Comment by gplssm** [comment]
Ok, there we are! Wednesday 16.00 to 17.00.

Let's have a focused session, then we''ll finish in time ;)
