### ISSUE TITLE
Developer meeting, May 8/9 at RLI, Berlin

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#274]
Topics, participants, helpers, presentations,....?

**Comment by uvchik** [comment]
@oemof/oemof-steering-committee : Who will take part.

**Comment by uvchik** [comment]
@oemof/oemof-steering-committee Who will participate?

**Comment by birgits** [comment]
I will!

**Comment by ckaldemeyer** [comment]
> @oemof/oemof-steering-committee Who will participate?

I am not sure weather I will because I am very short in time (specially in May) and I might just pop up at the user meeting.

**Comment by simnh** [comment]
I will be there and I guess @gnn  as well. I would think if @ckaldemeyer  could join, this would be great as I would like to discuss to major points: 

1. Solph Restructuring. (s. #300 ), Including:
* Multiperiod
* Differentiate Models (Investment, Dispathc, UnitCommitment etc
* Results

2. CSV-Reader  / Scenario class (related to 1.)
