### ISSUE TITLE
Authors of the next release

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#275]
According to issue #264 @gplssm created a DOI at [zenodo](https://zenodo.org/record/276054).

At zenodo all github contributors are authors even though some of them wrote code that is not part of the actual release (any more). Some authors are not part of the contributor list because of allocation problems between local accounts and github accounts even though their code is part of the actual release.

To avoid such injustices we decided to create a list of authors for the next release. If you think that your contribution is part of the next release please write a comment to this issue (e.g. "I want to be an author"). 

At the next developer meeting (#274) will be time to discuss the list or the procedure.

If you have objections against this procedure please do not hesitate to bring them up.

**Comment by ckaldemeyer** [comment]
:+1: Thanks for creating

**Comment by uvchik** [comment]
Sorry I forgot to include the group tag: @oemof/oemof-developer-group.

Please answer soon. The release will be in March (#276).

**Comment by cswh** [comment]
* What is our definition of "author of release"?
* Does it mean a contribution to the code between that release and the release before?
* How long do we include authors of previous releases? Or how to reference them in another way?

**Comment by ckaldemeyer** [comment]
> What is our definition of "author of release"?

Authors in the DOI which is planned to be created per release

> Does it mean a contribution to the code between that release and the release before?

Yes, with the exception of a "core of developers"

> How long do we include authors of previous releases? Or how to reference them in another way?

The idea was to keep core developers like @uvchik and @simnh even for years if fundamental things like solph which they created do not change. If a person hasn't contributed for longer (like e.g. 3 releases) and does not reply on the release/author discussion before creating the DOI he/she might be omitted based on the opinion of the current developers.

That's how I understood the consens/approach in the last webco with @uvchik , @gplssm , @birgits . Correct me if I am wrong!

**Comment by gplssm** [comment]
> > What is our definition of "author of release"?
> 
> Authors in the DOI which is planned to be created per release
> 
> > Does it mean a contribution to the code between that release and the release before?
> 
> Yes, with the exception of a "core of developers"
> 
> > How long do we include authors of previous releases? Or how to reference them in another way?
> 
> The idea was to keep core developers like @uvchik and @simnh even for years if fundamental things like solph which they created do not change. If a person hasn't contributed for longer (like e.g. 3 releases) and does not reply on the release/author discussion before creating the DOI he/she might be omitted based on the opinion of the current developers.
> 
> That's how I understood the consens/approach in the last webco with @uvchik , @gplssm , @birgits . Correct me if I am wrong!

Correct, that's how I understood it as well. For example, I haven't contributed since last release (v0.1.1), consequently I won't be author of v0.1.2.

**Comment by uvchik** [comment]
As I understand it, we couldn't find a sharp boarder. But we could find some poles. Their a definitely some contributors how wrote most of the code. Others wrote code that is not part of the actual release any more. 

We agreed that the first group should be author and the second group shouldn't. But there are some contributors in between. 

So we decided to make a self-assessment until the developer meeting in May, where we have time to talk about it.

I would say, take a look at the actual code base and imagine how it would look like without your contribution and try to compare it with a contribution to a journal paper. What should somebody do to become co-author of your paper? Do you think you have done this to oemof? Then you should be on the list of authors.

@gplssm The time between two releases varies from one day to some month. Sounds like a lottery to me. And if your contribution is a significant part of 0.1.1 it is still a significant part of 0.1.2 unless someone else revises your contribution.

**Comment by ckaldemeyer** [comment]
> As I understand it, we couldn't find a sharp boarder. But we could find some poles. Their a definitely some contributors who wrote most of the code. Others wrote code that is not part of the actual release any more.
> 
> We agreed that the first group should be author and the second group shouldn't. But there are some contributors in between.
> 
> So we decided to make a self-assessment until the developer meeting in May, where we have time to talk about it.
> 
> I would say, take a look at the actual code base and imagine how it would look like without your contribution and try to compare it with a contribution to a journal paper. What should somebody do to become co-author of your paper? Do you think you have done this to oemof? Then you should be on the list of authors.

I think this puts it quite well!

One addition from my side is that for all of us ( @uvchik @gplssm @birgits and me) it was most important that some rigid publication guidlines does not scare of potential contributors in any way.

So, if in doubt and a person has an objection of being mentioned it is being mentioned if it is somehow justified!

**Comment by simnh** [comment]
I am not sure if I quite get it right but generally I think oemof right now is build on the work of people that 
did not contribute since maybe one year, but nevertheless are kind of authors when it comes to the DOI. As this is used in publications etc... 

My proposal would therefore be rather an opt-out for people that think oemof has changed significantly since their last contribution or just naming oemof-developing group and defining this group somewhere else. The last options is really the best one I think....this can be alive then. If anyone is interested in persons they can check it out. Code-contributions can be seen as well on githug

**Comment by uvchik** [comment]
We were four participants at the web conference and we had to decide what to do for the next release. @s3pp for example contributed but is not on the list because his account was not assigned correctly. So we decided to make our own list instead of using the automatic list.

@simnh If you vote for the automatic list, I would like to add @s3pp. And I definitely do not want to talk about any longer.

P.S.: If we talk about issues and PRs the group seems to be quite small but if it comes to name the group seems to be quite big. I have two little children and a Ph.D, don't tell me you do not have time.

**Comment by cswh** [comment]
I really liked the way we took for the [header and license](https://github.com/oemof/oemof/wiki/Header-and-License) to just name the "oemof developer group". I think when somebody looks at the "oemof developer group" then at github it is quite clear, who is how strongly commited and involved in the process.

But if you want to choose explicit names for every release, I will not oppose, since my last commitment in the repository is already some time ago.

**Comment by uvchik** [comment]
I personally do not want to choose explicit names for every release. I would like to create a basic list and add newcomers.

I do not think that the contributors list at github really shows what people do/have done.

As we discussed at the developer meeting the `developer group` consists of active people while non-active people can still be authors.

I would not remove people whose contribution is old, I would remove people whose contribution is obsolete. But it is not important for me to remove people.

I thought self-assessment would be a good compromise, but it might be difficult to get a response from some authors.

**Comment by uvchik** [comment]
Sorry, this seems to be an emotional topic, so I edited my comment.

1. But how do we find a solution without ruining the atmosphere? WebCo, online voting...?

2. I think citing a group name is a good idea, because I think that `Krien et al.` does not feel right. I learned that a group can not be an author but an editor. For example a technical report of "greenpeace" should be cited as `Grennpeace (ed.) : The future of ....`. Follwoing this we could publish with 
`oemof organisation (ed.) : open energy modelling framework (oemof) ....`. What do you think?

3. We still need to define the group somewhere? My suggestion is to do it comparable to paper contribution but based on a self-assessment, because we do not have a main author who could decide it.

> I would say, take a look at the actual code base and imagine how it would look like without your contribution and try to compare it with a contribution to a journal paper. What should somebody do to become co-author of your paper? Do you think you have done this to oemof? Then you should be on the list of authors.

**Comment by ckaldemeyer** [comment]
> I think citing a group name is a good idea, because I think that Krien et al. does not feel right. I learned that a group can not be an author but an editor. For example a technical report of "greenpeace" should be cited as Grennpeace (ed.) : The future of ..... Follwoing this we could publish with
> oemof organisation (ed.) : open energy modelling framework (oemof) ..... What do you think?

I think citing the group name would make most people happy so it's probably the best compromise!

> We still need to define the group somewhere? My suggestion is to do it comparable to paper contribution but based on a self-assessment, because we do not have a main author who could decide it.
>> I would say, take a look at the actual code base and imagine how it would look like without your contribution and try to compare it with a contribution to a journal paper. What should somebody do to become co-author of your paper? Do you think you have done this to oemof? Then you should be on the list of authors.

We could create an issue and everybody who thinks he should be in the group drops a line.

After this, the "where to show/keep the group?" questions has to be answered. This could be (another) github group or we just take the simple variant an [link the programming people on oemof.org](https://oemof.org/contact/) which would be my favorite option as it is really simple.

**Comment by cswh** [comment]
When we have a place where to define the group we could as well use the opportunity to give more information on the contribution, perhaps even with categories like "concept, implementation, core, solph, feedinlib...". E.g. I would be happy to be listed with a contribution of something like "initial conceptual work on core concept, currently not active".

**Comment by ckaldemeyer** [comment]
> When we have a place where to define the group we could as well use the opportunity to give more information on the contribution, perhaps even with categories like "concept, implementation, core, solph, feedinlib...". E.g. I would be happy to be listed with a contribution of something like "initial conceptual work on core concept, currently not active".

I would keep it simple with without categories, etc. except for [currently inactive] or something similar.

So for the next release the DOI would be something like:

Stable version:
oemof developer group. (2016, November 2). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Version v0.X.X. See www.oemof.org for more information.
 
Developer version:
oemof developer group. (2016, November 23). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Commit 6c451c4. See www.oemof.org for more information.

?

And I think we should add a "citing oemof" section to the documentation to make it clearer. What do you think?

**Comment by simnh** [comment]
I like it this way

**Comment by uvchik** [comment]
I would prefer a different structure for the web page rather than keywords behind the names.

### Institutions or Supporting Institutions

* Centre of sustainabl... (ZNES) or University of...
* Reiner Lemoine... (RLI)

### Contact (people who are reachable and will answer)

* Peter Müller (RLI)
* Gaby Meier (ZNES)

### Developer (active people ) [equal to Contact?]

* Peter Müller (RLI)
* Gaby Meier (ZNES)
* Margit Muster (GTH)

### Former developer or Inactive developer

* Sabine Schuster (RLI)
* .....

**Comment by ckaldemeyer** [comment]
> I would prefer a different structure for the web page rather than keywords behind the names.
> 
> Institutions or Supporting Institutions
> 
> Centre of sustainabl... (ZNES) or University of...
> Reiner Lemoine... (RLI)
> Contact (people who are reachable and will answer)
> 
> Peter Müller (RLI)
> Gaby Meier (ZNES)
> Developer (active people ) [equal to Contact?]
> 
> Peter Müller (RLI)
> Gaby Meier (ZNES)
> Margit Muster (GTH)
> Former developer or Inactive developer
> 
> Sabine Schuster (RLI)
> .....

This would also be fine for me.

**Comment by uvchik** [comment]
According to our web conference, I removed the developer and added a list instead. If anybody wants to be contact, just write yourself into the list.
