### ISSUE TITLE
Should the fixed_cost attribute be a Sequence?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#278]
According to our documentation the fixed_costs attribute can be a scalar or a sequence.

http://oemof.readthedocs.io/en/stable/api/oemof.solph.html#oemof.solph.network.Flow

I looked at the code at it is not allowed to be iterable.

```python
self.actual_value = Sequence(kwargs.get('actual_value'))
self.positive_gradient = Sequence(kwargs.get('positive_gradient'))
self.negative_gradient = Sequence(kwargs.get('negative_gradient'))
self.variable_costs = Sequence(kwargs.get('variable_costs'))
self.fixed_costs = kwargs.get('fixed_costs')
```

Otherwise it should look like this.

```diff
- self.fixed_costs = kwargs.get('fixed_costs')
+ self.fixed_costs = Sequence(kwargs.get('fixed_costs'))
```

I think the code is right and the documentation is wrong because I cannot think of a scenario with time-variable fixed costs. They should be summed up, so it would be rather confusing.

**Comment by simnh** [comment]
> I think the code is right and the documentation is wrong because I cannot think of a scenario with time-variable fixed costs. They should be summed up, so it would be rather confusing.

I agree, can you fix the docs @uvchik  ? (Probably a copy-past error... ;) )

**Comment by ckaldemeyer** [comment]
> I agree, can you fix the docs @uvchik ? (Probably a copy-past error... ;) )

:+1:

**Comment by uvchik** [comment]
```diff
-    fixed_costs : numeric (sequence or scalar)
-        The costs associated with the absolute nominal_value of the flow.
+    fixed_costs : numeric
+        The costs of the whole period associated with the absolute nominal_value of the flow.
```

Is this okay.

**Comment by simnh** [comment]
Or the investment if investment exits...but this is the nominal value after optimization, so I think it s fine

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
Done!
