### ISSUE TITLE
Solph-Constraint Sandbox?

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#280]
Ola! 

We already talked about that, but we do not have a place at the moment for this. What I was thinking is a module where we collect functions that allow to add additional constraints that people can use inside their apps. For example one function could look like this: 
```
def flow_share(om, f1, f2, share):
    """
    """
    _def flow_rule(m, t):
        return m.flow[f1, t] == m.flow[f2, t] * share
    om.flow_share_constraint = po.Constraint(om.TIMESTEPS, rule=_flow_rule)

```

I frequently have such functions, so I think a oemof place to share it would be nice...

What do you think?

**Comment by ckaldemeyer** [comment]
You mean similar to this example? 

https://github.com/oemof/oemof/tree/dev/examples/solph/flexible_modelling

Sounds like a good idea and for me it would be a no-regret as the code is hidden and does not affect any functionalities. On the other hand it has to be maintained. But if the functions are commonly used its definetely an improvement!

**Comment by ckaldemeyer** [comment]
Concerning you provided example I am not sure if it should be externally or basic functionality as I stumbled upon this lacking functionality last week

**Comment by simnh** [comment]
yes kind of in this example. I mean, it can also be used as an example collection of functions, for users who need adapt their models. 

> Concerning you provided example I am not sure if it should be externally or basic functionality as I stumbled upon this lacking functionality last week

Well I thought, internal in a sense of a solph module but external in a sense of the creation of contraints from parameter settings...In this way it's inside oemof and we can see whether some of the functionality inside the 'sandbox' has to be integrated in the 'solph-core' .

**Comment by ckaldemeyer** [comment]
> Well I thought, internal in a sense of a solph module but external in a sense of the creation of contraints from parameter settings...In this way it's e.g. inside oemof.solph.sandbox and we can see whether some of the functionality inside the 'sandbox' has to be integrated in the 'solph-core' .

Sound very good!!!

**Comment by simnh** [comment]
I talked to @gnn and the proposed why is as follows: 

* create class like 'Container' where we add additional constraint functionality
* Add this class as a parent to OperationalModel, i.e. subclassing from two classes
* In this way we can use all methods of the container classes as methods inside the operationalmodel

This procedure is called 'mix-in' and should be the best way to do it. Only thing we need to check which class of the two we are subclassing from comes first ( most likely the new 'Container' class). 
Additionally we need to make sure that the Container class will not hold any class variables, but this should be no problem. 

I think it a great solution, because users will just get delivered new methods without the need of importing anything new. I will try to make a proposal soon on a feature branch

**Comment by ckaldemeyer** [comment]
> talked to @gnn and the proposed why is as follows:
> 
> create class like 'Container' where we add additional constraint functionality
> Add this class as a parent to OperationalModel, i.e. subclassing from two classes
> In this way we can use all methods of the container classes as methods inside the operationalmodel
> This procedure is called 'mix-in' and should be the best way to do it.

I have heard and read multiple times that one should avoid multiple inheritance as it is like opening pandoras box as you don't know where the stuff in your actual class comes from, etc.

See also here: https://learnpythonthehardway.org/book/ex44.html

"Avoid multiple inheritance at all costs, as it's too complex to be reliable. If you're stuck with it, then be prepared to know the class hierarchy and spend time finding where everything is coming from."

Maybe we just use composition instead?

**Comment by ckaldemeyer** [comment]
But I agree that it's a cool functionality. But we should be sharp when it comes to completely new concepts such as multiple inheritance

**Comment by simnh** [comment]
In our case I do not see any problems as we just provide methods to manipulate the opt-model and we might change the inner structure later anyway.  But of course it's an important point to consider..

I do not know how to implement this. with this pull-request: #284 the Mulit-inheritance proposal exist. If somebody else want to make another proposal - feel free. Otherwise I suggest moving forward.

**Comment by ckaldemeyer** [comment]
> In our case I do not see any problems as we just provide methods to manipulate the opt-model and we might change the inner structure later anyway. But of course it's an important point to consider..
> 
> I do not know how to implement this. with this pull-request: #284 the Mulit-inheritance proposal exist. If somebody else want to make another proposal - feel free. Otherwise I suggest moving forward.

I don't understand what speaks against you first suggestion of using functions having the om and other stuff as arguments. For me this would be much cleaner as it doesn't touch anything and is "minimal invasive". And you can still re-use functions in functions.

> I do not know how to implement this. with this pull-request: #284 the Mulit-inheritance proposal exist. If somebody else want to make another proposal - feel free. Otherwise I suggest moving forward.

I don't like the multiple inheritance solution as I said but don't have time to make a suggestion. Composition could work like described [here](https://codefellows.github.io/sea-python-401d4/lectures/inheritance_v_composition.html) and you could just instantiate an om with its args and then write methods that work on obj.self.

**Comment by uvchik** [comment]
Is it possible to inherit form the OM (I use the short version)?

Rename the OM to OM_basic. 
Create an OM class that inherits from OM_basic and has all the additional constraints.
Create an OM_experimental or OM_testing class that inherits from OM and has all experimental constraints.

If you want to use the additional constraints you have to change nothing. If you want to exclude the additional methods you have to use OM_basic and if you want to use the experimental stuff you can use OM_experimental. Normally an additional method will not break the system. 

Is this possible? What do you think?

If you want to write your own OM, @simnh might be better because you can still include the additional constraints.

First of all I do not want to stop @simnh, because I like the idea. We still we be able to change his approach later with little effort.

**Comment by ckaldemeyer** [comment]
> Is it possible to inherit form the OM (I use the short version)?
> 
> Rename the OM to OM_basic.
> Create an OM class that inherits from OM_basic and has all the additional constraints.
> Create an OM_experimental or OM_testing class that inherits from OM and has all experimental constraints.
> 
> If you want to use the additional constraints you have to change nothing. If you want to exclude the additional methods you have to use OM_basic and if you want to use the experimental stuff you can use OM_experimental. Normally an additional method will not break the system.
> 
> Is this possible? What do you think?

I think this is possible without problems but adding more classes is not really lean from my point of view and i like the idea of just having one om-class that is manipulated and adapted to the needs of the user.

> First of all I do not want to stop @simnh, because I like the idea. We still we be able to change his approach later with little effort.

As I said I also like the functionality and general idea. But what do you think about the idea @simnh suggested first of having a collections of "om-manipulation-functions" @uvchik ?

**Comment by ckaldemeyer** [comment]
Concerning your proposal I would not change any class names but just inherit/composite from the normal om for the added functionality. This should also work.

**Comment by simnh** [comment]
I still really like the mixin idea because of various reasons: 

* it's simple 
* can be used in different models
* we can add mixin-classes for other purpose (variable manipulation etc etc)

I will check with @gnn regarding your concerns and then implement it as it is on the feature branch right now. If we run into trouble we can still inherit as @uvchik suggested..(which I must admit sounds good as well. 
We could then just provide a model with extension:  `OperationalModelExt`, so users can either import OperationalModel or the new one.

**Comment by ckaldemeyer** [comment]
> I still really like the mixin idea because of various reasons:
> 
> it's simple
> can be used in different models
> we can add mixin-classes for other purpose (variable manipulation etc etc)

I also don't want to hinder you if you are bringing in new stuff. They were just objections..

> I will check with @gnn regarding your concerns and then implement it as it is on the feature branch right now. If we run into trouble we can still inherit as @uvchik suggested..(which I must admit sounds good as well.

As I said I would also like @uvchik s one parent inheritance solution but slightly changed without renaming the basic om but just `class FancyModel(OperationalModel)` and then add all the stuff.

This would be lean and straightforward without multiple inheritance and adheres to a good architectual style according to [this source](https://codefellows.github.io/sea-python-401d4/lectures/inheritance_v_composition.html):

> When overriding behavior for a subclass, remember that in good OO programming a subclass should be substantially similar to its parents. If you have a system which uses the parent class, you should be able to use the subclass in all the same places, and in all the same ways. This is known as the “Liskov Substitution Principle”. The authors of Think Python put it this way:
>> whenever you override a method, the interface of the new method should be
the same as the old.  It should take the same parameters, return the same
type, and obey the same preconditions and postconditions.
>> If you obey this rule, you will find that any function designed to work
with an instance of a superclass, like a Deck, will also work with
instances of subclasses like a Hand or PokerHand.  If you violate this
rule, your code will collapse like (sorry) a house of cards.
>> -- [ThinkPython 18.10]

**Comment by uvchik** [comment]
I have to admit that my approach does not work if you have your own model as OperationalModelExt does inherit from OperationalModel but not from SimSpecialModel.

Check out with @gnn and go ahead. We can gather experiences and then present the ultimate solution in v0.2.0 :smirk:

**Comment by ckaldemeyer** [comment]
> I have to admit that my approach does not work if you have your own model as OperationalModelExt does inherit from OperationalModel but not from SimSpecialModel.

I thought that @simnh s idea was just to have the possibility to provide additional constraints e. g. for flow shares ,etc. and with OperationalModelExt inheriting from om it could realize that.

If someone has some fancy models for certain technologies I am not sure if he would use the extended model but rather go in another direction such as HESYSOPT. Al leat I am planning to imlement our project stuff in the same or a similar structure.

> Check out with @gnn and go ahead. We can gather experiences and then present the ultimate solution in v0.2.0

That's maybe the best idea :smile:

**Comment by simnh** [comment]
We have decided to have a module with additional constraints...
