### ISSUE TITLE
Linear m:1 Transformer inside solph?

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#281]
We do not have one do we? Should we add one to solph.blocks? It's basically just inverting the 'LinearTransformer'...But we would ne a class name.

**Comment by uvchik** [comment]
:+1:  Good idea. I did something in this direction for the old solph. But I would do it more generic this time as I did it last time.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by ckaldemeyer** [comment]
To fix this here we agreed on

* N1Transformer
* NMTransformer (hidden magic without docs, etc.)

in the web conference

**Comment by uvchik** [comment]
Have a look at #287. We may add an nm-Transformer without changing the API.

**Comment by simnh** [comment]
closed in favour of #287
