### ISSUE TITLE
improve installation guide

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#283]
@birgits : I would keep it more simple:

1. Download latest Anaconda for Python 3.x (64 or 32 bit)
2. Install Anaconda
3. Open the ‘Anaconda Prompt’ and create a virtual environment by typing: 
      ```
      conda create -n yourenvname python=3.4
      activate yourenvname
    ```
    _It is recommended to use python 3.4. Some users reported, that oemof does not work with
    Windows + Anaconda + Python 3.5_
4. In ‘Anaconda Prompt’ type: pip install oemof
5. Install a Windows Solver if you want to use solph and execute the solph examples (See Run examples to check the installation ) to check if the installation of the solver and oemof was successful

**Comment by uvchik** [comment]
We may add that the 3.5-problem is not an oemof issue and that it could be already solved.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group 

Does anybody uses Linux + Anaconda?

Could you test python 3.5 there?

Travis-CI tested Python 3.5 and it should work.

**Comment by ckaldemeyer** [comment]
> Does anybody uses Linux + Anaconda?

Yes, me.

> Could you test python 3.5 there?

I have 3.5.2 and never had any errors. But I didn't install via pip and use the dev-Branch.

**Comment by uvchik** [comment]
So, how did you installiert oemof?

**Comment by ckaldemeyer** [comment]
> So, how did you installiert oemof?
>> But I didn't install via pip and use the dev-Branch instead.

**Comment by ckaldemeyer** [comment]
I can test it in a new environment of you want

**Comment by ckaldemeyer** [comment]
I'll post the result..

**Comment by uvchik** [comment]
Yes

**Comment by uvchik** [comment]
From inside your ve.

**Comment by ckaldemeyer** [comment]
> Yes

It has to be run from the environment and not from the oemof package folder and the command is `oemof_examples`and not `oemof_example` as in the [documentation](http://oemof.readthedocs.io/en/stable/installation_and_setup.html#run-examples-to-check-the-installation).

But it works as expected if glpk is installed:

	cord@cord-Laptop:~$ cd .anaconda3/bin/
	cord@cord-Laptop:~/.anaconda3/bin$ source activate test
	(test) cord@cord-Laptop:~/.anaconda3/bin$ oemof_examples simple_least_costs
	09:01:55-INFO-Path for logging: /home/cord/.oemof/log_files
	09:01:55-INFO-Used oemof version: 0.1.1
	09:01:55-INFO-Creating objects
	09:01:55-INFO-Create optimization problem
	09:01:58-INFO-Solve optimization problem
	GLPSOL: GLPK LP/MIP Solver, v4.57
	Parameter(s) specified in the command line:
	 --write /tmp/tmpytnff3zb.glpk.raw --wglp /tmp/tmp1h4vdzog.glpk.glp --cpxlp
	 /tmp/tmp6a7jwb9k.pyomo.lp
	Reading problem data from '/tmp/tmp6a7jwb9k.pyomo.lp'...
	16001 rows, 24001 columns, 38001 non-zeros
	120012 lines were read
	Writing problem data to '/tmp/tmp1h4vdzog.glpk.glp'...
	104007 lines were written
	GLPK Simplex Optimizer, v4.57
	16001 rows, 24001 columns, 38001 non-zeros
	Preprocessing...
	1915 rows, 7660 columns, 7660 non-zeros
	Scaling...
	 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
	Problem data seem to be well scaled
	Constructing initial basis...
	Size of triangular part is 1915
	      0: obj =   4.687770098e+05 inf =   8.620e+04 (1915)
	    500: obj =   7.144723125e+05 inf =   7.638e+04 (1881)
	   1000: obj =   9.494598891e+05 inf =   6.698e+04 (1803)
	   1500: obj =   1.189913087e+06 inf =   5.736e+04 (1743)
	   2000: obj =   1.482683451e+06 inf =   4.707e+04 (1628)
	   2500: obj =   2.084934829e+06 inf =   3.201e+04 (1269)
	   3000: obj =   2.688516261e+06 inf =   1.692e+04 (880)
	   3500: obj =   3.179545657e+06 inf =   4.644e+03 (452)
	   3966: obj =   3.331430091e+06 inf =   0.000e+00 (0)
	*  4000: obj =   3.324182445e+06 inf =   0.000e+00 (2232)
	*  4500: obj =   3.207953096e+06 inf =   0.000e+00 (1796)
	*  5000: obj =   3.109461520e+06 inf =   0.000e+00 (1057)
	*  5500: obj =   3.002466179e+06 inf =   0.000e+00 (533)
	*  6000: obj =   2.949382276e+06 inf =   0.000e+00 (55)
	*  6055: obj =   2.947725175e+06 inf =   0.000e+00 (0)
	OPTIMAL LP SOLUTION FOUND
	Time used:   0.4 secs
	Memory used: 16.6 Mb (17376236 bytes)
	Writing basic solution to '/tmp/tmpytnff3zb.glpk.raw'...
	40004 lines were written
	09:02:01-INFO-Plot results
	09:02:06-INFO-Check the results
	{'objective': 2947725.1748075397,
	 ('b_el', 'from_bus', 'demand_el', 'val'): 132243.7904593189,
	 ('b_el', 'from_bus', 'excess', 'val'): 928.12144333649996,
	 ('b_el', 'to_bus', 'pp_chp', 'val'): 11161.357377179973,
	 ('b_el', 'to_bus', 'pp_coal', 'val'): 33723.047183696115,
	 ('b_el', 'to_bus', 'pp_gas', 'val'): 30412.376282889993,
	 ('b_el', 'to_bus', 'pp_lig', 'val'): 22066.451107577774,
	 ('b_el', 'to_bus', 'pp_oil', 'val'): 2.2872602814999681,
	 ('b_el', 'to_bus', 'pv', 'val'): 7796.8431880300122,
	 ('b_el', 'to_bus', 'wind', 'val'): 28009.549502999955,
	 ('b_th', 'from_bus', 'demand_th', 'val'): 14881.80983624002,
	 ('b_th', 'to_bus', 'pp_chp', 'val'): 14881.80983624002,
	 ('coal', 'from_bus', 'pp_coal', 'val'): 86469.351753067938,
	 ('gas', 'from_bus', 'pp_chp', 'val'): 37204.524590599875,
	 ('gas', 'from_bus', 'pp_gas', 'val'): 60824.752565779985,
	 ('lignite', 'from_bus', 'pp_lig', 'val'): 53820.612457507486,
	 ('oil', 'from_bus', 'pp_oil', 'val'): 8.1687867196427497}
	(test) cord@cord-Laptop:~/.anaconda3/bin$ 

By the way: Didn't we change the default solver to CBC?

**Comment by ckaldemeyer** [comment]
> It has to be run from the environment and not from the oemof package folder and the command is oemof_examplesand not oemof_example as in the documentation.

Should I adapt the documentation?

**Comment by ckaldemeyer** [comment]
> Open the ‘Anaconda Prompt’ and create a virtual environment by typing:
> conda create -n yourenvname python=3.4
> activate yourenvname
> It is recommended to use python 3.4. Some users reported, that oemof does not work with
> Windows + Anaconda + Python 3.5

For linux it is `source activate` instead of `activate`. I can also adjust that

**Comment by birgits** [comment]
@ckaldemeyer I already changed `oemof_example` to `oemof_examples` in the documentation since I had the same problem. You can find my changes if you go to the latest documentation.
As for the `source activate` - as you said that only applies for Linux users but what you cited is in the Windows installation section. There is no installation guide for Anaconda and Linux yet, at least not in the latest documentation on rtd.  Maybe we could add it though.

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer I already changed oemof_example to oemof_examples in the documentation since I had the same problem. You can find my changes if you go to the latest documentation.

Oh, I didn't have a look. Thanks.

> As for the source activate - as you said that only applies for Linux users but what you cited is in the Windows installation section. There is no installation guide for Anaconda and Linux yet, at least not in the latest documentation on rtd. Maybe we could add it though.

Would it be an option to just adapt the Anaconda method to "[Windows/Linux] using Anaconda" like [here](http://docs.callio.pe/en/stable/user/installation.html)?

**Comment by ckaldemeyer** [comment]
And what do you think about the GLPK/CBC question? Should we change the documentation/examples to CBC completely?

**Comment by birgits** [comment]
@uvchik I will change the Windows Anaconda installation according to what you suggested in your first comment.
In an email you suggested to include a section with known installation problems with the following data:  [OS | Python-Version | Python-Distribution? | number of reports | problem]. I think that is quite a good idea. It will just be difficult to keep it up to date since problems might be solved at some point and should be taken of the list. What do you think?  I also think that the number of reports could serve as a good indicator as to whether it is a common problem or only one persons, but since there won't be that many reports yet it might be unnecessary.

**Comment by birgits** [comment]
> Would it be an option to just adapt the Anaconda method to "[Windows/Linux] using Anaconda" like here?

Sounds good! I could do it if you want!

**Comment by uvchik** [comment]
> In an email you suggested to include a section with known installation problems with the following data: [OS | Python-Version | Python-Distribution? | number of reports | problem]. I think that is quite a good idea. It will just be difficult to keep it up to date since problems might be solved at some point and should be taken of the list. What do you think? I also think that the number of reports could serve as a good indicator as to whether it is a common problem or only one persons, but since there won't be that many reports yet it might be unnecessary.

@birgits You are right. I thought the same, when I wrote the comment above. If we will have more such report we could open a wiki and link to the wiki. It is easier to keep a wiki up to date.

**Comment by uvchik** [comment]
> Would it be an option to just adapt the Anaconda method to "[Windows/Linux] using Anaconda" like here?

At the moment users go to their OS-section and read. 

@ckaldemeyer So how do you want to do it? An extra Anaconda-section and then link from the different OS-sections? I would keep the structure as it is.

**Comment by uvchik** [comment]
> And what do you think about the GLPK/CBC question? Should we change the documentation/examples to CBC completely?

The best thing would be a basic example with try/except that tries CBC and then GLPK and than reports something like:

oemof: okay
CBC: failed, check CBC-page or pyomo-page
GLPK: failed, check GLPK-page or pyomo-page

People could see that oemof works but CBC and GLPK do not work at all or do not work with pyomo.

**Comment by uvchik** [comment]
@ckaldemeyer : Thank you for testing the Anaconda/3.5 issue :+1: :smile:

**Comment by uvchik** [comment]
> And what do you think about the GLPK/CBC question? Should we change the documentation/examples to CBC completely?

#247

**Comment by ckaldemeyer** [comment]
> Sounds good! I could do it if you want!

:+1: 

> @ckaldemeyer So how do you want to do it? An extra Anaconda-section and then link from the different OS-sections? I would keep the structure as it is.

Maybe we just add the Anaconda section to the Linux part and link from there to the Windows part with a hint "the instructions are the same with the difference of SOURCE activate"?

Just one idea..

@birgits : Could you do it?

> The best thing would be a basic example with try/except that tries CBC and then GLPK and than reports something like:

You are right. But I think it's easier to just adapt the examples quickly only for CBC.

> #247

Oh, thanks! I missed that one!

**Comment by uvchik** [comment]
> Maybe we just add the Anaconda section to the Linux part and link from there to the Windows part with a hint "the instructions are the same with the difference of SOURCE activate"?
> 
> Just one idea..
> 
> @birgits : Could you do it?

I would add an Anaconda-section to Linux. There are 4 steps and some are different. The download link is different (okay, that's not a big deal), I think the Anaconda-Prompt is not an Anaconda-Prompt in Linux and starting and virtualenv is different. Only creating a virtualenv is the same, but this differs also because it does not work with 3.5 while under Linux people should use 3.5.

**Comment by ckaldemeyer** [comment]
> I would add an Anaconda-section to Linux. There are 4 steps and some are different. The download link is different (okay, that's not a big deal), I think the Anaconda-Prompt is not an Anaconda-Prompt in Linux and starting a virtualenv is different. Only creating a virtualenv is the same, but this differs also because it does not work with 3.5 while under Linux people should use 3.5.

I am also fine with this

**Comment by uvchik** [comment]
@birgits : I added a testing example (see: #247 / 1ac8d787df). We could add it here: http://oemof.readthedocs.io/en/stable/installation_and_setup.html#run-examples-to-check-the-installation

The output looks like this:
```
*********
Solver installed with oemof:
gurobi: not working
cbc: working
cplex: not working
glpk: working
*********
oemof successfully installed.

```

**Comment by ckaldemeyer** [comment]
#244 

I think this has been resolved now.

**Comment by birgits** [comment]
> @birgits : I added a testing example (see: #247 / 1ac8d78). We could add it here: http://oemof.readthedocs.io/en/stable/installation_and_setup.html#run-examples-to-check-the-installation

@uvchik your changes aren't in the dev branch yet, should I add the documentation already anyway? Is the example used to check the installed solvers or the oemof installation as well?

**Comment by uvchik** [comment]
I added the links to the new example but the new example is in the revise_examples branch.

The example uses solph to check the solvers. Therefore oemof should work. But it is not a full oemof test. But if solph works the rest should basically work, too.

**Comment by uvchik** [comment]
I made some more changes. The result can be seen [here](http://oemof.readthedocs.io/en/latest/installation_and_setup.html).

**Comment by birgits** [comment]
So does it mean you added your new example to the documentation or should I still do it?

**Comment by uvchik** [comment]
It's done but in PR #247. So you cannot see it at readthedocs.

**Comment by uvchik** [comment]
PR #247 is merged.

@ckaldemeyer, @birgits Please have a look, if your changes look as expected before we will release on Monday evening (oemof.readthedocs.io/en/latest).

**Comment by birgits** [comment]
Looks good!

**Comment by uvchik** [comment]
Okay, will be release in the actual state.
