### ISSUE TITLE
Divide solph components into generic and specific ones

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#286]
Memos from the web conference:

* solph components should be divided into generic and specific ones
  * generic components: Source, Sink, 1NTransformer, N1Transformer, NMTransformer
  * specific components: Storage, VariableFractionTransformer
* specific components can be build from generic components or with an internal logic (overall 3 layers)
* @ckaldemeyer with propose a new structure in a feature branch (preferred) or separate repository and implement e. g. a CAES component to test if the approach works as expected
* new ideas and other stuff will be discussed within the group

**Comment by ckaldemeyer** [comment]
I have now made up my mind a bit and would like to share my ideas!

Goals for solph from a bird's-eye perspective:

* Usability
* Low-entry barrier
* Flexibility in terms of new components

Current structure:

* Numerous classes in single modules (e.g. `network.py` and `blocks.py`)
* Logical/semantic units are partly spread across different modules (e.g. a component has a network class and a solph block class)
* New components have to be added manually in `models.py` and `groupings.py`

Thoughts/cites based on different sources concerning code organisation [1,2,3,4,5]:

* Class definition
  * Classes should be build using the [Single Reponsibility Principle (SRP)](https://en.wikipedia.org/wiki/Single_responsibility_principle)
  * A system of classes should consist of many small classes with single responsibilities
* Project/code/class organisation
  * There is no single correct answer but classes are usually grouped in a single source file (e.g. a Python module) if they form a logically self-contained unit of inter-dependant classes
  * "Think in terms of a "logical unit of packaging" which may be a single class, but more often will be a set of classes that closely cooperate"
  * "A module is a distinct thing that may have one or two dozen closely-related classes. The trick is that a module is something you'll import, and you need that import to be perfectly sensible to people who will read, maintain and extend your software. The rule is this: a module is the unit of reuse."
  * "Using a good package organization, even new programmer who read your code will be able to quickly understand your application structure."

So my idea was to think about a structure of Python packages and modules without re-inventing the wheel!

The current structure looks like the following:

* __init__.py
* blocks.py (responsible for for blocks used in at least one component -> N:M relation)
* groupings.py (responsible for the grouping functionalities)
* inputlib (responsible for creating nodes -> currently contains the csv-reader)
  * __init__.py
  * csv_tools.py
* models.py  (responsible for the overall operational/invest/... model including sets, constraint and objective creation, methods to solve it and get additional information and result processing)
* network.py (responsible for inherited core and new solph classes and related functions)
* options.py  (responsible for classes that for some reason do not fit in network.py)
* plumbing.py (responsible for helper functions that should be provided for within other files)

An my sketched idea for a new structure looks like this:

* __init__.py
* main.py/model.py (responsible for abovementioned funcs + automatic component integration)
* components (responsible for components where the network and block classes are stored within one module per component)
  * __init__.py
  * investment.py
  * flow.py
  * ...
  * some_fancy_component.py
* inputlib (responsible for creating nodes)
  * __init__.py
  * csv_tools.py
* misc (responsible for misc)
  * __init__.py
  * plumbing.py
  * groupings.py
* outputlib (responsible for creating results and integrating results for new components)
  * __init__.py
  * to_dict.py
  * to_dataframe.py

So the idea would be be that the only thing I have to do to add a new component (e.g. a CAES plant) is to create a new module within the package `components`. I know that the name `components` is misleading and I am open for other suggestions. But the general idea would be to have the possibility to easily create new components by only adding a module and having everything "at a glance".

This is of course only a sketch and for discussion. But what do you think about this?

Cheers
Cord

[1] https://www.amazon.de/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882
[2] https://bytes.com/topic/python/answers/25419-best-practices-how-organize-classes
[3] http://stackoverflow.com/questions/1801878/the-pythonic-way-of-organizing-modules-and-packages
[4] http://stackoverflow.com/questions/106896/how-many-python-classes-should-i-put-in-one-file
[5] htttp://pythonthusiast.pythonblogs.com/230_pythonthusiast/archive/1395_part_3_addendum_how_python_organize_your_application_code.html

**Comment by ckaldemeyer** [comment]
@uvchik @s3pp @simnh It would be nice to get some feedback!

**Comment by ckaldemeyer** [comment]
Memo to myself after talking to @simnh : 

* Generic part (sink, source, transformer) on upper level
* Specific part somewhere else e.g. in for of a package

**Comment by ckaldemeyer** [comment]
After talking to @uvchik and beeing afraid of a long-taking solph-restructering-process, the option to implement very user specific components using a mix-in (as in https://github.com/oemof/oemof/issues/280 ) or just by subclassing/composition popped into my mind:

1.) OperationalModel(MyAdditionalClassWithConstraintsOrSpecificComponentModels, pyomo.ConcreteModel)
  * OM holds oemof and specific component models from mix-in class and these models are linked via constraints flow[i, o, t] = my_fancy_var[t]
  * OM integrates result processing for specific components from mix-in class

2.) MyFancyModel(OperationalModel)
  * MFM implements specific component models in addition to existing oemof component models and these models are linked via constraints flow[i, o, t] = my_fancy_var[t]
  * MFM overrides result dict and adds "virtual bus" that includes specific component results or creates a specific result object

I quite like the second option as it is minimal-invasive, comes without multiple-inheritance and does not touch anything. And maybe there's even a way to integrate well with the improved ResultDataFrame.

Or am I missing something?

I'll think about this over the weekend and enjoy the sun now :smile:

**Comment by ckaldemeyer** [comment]
> I'll think about this over the weekend and enjoy the sun now

I have thought about this and do not like the "hard coded" idea of subclassing for special components anymore. To me it should be possible to flexibly add new components either in a generic structure as the one proposed above (which needs some changes and collaboration) or on an app level like in HESYSOPT, etc.

@uvchik : Did you have any new ideas or insights?

If not, my idea was the following for my special components:

* Fork/use HESYSOPT and implement components on an app level
* See how the result-df integrates special results and adapt it
* [Port new classes to oemof if they're relevant/interesting]

**Comment by uvchik** [comment]
I agree. I think it is a good idea to help people building new components. Later we should find a place where we can integrate cool components into solph.

I think two steps will help people to do this
* @simnh 's approach to add constraints (#284)
* your idea of improving the results-DF to make it easier to find the results of own components

We should focus on this instead of spending to much time in restructuring solph again.

@ckaldemeyer Did I get your idea right?

**Comment by ckaldemeyer** [comment]
> I agree. I think it is a good idea to help people building new components. Later we should find a place where we can integrate cool components into solph.
> 
> I think two steps will help people to do this
> 
> @simnh 's approach to add constraints (#284)
> your idea of improving the results-DF to make it easier to find the results of own components
> We should focus on this instead of spending to much time in restructuring solph again.
> 
> @ckaldemeyer Did I get your idea right?

Yes. An we keep on doing things instead of discussing (which often of course is good and add extra value) :smile:

**Comment by simnh** [comment]
I really like the restructuring...

**Comment by simnh** [comment]
I vote for restructuring as @ckaldemeyer suggested...give it a shot!!!

Let's get specific with components, enough of that generic stuff :)

**Comment by uvchik** [comment]
> Let's get specific with components, enough of that generic stuff :)

Interesting. Something happened in Flensburg :smirk:

**Comment by uvchik** [comment]
Sorry, wrong button :blush:

**Comment by ckaldemeyer** [comment]
Did you delete the feature branch?

**Comment by ckaldemeyer** [comment]
I once started on `features/generic-and-specific-solph-components` :D

**Comment by uvchik** [comment]
Normally I do not delete open branches, so I think I didn't.

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/pull/300

@oemof/oemof-solph : Please have a look as I want to make progress here :smile:
