### ISSUE TITLE
Add TransformerNM

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#287]
API of actual LinearTransformer (for 2 outputs):

```python
LinearTransformer(
    label="something",
    inputs={bus_in1: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5})
```

We could extend this API to allow multiple inputs AND multiple outputs:

### Version 1:
```python
LinearTransformer(
    label="something",
    inputs={bus_in1: Flow(),
            bus_in2: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5,
                        bus_in1: 1.5,
                        bus_in2: 3})
```

### Version 2:
```python
LinearTransformer(
    label="something",
    inputs={bus_in1: Flow(),
            bus_in2: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={'out': {bus_out1: 0.3,
                                bus_out2: 0.5},
                        'in': {bus_in1: 1.5,
                               bus_in2: 3})
```

### Version 3:
```python
LinearTransformer(
    label="something",
    inputs={bus_in1: Flow(),
            bus_in2: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors_out={bus_out1: 0.3,
                            bus_out2: 0.5}
    conversion_factors_in={bus_in1: 1.5,
                           bus_in2: 3})
```

The first version might be a little bit more difficult under the hood, but the nice thing is, that it does not break the API.

@oemof/oemof-solph : What do you think? Which version do you prefer? A 4th version?

**Comment by uvchik** [comment]
If we use the first version we just have to make sure, that we add non existing conversion factors with 1, but this will not be a problem in the transformer network class.

In the transformer block class we just have to add one more loop (looping the input flows).

In my opinion this is much more straight forward than n1 and 1n Transformer.

**Comment by ckaldemeyer** [comment]
> The first version might be a little bit more difficult under the hood, but the nice thing is, that it does not break the API.
> 
> @oemof/oemof-solph : What do you think? Which version do you prefer? A 4th version?

I would also prefer the first version but just rename it to `Transformer` as in solph everything is linear.

> If we use the first version we just have to make sure, that we add non existing conversion factors with 1, but this will not be a problem in the transformer network class.
> 
> In the transformer block class we just have to add one more loop (looping the input flows).
> 
> In my opinion this is much more straight forward than n1 and 1n Transformer.

:+1:

**Comment by uvchik** [comment]
>... but just rename it to Transformer as in solph everything is linear.
:+1:

**Comment by simnh** [comment]
I do not jet understand to which constraints this will resolve. Do I miss something here? 

is it: 

inflow1 * inflow_factor1 + inflow2 + inflow_factor2 + inflowM * inflow_factorM= outflow1 + outflow2 + outfowN

or (mapping first to first etc) : 
inflow1 * inflow_factor1 = outflow1 

At the moment it is clear when we have 1:N or N:1 because we only have 1 flow on the in OR outflow.

**Comment by uvchik** [comment]
Actually we can create an NxM-Transformer by connecting the Nx1 and 1xN Transformer using a bus. If I am right this would end in the following constraints (1N, N1 and Bus)

![n1_1n_transf](https://cloud.githubusercontent.com/assets/4760584/23677720/92649ec0-0381-11e7-949b-9a63d6a29f21.png)

My idea is to connect the equations directly. 

![nm_transf](https://cloud.githubusercontent.com/assets/4760584/23677727/9a1b68f6-0381-11e7-969e-4427e0b26ac7.png)

The LP-file for one time step would change from::
```
1N: in1*fi1=out
    in2*fi2=out, ...

N1: in=out/fo1
    in=out/fo2, ....

BUS: out=in
```
to:
```
in1*fi1 = out/fo1
in1*fi1 = out/fo2
in2*fi1 = out/fo1
in2*fi1 = out/fo2
...
```

I hope I did not forget anything.

**Comment by ckaldemeyer** [comment]
Maybe just staying with `N1Transformer` and `1NTransformer` (LinearTransformer) would also be o.k. as its straightforward and N:M relationships can be build from it. In most cases it will be 1:N/N:1 anyway I would guess ;)

**Comment by uvchik** [comment]
The interesting thing is that the API stays the same. So it might not be more difficult for the user in most cases.

```python
Transformer1N(
    label="something",
    inputs={bus_in1: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5})

TransformerNM(
    label="something",
    inputs={bus_in1: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5})
```

```python
TransformerN1(
    label="something",
    inputs={bus_in1: Flow(),
            bus_in2: Flow()},
    outputs={bus_out1: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5})

TransformerNM(
    label="something",
    inputs={bus_in1: Flow(),
            bus_in2: Flow()},
    outputs={bus_out1: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_in1: 1.5,
                        bus_in2: 3})
```

But I do not have to do it if you do not like it. I just thought it would be consequent.

**Comment by ckaldemeyer** [comment]
For the N1/1N cases we have a clearly input/output centralised view:

            flow(i, n, t) * conversion_factor(i, n, t) = flow(n, o, t) [N1Transformer]
            flow(i, n, t) * conversion_factor(n, o, t) = flow(n, o, t) [1NTransformer]

leading to N equations depending on the number of inputs or outputs.

Let's take the example from above:

	LinearTransformer(
	    label="something",
	    inputs={bus_in1: Flow(),
		    bus_in2: Flow()},
	    outputs={bus_out1: Flow(),
		     bus_out2: Flow()},
	    conversion_factors={bus_out1: 0.3,
		                bus_out2: 0.5,
		                bus_in1: 1.5,
		                bus_in2: 3})

In your example it would look like:

            flow(bus_in1, LT, t) * conversion_factor(bus_in1, LT,, t) = flow(LT, o?, t) [N1Transformer]
            flow(bus_in2, LT, t) * conversion_factor(bus_in2, LT,, t) = flow(LT, o?, t) [N1Transformer]
            flow(i?, LT, t) * conversion_factor(LT, bus_out1, t) = flow(LT,  bus_out1, t) [1NTransformer]
            flow(i?, LT, t) * conversion_factor(LT, bus_out2, t) = flow(LT,  bus_out2, t) [1NTransformer]

So I need some kind of information about the relation between the flows in terms of "mapping of conversion factors" as soon as it gets an N:M relation, or not?

As long as it is N1/1N it would of course work and the equations could be build depending on the parametrisation.

Or am I missing something?

**Comment by uvchik** [comment]
I guess it would look like this. All inputs are connected with all outputs.
```python
flow(bus_in1, LT, t) * conversion_factor(bus_in1, LT, t) * conversion_factor(LT, bus_out1, t) = flow(LT,  bus_out1, t)
flow(bus_in1, LT, t) * conversion_factor(bus_in1, LT, t) * conversion_factor(LT, bus_out2, t) = flow(LT,  bus_out2, t)
flow(bus_in2, LT, t) * conversion_factor(bus_in2, LT, t) * conversion_factor(LT, bus_out1, t) = flow(LT,  bus_out1, t)
flow(bus_in2, LT, t) * conversion_factor(bus_in2, LT, t) * conversion_factor(LT, bus_out2, t) = flow(LT,  bus_out2, t)
```
It leads do n*m equations. 

**Short notation:**
```
in_flow1 * eta_in1 * eta_out1 = out_flow1
in_flow1 * eta_in1 * eta_out2 = out_flow2
in_flow2 * eta_in1 * eta_out1 = out_flow1
in_flow2 * eta_in1 * eta_out2 = out_flow2
...
```

**Comment by uvchik** [comment]
If you do it your way it looks pretty much the same:

```
in_flowN * eta_out1 = out_flow1
in_flowN * eta_out2 = out_flow2

in_flow1 * eta_in1 = out_flowN
in_flow2 * eta_in2 = out_flowN

in_flowN = out_flowN
```

I guess the presolve of the solver will dissolve the equations to the form above.

**Comment by ckaldemeyer** [comment]
> Short notation:
> 
> in_flow1 * eta_in1 * eta_out1 = out_flow1
> in_flow1 * eta_in1 * eta_out2 = out_flow2
> in_flow2 * eta_in1 * eta_out1 = out_flow1
> in_flow2 * eta_in1 * eta_out2 = out_flow2
> ...

Shouldn't this be:

    in_flow1 * eta_in1 * eta_out1 = out_flow1
    in_flow1 * eta_in1 * eta_out2 = out_flow2
    in_flow2 * eta_in2 * eta_out1 = out_flow1
    in_flow2 * eta_in2 * eta_out2 = out_flow2

if I follow your idea?

**Comment by uvchik** [comment]
Yes, this was a typo :smile:

**Comment by ckaldemeyer** [comment]
> Yes, this was a typo

Ah, o.k. I was a bit confused :smile: 

Anyhow, if I allow to add input- and output-wise  conversion factors I have to make sure they match to each other in combination with flow upper/lower bounds, etc. as otherwise a weird behaviour occurs or the problem becomes infeasable.

From my current view just staying with `1NTransformer` and `N1Transformer` would be a bit more specific and is less complex, reflects 95 % of all cases and reduces the potential  occurance of errors.

**Comment by ckaldemeyer** [comment]
By the way we could already implement an interface for `LinearTransformer` as `1NTransformer` via subclassing for the release from my point of view.

Of course only if we agree..

**Comment by uvchik** [comment]
> From my current view just staying with 1NTransformer and N1Transformer would be a bit more specific and is less complex, reflects 95 % of all cases and reduces the potential occurrence of errors.

Okay, I am fine with that and it is far better than discussing for weeks :smirk:

> By the way we could already implement an interface for LinearTransformer as 1NTransformer via subclassing for the release from my point of view.

Sorry, but the release is already done. But I think we can release again in May after the developer meeting.

**Comment by ckaldemeyer** [comment]
> By the way we could already implement an interface for LinearTransformer as 1NTransformer via subclassing for the release from my point of view.
> Sorry, but the release is already done. But I think we can release again in May after the developer meeting.

Oh, I totally missed that :smile: Thanks!

**Comment by uvchik** [comment]
> Anyhow, if I allow to add input- and output-wise conversion factors I have to make sure they match to each other in combination with flow upper/lower bounds, etc. as otherwise a weird behaviour occurs or the problem becomes infeasable.

The bounds and all other attributes (beside the conversion factors) belong to the flows and they will be the same if you connect an 1N and an N1 with a bus. Same thoughts, same source of errors, same chance of infeasibility. 

But as I said above I can live with 1N and N1 if you like it better.

**Comment by ckaldemeyer** [comment]
> Anyhow, if I allow to add input- and output-wise conversion factors I have to make sure they match to each other in combination with flow upper/lower bounds, etc. as otherwise a weird behaviour occurs or the problem becomes infeasable.
> The bounds and all other attributes (beside the conversion factors) belong to the flows and they will be the same if you connect an 1N and an N1 with a bus. Same thoughts, same source of errors, same chance of infeasibility.

Yes, but with the difference that this combination is far more unusual and if someone of the 5 % uses it, he will probably think more about it in advance.

> But as I said above I can live with 1N and N1 if you like it better.

:+1: I think this is far less prone to errors and more straightforward.

**Comment by uvchik** [comment]
> :+1: I think this is far less prone to errors and more straightforward.

I still do not agree because, if you think it is to complicate for you, you can do exactly the same with the NMTransformer. Nobody forces you to use more than one input or output.

CHP with 1NTransformer
```python
Transformer1N(
    label="chp",
    inputs={bus_in: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5})
```
CHP with Transformer (NM)
```python
Transformer(
    label="chp",
    inputs={bus_in: Flow()},
    outputs={bus_out1: Flow(),
             bus_out2: Flow()},
    conversion_factors={bus_out1: 0.3,
                        bus_out2: 0.5})
```

Your heat_pump example with TransformerN1:

```
cop = 3  # coefficient of performance of the heat pump

TransformerN1(
    label='heat_pump',
    inputs={bus_elec: Flow(), bus_low_temp_heat: Flow()},
    outputs={bus_th_high: Flow()},
    conversion_factors={bus_elec: cop,
                        b_th_low: cop/(cop-1)})
```


Your heat_pump example with Transformer (NM):

```
cop = 3  # coefficient of performance of the heat pump

Transformer(
    label='heat_pump',
    inputs={bus_elec: Flow(), bus_low_temp_heat: Flow()},
    outputs={bus_th_high: Flow()},
    conversion_factors={bus_elec: cop,
                        b_th_low: cop/(cop-1)})
```

The only difference is, that the Transformer (NM) can also cover a gas/coal driven chp-powerplant with one component instead of three (two transformer and a bus). But if you think it is too complicated for you, you can use the Transformer (NM) in the same manner as explained above and connect two of them with a bus you just do not have to do it.

**Comment by ckaldemeyer** [comment]
> I think this is far less prone to errors and more straightforward.
> I still do not agree because, if you think it is to complicate for you, you can do exactly the same with the NMTransformer. Nobody forces you to use more than one input or output.
> 
> CHP with 1NTransformer
> 
> Transformer1N(
>     label="chp",
>     inputs={bus_in: Flow()},
>     outputs={bus_out1: Flow(),
>              bus_out2: Flow()},
>     conversion_factors={bus_out1: 0.3,
>                         bus_out2: 0.5})
> CHP with Transformer (NM)
> 
> Transformer(
>     label="chp",
>     inputs={bus_in: Flow()},
>     outputs={bus_out1: Flow(),
>              bus_out2: Flow()},
>     conversion_factors={bus_out1: 0.3,
>                         bus_out2: 0.5})
> Your heat_pump example with TransformerN1:
> 
> cop = 3  # coefficient of performance of the heat pump
> 
> TransformerN1(
>     label='heat_pump',
>     inputs={bus_elec: Flow(), bus_low_temp_heat: Flow()},
>     outputs={bus_th_high: Flow()},
>     conversion_factors={bus_elec: cop,
>                         b_th_low: cop/(cop-1)})
> Your heat_pump example with Transformer (NM):
> 
> cop = 3  # coefficient of performance of the heat pump
> 
> Transformer(
>     label='heat_pump',
>     inputs={bus_elec: Flow(), bus_low_temp_heat: Flow()},
>     outputs={bus_th_high: Flow()},
>     conversion_factors={bus_elec: cop,
>                         b_th_low: cop/(cop-1)})
> The only difference is, that the Transformer (NM) can also cover a gas/coal driven chp-powerplant with one component instead of three (two transformer and a bus). But if you think it is too complicated for you, you can use the Transformer (NM) in the same manner as explained above and connect two of them with a bus you just do not have to do it.

You could have written only that the API remains the same. I think I got the point already 5 posts earlier :smile: 

Nevertheless, I do not have any interest in the NMTransformer and think 1N and N1 are absolutely sufficient. And I would not even want to adjust docstrings for a combined transformer..

It feels like you would really like the NM solution. It would also be o.k. for me but I don't want to spend time on it :smile:

**Comment by ckaldemeyer** [comment]
Go ahead if you want it!

**Comment by simnh** [comment]
What about this one? Do we want to include something of this ?

**Comment by ckaldemeyer** [comment]
For me, it's not absolutely necessary but I guess @uvchik was planning to implement it. Maybe with milestone "some day..." :-)
