### ISSUE TITLE
Feedback from Website Visitor

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#29]
Not for the first time I got the feedback that people did not see the main menu at first glance.

Therefore I would like to change to a another theme. You can preview it here: https://newoemof.wordpress.com/

We activate newoemof a long time ago to test themes. This one is very similar to the old one but the menu is now below the big logo.

@oemof/oemof-developer-group What do you think.

I would chang the theme, because this is not a big deal. I will not do anything else.

If anybody thinks we should improve our website - feel free.

**Comment by c-moeller** [comment]
Looks better than the old design.

**Comment by ckaldemeyer** [comment]
> I would be nice to get a feedback. If there is no feedback at all I will do what I what as I think nobody is interested.
> 
> For me it is interesting because the visits on our website are increasing and I myself do not like the "hidden" menu.
> 
> For me the selected Button2 theme is okay and I will not spend time to search another.

I like the theme but not the black frame arround it. Thanks for you effort!

**Comment by EdithaK** [comment]
I like it.
