### ISSUE TITLE
Fix error in example tests

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#290]
The error occured with the following [commit](https://github.com/oemof/oemof/commit/6f4edfa10f88f172dcb48071c5dc5261d8922219) which was meant to fix the creaking pyomo tests by changing the LP files.

To me they look allright from the content (and bla=bla is equal to -bla=-bla) but the check fails if pyomo writes the LP file not in the same style as the one on the file system/branch in `tests/lp_files`.

I think we could fix it by creating a new lp file and substituting it with the one on the branch.

@uvchik : Do you remember why you changed it?

**Comment by uvchik** [comment]
nosetests:
The were pyomo changes with version 5.0. That's why the tests will not pass unless you have pyomo > 5.0 installed. Even though oemof works with pyomo 4.2. We discussed this in another issue. We could change the setup.py but as it is just a developer issue we did not change anything so far.

example tests:
The example test still do not work, as the csv-dispatch example changed. Will you check and fix it?

**Comment by uvchik** [comment]
Sorry, not csv-dispatch but simple-least-cost example.

**Comment by ckaldemeyer** [comment]
> nosetests:
> The were pyomo changes with version 5.0. That's why the tests will not pass unless you have pyomo > 5.0 installed. Even though oemof works with pyomo 4.2. We discussed this in another issue. We could change the setup.py but as it is just a developer issue we did not change anything so far.

Oh, I missed that.
 
> example tests:
> The example test still do not work, as the csv-dispatch example changed. Will you check and fix it?

I can have a look tomorrow if I find the time on the conference..

**Comment by uvchik** [comment]
No problem. I have to postpone the release any way.

**Comment by ckaldemeyer** [comment]
> Sorry, not csv-dispatch but simple-least-cost example.

The simple least cost example is somehow missing on the `dev` branch but exists on `master`. I'll have a look later and continue to listen to the presentations.. ;)

**Comment by ckaldemeyer** [comment]
It was renamed to simple dispatch example in commit:

https://github.com/oemof/oemof/commit/fecd5a04673acacfc1bd841fdecbb59e54dda8dd#diff-79dfe2116242394c070520d20e082332

So the old folder can also be deleted and I'll fix the test result dict for the heatpump adaptions (M1 Transformer) in the simple dispatch example.

**Comment by ckaldemeyer** [comment]
I have now integrated the new results (after introducing the heat pump) in the test: #293

**Comment by uvchik** [comment]
Everything is fine now in the actual dev branch (release branch(.
