### ISSUE TITLE
Throw error if problem is infeasible

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#292]
At the moment the solve method ot the OperationalModel throws an error when the problem is infeasible, but this error comes from the result() method which is called. 

This can be extend to the full information from the solver BTW,..

**Comment by uvchik** [comment]
:+1: 

Good idea. We could catch the error and raise an Infeasibility error/warning. This could be more specific than the actual error.

**Comment by simnh** [comment]
I will do this on the dev today...
