### ISSUE TITLE
Version 0.1.4

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#299]
Don't be confused that we already have oemof v0.1.4.

1. There was a bug in v0.1.2 (#298), so I had to fix it and release again
2. I made a mistake uploading v0.1.3 to pypi and had to upload it again with a different version number

@gplssm Would you create a zenodo DOI for this release. I think we do not need one for v0.1.2.

**Comment by gplssm** [comment]
Et voilà! http://doi.org/10.5281/zenodo.438676

Actually the entry in Zenodo was already automatically created by the GitHub-Zenodo service.

I had to manually edit this entry to achieve the format we agreed on in #264 
Manual editing was required for 3 fields:
* authors: see #264 (originally takes all contributors)
* title: see #264 (original: oemof/oemof: Lerning to test)
* description: I took first paragraph of the README (originally takes release description)

I'll try to configure the zenodo service accordingly.

**Comment by uvchik** [comment]
Is there a reason, why it is called [Data set]? Can we change it to e.g. [software] in future releases?

```
oemof Developer Group. (2017). Open Energy Modelling Framework (oemof) - A modular open 
source framework to model energy supply systems. Version v0.1.4 [Data set]. Zenodo. 
http://doi.org/10.5281/zenodo.438676
```

**Comment by ckaldemeyer** [comment]
> Is there a reason, why it is called [Data set]? Can we change it to e.g. [software] in future releases?
> 
> oemof Developer Group. (2017). Open Energy Modelling Framework (oemof) - A modular open 
> source framework to model energy supply systems. Version v0.1.4 [Data set]. Zenodo. 
> http://doi.org/10.5281/zenodo.438676

Or can we still change it now?

**Comment by gplssm** [comment]
Actually, I don't understand why "[Data set]" is written there. The data is categorized as software... Maybe it's a bug?

At least "[Data set]" does not appear in the bibtex entry Zenodo produces

```
@misc{oemof_developer_group_2017_438676,
  author       = {oemof Developer Group},
  title        = {{Open Energy Modelling Framework (oemof) - A 
                   modular open source framework to model energy
                   supply systems. Version v0.1.4}},
  month        = mar,
  year         = 2017,
  doi          = {10.5281/zenodo.438676},
  url          = {https://doi.org/10.5281/zenodo.438676}
}
```

**Comment by gplssm** [comment]
It is still possible to edit this metadata. Once we figure out how to avoid "[Data set]", we could configure Zenodo accordingly

**Comment by uvchik** [comment]
I do not understand where it comes from but you I can find it in other software projects at Zenodo as well. Maybe we shouldn't care about it. At least I will not have time to care.

Thank you @gplssm. In my opinion you can close this issue.

**Comment by gplssm** [comment]
I haven't found a way to deal with this... But the question was already ask in the zenodo repo https://github.com/zenodo/zenodo/issues/874

I hope some from Zenodo takes up on this.
