### ISSUE TITLE
roles and responsabilities

### ISSUE THREAD

**Issue by beritRLI** [oemof/oemof#3]
roles and responsabilities is a subject we also mentioned in the expert-interviews. In the attached google docs is a first summary for oemof.
Many of the roles can be joint but they should be formulated one by one so that it is easier to change the responsability for them or to puzzle them in different ways.

Feel free to comment.

https://docs.google.com/spreadsheets/d/1SMXyg7AzyGClsXqBxuRUm9RtbwOfirLsak6_Btq9V8A/edit?usp=sharing

**Comment by christian-rli** [comment]
closing this together with https://github.com/OpenEnergyPlatform/organisation/issues/1
