### ISSUE TITLE
Check example app

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#3]
Check the scenario in example app and decide if another (or second) example is necessary.

**Comment by uvchik** [comment]
I do not know what to do with this issue. Please make it more concrete or close it.

**Comment by simonhilpert** [comment]
Is there any progress or should we set the milestone to february?

**Comment by caro-rli** [comment]
The idea was to have another (bug free) example with different parameter settings. Since I'm working now with an investment example, I will transfer the general ideas to another example app with the January release.

**Comment by ckaldemeyer** [comment]
As we are discussing this now: What do you think about prodiving an example that includes all oemof-components? This could also be connected to a test, so that we make sure that everything still works after bigger changes in the code base.

**Comment by caro-rli** [comment]
Sounds good. But this won't work for the January release anymore.

**Comment by caro-rli** [comment]
I'm afraid I can also not finish my first idea until January release since there is a lot of obscurity still for me when running an investment model and I'm not in the office next week.. sorry!

**Comment by cswh** [comment]
@ckaldemeyer: did your commit fix this issue?

**Comment by birgits** [comment]
This issue has been forwarded to the next release date for a couple of months now. Is anyone still working on it? Should we close it or keep it as a reminder?

**Comment by simnh** [comment]
I think we can close this, but check if it runs correctly. If, we can maybe move it from developing examples to 
examples and rename (specific). 
Or I ll just do that....

**Comment by ckaldemeyer** [comment]
:+1: I accidently referenced this issue using a hashtag. But thanks for keeping it alive ;-)
