### ISSUE TITLE
Simulation with one timestep not possible

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#306]
Cannot simulate an energy system with only one timestep...

**Comment by ckaldemeyer** [comment]
> Cannot simulate an energy system with only one timestep...

This is probably due to the set "previous_timesteps", right?

**Comment by simnh** [comment]
maybe...

**Comment by uvchik** [comment]
An error message would be helpful.

If it is easy to fix, we should fix it. Otherwise we could catch it and do not allow less than two steps.

**Comment by uvchik** [comment]
Some people were thinking about looping time step by time step around a simple model. This will not be possible if it is not possible to simulate one time step. I do not have the time to care about now but I think it's good to keep it in mind. So I will postpone it.

**Comment by uvchik** [comment]
Closed by #519
