### ISSUE TITLE
Implementation of base storage and adaption of the current one: @uvchik @birgits  

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#311]
As discussed on the user meeting..

**Comment by birgits** [comment]
Just found this issue again but don't at all remember what it's about... Does any of you remember @uvchik @ckaldemeyer?

**Comment by uvchik** [comment]
At the moment the storage contains a storage component and two transformers that manage the input efficiency and output efficiency. The idea was to create a basic storage component without these transformers. People sometimes want to connect things in a different way and such a component would be flexible and less complicated.

**Comment by ckaldemeyer** [comment]
>> Just found this issue again but don't at all remember what it's about... Does any of you remember @uvchik @ckaldemeyer?

> At the moment the storage contains a storage component and two transformers that manage the input efficiency and output efficiency. The idea was to create a basic storage component without these transformers. People sometimes want to connect things in a different way and such a component would be flexible and less complicated.

The idea was also to make the storage the first custom component: https://github.com/oemof/oemof/pull/332

But let's discuss it if the PRs are ready code-wise :-)

**Comment by uvchik** [comment]
This issue has been addressed by PR #480, which is already part of the v0.2.2 release.
