### ISSUE TITLE
oemof_examples fails with Python3.6

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#312]
On the oemof user meeting an error executing `oemof_examples` with python3.6 was discovered.

More specific executing

```
oemof_examples test_installation
```

throws an error related to pyomo (the actual traceback of the error can't be provided yet, as I don't have Python3.6).

We should add a hint on the usage of Python3.6.

**Comment by gplssm** [comment]
According to @gnn this is purely a Pyomo related bug which is already fixed in the upcoming version.

**Comment by gnn** [comment]
Yeah, you're right. This is an upstream [issue](https://github.com/Pyomo/pyomo/issues/103) with pyomo which they already fixed so we only have to wait for the next official release.
