### ISSUE TITLE
Solph Improvements

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#315]
Reminder: 

* Complex components (consisting of flows, comp, bus etc)  @gnn 
* Connecting components (implicit creation of Buses) @gnn #304 
* Parentclass for Flow, Bus, Component (to hold attributes like investment) @gnn 
* Move constraints definition to components (use annotations @…) @gnn 
* Specific components @ckaldemeyer  #310 , #286 
* Specific models (Expansion model etc)  @simnh
* Detect opt-variable type via attribute value (remove fixed, actu val, etc) @gnn 
* Move most methods to `EnergySystem` (create model, etc) @simnh

The general idea is to move more to the energy class. One draft on how it can be used is here (based on ideas of @gnn and @simnh: 
```
New Workflow idea for the energy system 

es = EnergySystem() / EnergySystem.from_csv() / from_json() 

# if not read from csv or others should be added
es.add(components) 

# This functionalitiy does not exist but I think it woudl be great to allow for scenario definition
es.add_scenarios([scenario1, scenario2]) 

# Create the empty model 
model = Model.create( ExpansionModel )

# tell the energy system to use the defined model
es.use(model) 

# compute (simulate / optimize) 
es.compute()

# results are back in es and can be processed with outputtlib 
es.results 
```

**Comment by uvchik** [comment]
Nothing happened for two and a half years. It is related to #420.
