### ISSUE TITLE
New mail address

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#32]
We have a new mail address to contact the oemof developer group.

contact@oemof.org

This address points to a mailing list hosted at posteo (oemof@lists.posteo.de).

https://lists.posteo.de/listinfo/oemof

Please subscribe to this list and help to answer requests.

In my opinion we should use this address in the code base, web page, presentations etc.

@oemof/oemof-developer-group What do you think? Comments welcome!

**Comment by fwitte** [comment]
Similar to #38 and #37, move this information to some kind of wiki?

**Comment by uvchik** [comment]
:+1:

**Comment by p-snft** [comment]
Do not forget to add it to https://pypi.org/project/oemof/, which points to oemof@rl-institut.de.

**Comment by uvchik** [comment]
> Do not forget to add it to https://pypi.org/project/oemof/, which points to [oemof@rl-institut.de](mailto:oemof@rl-institut.de).

Done :smile: Will be visible with the next release.

**Comment by busiing** [comment]
> Similar to #38 and #37, move this information to some kind of wiki?

Please update the related issues mentioned :)
