### ISSUE TITLE
Move Storage to custom module

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#324]
As we will have specific components in a new module soon, I think we should move all 'specific' components to that module as well. 

I actually think this should be done for all components except the basic ones, ie. Sink, Source, LinearTransformer (NM or 1M, M1). In this process I would like to remove the VariableFractionTransformer and rename this to extraction turbine and move it to custom (or heat?). Then we will have a clear definition / distinction

**Comment by uvchik** [comment]
I am fine with that. We should write down somewhere what basic classes are. Is the following definition right:

"Basic classes are classes that also exist in the network module."

**Comment by simnh** [comment]
We can agree on that definition...

**Comment by uvchik** [comment]
I think it's just good to have one to avoid later discussions.

**Comment by ckaldemeyer** [comment]
> I think it's just good to have one to avoid later discussions.

:+1:

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/pull/329

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/issues/335

**Comment by ckaldemeyer** [comment]
Done
