### ISSUE TITLE
Relative vs. absolute imports

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#328]
During the last pull request (#303) I came across differently imported modules/packages e.g. in the [init files](https://github.com/oemof/oemof/blob/dev/oemof/solph/__init__.py) or within the [solph models](https://github.com/oemof/oemof/blob/dev/oemof/solph/models.py)

According to [this Q&A](https://stackoverflow.com/questions/4209641/absolute-vs-explicit-relative-import-of-python-module) relative imports were not recommended for a longer time but meanwhile both options are o.k.

Would it make sense to agree on something and just change everything to be not ambiguous?

**Comment by uvchik** [comment]
I changed to absolute imports in my own projects some time ago. I definitely agree with a consistent solution and it seems to me that absolute imports are the better way.

**Comment by ckaldemeyer** [comment]
> I changed to absolute imports in my own projects some time ago. I definitely agree with a consistent solution and it seems to me that absolute imports are the better way.

So we could remove all relative imports..

**Comment by uvchik** [comment]
@ckaldemeyer thank you for bringing this up. Let's keep this issue open and make a last check right before the release, so that we have everything in line for v0.2.0.

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer thank you for bringing this up. Let's keep this issue open and make a last check right before the release, so that we have everything in line for v0.2.0.

:+1:

**Comment by uvchik** [comment]
I think I fixed it. Maybe I missed something. I will close anyway. If you find something just fix it yourself.
