### ISSUE TITLE
Rename NodesFromCSV

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#330]
The name still stems from the original idea of a class and breaks the naming convention. It should be changed to `nodes_from_csv` everywhere. Maybe with a naming wrapper and a deprecated warning..

**Comment by uvchik** [comment]
Some of the restructure was made in #294, but to my pity we never merged it. You could still have a look at the code and use whatever you like.

**Comment by ckaldemeyer** [comment]
> Some of the restructure was made in #294, but to my pity we never merged it. You could still have a look at the code and use whatever you like.

Thanks. Let's integrate it in #327

**Comment by ckaldemeyer** [comment]
Realized during restructuring.
