### ISSUE TITLE
Fixed costs for Flows

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#334]
I am just double-checking some solph expressions for a calculation which includes fixed costs.

In the [documentation](http://oemof.readthedocs.io/en/stable/api/oemof.solph.html#oemof.solph.network.Flow) it says 

> fixed_costs (numeric) – The costs of the whole period associated with the absolute nominal_value of the flow.

which made me think that I have to pass the overall value for fixed costs e.g. for an absolute value of `P_el=90 MW` with costs of `1000 EUR/MW` the fixed costs should be set to `90,000 EUR`.

This made me skeptical as I thought (and only find it logically) to provide specific costs per unit e.g. `1000 EUR/MW` in this case.

Actually, luckily this is also [how it is implemented currently](https://github.com/oemof/oemof/blob/dev/oemof/solph/blocks.py#L509) and it was just not documented clearly.

@oemof/oemof-solph : Do you also think that the description is misleading?

Then, I would adapt it!

**Comment by birgits** [comment]
When I first read the explanation for fixed_costs I thought it should be the 1000 EUR/MW but reading how you understood it made me question it as well. So I guess it should be clarified. I can't think of anything good though. Maybe we could explain it using an example.

**Comment by ckaldemeyer** [comment]
> When I first read the explanation for fixed_costs I thought it should be the 1000 EUR/MW but reading how you understood it made me question it as well. So I guess it should be clarified. I can't think of anything good though. Maybe we could explain it using an example.

What do you think of
> fixed_costs (numeric) – The costs associated with one unit of the absolute nominal_value of the flow for the whole period.

or

> fixed_costs (numeric) – The specific costs for one unit of the absolute nominal_value of the flow for the whole period.

?

**Comment by ckaldemeyer** [comment]
Actually ` absolute nominal_value` is redundant for me. The `absolute` could be removed for me.

**Comment by ckaldemeyer** [comment]
We could also be more specific
> fixed_costs (numeric) – The costs associated with one unit of the absolute nominal_value of the flow for the whole period e.g. fixed OPEX.

**Comment by ckaldemeyer** [comment]
But maybe being too specific could also be misleading..

**Comment by birgits** [comment]
I like your last suggestion best!

**Comment by ckaldemeyer** [comment]
> I like your last suggestion best!

:+1:

**Comment by ckaldemeyer** [comment]
I'll do it after my holiday..

**Comment by simnh** [comment]
What about this one?

**Comment by uvchik** [comment]
Close in favour of #394
