### ISSUE TITLE
Adapt examples (to new outputlib)

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#335]
If we are going to adapt all examples to the new outputlib:

* should we remove all functions but the one that returns the results for the result check?
* should we try to streamline everything e.g. using the same import style, order, ...?
* should we try to remove hidden magic e.g. making automatic instatiation like Source(....) without a reference impossible or at least hide the possibility within the examples?

I think this is a good chance to clean up a bit..

**Comment by ckaldemeyer** [comment]
@uvchik : Do you need the other functions within the examples?
Otherwise I would remove them because I think it makes things more complicated for new users because of nested usage, global/local parameters, ...

**Comment by ckaldemeyer** [comment]
We could still leave one function that returns the results!

**Comment by ckaldemeyer** [comment]
As an alternative, we could put everything on one function.

**Comment by uvchik** [comment]
By now the `example.py` can be executed as a script typing `oemof_examples`. This was intended to test the oemof installation right after the installation process. I think this is good idea but in my opinion we should reduce it to one test example (see `test_installation.py`).

**Comment by ckaldemeyer** [comment]
> By now the example.py can be executed as a script typing oemof_examples. This was intended to test the oemof installation right after the installation process. I think this is good idea but in my opinion we should reduce it to one test example (see test_installation.py).

:+1:

**Comment by ckaldemeyer** [comment]
@simnh: The normal storage is still existing.

Should we only keep the one in custom and delete the one in `blocks.py` ?

**Comment by ckaldemeyer** [comment]
https://github.com/oemof/oemof/pull/329

**Comment by simnh** [comment]
delete!
