### ISSUE TITLE
Add meta data to the results dictionary

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#340]
I would like to add some extra data to the results dictionary. As we already agreed on the new API I thought that the best way would be an extra function. I will create a PR if you basically agree.

```python
[...]
om.solve(solver=solver)
results = processing.results(energysystem, om)
meta_results = processing.meta_results(om)
[...]
```

This function will copy some solver results, objective result etc. to one level. Possible keys could be:

```'objective', 'Time', 'Status', 'Termination condition', 'Number_of_variables', ...```

The name of the function can be discussed. 

I had the idea to add it to the results dictionary but I dismissed this idea. The good thing of this approach is that it will not effect the existing API but supplements it. If you do not like it you can ignore it. If you want to add it to the results dict you can easily do it with:

```python
results = processing.results(energysystem, om)
results['meta'] = processing.meta_results(om)
```

**Comment by ckaldemeyer** [comment]
> I would like to add some extra data to the results dictionary. As we already agreed on the new API I thought that the best way would be an extra function. I will create a PR if you basically agree.
> 
> [...]
> om.solve(solver=solver)
> results = processing.results(energysystem, om)
> meta_results = processing.meta_results(om)
> [...]
> This function will copy some solver results, objective result etc. to one level. Possible keys could be:
> 
> 'objective', 'Time', 'Status', 'Termination condition', 'Number_of_variables', ...
> 
> The name of the function can be discussed.
> 
> I had the idea to add it to the results dictionary but I dismissed this idea. The good thing of this approach is that it will not effect the existing API but supplements it. If you do not like it you can ignore it. If you want to add it to the results dict you can easily do it with:
> 
> results = processing.results(energysystem, om)
> results['meta'] = processing.meta_results(om)

I like that idea of not mixing up both structures. Concerning the naming I don't have any better ideas ;-)

**Comment by uvchik** [comment]
I added this function with commit 00e898f. See [this comment](https://github.com/oemof/oemof/pull/329#issuecomment-336922424) of PR #329 for more information. Please comment there.
