### ISSUE TITLE
Add gradient  (ramp) costs

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#344]
I just noted that it's not possible to add costs associated with gradients / ramping up and down..

Maybe with the new functionality to just add attributes to the flow we can find a way to easily provide this constraint if such an attribute is present?

**Comment by ckaldemeyer** [comment]
> I just noted that it's not possible to add costs associated with gradients / ramping up and down..
> 
> Maybe with the new functionality to just add attributes to the flow we can find a way to easily provide this constraint if such an attribute is present?

I think this would be of value! But if it is a standard functionality I would define these attributes explicitly for the Flow class. The functionality of adding arbitrary attributes should (from my point of view) be used for real fancy costum components only as it is quite convenient. Otherwise we just have almost empty classes and automatically set args and kwargs in combination with some pyomo-logic behind it ;-)

**Comment by ckaldemeyer** [comment]
Basically if a gradient (https://github.com/oemof/oemof/pull/329/commits/f93f94d03f0e7442f71fee5307a094877294b3a2) and related costs are set, these just have to generate an objective expression, or not?!

**Comment by simnh** [comment]
yeah, it's prettey simple...just a question of where to put it and not ' blow up ' the flow class..but we can put it there.. (or provide a api like this: 

Flow(nominal_value=10, pos_gradient={'ub': 0.5, 'cost': 5}, .. )

**Comment by ckaldemeyer** [comment]
> yeah, it's prettey simple...just a question of where to put it and not ' blow up ' the flow class..but we can put it there.. (or provide a api like this:
> 
> Flow(nominal_value=10, positive_gradient={'ub': 0.5, 'cost': 5}, .. )
> 
> ub for upper bound variable bound
> or
> 
> Flow(nominal_value=10, gradient={'up': 0.5, 'down': 10, 'cost': 5}, .. )
> 
> but then there would be no possibility to different costs....I don't know..I can make a proposal

I would prefer:

    Flow(nominal_value=10, positive_gradient={'ub': 0.5, 'cost': 5}, .. )

**Comment by ckaldemeyer** [comment]
Or something like:

Flow(nominal_value=10, positive_gradient=0.5, positive_gradient_costs=5)

But the dict variant is a bit cleaner I guess..

**Comment by simnh** [comment]
mh..dict would work, but would cause ''problems'' inside the csv-reader I guess..

csv-reader is annoying. 

I don't know...

**Comment by ckaldemeyer** [comment]
> mh..dict would work, but would cause ''problems'' inside the csv-reader I guess..
> 
> csv-reader is annoying.

If all people are complaining and noone wants to maintain it we could also just remove it from v.0.2. and move it to some application or keep it in the examples repository.

Sometimes (very often from my point of view) less is more.

**Comment by simnh** [comment]
I like your way of thinking :) ... vote for remove!
