### ISSUE TITLE
Minimum Up/Down constraints

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#346]
Actually one can set the the min-up down time, but we do not provide any constraints...either we should add these constraints or remove it for solph.options.py

**Comment by ckaldemeyer** [comment]
> Actually one can set the the min-up down time, but we do not provide any constraints...either we should add these constraints or remove it for solph.options.py

I'll need it for our project and implement it when I come to it!

**Comment by simnh** [comment]
NICE!

**Comment by jnnr** [comment]
Seems like this has been lying for a while. Any news regarding this issue? As it is a bug, we should not postpone it too long.

**Comment by ckaldemeyer** [comment]
> Seems like this has been lying for a while. Any news regarding this issue? As it is a bug, we should not postpone it too long.

I have implemented this with https://github.com/oemof/oemof/pull/446

@jnnr @simnh : Please review so that we can merge ;)

**Comment by jnnr** [comment]
Will do! :)
