### ISSUE TITLE
Renaming OperationalModel to ???

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#354]
I think we should rename this, as it's not quite the right name because it is not only an op. model.

I could BaseModel, GenericModel  (as eveything can be created from this model), StandardModel, Model, MultiPurposeModel, MultiModel, GeneralModel ...??

**Comment by ckaldemeyer** [comment]
> I could BaseModel, GenericModel (as eveything can be created from this model), StandardModel, Model, MultiPurposeModel, MultiModel, GeneralModel ...??

Just from the word I like `BaseModel`. But can other models be added on top? If yes, this would be my priority. Otherwise, I would go with Model or just use Pyomos `ConcreteModel`.

**Comment by ckaldemeyer** [comment]
> Just from the word I like BaseModel. But can other models be added on top? If yes, this would be my priority.

I think the idea was also to subclass from a `BaseModel`, wasn't it? So a BaseModel is like a BaseClass which would fit for me.

**Comment by uvchik** [comment]
As far as we do not have anything else I am fine with Model. Moreover BaseModel, DefaultModel or GenericModel would also be fine. It is easier to find a name if we have anything else so maybe Model is good enough by now.

**Comment by ckaldemeyer** [comment]
That about `OptimizationModel` or `LinearOptimizationModel`. I hate naming discussions. I would go with `BaseModel`, `GenericModel` or `Model` in this priority.

**Comment by uvchik** [comment]
I hate naming discussions.
👍

**Comment by simnh** [comment]
mh, ok I ll think about the fit depeding on possible future subclassing etc. I ll get back to you

**Comment by simnh** [comment]
I like `GenericModel`, because we can maybe subclass then from BaseModel. And generic fits best because everything is possible based on this model type.

**Comment by uvchik** [comment]
I'm fine with everything.

**Comment by ckaldemeyer** [comment]
> I'm fine with everything.

Me too.

**Comment by uvchik** [comment]
Closed in favour of #363.
