### ISSUE TITLE
Remove/move CSV-Reader?

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#355]
As it touches many things (e. g. https://github.com/oemof/oemof/issues/344, https://github.com/oemof/oemof/issues/350, https://github.com/oemof/oemof/issues/258, https://github.com/oemof/oemof/issues/243) and no one has ambitions to maintain it, we should think about moving it to the (development) example repository.

What do you think?

**Comment by uvchik** [comment]
It is a difficult question and I do not fully oversee the consequences. Shall we meet in the webroom to talk about it. We could also move it to renpassG!S.

**Comment by ckaldemeyer** [comment]
> It is a difficult question and I do not fully oversee the consequences. Shall we meet in the webroom to talk about it. We could also move it to renpassG!S.

I don't have time today. As I see it, we could remove it and move the functionality to respective apps. The app-maintainers can then care about the problem and it doesn't slow down our developing process.

**Comment by ckaldemeyer** [comment]
For me, less is more here similarly to the outputlib discussion.

**Comment by simnh** [comment]
lets just remove it with the next version, for our own applications, we can move it if we like. otherwise, the guys with their applications should do this.

What solution? removeotion!

**Comment by uvchik** [comment]
Another idea is to provide own packages as `oemof_csv_reader` for example. These packages could have there own maintainer group and can be bound to a specific version e.g. v0.1.x. If there is no maintainer any more this package will get bogged down but this does not effect any of the other packages. Having oemof v0.4.x we may close packages with oemof<0.2 in the setup.py.

**Comment by simnh** [comment]
@ckaldemeyer and I vote for remove, if you can live with this @uvchik , we could just do this?

We do not have maintainers right now, when someday somebody comes around, he can have a look at the code of version 0.1.5...

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer and I vote for remove, if you can live with this @uvchik , we could just do this?
> 
> We do not have maintainers right now, when someday somebody comes around, he can have a look at the code of version 0.1.5...

:+1:

**Comment by uvchik** [comment]
Remove it!

But nevertheless we should talk about my proposal. I think we should find ways to integrate people and new ideas without effecting the main code base. I do not want new people feeling thwarted, so I think it is good idea to offer a way to integrate experimental stuff. Furthermore it frees people from being compatible to everything.

**Comment by simnh** [comment]
We can have a new issue for discussion, I close this for now

**Comment by uvchik** [comment]
Shouldn't we leave it open until we have a PR removing the csv-reader?

**Comment by ckaldemeyer** [comment]
> Shouldn't we leave it open until we have a PR removing the csv-reader?

**Comment by simnh** [comment]
but on dev there is no csv-reade anymore, isnt it?

**Comment by ckaldemeyer** [comment]
> Shouldn't we leave it open until we have a PR removing the csv-reader?

I'd say yes!

**Comment by simnh** [comment]
ah ok, sorry, I looked on the wrong level for the inputlib directory....

**Comment by uvchik** [comment]
Closed in favour of #376.
