### ISSUE TITLE
Layout of the API documentation failed or is missing after moving classes to components module

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#365]
* [x] [GenericInvestmentStorageBlock](http://oemof.readthedocs.io/en/latest/api/oemof.solph.html#oemof.solph.components.GenericInvestmentStorageBlock) - broken
 * [x] [GenericStorageBlock](http://oemof.readthedocs.io/en/latest/api/oemof.solph.html#oemof.solph.components.GenericStorageBlock) - broken
 * [x] [GenericCHPBlock](http://oemof.readthedocs.io/en/latest/api/oemof.solph.html#oemof.solph.components.GenericCHPBlock) - missing

**Comment by ckaldemeyer** [comment]
Thanks for pointing this out!

> GenericCHPBlock - missing

Actually, I am not sure if I should/want to provide all equations within the block since all equations are already documented within the paper (referenced in the docstring). Generally, if I do this I would also have to do it for custom components like the (non-prominent) CAES.

But of course, I could do it if you think it is necessary..

@uvchik @simnh : What do you think?

**Comment by uvchik** [comment]
It is a general question of what has to be done to add a new component. Until now the equations of all components can be found in the docstrings of the block. I do not know if this is the best place but until we have a better place all equations should be there. At least it is the same place for all components.

**Comment by ckaldemeyer** [comment]
Weird. Somehow I did not get any notifications...

> It is a general question of what has to be done to add a new component. Until now the equations of all components can be found in the docstrings of the block.
> I do not know if this is the best place but until we have a better place all equations should be there. At least it is the same place for all components.


What about just adding equations for blocks.py and components.py and leaving it to the user within custum.py? So in this case, I would just add the ones for GenericCHP which is within components.

@simnh : What do you think?

**Comment by uvchik** [comment]
I fixed some equations in the documentation. I think we have to check them all for the release.

**Comment by ckaldemeyer** [comment]
> I fixed some equations in the documentation. I think we have to check them all for the release.

I agree. Let's include all equations and I'll also add the ones for GenericCHP and the GenericCAES!

**Comment by uvchik** [comment]
> I'll also add the ones for GenericCHP and the GenericCAES!

That's cool. Thank you.
