### ISSUE TITLE
solph.plumbing.Sequence not JSON- serializable

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#369]
Working on this branch...

https://github.com/oemof/oemof/tree/features/json-dump

With this pull request for json-dump feature! 
#368

**Comment by jnnr** [comment]
Set to milestone v0.2.2 as in PR #368.

**Comment by uvchik** [comment]
@simnh Still valid?

**Comment by jnnr** [comment]
The corresponding PR has been closed in June 2018 and the branch has been deleted. I guess this issue can be closed as well, @simnh ? Please object if I am wrong!
