### ISSUE TITLE
Unique class names

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#37]
At the moment I am working on a dataframe representation of the new result object which enables statistics, plotting ,etc..

While extracting the data from the result dictionary I used the class names to figure out what kind of object I am dealing with and also to use the class name as pandas index. If I use Pythons built in *object.__class__.__name__* this delivers the class of the object e. g. *Bus* or *SimpleExtractionCHP*. Since the classes *Transport*, *Transformer* and *Sink* all have a common subclass *Simple* the usage of delivers ambiguous *object.__class__.__name__* results.

Having unique core class names might be handy in some cases where objects are treated by there type. In my case it helps me to create "speaking names" since some object-uids in *renpass-gis* are not speaking for themselves. And I still remember Simon introducing a core class attribute "lower_name" to treat classes which is now also solved by using *type(object)*.

My point: I think having unique class names could be handy for current and future applications

@oemof/oemof-main: What do you think?

Cheers
Cord

**Comment by uvchik** [comment]
Why don't you just create a list with the new names and if nobody has objections you will be free to implement them.

**Comment by simonhilpert** [comment]
I think that's a  good way to go! But it should follow a logical structure if possible..(we tried this, but I think we failed in the first place at this)

**Comment by ckaldemeyer** [comment]
* Entity
  * Bus
    * Component
       * Sink
         * SimpleSink
       * Source
          * Commodity
          * DispatchSource
          * FixedSource
       * Transformer
         * SimpleTransformer
         * CHP
         * SimpleExtractionCHP
         * Storage
       * Transport
         * SimpleTransport

What about just adding the parent class name at the end of the sublass name?

**Comment by simonhilpert** [comment]
Actually I think we should remove the "Simple" components and try to find either good descriptive names or even only acronyms. I dont know really, I just realized that I alway had hard times finding nice names for example VariableEfficiencyCHP is a new component from the last release...


* Transformer
** BPCHP (backpressure chp)
** EXPCHP (extraction chp)
** VARBPCHP (backpressure chp with variable electrical efficiency)
..

**Comment by ckaldemeyer** [comment]
That would even be better. But if we do that, finding a structure that works in the long run needs quite some effort.

Such naming structure problems is something that I have stumbled across many times already. Even in small "private projects".

@gnn : Are there any general solutions (e.g. "naming frameworks", etc.) for this from the computer science side?

**Comment by cswh** [comment]
I remember that @gnn didn't like the multiple Simple classes anyway. And I would like unique class names as well!

We definetly need the "OEP decision tool"!!! Just in issues it is not very transparent in my opinion.

**Comment by uvchik** [comment]
@cswh wrote:
> We definetly need the "OEP decision tool"!!!

:+1:

> Just in issues it is not very transparent in my opinion.

Everybody should scan the issues once a week.

Use the search field with `is:issue label:"decision wanted"`

**Comment by cswh** [comment]
A little offtopic, but I started a [wikipage](https://github.com/oemof/oemof_base/wiki/Rules-for-decision-making) for the decision making rules so far. Feel free to add to the page or start a decision making process for other rules ;).

**Comment by uvchik** [comment]
@ckaldemeyer, @simonhilpert : For me both versions are okay. Just go ahead. For me it is okay for the January release. The earlier, the better.

**Comment by uvchik** [comment]
We should move this topic to the restructuring meeting.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
Obsolete, because we do have a new structure.
