### ISSUE TITLE
Sphinx documentation is triggered twice

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#373]
New commits on the `dev` branch triggers the build process of the Sphinx documentation at ReadTheDocs. But it seems to me that every commit triggers the build process twice because there are always two build processes at one time.

@gnn I think you added the trigger, could you check it or give me an idea where I can check it.

**Comment by gnn** [comment]
Could be related to rtfd/readthedocs.org#3255. Let's watch this one for any news.
I also stopped the `oemof` repository from using the readthedocs integration that is built into github and set up a github webhook that talks to a readthedocs endpoint manually. Maybe that makes rtd only start one build per pushed commit.

**Comment by uvchik** [comment]
It is not urgent so I will postpone it but we should keep an eye on it.

**Comment by jnnr** [comment]
Is this still an issue?

**Comment by uvchik** [comment]
It seems to be okay now, otherwise I will reopen it.
