### ISSUE TITLE
Unpacking of results nodes-tuple

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof#387]
I stumbled upon the nodes-tuple in results output or `views.node` function.
The "problem" is that I want to extract the `sequences` in a nice way, like this:
```
node_results = views.node(results, node)
for ((from_node, to_node), flow_name), timeseries in node_result.items()
    ...
```
This works nicely, in case no single node-tuple is involved. As soon as I do this for a storage, I ran into the following error:
`Value Error: not enough values to unpack`
because inside it the capacity series is build as (storage,)-tuple, which cannot be unpacked into two values. Possible workaround is as follows:
```
node_results = views.node(results, node)
for (nodes, flow_name), timeseries in node_result.items()
    from_node = nodes[0]
    to_node = nodes[1] if len(nodes) > 1 else None
    ...
```
My question is, if it would be possible to set 2nd node to `None` in case of single-node-tuples (ie. storage) in the **results creation**? Or does this lead to further complications? Or is it to late for the release?

**Comment by ckaldemeyer** [comment]
> I stumbled upon the nodes-tuple in results output or views.node function.
> The "problem" is that I want to extract the sequences in a nice way, like this:
> 
> node_results = views.node(results, node)
> for ((from_node, to_node), flow_name), timeseries in node_result.items()
>     ...
> This works nicely, in case no single node-tuple is involved. As soon as I do this for a storage, I ran into the following error:
> Value Error: not enough values to unpack
> because inside it the capacity series is build as (storage,)-tuple, which cannot be unpacked into two values. Possible workaround is as follows:
> 
> node_results = views.node(results, node)
> for (nodes, flow_name), timeseries in node_result.items()
>     from_node = nodes[0]
>     to_node = nodes[1] if len(nodes) > 1 else None
>     ...
> My question is, if it would be possible to set 2nd node to None in case of single-node-tuples (ie. storage) in the results creation? Or does this lead to further complications? Or is it to late for the release?

This is no problem and would work really quickly. We had been discussing this in the respective PR and the discussion was about whether it is `(my_node,)` or `(my_node, my_node)`. The decision was made for `(my_node,)` but not for a particular reason as it was rather a matter of taste.

But obviously the "empty" tuple element makes tasks like slicing a bit harder, induces more code and we should change it then.

The following options (including your option, which I also like), would be very quickly to implement:

* `(my_node, my_node)`
* `(my_node, None)`

I could live with both with a slight tendency for the second one as the `None` entry shows that the entry is not for a flow.

Wouldn't this also ease https://github.com/oemof/oemof/pull/380 ?

@simnh @uvchik @gnn : What do you think?

**Comment by ckaldemeyer** [comment]
@simnh votes for the second option as well!

**Comment by uvchik** [comment]
I agree, I think it is good idea to add the None value. Thank you for bringing this up.

@henhuy Will you change it?

As it changes the API, we have to fix it before the release.

**Comment by henhuy** [comment]
Yes, I will. Thanks for the quick response!

**Comment by ckaldemeyer** [comment]
> Yes, I will. Thanks for the quick response!

:+1:
