### ISSUE TITLE
Add group "oemof-everybody/entry"

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#393]
Add a group for tasks that are suitable for new users or just have to  be done e.g. documentation, news-posts, and start with users from the dev-meeting...

**Comment by uvchik** [comment]
The new name is oemof-assistants. See oemof/organisation#23 for detailed information.

**Comment by ckaldemeyer** [comment]
> The new name is oemof-assistants. See oemof/organisation#23 for detailed information.

:+1:
