### ISSUE TITLE
Add offsets to Transformer class

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#404]
I would like to add the possibility to provide (optional) offsets within the `Transformer` class as it is one missing feature needed to completely describe a linear equation.

    TF = solph.Transformer(
        label='TF',
        inputs={my_bus1: solph.Flow()},
        outputs={my_bus2: solph.Flow(), my_bus3: solph.Flow()},
        conversion_factors={my_bus2: 0.3, my_bus2: 0.4},
        offsets={my_bus2: 1, my_bus3: 2})

This important for modelling equations that do not cross the origin of the coordinate system e.g. in combination with a `solph.NonConvexFlow`modelling heat pumps, etc..

@oemof/oemof-solph : If you agree, I would implement this feature as an option for the `Transformer` class!

Are you o.k. with this?

**Comment by uvchik** [comment]
I had the same thoughts when I saw PR #377 but I think it will not work that easily.

The offset is nice to get a non-linear efficiency but you may get unwanted behaviour such as a standby consumption (output=0, input=offset) or a magical output (input=0, output=offset). To avoid this behaviour you need to define a nonconvex flow as it is done in PR #377.

Therefore I think it might be cleaner to create an new child class where this behaviour is implemented.

Any way I am open for a PR. As a new attribute does not break the backwards compatibility we can easily publish it with 0.2.1 and do not necessarily need to hurry.

**Comment by simnh** [comment]
yes @uvchik the idea ist really close to #377. I'm also not sure where to place it. For me either inside the Transformer or inside a new component class would be fine.  At some point in time we might see more clearly how to actually structure the components.

One way to think of it to just have different types of "relations" with a relation attribute for one component, for example in the facades-module.

**Comment by ckaldemeyer** [comment]
> I had the same thoughts when I saw PR #377. The offset is nice to get a non-linear efficiency but you may get unwanted behaviour such as a standby consumption (output=0, input=offset) or a magical output (input=0, output=offset).

To me, this is not magical but just logical ;-) And the standard behaviour would be to have no offset and everything works as it does now.

> To avoid this behaviour you need to define a nonconvex flow as you mentioned it and as it is done in PR #377.

This would not be needed anymore if I implement it; at least if there is only one (segment of a) linear equation.

> Therefore I think it might be cleaner to create an new child class where this behaviour is implemented.
> 
> Any way I am open for a PR. As a new attribute does not break the backwards compatibility we can easily publish it with 0.2.1 and do not necessarily need to hurry.

I would suggest to realise it in the same class and make it optional. Of no offsets are passed, everything works as expected, if yes, they are included within the equations. As it does not lead to a MIP, I think the place is right within the `Transformer` class from my point of view as subclassing for one additional optional attribute seems to be overloaded.

> yes @uvchik the idea ist really close to #377. I'm also not sure where to place it. For me either inside the Transformer or inside a new component class would be fine. At some point in time we might see more clearly how to actually structure the components.
> 
> One way to think of it to just have different types of "relations" with a relation attribute for one component, for example in the facades-module.

Yes, potentially we could also just have nodes and pass transfer functions over the edges :-)

But for now, are you both fine if I start within the `Transformer` class?

**Comment by ckaldemeyer** [comment]
> This would not be needed anymore if I implement it; at least if there is only one (segment of a) linear equation.

I was wrong here. This is indeed a special case. But nevertheless, offsets are missing..

**Comment by simnh** [comment]
Yes! Just as I said on the last meeting, lets do it somewhere as long as we still allow ourselves to move it around later...

**Comment by ckaldemeyer** [comment]
> BTW: offset would only work with binary variables, right? so basically you have flow1 = binary * offset + slope flow2 =

Yes and no. I would like to use them with BinaryFlows and think this will be the most used option. But some people might also use them without BinaryFlows e.g. if there is always some flow existent.

**Comment by ckaldemeyer** [comment]
I could either implement it generally for continuous/nonconvex flows or just add a component like in https://github.com/oemof/oemof/pull/377

**Comment by simnh** [comment]
if you find a good way how to implement it generally, why not!

**Comment by uvchik** [comment]
> I was wrong here. This is indeed a special case. But nevertheless, offsets are missing..

I hoped that I have overseen something 😞 

But anyway I think you try to implement it optionally in the transformer class and if get the feeling that it becomes to hacky you can move to a child class or what ever. I think it is a good idea.

**Comment by ckaldemeyer** [comment]
The behaviour I want can be expressed within the following equations:

    (I) min_F1 * Y_F1 <=  F1 <= max_F1 * Y_F1
    (II) F2 = F1 * conversion_factor_F2 +  Y_F1 * offset_F2

The first is already possible with nonconvex flows and the second expression within the second equation what I want because otherwise the line of F2 will cross the origin of the coordinate system.

This makes me think that dealing with an optional offset within the `NonConvexFlow` class might be the best option!?

I'll give it a try and annoy you with the result :-)

**Comment by uvchik** [comment]
I updated the comment above it was unreadable....

**Comment by simnh** [comment]
This touches upon a not great implementation, actually I favor something like setting min in nonconvex only triggers Pmin constraints. If min of flow is set, the your equation (I) is build.

**Comment by ckaldemeyer** [comment]
> This touches upon a not great implementation, actually I favor something like setting min in nonconvex only triggers Pmin constraints. If min of flow is set, the your equation (I) is build.
> 
> Update your feature branch with new dev, as there have been many changes!

We had a telephone call and I'll probably just add a new component as it is more explicit..

**Comment by uvchik** [comment]
> We had a telephone call and I'll probably just add a new component as it is more explicit..

👍

**Comment by uvchik** [comment]
Postpone to v0.2.1?

**Comment by ckaldemeyer** [comment]
> Postpone to v0.2.1?

I have a local branch for this and will provide it with equations asap..

**Comment by uvchik** [comment]
> > Postpone to v0.2.1?
> 
> I have a local branch for this and will provide it with equations asap..

I guess this means yes.

**Comment by ckaldemeyer** [comment]
> Postpone to v0.2.1?
> 
>     I have a local branch for this and will provide it with equations asap..
> 
> I guess this means yes.

For postponing? No..

**Comment by uvchik** [comment]
Okay, then have to be fast. The deadline was yesterday.

**Comment by ckaldemeyer** [comment]
> Okay, then have to be fast. The deadline was yesterday.

Yes! Sorry... https://github.com/oemof/oemof/pull/424

**Comment by jnnr** [comment]
#424 has been merged before release v0.2.0, so I close this issue.
