### ISSUE TITLE
Naming convetions oemof-base vs. oemof_base

### ISSUE THREAD

**Issue by cswh** [oemof/oemof#41]
So far we have different namings. In some places we use oemof-base (e.g. Installtion and Setup section, http://oemof-base.readthedocs.org/) and in other places we use oemof_base (e.g. Readme section, http://www.pythonhosted.org/oemof_base/). 

@oemof/oemof-main :
* Is there a consistent way to use just one version?
* If not, when to use what?

**Comment by ckaldemeyer** [comment]
I think oemof_base is the folder name in the repo and oemof-base is used for the pip package.

Maybe it would make sense to only have one name. In this case I would vote for "oemof_base" since this is unlikely to bring up errors (file naming, etc.)..

**Comment by cswh** [comment]
Ok if it shall be "oemof_base", what would we have to do to change everything to it? 
* How to change it on readthedocs? 
* And if I do `pip3 list` at my machine, `oemof-base` is listed. Can that be changed as well?

**Comment by ckaldemeyer** [comment]
I think we need to decide which way to go first. This would answer both questions.

I am not really familiar with the pip packaging procedures. @uvchik and @gnn might know more about that.

**Comment by ckaldemeyer** [comment]
Or at least question one ;)

**Comment by uvchik** [comment]
Pypi and readthedocs change the names automatically.

Both links work but the first one will be redirected: 

* http://oemof_base.readthedocs.org
* http://oemof-base.readthedocs.org

You can install both:
```sudo pip3 install oemof-base```
```sudo pip3 install oemof_base```

The result is always the same:
```Requirement already satisfied (use --upgrade to upgrade): oemof-base...```

I don't care about that and would not change anything.

**Comment by uvchik** [comment]
I think @gnn 's comment on issue #45 would solve that. A dot is a dot is a dot :smile:

**Comment by uvchik** [comment]
As we renamed the repository to oemof this issue is obsolete.
