### ISSUE TITLE
Shall we use or remove the results attribute of the EnergySystem class?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#419]
The EnergySystem class still has a results attribute. I think it is a relict of the old results processing.

I find it very useful to store the results together with the EnergySystem:
[The following code is from this test example](https://github.com/oemof/oemof/blob/dev/tests/test_scripts/test_solph/test_storage_investment/test_storage_investment.py#L96).

```python
# First script
[....]
om = solph.Model(energysystem)
om.solve(solver=solver)
energysystem.results['main'] = processing.results(om)
energysystem.results['meta'] = processing.meta_results(om)

energysystem.dump()

#**************************************
# Second script (I would like to make the restore method a function)
energysystem = solph.EnergySystem()
energysystem.restore()

# Results
results = energysystem.results['main']
meta = energysystem.results['meta']

storage = energysystem.groups['storage']
print(results[(storage, None)]['scalars']['invest'])

print(meta['objective'])
```

In that way it is possible to process all results you need and dump them together with the EnergySystem. The EnergySytem will help you to get single nodes using the `groups` method.

As mentioned above I would like to make the restore method a function (but this is a detail):

```python
def restore_energysystem(filename=None):
    es = solph.EnergySystem(filename=None)
    es.restore()
    return es
```

1. Shall we promote the use of the results attribute like this in the documentation?
2. Shall we remove the results attribute?
3. Shall we add a method to the EnergySystem class that calls the processing.results function an adds the dictionary to the attribute?

I vote for 1 but you may convince me of 3. 😄

**Comment by simnh** [comment]
We had it like 3. once. I think in the future the energysystem should become the central place for more stuff (e.g. #315 ). Therefore I like option 3, if we do not much with the energysystem, I sometimes wonder why we actually have the energy system...

**Comment by uvchik** [comment]
Do you have ideas for an API? Like this?

```python
es = EnergySystem(...)
[...]

om.solve(solver=solver)

es.fetch_results(om)

print(views.node(es.results, 'storage'))
print(es.meta['objective'])
```

**Comment by simnh** [comment]
I think it would be nice to be close to the workflow of #315, so actually adding the model, computing the results and writing it back automatically...but as I said, for it would be nice to just try something and have a steady process for the API that might slightly change along time

**Comment by uvchik** [comment]
But we have to decide what to do in v0.2.0.

Implementing the API from #315 is easy but there is a bundle of other topics there that might take its time.

Another problem is that we cannot dump the EnergySystem if it holds the pyomo-Model. At the moment it is not possible (at least as far as I know) to pickle the pyomo-Model (om).

**Comment by simnh** [comment]
I can make a proposal on thursday (we can exclude the model when dumping maybe?)

**Comment by simnh** [comment]
I created a pull request #420 where I added some stuff to the energy system. The results object will now hold actually the results of a model and the information about solution etc. will be found in the associated model itself...

**Comment by uvchik** [comment]
I postponed it v0.2.1 so in the first step we have to do it backwards compatible.

**Comment by gnn** [comment]
What does that mean in relation to @simnh's changes? Are they still OK?
Also, concerning the refactoring of the `restore` method to a function, would it be possible to make it a class method instead? It would look like this:

```python
class EnergySystem:
    @classmethod
    def restore(cls, filename=None):
        es = cls(filename=None)
        # Note the underscore in front of the method. You can either create a
        # private instance method restoring energy system objects from files, or
        # just copy the code to do so into the class mehod.
        # Or you could name the class method `from_file` in which case `restore`
        # would still be available as the name of the instance method.
        es._restore()
        return es
```

and you would restore an energy system like this:

```python
es = EnergySystem.restore(path_to_file)
```
If you tell me on which branch the changes refactoring the method to a function reside, I can do the change to class method.

**Comment by uvchik** [comment]
Can we add the class method parallel to the existing method. Than it will not change the API and there is no hurry. If not we should hurry because your variant is nice. In the old variant we could return self to get something like `es = EnergySystem().restore(path_to_file)` but yours is nicer.

**Comment by uvchik** [comment]
There is no branch except the one @simnh created but this is a more extensive revision 😄

**Comment by gnn** [comment]
Ah, you're right. No reason not to keep both variants for now.
I'll implement my suggestion for `0.2.1`.

**Comment by jnnr** [comment]
In my opinion, the results attribute is important. If I want to store results after optimisation but want to use functions of the outputlib (like views.node()) later during postprocessing, the only way I see is to dump the whole energysystem with the results. 

I do not mind doing the storing of the results to the energysystem actively, so I am ok with option 1. 

Altogether, what is the status of this issue? Is there some PR coming soon? Shall we leave it open?

**Comment by uvchik** [comment]
I think we should talk about a new structure `EnergySystem` and `Model` structure on the developer meeting (s. #420). So I think we can close this issue.

**Comment by simnh** [comment]
I agree we @uvchik
