### ISSUE TITLE
Add mathematical description to docstrings

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#428]
The following (custom) components do not have their mathematical description listed in their docstrings yet:

* [x] GenericCHP: https://github.com/oemof/oemof/blob/dev/oemof/solph/components.py#L498
* [x] GenericCAES: custom.py (to be added when merged)
* OffsetTransformer: https://github.com/oemof/oemof/blob/dev/oemof/solph/custom.py#L361  (#522 already deals with the `OffsetTransformer` - including the math descricption)

It should/could be completed easily until the next release by looking into the referenced papers and transferring the equations.

**Comment by jnnr** [comment]
The mathematical documentation of the named components is still missing. Please give us some formulas! :) I added checkboxes to Cords list.

**Comment by ckaldemeyer** [comment]
> The mathematical documentation of the named components is still missing. Please give us some formulas! :) I added checkboxes to Cords list.

I do not have time for this until September and the references are already contained. If anyone has spare time, feel free to transfer the equations (which is only work and not much thinking) ;)

**Comment by uvchik** [comment]
> I do not have time for this until September and the references are already contained.

@ckaldemeyer The next regular release is scheduled for October :smile:

**Comment by jakob-wo** [comment]
I marked the GenericCHP as "done". As far as I can tell, PR #525 (already merged into dev) contributed a detailed explanation of the equations.

**Comment by uvchik** [comment]
You could talk to @joroeder about the docstring template for all block classes and check if the docstring of the `GenericCHPBlock` is in line with the new conventions.

**Comment by jakob-wo** [comment]
jip! I will compare status quo of the `GenericCHPBlock` docstring with the recommondations made in Issue #544 in the next days - Anything regarding the docstring conventions shall be commented and added there, so that I can take it into account.

**Comment by jakob-wo** [comment]
In the Branch "feature/docu_add_math_desriction_caes" I am going to implement the caes equations from the paper mentioned in `GenericCAES.` I would like to see if the formatting works as expected - How can I make the Branch a selectable docu in readthedocs?

**Comment by joroeder** [comment]
For checking the formatting, you can create a local build - I just learned at dev meeting :)

```pip install sphinx```

```sphinx-build -b html "...\oemof\doc" ".\your\local\path\```

For checking your branch after committing, your branch needs to be added the readthedocs and build there.

**Comment by jakob-wo** [comment]
Yes, I figured how to build localy, too. But how do I add the branch to the readthedocs so it is visible to everyone? Sometimes that might be helpful, I think.

**Comment by jakob-wo** [comment]
I removed the checkbox from the OffsetTransformer in this Issue because it seems to be dealed with in another Issue already.

**Comment by joroeder** [comment]
> For checking the formatting, you can create a local build

Sorry, maybe I have told you something you already now. To specifiy your actual question: You need to login at readthedocs (or first create an account) and then somebody of the admins like @uvchik or @gnn or @birgits needs to add you to the admins. Then you can add your branch to the readthedocs versions. btw, I want to be added as well, my name at readthedocs is the same: joroeder. thanks! :)

**Comment by jakob-wo** [comment]
Ah ok! That is exactly the information I was looking for - thanks a lot!

**Comment by jakob-wo** [comment]
While adding the constraints and variable created by `GenericCAESBlock` to the docstring I found the declaration of two variables (`exp_p_spot` and `cmp_p_spot`) that are without usage in constraints. @ckaldemeyer Can you tell me if they have any purpose and therefore shall remain? It is not necessary to explain the purpose itself at this point ;-)

**Comment by jakob-wo** [comment]
I consider this Issue to be done and therefore I would close it within the next days... everyone ok with that?

**Comment by p-snft** [comment]
It is, thanks.
