### ISSUE TITLE
Fix outputlib documentation

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#432]
In the outputlib documentation (http://oemof.readthedocs.io/en/stable/oemof_outputlib.html#collecting-results) it says:

    views.convert_keys_to_strings(results)
    print(results[(wind, bus_electricity)]['sequences'])

Which won't work since string labels have to be passed.

This could be fixed by someone.

**Comment by jnnr** [comment]
Sure, you are right. I will correct it.

**Comment by jnnr** [comment]
Shall I start a pull request into master or dev?

**Comment by ckaldemeyer** [comment]
> dev-branch to make it visible in the "latest" documentation. To make it visible in the stable documentation we need to release....
> 
> ...but no problem I think we will soon release v0.2.1 with some fixes and @henhuy's features.

:+1:

**Comment by jnnr** [comment]
Thanks! I corrected the mistake. I just added the missing '' to make the arguments strings. I committed to dev directly, as it seemed to little a change to qualify for a pull request. I hope that's alright.

Little or not, it is a crucial detail, so thanks again for pointing that out, @ckaldemeyer!

**Comment by ckaldemeyer** [comment]
> Thanks! I corrected the mistake. I just added the missing '' to make the arguments strings. I committed to dev directly, as it seemed to little a change to qualify for a pull request. I hope that's alright.
> 
> Little or not, it is a crucial detail, so thanks again for pointing that out, @ckaldemeyer!

Thanks!

**Comment by uvchik** [comment]
Thank you.

Will you close this issue after you have deleted the branch.

**Comment by uvchik** [comment]
Okay, I will delete the branch, but as mentioned above I think this is part of the merge/rebase.
