### ISSUE TITLE
oemof_installation_test does not work

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#435]
An error occurs if oemof is installed with `pip install oemof`, no error occurs if oemof is installed with `pip install -e /path/to/clone`. That's why we did not notice.

The bug is annoying because inexperienced users may think that the oemof installation is not working but oemof works fine only the test script does not work.

We should not even repair the script but change the place because it is a bad practice to create a tests package within the python site-packages.

Until we fixed the script people can use the script one can use the [installation_test from the example repository](https://github.com/oemof/oemof_examples/tree/master/examples/oemof_0.2/installation_test).

 We should announce that. I will start with the release message.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group Shall we fix it, or remove it?

@gnn What do you think?

**Comment by ckaldemeyer** [comment]
> @oemof/oemof-developer-group Shall we fix it, or remove it?

Removal!

**Comment by jnnr** [comment]
For me, it works and says "successfully installed". Just gives some warnings.

**Comment by uvchik** [comment]
> Just gives some warnings.

The warnings are part of the script, that is not the problem.

> For me, it works and says "successfully installed".

It works for local installations and this is the reason why we did not notice this bug before the release. But it does not work if you install oemof with `pip install oemof`.

**Comment by jnnr** [comment]
Thanks Uwe, and sorry, I just read your initial post again. Sorry for the confusion.
