### ISSUE TITLE
Default _Sequence causes multiple list extensions. Performance/memory issue? 

### ISSUE THREAD

**Issue by henhuy** [oemof/oemof#436]
I just saw that a sequence with a default value generated by `plumbing._Sequence` does not create a list at first, but extends the list every time an item with higher index is demanded. This leads to the following behavior: Say I have an energysystem with 8760 timesteps, while building this energysystem every sequence which was build by default calls it `__getitem__` function 8760 times and thus the function extends the internal data list every time by only one value. Maybe this is not very good for performance and memory reasons...

Two suggestions:
1. If no additional value is set via `__setitem__` every time only default is returned (no list extension)
2. If length of sequence is known, list is pre-built with `[default] * length` items

What do you say?

**Comment by uvchik** [comment]
I do not understand the implications for the performance but if everything works I am fine with it.

I think you should wait for a comment of @gnn or create a PR and set @gnn as reviewer because he wrote the function.

**Comment by simnh** [comment]
I think 2. never happens. How should the length be know, if so, it will be a iterable object, so there is no problem anyway. 

For the 1. proposal: I think this is a good idea, however, as we have a lot of optional attributes that may be a sequence but do not have to, we implemented it this way as constraints etc. are always constructed for the all timesteps.

So you need to find a solution when a index is provided, as a list is assumend, e.g. `flow_object.min[5]`

Maybe you already know this, then I did not understand your proposal....

One other option might be to do the following instead: If the default value is set as an attribute, find the timeindex of the energy-system-object and do what you said something like `[default] * len(time_index)`

**Comment by jnnr** [comment]
The respective PR has been merged, so I will close this issue.
