### ISSUE TITLE
Upcoming release v0.2.1

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof#447]
**Release v0.2.1 at the Wednesday, 07. March 2018 10 AM**

Dear developers! @oemof/oemof-developer-group 

in a few weeks we would like to release the following version to the great accomplishment of v0.2.0. It is best not to wait to long with that to be able to capture all the bits that came up since then. 

This is a good chance to include your new contributions, to finish something that you are working on at the moment or to tackle some open issue that should be resolved soon.

**Comment by jnnr** [comment]
@uwe: I registered to get a pypi account. Could you please tell me how I get permissions to upload to pypi?

**Comment by jnnr** [comment]
Dear developers! Thank you for your contributions and your help for this release. 

While the last adaptions are on their way, I would like to invite you have a look at the what's new (https://github.com/oemof/oemof/blob/dev/doc/whatsnew/v0-2-1.rst) to see if my conclusion of the changes are correct and I did not miss anything.

Also, if you want to, put your name to the list of contributors. Thanks again for your help!

**Comment by ckaldemeyer** [comment]
> Dear developers! Thank you for your contributions and your help for this release.
> 
> While the last adaptions are on their way, I would like to invite you have a look at the what's new (https://github.com/oemof/oemof/blob/dev/doc/whatsnew/v0-2-1.rst) to see if my conclusion of the changes are correct and I did not miss anything.
> 
> Also, if you want to, put your name to the list of contributors. Thanks again for your help!

Thanks for your effort. I just wanted to change a minor formatting thing within the notes on the dev but now managed to somehow destroy the layout. Maybe someone can have a look. I don't see my mistake right now ;-)

**Comment by ckaldemeyer** [comment]
> Dear developers! Thank you for your contributions and your help for this release.
> 
>     While the last adaptions are on their way, I would like to invite you have a look at the what's new (https://github.com/oemof/oemof/blob/dev/doc/whatsnew/v0-2-1.rst) to see if my conclusion of the changes are correct and I did not miss anything.
> 
>     Also, if you want to, put your name to the list of contributors. Thanks again for your help!
> 
> Thanks for your effort. I just wanted to change a minor formatting thing within the notes on the dev but now managed to somehow destroy the layout. Maybe someone can have a look. I don't see my mistake right now ;-)

O.k., it was already "broken" with https://github.com/oemof/oemof/blob/f1005a561121729605252ad390b6bfe1d8d7b699/doc/whatsnew/v0-2-1.rst

So it wasn't me ;-)

**Comment by uvchik** [comment]
I will have a look.

**Comment by ckaldemeyer** [comment]
> I will have a look.

Thank you!

**Comment by uvchik** [comment]
- I added the links for most PRs if I found it. Please remember in the future. It is more transparent.
- The contributor names are now in alphabetic order.
- The layout is fixed.

**Comment by uvchik** [comment]
I hope, I did not overwrite anything as more than one person adapted the file at the same time....

**Comment by ckaldemeyer** [comment]
> I added the links for most PRs if I found it. Please remember in the future. It is more transparent.
> The contributor names are now in alphabetic order.
> The layout is fixed.

Thanks!

**Comment by uvchik** [comment]
http://oemof.readthedocs.io/en/latest/whats_new.html#v0-2-1-march-9-2018

**Comment by jnnr** [comment]
Thanks! Especially for adding the issues. That's very useful.

**Comment by jnnr** [comment]
Dear developers, thanks again for your effors. The fixes of PRs #460 and #456 will be included in v0.2.1. Just to let you know: As I have other urgent projects in the beginning of this week I would like to postpone the release until Wednesday. I hope this is fine with everyone.

**Comment by ckaldemeyer** [comment]
> Dear developers, thanks again for your effors. The fixes of PRs #460 and #456 will be included in v0.2.1. Just to let you know: As I have other urgent projects in the beginning of this week I would like to postpone the release until Wednesday. I hope this is fine with everyone.

For me, this would be absolutely fine. Thanks!

**Comment by jnnr** [comment]
Dear developers, sorry for the delay. To wrap up: 
merged:
* 460 allowes to serialize and deserialize nodes arbitrary number of times.
* 456 fixes the issue with pyomo.
* 462 adds the possiblity to return dataframe with multiindex column / index for a view.

still has to be merged:
* 465 fixes issues like the non-running simple dispatch example 464

Is there anything missing for the release?

**Comment by uvchik** [comment]
We should release soon because of the pyomo-issue.

I would just merge 460/465 and release.

We can release v0.2.2 in two weeks if we forgot something important.

**Comment by jnnr** [comment]
I merged #465 and #460.

**Comment by uvchik** [comment]
Thank you for the release :tada: Great work.

**Comment by ckaldemeyer** [comment]
:+1: Thanks! :tada:

**Comment by nesnoj** [comment]
Cheers! :tada:

**Comment by jnnr** [comment]
Thank you all for your contributions and commitment! Well done! The news for the release is now published, have a look if you want: https://oemof.org/2018/03/20/gambling-generator-v0-2-1/
