### ISSUE TITLE
Add datapackage-reader

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#450]
We are currently adding functionality to build energy system from a datapackage structure. 

I guess we will be aiming for full oemof-solph functionality without `solph.options` for the start. 

If two complicated we will use facades module, but we will try to be as generic as possible. There is a pull request open: #451

**Comment by simnh** [comment]
Example can be found in the oemof examples repo:

https://github.com/oemof/oemof_examples/tree/features/data-package-reader/examples/oemof_0.2/datapackage-reader

**Comment by uvchik** [comment]
PR #451 is merged and the link does not work any more. I think we can close it.
