### ISSUE TITLE
Outputlib: Param Results 

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#463]
Hey, 

I just stumbled upon the `param_results` function in the outputlib (I kind of missed the PR). I really like the idea of this feature and its a great enhancement I think! However, I would like to point out a few things: 

* I guess the Docstring is not correct, at least I get back only tuples as keys and if its about the node parameters i get `(node, None)`. The docu states that flows are found under key `flows` and nodes under `nodes`. But maybe I just don't understand the doc string right? 
[see code here](https://github.com/oemof/oemof/blob/ba321fd38fcc7d94932684fbdaae631af1b1eff4/oemof/outputlib/processing.py#L319-L321)
* The outputlib may be the right place for now, but I think the name is kind of confusing, as their are not results processed but input parameter (if I understand it correct?). Therefore I would suggest renaming it. 
* In addition, I would like to think about if None values should be converted to strings when `key_as_str `is set to True. I think we could rather leave it as None

I think this all relates to handling of input/output (exo-endogenous parameter handling, viewing, processing), the scenario definition and energy system methods. But the things above can be addressed anyway...

**Comment by uvchik** [comment]
This was a project of @ckaldemeyer and @henhuy and I did not use it so far, so I removed my name from the assignees.

**Comment by henhuy** [comment]
Hi @simnh,
thank you for your feedback.
Indeed, I agree to all of your recommendations!
As Uwe pointed out, we shouldn't change the API. So I think, I will cover point 1 and 3, but renaming of the function has to be postponed, right?

**Comment by simnh** [comment]
Yes, but we should keep it in mind before the next major release v0.3...

We can make a PR for this and discuss further things there...

**Comment by uvchik** [comment]
> Yes, but we should keep it in mind before the next major release v0.3...

Indeed. We can already start the roadmap for the v0.3 release and add everything we would like to change for the next mayor release.  We can discuss the list on the dev-meeting in May and complete the release on the dev-meeting in December... :smile:

**Comment by uvchik** [comment]
The None/'None' issue is still open. Everything else is fixed.

**Comment by busiing** [comment]
Self-assignment due to oemof dev meeting - issue auction

**Comment by uvchik** [comment]
I think this is fixed with a compromise. By default None will be 'None' if the keys have been converted to strings but one can set the parameter `keep_none_type` to True to avoid 'None' strings and keep the None Type.

```python
convert_keys_to_strings(result, keep_none_type=True)
```
