### ISSUE TITLE
Is there a reason why the api of results and param_results differs?

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#473]
The api of `results` and `param_results` differs in the processing module. Is there a reason for the difference?

To get keys as strings I have to different things even though the structure is quite similar.

Shouldn't we add a `keys_as_str` attribute to the `results` function as well?

```python
# results
my_results = processing.results(om)
my_results = processing.convert_keys_to_strings(my_results)

# param results
my_param_results = processing.param_results(om, keys_as_str=True)

**Comment by jnnr** [comment]
Yes, good idea. I would vote for adopting the `keys_as_str` option to `results()`.

**Comment by uvchik** [comment]
@jnnr This is what I first thought but we decided that the output of the results function is the standardised API of the oemof output. Adding the attribute would lead to two different outputs and we would not have one standardised API any more.

**Comment by henhuy** [comment]
Okay then - shall we simply remove the `keys_as_str` parameter from `param_results` function?

**Comment by uvchik** [comment]
> Okay then - shall we simply remove the keys_as_str parameter from param_results function?

:+1: 

Shall we also rename it (see #485) ?

**Comment by uvchik** [comment]
Fixed.
