### ISSUE TITLE
Usage of Python/oemof-packages

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#48]
I have just stumpled across an article about a Python workflow using Anaconda: http://stiglerdiet.com/blog/2015/Nov/24/my-python-environment-workflow-with-conda/ .

By the way, I got it from http://www.pythontips.com which is worth outchecking ;-)

So far we are a small crowd of developers mostly working on GNU/Linux and only have a few pure application-users. In the installation HowTo, everything is explained using the systems Python installation which can have some disadvatages when working on different projects, versions, etc.. See the article for more information.

Even if that might not apply for most of us, when I look at the future development and usage of oemof in university courses and seminars, I see long installation parties for different operating systems (Windows, OSX, Linux, ...) coming since the Python distributions, PATH-adjustments, etc. differ a lot among the OSes.

If I get the above article right, all this could be prevented by using the explained workflow since Anaconda is available for all mainstream operating systems. Looking at the license (which is BSD 3-clause: http://docs.continuum.io/anaconda/eula) we shouldn't get into trouble. If we did it like this, our installation HowTo would be comparably lean, similar to Stefan's: http://docs.callio.pe/en/stable/user/installation.html

@oemof/oemof-main What do you think?

**Comment by uvchik** [comment]
I thought we already agreed on the meeting in Flensburg, that we can use both. So I think that everybody is free to create a package for conda. I don't see a reason to object. Except the release manager who has to create another package :smirk:. Do you have an instruction? Shouldn't be too difficult. To make it easier for the release manager we could make a team for pypi and one for anaconda, so that not everybody has to know how to create a package.

The pvlib also offers both:

> To obtain the most recent stable release, just use pip or conda:
> ```
pip install pvlib
```
> ```
conda install -c http://conda.anaconda.org/pvlib pvlib
```
This is just one line in the Readme and maybe another line with a link to "How to install Anaconda".

**Comment by ckaldemeyer** [comment]
You are right, I forgot about that discussion. So the question is: should we provide a conda-package for each release?

Here are two HowTos that explain how to create conda packages from pypi packages:

* http://www.peterbronez.com/Using%20PyPi%20Packages%20with%20Conda
* http://conda.pydata.org/docs/build_tutorials/pkgs.html

**Comment by ckaldemeyer** [comment]
In my opinion, we should have a conda package..

**Comment by uvchik** [comment]
I'm fine with conda but will not do it.

**Comment by cswh** [comment]
Perhaps we can do it for the major releases, like v0.1.0 in May?

**Comment by ckaldemeyer** [comment]
Yep. I am planning to switch back to xubuntu with the release of 16.04 and in that case want to set up my Python environment using anaconda anyway.

I would offer myself to look after the conda package.

**Comment by uvchik** [comment]
Cool :smile: Thank you.

**Comment by uvchik** [comment]
Can we close this issue?

**Comment by birgits** [comment]
@ckaldemeyer: Clemens suggested to do this for the major release in may. What do you think?

**Comment by ckaldemeyer** [comment]
Refering to my initial post:

Simon and me are using Anaconda including pandas, pyomo, glpk, ... in a master course now and the installation worked fine on all OSes using a suitable recipe (https://github.com/CAChemE/pyomo-recipes).

I think for unexperienced people even the Python installation is a first obstacle and if we want oemof to be used by many people we should lower the entry barriers where possible.

@birgits: Yes, I think it's a good idea to provide a package in May. I'll check how the process works and post it here!

**Comment by uvchik** [comment]
As I know it, it is no problem to install a pip package within conda. 

How big is the advantage compared to the extra work.

Will anybody be responsible for the conda package and its updates. Otherwise we can close this issue.

**Comment by ckaldemeyer** [comment]
You're right with the pip installation option.

> How big is the advantage compared to the extra work.

Not very big. I'll close it and we can still re-open it if the need for a conda package comes up.
