### ISSUE TITLE
Explicit timeincrement / weighting for energy system and models

### ISSUE THREAD

**Issue by simnh** [oemof/oemof#487]
Currently we use the timeindex (pd.DataTimeIndex) to determine the 'timeincrement' within the model(s). However there are some drawbacks: 

1. Sometimes you like to set different weighting for objective and constraints (this option has been added on the solph level already)
2. For a datetimeindex with no valid 'freq' attribute, this does not work. If typical periods with different weightings are used, this is for example the case. 

I propose to add a `temporal` attribute to the energy system, which will be a pandas dataframe with datetimeindex and possible columns: 

Something like: 
`weighting`, `constraint_weighting` and `objective_weighting`

I would like to implement this soon (we can discuss the exact way in a pull request) and add a depreciated warning to the timeindex which we could remove in v0.3

Regarding the best way and the API I am still quite unsure what would be the best way to keep it simple (like now) but still flexible without too complicated internal logic....

What do you think?

**Comment by uvchik** [comment]
I noticed that silent changes have been done. Instead of implicitly setting a time increment I would rather make it possible to pass the time increment to the class.

```diff
- self.timeincrement = sequence(self.es.timeindex.freq.nanos / 3.6e12)
+ self.timeincrement = kwargs.get('timeincrement')
+ if self.timeincrement is None:
+    try:
+        self.timeincrement = sequence(self.es.timeindex.freq.nanos / 3.6e12)
+    except AttributeError:
+        raise AttributeError(
+                'Could not get timeincrement from pd.DateTimeIndex! ' +
+                'To avoid this error, make sure the `freq` attribute of ' +
+                'your timeindex is not None or set the timeincrement directly.')
```

Furthermore I would prefer a PR/issue for such changes.

**Comment by uvchik** [comment]
Nothing happened for one and a half year. Please reopen if it is still valid.
