### ISSUE TITLE
Add cost attributed to NonConvexFlow to objective expression 

### ISSUE THREAD

**Issue by mloenneberga** [oemof/oemof#488]
Hi all, 

on my oemof branch i added a cost attribute to NonConvexFlow, i.e. cost that occur in case the status is 1 disregarding the actual value. Do you think its useful to have such cost in Oemof? I would be happy to have your feedback before preparing a pull request.

I used it to model operating cost which are dependent on the operating hours of an OffsetTransformer.

**Comment by simnh** [comment]
Hey, I think this can indeed be useful. Can you create a pull request? 

>  ...dependent on the operating hours 

But  doesn't this mean that the value you set is dependent on the sum of status values?

**Comment by uvchik** [comment]
> But doesn't this mean that the value you set is dependent on the sum of status values?

I would say yes, with EUR/hour (or per time increment) if the status is 'on'.

**Comment by mloenneberga** [comment]
Yeah its dependent on the sum of status variables.  Thanks for your feedback i will prepare a pull request.

**Comment by uvchik** [comment]
I think this is closed by #509.
