### ISSUE TITLE
Change license to a permissive licence

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#50]
oemof is a basic library that should be used in other libraries. The GPL3 makes it more complicate to use it in projects with permissive licenses such as BSD, MIT, Apache...

Therefore, I would like to change the license to a more permissive license.

The easy MIT licences could be a good choice. 

Please poke your colleagues and edit the list (if you can) or write a comment with a clear statement.

UPDATE: The following list will be updated according to the votes below. **Votes for MIT**.

## oemof-core, solph, outputlib,  :heavy_check_mark: 
@uvchik :heavy_check_mark: 
@ckaldemeyer :heavy_check_mark: 
@gnn :heavy_check_mark:
@simnh :heavy_check_mark: 
@c-moeller :heavy_check_mark: 
@jnnr :heavy_check_mark: 
@gplssm :heavy_check_mark:
@p-snft :heavy_check_mark: 
@steffenGit :heavy_check_mark: 
@birgits :heavy_check_mark:
@cswh :heavy_check_mark:
@henhuy :heavy_check_mark: 
@FranziPl :heavy_check_mark: 
@joroeder :heavy_check_mark:
@FabianTU :heavy_check_mark: 
@jakob-wo :heavy_check_mark: 
@pkassing :heavy_check_mark: 
@bmlancien :heavy_check_mark: 
@lluismillet :heavy_check_mark:
@wolfbunke :heavy_check_mark: 
@mloenneberga :heavy_check_mark:
@drjod :heavy_check_mark:
@elisapap :heavy_check_mark:
@elisagaudchau :heavy_check_mark:
@chrisflei :heavy_check_mark:
@ajimenezUCLA :heavy_check_mark: 

## oemof-examples  :heavy_check_mark:
@simnh :heavy_check_mark:
@uvchik :heavy_check_mark:
@c-moeller :heavy_check_mark:
@birgits :heavy_check_mark:
@jnnr :heavy_check_mark:
@s3pp :heavy_check_mark:
@gnn :heavy_check_mark:
@ckaldemeyer :heavy_check_mark:
@oakca :heavy_check_mark:
@SabineHaas :heavy_check_mark:
@nesnoj :heavy_check_mark: 
@pkassing :heavy_check_mark: 
@p-snft :heavy_check_mark:
@fwitte :heavy_check_mark:
@tbors :heavy_check_mark:

## feedinlib :heavy_check_mark: 
@uvchik :heavy_check_mark: 
@gplssm :heavy_check_mark:
@gnn :heavy_check_mark:
@birgits :heavy_check_mark:
@ckaldemeyer :heavy_check_mark: 
@pajot :heavy_check_mark: 

## windpowerlib :heavy_check_mark: 
@uvchik :heavy_check_mark: 
@SabineHaas :heavy_check_mark: 
@birgits :heavy_check_mark:
@pajot :heavy_check_mark: 

## demandlib :heavy_check_mark: 
@uvchik  :heavy_check_mark: 
@gplssm :heavy_check_mark:
@birgits :heavy_check_mark:
@jnnr :heavy_check_mark: 
@c-moeller :heavy_check_mark: 
@pajot :heavy_check_mark: 
@henhuy :heavy_check_mark: 
@Pyosch :heavy_check_mark:

## tespy :heavy_check_mark: 
@fwitte :heavy_check_mark:
@uvchik  :heavy_check_mark:
@ShuangChen88  :heavy_check_mark:
@TimHoener  :heavy_check_mark:
@pjhansen  :heavy_check_mark:
@nilsstolze  :heavy_check_mark:

## cydets :heavy_check_mark:
@ckaldemeyer :heavy_check_mark:
@fwitte :heavy_check_mark:
@psychon :heavy_check_mark:

**Comment by p-snft** [comment]
As we addressed this topic in this year's developer spring meeting, I hope we do not need long discussions. I still see three different options:
* MIT: You may use the code when you name the authors on redistribution.
* Apache: You may use the code when you give needed patent licenses (if applicable).
* LGPL: You may use the code when you relicense changes directly to the code under the same license.

GPL (what we have now) requires the user to relicense any derived software (even if it just imports oemof) to use GPL as well. It is discouraged to use it for libraries. (I wonder if this was clear when the license was chosen.)

From the **user perspective**, Apache and LGPL3+ have a benefit, as it addresses the risk of possible patent claims. From the **developers' perspective** who want to use code fragments and not oemof as a whole, the reusablity relies very much on their chosen license. As there are many options around, it probably makes have a look at something like an [inheritance tree](https://en.wikipedia.org/wiki/License_compatibility#/media/File:Floss-license-slide-image.png).

At the moment I assume that software patents on the oemof code are not the major issue, so I would also opt for MIT.

**Comment by ckaldemeyer** [comment]
I agree with your arguments towards a higher reusability of the code. Is there a special reason why you did not consider the BSD licenses?

**Comment by p-snft** [comment]
BSD and MIT licenses allow practically the same things but MIT license is more explicit: MIT allows to
"use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies". In contrast, BSD allows "Redistribution and use", where "use" is meant to include all the things explicitly mentioned in the MIT license.

Also, I would consider the existent of the various BSD licenses confusing (zero, two or the clause, original, revised, …) whereas "MIT license" is very distinct. (I know, there are "only" four BSD licenses, but they have various names.)

PS: Is there a reason to prefer BSD over MIT?

**Comment by uvchik** [comment]
I heard that both are similar but MIT is clearer, so I would prefer MIT. 

It seems that most projects on github think that way, even though the majority is not necessarily rigth :smirk: .

![Bildschirmfoto_2019-09-30_11-39-29](https://user-images.githubusercontent.com/4760584/65867599-0241f080-e377-11e9-9c35-64590f5761a5.png)

Source: https://github.blog/2015-03-09-open-source-license-usage-on-github-com/

**Comment by ckaldemeyer** [comment]
> BSD and MIT licenses allow practically the same things but MIT license is more explicit: MIT allows to
> "use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies". In contrast, BSD allows "Redistribution and use", where "use" is meant to include all the things explicitly mentioned in the MIT license.
> 
> Also, I would consider the existence of the various BSD licenses confusing (zero, two or the clause, original, revised, …) whereas "MIT license" is very distinct. (I know, there are "only" four BSD licenses, but they have various names.)

Thanks a lot for clarification!

> PS: Is there a reason to prefer BSD over MIT?

I do not prefer BSD not aware of the similarities and differences. The last timeit looked into licensing (of scientific software) I had the feeling that BSD 2-clause was the prominent permissive license but this was years ago and has obviously changed meanwhile.

> I heard that both are similar but MIT is clearer, so I would prefer MIT.
> 
> It seems that most projects on github think that way, even though the majority is not necessarily rigth smirk .

These stats are really interesting. Thanks.

Generally, to me the question of licensing is quite a big one as it touches personal views (of software and other intellectual property) and last but not least the project organization as different projects under the oemof umbrella might loose their compatibility.

This does not mean that I do not support the idea as my gut feeling is that the pros of a permissive license outperform the cons in this case while preferring an MIT license if we re-license to a permissive one.

But wouldn't this be a good session for the meeting in december as many people are involved?

Anyhow, thanks for clarification!

**Comment by p-snft** [comment]
> But wouldn't this be a good session for the meeting in december as many people are involved?

Actually, we have to ask every single contributor to re-license the according code fragments. For oemof this means, that it can change to the most permissive license that every author agrees to.

**Comment by uvchik** [comment]
> But wouldn't this be a good session for the meeting in december as many people are involved?

It has been a session at the last meeting but a lot of contributors did not attend. But as @p-snft mentioned we have to ask everybody.

> Actually, we have to ask every single contributor to re-license the according code fragments. For oemof this means, that it can change to the most permissive license that every author agrees to.

I think we should ask everybody and give them time to object. But if people do not react ever again I would take that as a silent approval. But we should try to contact everybody.

> Generally, to me the question of licensing is quite a big one as it touches personal views (of software and other intellectual property) and last but not least the project organization as different projects under the oemof umbrella might loose their compatibility.

I would try to find an overall consent on that. So I updated the list in the first comment and ask everybody who reads this to poke your colleagues and friends from the list above.

**Comment by gplssm** [comment]
I fully agree to change the code licensing of the code in the oemof packages I contributed to the MIT license.

Good initiative! :clap: I'll to that RLI people react

**Comment by ckaldemeyer** [comment]
> > But wouldn't this be a good session for the meeting in december as many people are involved?
> 
> It has been a session at the last meeting but a lot of contributors did not attend. But as @p-snft mentioned we have to ask everybody.
> 
> > Actually, we have to ask every single contributor to re-license the according code fragments. For oemof this means, that it can change to the most permissive license that every author agrees to.
> 
> I think we should ask everybody and give them time to object. But if people do not react ever again I would take that as a silent approval. But we should try to contact everybody.
> 
> > Generally, to me the question of licensing is quite a big one as it touches personal views (of software and other intellectual property) and last but not least the project organization as different projects under the oemof umbrella might loose their compatibility.
> 
> I would try to find an overall consent on that. So I updated the list in the first comment and ask everybody who reads this to poke your colleagues and friends from the list above.

Thanks for your initiative @p-snft, @uvchik and @gplssm. I have updated cydets and will discuss with @fwitte. I know that @simnh is not in his office in October but he might react anyhow.

**Comment by fwitte** [comment]
Agree, this is a very good idea! I  added my check-marks already @ckaldemeyer :)!

**Comment by ckaldemeyer** [comment]
Oh, so we were probably editing parallely ;-)

**Comment by gnn** [comment]
Interesting. I usually prefer the Modified BSD (BSD-3-Clause) license because it's wording is clearer to me. But since it's essentially equivalent to the MIT license, I'm on board with MIT.

**Comment by pajot** [comment]
I fully agree to changing the code licensing of the code in the oemof packages I contributed to the MIT license.

:)

**Comment by bmlancien** [comment]
I agree to change the licensing of the code.

**Comment by oakca** [comment]
agreed

**Comment by nesnoj** [comment]
I fully agree to changing the code licensing of the code in the oemof packages I contributed to the MIT license.

**Comment by jakob-wo** [comment]
I actually like the GPL. But I wont stand in the way if the majority (especially the main-developers) want to change to a more permissive licence.
Therefore, I agree to change the licence to MIT.

**Comment by lluismillet** [comment]
I agree to change the licensing to MIT and welcome the proposed change! Thanks

**Comment by cswh** [comment]
I agree to any licence changes.

**Comment by s3pp** [comment]
I also agree to the proposed licence changes.

**Comment by psychon** [comment]
I hereby place all of my current changes to cydets (https://github.com/oemof/cydets/commit/9e7597c6129a5feb81d035d4f43b885dc0b38ab8, https://github.com/oemof/cydets/commit/680814317a7cb8998ec3e98bfb0ab46a87705c44, https://github.com/oemof/cydets/commit/5b89c382279a8487e88c5047c7d06a445282efb2) under the WTFPLv2. 
<details>
<summary>Non family-safe full license text follows (copied from http://www.wtfpl.net/about/)</summary>

>         DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
>                         Version 2, December 2004 
>     
>      Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 
>     
>      Everyone is permitted to copy and distribute verbatim or modified 
>      copies of this license document, and changing it is allowed as long 
>      as the name is changed. 
>     
>                 DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
>        TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 
>     
>       0. You just DO WHAT THE FUCK YOU WANT TO.
</details>

I also make it clear that it is my understanding that this license explicitly allows everyone to change the license of my contributions in whatever way they see fit.

<details><summary>FAQ</summary>

## Why don't you just say "public domain"?

[Because I do not live in the USA.](https://en.wikipedia.org/wiki/Public_domain#Dedicating_works_to_the_public_domain) In my jurisdiction, (AFAIK) copyright is something that cannot simply be given up (or even transferred).
</details>

**Comment by wolfbunke** [comment]
Hi everybody,

I also agree on the license change to MIT. 

Thanks a lot and keep on coding :)
Wolf

**Comment by nailend** [comment]
I fully agree to change the licensing to MIT and welcome the proposed change! Thanks a lot!

**Comment by chrisflei** [comment]
Hi,
Sorry for the late reply.
I also agree to the change to MIT.
Chris

**Comment by uvchik** [comment]
The majority of the oemof contributors agreed with the change from the GPLv3 to MIT. 

So far only 6 contributors have not given a response. Please give your feedback soon :exclamation: 

@pkassing, @ajimenezUCLA, @tbors, @TimHoener, @pjhansen, @nilsstolze

**Comment by pjhansen** [comment]
﻿I accept from switching GPLv3 to MIT.

**Comment by FranziPl** [comment]
I asked tbors. He cannot log in to github with his account, but he is fine with the licence change.

**Comment by uvchik** [comment]
We got a positive feedback from 37 of 39 contributors to change the licence of all oemof repositories from the GPLv3 to the more permissive MIT licence.

The missing feedback from @ajimenezUCLA affects the `solph` package and therefore the oemof repository, the missing feedback of @TimHoener the `tespy` repository. All the other repositories are ready to change their licence.

@ajimenezUCLA and @TimHoener please give a feedback soon :exclamation:

**Comment by p-snft** [comment]
Both persons seem to be one-time contributors, so they might not be too attached to oemof. @ajimenezUCLA solely authored https://github.com/ajimenezUCLA/oemof/commit/886600d8376fdd21ce05e1e878530bbece95aa3a. @TimHoener commited https://github.com/oemof/tespy/commit/8e7f2b3e5a1fa067d7903592952b2a95aeb40e5c.

**Comment by TimHoener** [comment]
I agree to the licence change.

**Comment by ajimenezUCLA** [comment]
Hi guys, I'm all for the change as well.

**Comment by fwitte** [comment]
Great, we are complete now, thank you everybody for your feedback!

**Comment by uvchik** [comment]
Shall we write an news message at oemof.org?

**Comment by fwitte** [comment]
Do we still want to publish a news entry? Otherwise we could close here, I think.

**Comment by uvchik** [comment]
I think we still should as soon as somebody finds the time.

**Comment by p-snft** [comment]
A fitting point in time would be when https://github.com/oemof/feedinlib/pull/39 is pulled. Then, all projects have a permissive license. (Some examples still name the GPL in their header, though.)

**Comment by p-snft** [comment]
Done.
