### ISSUE TITLE
Improve the documentation of the outputlib

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#500]
We should write it directly for the v0.3.0 release because there are already some API changes and in my opinion it does not make sense to write a documentation and adapt it a few month later.

@oemof/oemof-assistants Who would help?

**Comment by uvchik** [comment]
@oemof/documentation, @oemof/oemof-assistants Still help needed.

The documentation of the outputlib needs to be checked.

**Comment by uvchik** [comment]
This is a good issue for inexperienced users. You do not have to do it now it can be postponed to the next release. I could help if you have any questions

https://oemof.readthedocs.io/en/stable/oemof_outputlib.html#oemof-outputlib-label

This is what we have now. Do you think this is enough? What questions do new users have about results processing?

For me everything is pretty clear therefore it would be nice to get a feedback from new users :exclamation:

**Comment by p-snft** [comment]
For me, the `outputlib` was not too intuitive in the beginning and I am still working based on examples. However, I would not wait for this for the v.0.3.0 release.

**Comment by joroeder** [comment]
Do you think we can close this issue for now? If there is any need for further improvements, we can open a new issue...

**Comment by p-snft** [comment]
As it is improved, I think it is in order to mark this issue solved.
