### ISSUE TITLE
Check implementation of time-increment indepency

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#51]
So far we are only calculating on an hourly basis which implies that power and energy have the same value e. g. 1 MW equals 1 MWh. This is also reflected in all underlying solph-equations which to not distinguish between power and energy.

To allow time-increment independency, all equations that contain energy balances have to be extended by a multiplication with the time-increment.

**Example:**

A (very) simple storage balance:

W_sto(t)= W_sto(t-1) + Tau \* (P_sto_in(t) - P_sto_out(t)) for all t element [1, t_max]

In this case "Tau" is the chosen time-increment (e.g. 0.25 h).

**Comment by ckaldemeyer** [comment]
I have made up my mind about this and went through the files to get an idea what's the best way for an implementation.

Here's my proposal which basically only affects objective components:

objective_expressions.py:

	# PROPOSAL: capacity * time_increment * prices in unit/amount of energy
	def add_opex_var(model, block, ref='output'):

	# PROPOSAL: capacity * time_increment * prices in unit/amount of energy
	def add_input_costs(model, block):

	# PROPOSAL: no changes (only capacities and prices/unit of capacity)
	def add_opex_fix(model, block, ref=None):

	# PROPOSAL: capacity * time_increment * prices in unit/amount of energy
	def add_revenues(model, block, ref='output', idx=0):

	# PROPOSAL: capacity * time_increment * prices in unit/amount of energy
	def add_curtailment_costs(model, block=None):

	# NO CHANGES  (only capacities and prices/unit of capacity)
	def add_capex(model, block, ref='output'):

	# NO CHANGES  (starts * price/start)
	def add_startup_costs(model, block):

	# NO CHANGES  (starts * price/start)
	def add_shutdown_costs(model, block):

	# NO CHANGES (ramping capacity * prices/unit of capacity)
	def add_ramping_costs(model, block, grad_direc='positive'):

	# PROPOSAL: capacity * time_increment * prices in unit/amount of energy
	def add_excess_slack_costs(model, block=None):

	# PROPOSAL: capacity * time_increment * prices in unit/amount of energy
	def add_shortage_slack_costs(model, block=None):

linear_constraints.py:

	# NO CHANGES (only capacity related)
	def add_bus_balance(model, block=None):

	# NO CHANGES (only capacity related)
	def add_simple_io_relation(model, block, idx=0):

	# NO CHANGES (only capacity related)
	def add_two_inputs_io_relation(model, block):

	# NO CHANGES (only capacity related)
	def add_eta_total_chp_relation(model, block):

	# NO CHANGES (only capacity related)
	def add_simple_chp_relation(model, block):

	# NO CHANGES (only capacity related)
	def add_postheat_relation(model, block):

	# NO CHANGES (only capacity related)
	def add_simple_extraction_chp_relation(model, block):

	# NO CHANGES (only capacity related)
	def add_global_output_limit(model, block=None):

	# NO CHANGES (only capacity related)
	def add_fixed_source(model, block):

	# NO CHANGES (only capacity related)
	def add_dispatch_source(model, block):

	# MANDATORY: capacity * time_increment
	def add_storage_balance(model, block):

	# NO CHANGES (only capacity related)
	def add_storage_charge_discharge_limits(model, block):

	# NO CHANGES (only capacity related)
	def add_output_gradient_calc(model, block, grad_direc='both', idx=0):

linear_mixed_integer_constraints:

	# NO CHANGES (only capacity related)
	def set_bounds(model, block, side="output"):

	# NO CHANGES (only capacity related)
	def add_variable_linear_eta_relation(model, block):

	# NO CHANGES (only capacity related)
	def add_output_gradient_constraints(model, block, grad_direc="both"):

	# NO CHANGES (just sets BinaryVar)
	def add_startup_constraints(model, block):

	# NO CHANGES (just sets BinaryVar)
	def add_shutdown_constraints(model, block):

	# NO CHANGES
    def add_minimum_downtime(model, block):

	# NO CHANGES
    def add_minimum_uptime(model, block):

Additionally some doctrings have to be adjusted e. g. the ones for the minimum up- and downtimes. Introducing a time-increment means in this case that the time has to be provided in timesteps e. g. 16 for an up-/downtime of 4 hours when calculating quarter-hourly or 2 for when calculating two-hourly.

@oemof/oemof-main : As this is quite fundamental it would be nice to hear your opinion ;-)

**Comment by uvchik** [comment]
> Additionally some doctrings have to be adjusted e. g. the ones for the minimum up- and downtimes. Introducing a time-increment means in this case that the time has to be provided in timesteps e. g. 16 for an up-/downtime of 4 hours when calculating quarter-hourly or 2 for when calculating two-hourly.

If it is a change within solph we shouldn't need to change a docstring of the core package. Otherwise it shows a structural problem. Furthermore I would keep the unit `hour` for the up-/downtime and recalculate it within solph. The downtime is a parameter of the power plant and I do not want to change it if I change the time increment of my simulation. As we do have a pandas time index within the energy system object it should be possible.

What about the capex? Is the capex related to one year and what happens if optimise half a year?

@ckaldemeyer Thank you for your approach. It also shows that we have to clarify some things.

**Comment by ckaldemeyer** [comment]
> If it is a change within solph we shouldn't need to change a docstring of the core package. Otherwise it shows a structural problem.

Yes, I would just change the docstring in solph.

> Furthermore I would keep the unit hour for the up-/downtime and recalculate it within solph. The downtime is a parameter of the power plant and I do not want to change it if I change the time increment of my simulation. As we do have a pandas time index within the energy system object it should be possible.

I am not sure here. One the one hand I understand you point coming from the reality and looking after which object the data belongs to. On the other hand it makes solph more specific and the current idea is to move towards something more generic. Following this, the user just has to know how things work and has to make sure that his parametrisation suits which must be the case for other units such as prices, capacities, ... as well.

At the moment, I tend to the second solution.

> What about the capex? Is the capex related to one year and what happens if optimise half a year?

From my opinion: same as in the answer before. The user has to make sure that everything is in line. This also accounts for opex_var, opex_fix, ...

But specificly for CAPEX: aren't they the same for different optimisation horizons?

**Comment by ckaldemeyer** [comment]
I have thought again about this. My CAPEX-question was stupid because one can of course recalculate them for different time spans such as one year, ... 

But I would still leave it to the user!

**Comment by uvchik** [comment]
Actually your issue was not about the capex but it touches a basic discussion that is also relevant for the capex.

How shall we define time parameters and time-depended parameters. It is related to you topic but if you want I could open a new issue.

> At the moment, I tend to the second solution.
I get the point but I am still indecisive. If we do so we should rename the attribute to avoid miss interpretation.

The crf (capital recovery factor) and interests are given per year. If we simulate two years or half a year we have to multiply it with 2 or 0.5 or we have to make clear that lifetime and wacc are only for one year simulations. Otherwise one have to calculate  its own crf and pass it to the simulation.

The opex_fix has already the right docstring because it says "monetory value over the full time period".

```
class Component(Entity):
    [...]
    capex : float
        Capital expenditure. To get the capital cost it is multiplied with
        out_max (monetory value per power).
    lifetime : float
        lifetime of component (e.g. years)
    wacc : float
        weigted average cost of capital (dimensionless)
    crf : float
        capital recovery factor: (p*(1+p)^n)/(((1+p)^n)-1)
    opex_fix : float
        fixed operational expenditure (e.g. expenses for staff) (monetory
        value over the full time period).
    opex_var : float
        Variable operational expenditure (e.g. spare parts). You can use it to
        define the fuel costs. Fuel cost can be defined in different ways, so
        be aware not to define them twice.
    """
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        [...]
        self.capex = kwargs.get('capex', 0)
        self.lifetime = kwargs.get('lifetime', 20)
        self.wacc = kwargs.get('wacc', 0.05)
        self.opex_var = kwargs.get('opex_var', 0)
        self.opex_fix = kwargs.get('opex_fix', 0)

        self.crf = kwargs.get('crf', None)
        if self.crf is None:
            p = self.wacc
            n = self.lifetime
            self.crf = (p*(1+p)**n)/(((1+p)**n)-1)
```

**Comment by caro-rli** [comment]
> What about the capex? Is the capex related to one year and what happens if optimise half a year?

Just to understand this topic: Aren't these two different points. One is having the possibility to use various time-increments (quarter, hour, ...) and the other is about time-horizons (one year, half an year, ...) ?

**Comment by uvchik** [comment]
That's what I said in my comment before. I could open an extra issue, but it touches similar points.

The main point of this topic to implement various time-increments. If you want to do this it has to be clear how we want to define time and time depended variables. And this is also relevant for various time horizons.

Will `maximal downtime` be defined in 'hours' or in 'number of time increments'?
Will `opex_fix` be related to one year or to the time horizon?

I we want to use 'number of time increment' we should also related `opex_fix` to the time horizon or the other way round. Otherwise it will be confusing in my opinion.

The calculation of the capital recovery factor is something special, that we need to outsource if we decide to relate everything to time increments/horizons.

Shall I open a new issue for that question. It definitely blocks this issue.

**Comment by ckaldemeyer** [comment]
As Caro stated we have two points:

1. Flexible time increments
2. Different time (optimisation) horizons

Both affect the definition/treatment of other parameters which are passed into a specific model. 

Would it make sense to shift this issue to a single session at the next meeting in Flensburg?

**Comment by uvchik** [comment]
> Would it make sense to shift this issue to a single session at the next meeting in Flensburg?

That is a good idea, because it is very basic decision.

**Comment by uvchik** [comment]
@ckaldemeyer : Is this solved with the re-factored solph?

**Comment by simnh** [comment]
We implemented it but it has not yet been checked/tested. @ckaldemeyer is not available until august we
are looking for someone who: 

1. Checkst for the factor  `tau`  in all pyomo constraints that need to have it (everthing that's energy not power) 
2. Maybe check for results with an adapted example.

Who can take care of this ?

**Comment by caro-rli** [comment]
Ok, now I'm stumbling over this having an example which needs 15 min time steps. So I'm trying to check this.

**Comment by caro-rli** [comment]
Do you have an example where you use a time increment other than 1?
I now have an example with 1 year in 15 min time steps (35040 in total). When I set the time increment to 0.25 like this:

```python
solph.OperationalModel(energysystem, timeindex=energysystem.time_idx,
                       timeincrement=0.25)
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/caro/rlihome/Git/eos/examples_SOLPH_0.1/example_one_node.py", line 401, in <module>
    main(**arguments)
  File "/home/caro/rlihome/Git/eos/examples_SOLPH_0.1/example_one_node.py", line 385, in main
    **arguments)
  File "/home/caro/rlihome/Git/eos/examples_SOLPH_0.1/example_one_node.py", line 266, in create_energysystem
    timeincrement=0.25)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/models.py", line 203, in __init__
    block._create(group=self.es.groups.get(group))
  File "/home/caro/rlihome/Git/oemof/oemof/solph/blocks.py", line 776, in _create
    self.balance_build = BuildAction(rule=_busbalance_rule)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 448, in __setattr__
    self.add_component(name, val)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/block.py", line 780, in add_component
    val.construct(data)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/action.py", line 58, in construct
    self._rule(self._parent())
  File "/home/caro/rlihome/Git/oemof/oemof/solph/blocks.py", line 775, in _busbalance_rule
    block.balance.add((n, t), expr)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/constraint.py", line 1095, in add
    cdata = self._check_skip_add(index, expr)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/constraint.py", line 911, in _check_skip_add
    condata = _GeneralConstraintData(expr, component=self)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/constraint.py", line 286, in __init__
    self.set_value(expr)
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/constraint.py", line 562, in set_value
    val = self._lower()
  File "/usr/local/lib/python3.4/dist-packages/pyomo/core/base/expr_coopr3.py", line 687, in __call__
    ans *= n
TypeError: can't multiply sequence by non-int of type 'float'
```

What am I doing wrong?

**Comment by caro-rli** [comment]
I'm on first-refactoring/solph/dev

**Comment by simnh** [comment]
This functionality is untested, although, with integer values, i.e. 2H 4H timeincrement, it work for me so far (at least no python error), and the results looked ok as well
Does it work with timeincrement=1? 

BTW:
- You do not need to pass the timeindex to to model if the es has a time_idx defined (which is necessary for outputlib)
- you may also use the release branch now

**Comment by uvchik** [comment]
The parameters in solph are sequences to make it possible to use either a scalar or a list-like object.

Sometimes the multiply method is overloaded in class such as the string class. 
The following code should make it quite clear:

```python
>>> name = "caro"
>>> name * 2
'carocaro'
>>> name * 0.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by ckaldemeyer** [comment]
I haven't implemented the time independency but the only difference in the equations should be a multiplication with the time increment `timeincrement=0.25`.

Have you tried to convert it into a solph sequence?

**Comment by caro-rli** [comment]
I guess I have some other problems with my app which lead to this error. The storage_invest.py runs.

> but the only difference in the equations should be a multiplication with the time increment timeincrement=0.25.

But I also have to adapt the data frame time index, like this:

```python
date_time_index = pd.date_range('1/1/2012', periods=35040,
                                    freq='15Min')
```

Don't I?
This is not working though.

> The parameters in solph are sequences

> Have you tried to convert it into a solph sequence?

You mean a numpy array or something? This seems not necessary as setting the timeincrement to a scalar is running.

**Comment by caro-rli** [comment]
It seems to be a problem with the data frame index bigger than 8760 time steps, because

```
date_time_index = pd.date_range('1/1/2012', periods=4380,
                                    freq='2H')
```

with timeincrement=2 is running.

Results still untested...

**Comment by uvchik** [comment]
The time index has to be passed to the energy system. Be aware that you are able to pass a different time index to the model, but you should not do that unless you know what you are doing.
```python
dt_index = pd.date_range('1/1/2012', periods=4380, freq='2H')
energysystem = solph.EnergySystem(
        groupings=solph.GROUPINGS, time_idx=date_time_index)
solph.OperationalModel(energysystem)  # not: solph.OperationalModel(energysystem, timeindex=something)
```

The time increment by default is calculated in the following way:
```python
timeincrement = timeindex.freq.nanos / 3.6e12)
```
You still can pass a different time increment but you should not do that unless you know what you are doing. You can always pass the same time increment but this is not necessary.

The error message clearly says that you ```can't multiply sequence by non-int of type 'float'```. A time increment of 1, 2 or 4 is an integer 0.25 is a float, that's why 1, 2 and 4 work and 0.25 doesn't.

My example from above explains why 2 works and 0.25 doesn't. And 2.5 will not work either because it is a float, too. It does not have to do anything with the number of periods (time steps).

> I haven't implemented the time independency but the only difference in the equations should be a multiplication with the time increment timeincrement=0.25.

This multiplication with the time increment is exactly what causes the problem.

> Have you tried to convert it into a solph sequence?

If multiplication of a sequence with a float does not work a multiplication of two sequences should not work either. Better convert it to a float so that you can multiply two floats. I just cannot test it because I  do not have a working example.

You definitely should test the results because due to overloading the result of the multiplication could be different than expected (see example below).

```python
a = str(3)
>>> a * 2
'33'
```

**Comment by ckaldemeyer** [comment]
> The time increment by default is calculated in the following way:
>
> timeincrement = timeindex.freq.nanos / 3.6e12)

This makes sense to me. Thanks.

>You still can pass a different time increment but you should not do that unless you know what you are doing. You can always pass the same time increment but this is not necessary.

Ah, ok. But is it intended to provide two ways for the same thing? Where would this option be useful? At a first glance it looks rather confusing but maybe I just don't see it :)

> The error message clearly says that you can't multiply sequence by non-int of type 'float'. A time increment of 1, 2 or 4 is an integer 0.25 is a float, that's why 1, 2 and 4 work and 0.25 doesn't.

If it is passed as an argument, what would be the right way to pass quarter hours then?

**Comment by uvchik** [comment]
> Ah, ok. But is it intended to provide two ways for the same thing? Where would this option be useful? At a first glance it looks rather confusing but maybe I just don't see it :)

Might be confusing. You should pass a datetime index. If you do not want to pass a datetime index you can alternatively pass `timesteps` and `timeincrement`. The datetime index is the preferred way and you can pass the energysystem containing a datetime index to the outputlib and get plots with dates and timestamps.

> If it is passed as an argument, what would be the right way to pass quarter hours then?

Pass a datetime index with quarter hours. This will work when @caro-rli fixed the bug from above.

**Comment by ckaldemeyer** [comment]
Thanks. I'll continue to go with the datetimeindex :-)

**Comment by caro-rli** [comment]
I think I have been unclear before. Timeincrement=0.25 is running. The error from above was due to some other problems in my app. I'm now with the storage_invest.py

Setting the periods of the time index to 35040 does not run.
The error I get ist:

```
Traceback (most recent call last):
  File "/home/caro/rlihome/Git/oemof/examples/solph/storage_optimization/storage_invest.py", line 232, in <module>
    esys = optimise_storage_size()
  File "/home/caro/rlihome/Git/oemof/examples/solph/storage_optimization/storage_invest.py", line 126, in optimise_storage_size
    om = solph.OperationalModel(energysystem)
  File "/home/caro/rlihome/Git/oemof/oemof/solph/models.py", line 167, in __init__
    if self.flows[o, i].actual_value[t] is not None and (
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/series.py", line 583, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/local/lib/python3.4/dist-packages/pandas/indexes/base.py", line 1980, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/index.pyx", line 103, in pandas.index.IndexEngine.get_value (pandas/index.c:3332)
  File "pandas/index.pyx", line 111, in pandas.index.IndexEngine.get_value (pandas/index.c:3035)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 303, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6610)
  File "pandas/hashtable.pyx", line 309, in pandas.hashtable.Int64HashTable.get_item (pandas/hashtable.c:6554)
KeyError: 8760
```


So I do understand this...

> The error message clearly says that you can't multiply sequence by non-int of type 'float'. A time increment of 1, 2 or 4 is an integer 0.25 is a float, that's why 1, 2 and 4 work and 0.25 doesn't.

...but this seems not to be the problem.

**Comment by caro-rli** [comment]
Sorry for the mess. I guess this is a problem with the input data I use. I'm confused about the different apps I'm using. I'm going to fix my example in the other app (where I already adapted the input data) and let you know about the results.

**Comment by simnh** [comment]
whats happining hear? Is this outdated?  timeincrement already exist in th new solph v0.1 may you can at least test this functionality ? @ckaldemeyer

**Comment by ckaldemeyer** [comment]
At least for renpassG!S everything worked fine with the new version.

@caro-rli : Could you fix your issues with the quarter-hourly model and did it work as expected?

**Comment by simnh** [comment]
Ok but if it works we can close this one...

**Comment by ckaldemeyer** [comment]
If @caro-rli is fine she can close it :)

**Comment by ckaldemeyer** [comment]
@caro-rli : Can you close it or should we postpone it to the next release?

**Comment by caro-rli** [comment]
I'm going to check this today.

**Comment by caro-rli** [comment]
Still in the middle of checking for time increments < 1. If everything's ok I'm going to close this tomorrow.

**Comment by caro-rli** [comment]
Still in trouble with this issue, so I'm going to postpone it.
With time increments < 1 I get an error.
But I'm on an older commit, so this error might have nothing to say... switching my app to a newer commit is unfortunately not possible this quickly.

```
/home/caro/rlihome/Git/oemof/oemof/solph/models.py:172: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.flows[o, i].nominal_value)
16:47:20-INFO-Solve the optimization problem
Traceback (most recent call last):
  File "example_quartier.py", line 934, in <module>
    main(**arguments)
  File "example_quartier.py", line 914, in main
    esys = optimize_energysystem(esys)
  File "example_quartier.py", line 644, in optimize_energysystem
    om.solve(solver=arguments['--solver'], solve_kwargs={'tee': True})
  File "/home/caro/rlihome/Git/oemof/oemof/solph/models.py", line 344, in solve
    results = opt.solve(self, **solve_kwargs)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/opt/base/solvers.py", line 559, in solve
    self._presolve(*args, **kwds)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/opt/solver/shellcmd.py", line 195, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/opt/base/solvers.py", line 643, in _presolve
    **kwds)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/opt/base/solvers.py", line 711, in _convert_problem
    **kwds)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/opt/base/convert.py", line 109, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/solvers/plugins/converter/model.py", line 85, in apply
    io_options=io_options)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/core/base/PyomoModel.py", line 974, in write
    io_options)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/repn/plugins/cpxlp.py", line 162, in __call__
    include_all_variable_bounds=include_all_variable_bounds)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/repn/plugins/cpxlp.py", line 675, in _print_model_LP
    bound = self._get_bound(bound) - offset
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/repn/plugins/cpxlp.py", line 172, in _get_bound
    return value(exp)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/core/base/numvalue.py", line 150, in value
    tmp = numeric(exception=exception)
  File "/home/caro/.virtualenvs/simulation_caro/lib/python3.5/site-packages/pyomo/core/base/expr_coopr3.py", line 687, in __call__
    ans *= n
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by ckaldemeyer** [comment]
> Still in trouble with this issue, so I'm going to postpone it.
> With time increments < 1 I get an error.
> But I'm on an older commit, so this error might have nothing to say... switching my app to a newer commit is unfortunately not possible this quickly.

I think @caro-rli should be in charge since I am done with it

**Comment by ckaldemeyer** [comment]
@c-moeller : Is this realistic for the next release?

**Comment by ckaldemeyer** [comment]
Any progress here? If yes, we could integrate it into v.0.2.

**Comment by ckaldemeyer** [comment]
@c-moeller

**Comment by c-moeller** [comment]
Sorry for the delay!
Still not working for me. I seem to make anything wrong... I have no problem using a timeincrement of 2 with 4380 timesteps which work with plausible results but other with timeincrement=0.25 don't work.

Will further check this out next week on the way to Munich...

If anyone has an example for me with a successful parameter combination (timesteps, freq, timeincrement, data) I would be glad. Thanks :smile:

**Comment by ckaldemeyer** [comment]
> Sorry for the delay!
> Still not working for me. I seem to make anything wrong... I have no problem using a timeincrement of 2 with 4380 timesteps which work with plausible results but other with timeincrement=0.25 don't work.
>

What does "don't" work mean? The error from above?

> Will further check this out next week on the way to Munich...
> 
> If anyone has an example for me with a successful parameter combination (timesteps, freq, timeincrement, data) I would be glad. Thanks

Changing the datetimeindex to a quarter-hourly resolution should do the job with any example!

**Comment by c-moeller** [comment]
> Changing the datetimeindex to a quarter-hourly resolution should do the job with any example!

Ok, that works, finally ... thank you.

An error occurs still when I'm combining the 15 min resolution with a time horizon of one year. But that might be also a problem with my data input. No need to discuss this here.
