### ISSUE TITLE
python 3.7 release

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#511]
Python 3.7 is released and we should start to test it.

How long shall we support python 3.4?

I would suggest to replace python 3.4 with python 3.7 in the travis test to save resources! 

At the moment we test 3.4, 3.5, 3.6.

I think one of the "slowest" Linux distributions (debian stable) released debian 9 (stretch) with python 3.5 a year ago. As python 3.5 is backwards compatible it should be no problem to update from 3.4.

@oemof/oemof-developer-group Do you agree?

**Comment by uvchik** [comment]
No opinions, comments...?

I would like to **remove python 3.4** from the test and **add python 3.7**. That means that oemof officially supports **Python >= 3.5**. It may work for other version but as it is not tested it is not guaranteed.

@oemof/oemof-developer-group Do you agree?

**Comment by c-moeller** [comment]
Sounds good.

**Comment by henhuy** [comment]
I agree!

**Comment by p-snft** [comment]
Done with the release of [v0.2.3](https://github.com/oemof/oemof/releases/tag/v0.2.3).
