### ISSUE TITLE
test on "test_variable_chp" fails after cloning the repository

### ISSUE THREAD

**Issue by philipphanemann** [oemof/oemof#515]
Hello, 

I just forked and cloned the repo. Afterwards, I immediately run the tests a) with nosetests (as mentioned in the docs) and b) with pytest. 

During the pytest run, the last test named "test_variable_chp" failed with an IndexError. I suppose this should not be the case?  

Best regards
Philipp

**Comment by uvchik** [comment]
We use nosetests and therefore our tests are made for nosetests. If you use another test environment the tests may not work, but this does not indicate a problem.

**Comment by philipphanemann** [comment]
Thanks for the quick answer. I should have checked that the same test has passed nosetest, which it was intended for. Since I did not have any problem to run the respective example, this issue can be closed.
