### ISSUE TITLE
ImportError: cannot import name 'LinearTransformer'

### ISSUE THREAD

**Issue by mnimaruf** [oemof/oemof#524]
Hi,

I am pretty new to oemof and was trying to create my first energy system from the examples. When I am adding the entities to the energy system, I am getting the import error- 

_from oemof.solph import Bus, Flow, Sink, Source, LinearTransformer
ImportError: cannot import name 'LinearTransformer'_

Also got another import error later while trying to import the operational model-

_from oemof.solph import OperationalModel
ImportError: cannot import name 'OperationalModel'_

Any help on these issues?

**Comment by uvchik** [comment]
It seems that you have mixed up versions. The following line is from `oemof v0.1.x`

```python
from oemof.solph import Bus, Flow, Sink, Source, LinearTransformer
```

If you install oemof with pip you get the most actual version `v0.2.2`.

Have a look at the example repository but make sure you use the v0.2.x examples!

https://github.com/oemof/oemof_examples/tree/master/examples

**Comment by mnimaruf** [comment]
Thank you.
