### ISSUE TITLE
Provide minimal example for parameter access in optimization model

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#531]
To be put in the example-repository!

**Comment by uvchik** [comment]
@simnh opened a v0.3 folder in the example repository you could add a PR there but make sure the PR is against the dev and not the master branch.

**Comment by ckaldemeyer** [comment]
> @simnh opened a v0.3 folder in the example repository you could add a PR there but make sure the PR is against the dev and not the master branch.

Thanks. I'll put it there if I find the time!
