### ISSUE TITLE
Check combination of investment class with NonConvex

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof#535]
The [documentation states](https://oemof.readthedocs.io/en/stable/oemof_solph.html#using-the-investment-mode) that
> At the moment the investment class is not compatible with the MIP classes NonConvex.

However, this seems to be true only if these classes are combined in one component. This should be validated and specified accordingly in the documentation.

**Comment by simnh** [comment]
You could provide an (very simple) example (based on existing ones) in the oemof examples repository.
Once this has been 'validated' this way (which I am 100% sure that it works), we can add a few lines to the docs with a link to this example.
