### ISSUE TITLE
Asking for a review

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#539]
The`review request` is an important feature for pull requests but the work flow seems to be quite unclear.

If I request a review in my PR the person I choose will receive a notification. Therefore a review should be requested when the PR is finished and ready to merge (in the opinion of the author) and not at the beginning of the process.

Most of the time a requested a review at the beginning but I would suggest to change the workflow in this point.

@oemof/oemof-developer-group Do you agree?

**Comment by p-snft** [comment]
Good point. I agree, as this helps reducing work load for reviewers.

**Comment by c-moeller** [comment]
+1

**Comment by ckaldemeyer** [comment]
I agree!
