### ISSUE TITLE
Next major release: v0.3.0

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#540]
Release branch ([releases/v0_3_0](https://github.com/oemof/oemof/tree/releases/v0_3_0)): [![Build Status](https://travis-ci.org/oemof/oemof.svg?branch=releases%2Fv0_3_0)](https://travis-ci.org/oemof/oemof) [![Coverage Status](https://coveralls.io/repos/github/oemof/oemof/badge.svg?branch=releases%2Fv0_3_0)](https://coveralls.io/github/oemof/oemof?branch=releases%2Fv0_3_0)
We are planing the next major release but we did not decide everything at the dev-meeting.
Major release means that API-changes are possible.

1. When do we want to release (think of the API changes you want to make)?
2. Does anybody needs a v0.2.3 release before the major release (depends on first question)?

I already started a release-branch (`releases/v0_3_0`), so API changing PR should be against the release-branch and not the dev-branch.

**Comment by uvchik** [comment]
I would suggest 15 January 2019 and I do not need a minor release (v0.2.3) before. This might sound long but most people will have a busy time before Christmas and in January people might be more open for our release message :smile:

**Comment by p-snft** [comment]
Using Python 2.7, `oemof.solph` is currently broken. Depending on the needed effort, a timely fix for v0.2 might be a good idea. But imho, this should be a pure maintenance release.

As for v0.3, the 15th of January sounds fine.

**Comment by uvchik** [comment]
> Using Python 2.7, `oemof.solph` is currently broken.

Sorry, but we decided to not support python 2.7 in oemof and I think we will not change this decision. The more as scientific packages oemof relies on (numpy, pandas, pvlib) will drop Python2 support in 2019. If you think you have good arguments you could open a new issue to discuss it.

**Comment by p-snft** [comment]
I am sorry, Python 3.7.

**Comment by uvchik** [comment]
> I am sorry, Python 3.7.

see #541

**Comment by uvchik** [comment]
There is already one. Just click "branches" on the main page (the link where the number of branches is shown) to get an overview. PRs which break the API should be against the release branch and not against `dev`. At the moment the v03-branch is still in line with the dev because the API-breaking PRs are not merged by now.

To check the documentation I will have to activate this branch at read the docs. Thanks for the hint, I will do this now.

![grafik](https://user-images.githubusercontent.com/4760584/49365037-031ddd80-f6e6-11e8-92b8-3c959229feee.png)

**Comment by uvchik** [comment]
@p-snft The docs should work now for the release branch. Use:

http://docs.oemof.org/en/releases-v0_3_0/

**Comment by p-snft** [comment]
Ah, ok, Thank you!

**Comment by uvchik** [comment]
As there have not been any movement here, I will take a step forward.

I would suggest to set the release date to the end of May.

Deadline for merges would be May 22.

**Comment by uvchik** [comment]
@oemof/oemof-developer-group 

Please check all issues/PR you are related to and adapt the milestone if necessary.

v0.2.4 -> hotfixes to release before the end of May
v0.3.0 -> make sure that you will be able to finish everything before May 22 (API change possible)
v0.3.1 -> you will have more time, but no API changes allowed
v0.4.0 -> next major release (winter?)

There is already a release branch for v0.3.0 make sure all your changes are in this branch. The dev branch is still compatible with the v0.2.0 API.

**Comment by p-snft** [comment]
I second that. Without fixed release dates, new ideas will come up and shift the release. (I feel a little guilty about that.)

I think we should be able to define the feature set of v0.3 at latest on 15th of May (first day of the dev meeting). Everything that has no pledge by then, should be postponed to a later release.

**Comment by p-snft** [comment]
@oemof/oemof-solph I would start merging/postponing the PRs. If the PR was started by me, and everything lacking is the review, I will probably merge at will.

**Comment by uvchik** [comment]
Please check the "whatsnew" file and add your name and the changes you did.

I copied the examples to the v0.3 folder. I could not check the Jupyter notebooks (jupyter_tutorials, sector coupling) and sdewes2017 due to missing packages. We have to remove untested examples from the repository to avoid additional support and questions from users if the examples do not work.

The `oemof-core` example does not work at all and has to be removed if nobody fixes it.

Please HELP :exclamation:
