### ISSUE TITLE
Time increment not needed in Bus balance

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#563]
The Bus balance looks like this:

![bildschirmfoto_2019-02-05_17-58-22](https://user-images.githubusercontent.com/4760584/52290107-a5b93d80-296f-11e9-81a3-55b70db33587.png)

While τ is the time increment. Within one time step the time increment is constant and therefore it can be eliminated from the equation. Or did I forget a special case?

It does not harm anybody. It is just a useless constant on both sides .

**Comment by FranziPl** [comment]
I'm sorry, I don't know what is meant with different time increments, because I agree with the point, for one single timestep, the time increment is constant at both sites. So it doesn't matter, if the time increments are not the same in all time steps.
For me it's fine.

**Comment by FranziPl** [comment]
I close this Issue, because the corresponding PR #564 is merged and closed.
