### ISSUE TITLE
Wrong equation in documentation

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#565]
In the second equation the P_el should be `greater equal` not `lower equal` than the right hand side.

https://oemof.readthedocs.io/en/latest/api/oemof.solph.html#oemof.solph.components.ExtractionTurbineCHPBlock

In this context we could check the rest :-)

@oemof/oemof-assistants Does anybody wants to help?

**Comment by ajimenezUCLA** [comment]
I would like to be assigned this, I need to figure out how to use docstring though.

**Comment by p-snft** [comment]
As nobody joins the search for errors in equations: It would be useful to perform the check based on the updated docstring template (see #565). When the equations are rewritten to a more readable form, it is easy to check them right away.

Thus, I am going to perform the pull request #568.
