### ISSUE TITLE
Error in docstring: Equation on summed_max

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof#566]
The docstring does not represent the equation that is implemented a few lines later in https://github.com/oemof/oemof/blob/dev/oemof/solph/blocks.py
Docstring:
>
    Flow max sum :attr:`om.Flow.summed_max[i, o]`
      .. math::
        \sum_t flow(i, o, t) \cdot \tau \leq summed\_max(i, o), \\
        \forall (i, o) \in \textrm{SUMMED\_MAX\_FLOWS}.

This is the [rendered version](https://oemof.readthedocs.io/en/latest/api/oemof.solph.html#oemof.solph.blocks.Flow)
Equation:
>
        def _flow_summed_max_rule(model):
            """Rule definition for build action of max. sum flow constraint.
            """
            for inp, out in self.SUMMED_MAX_FLOWS:
                lhs = sum(m.flow[inp, out, ts] * m.timeincrement[ts]
                          for ts in m.TIMESTEPS)
                rhs = (m.flows[inp, out].summed_max *
                       m.flows[inp, out].nominal_value)
                self.summed_max.add((inp, out), lhs <= rhs)
        self.summed_max = Constraint(self.SUMMED_MAX_FLOWS, noruleinit=True)
        self.summed_max_build = BuildAction(rule=_flow_summed_max_rule)

Same for `summed_min`. Can be easily fixed by adding the factor `nominal_value` in the docstrings.

**Comment by uvchik** [comment]
@oemof/oemof-assistants : Could be fixed in one PR together with #565.

**Comment by ajimenezUCLA** [comment]
I would like to be assigned to this, I have a question about the equation. nominal_value should be multiplied to tau? or summed_max(i,o)
I'm trying to understand the equation.

**Comment by p-snft** [comment]
I read "summed max" as "maximum full-load hours": The total integrated energy flow (lhs) has to be lower or equal the maximum full load hours times the installed power ("nominal value").

PS: This specific issue has been fixed by my commit above. It is not merged, yet, so the ticket is still open.
