### ISSUE TITLE
oemof installation

### ISSUE THREAD

**Issue by lxlsygc** [oemof/oemof#578]
**I have followed the oemof installation procedure (in Windows) step by step:**

C:\Python\WPy64-3680\scripts>pip install oemof
Collecting oemof
Collecting pandas<0.24,>=0.18.0 (from oemof)
  Using cached https://files.pythonhosted.org/packages/0e/67/def5bfaf4d3324fdb89048889ec523c0903c5efab1a64c8dbe0ac8eec13c/pandas-0.23.4-cp36-cp36m-win_amd64.whl
Collecting numpy<1.16,>=1.7.0 (from oemof)
  Using cached https://files.pythonhosted.org/packages/51/70/7096a735b27359dbc0c380b23b9c9bd05fea62233f95849c43a6b02c5f40/numpy-1.15.4-cp36-none-win_amd64.whl
Collecting networkx<2.3 (from oemof)
Collecting pyomo<5.6,>=4.4.0 (from oemof)
  Using cached https://files.pythonhosted.org/packages/06/b2/8cdcc7a77d42082b2fdc6419fc3358e15b5b6f29fdfa10b8ad67f0101d87/Pyomo-5.5.1-py3-none-any.whl
Collecting dill<=0.2.8.5 (from oemof)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pandas<0.24,>=0.18.0->oemof) (2.8.0)
Requirement already satisfied: pytz>=2011k in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pandas<0.24,>=0.18.0->oemof) (2018.9)
Requirement already satisfied: decorator>=4.3.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from networkx<2.3->oemof) (4.3.2)
Requirement already satisfied: six>=1.4 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pyomo<5.6,>=4.4.0->oemof) (1.12.0)
Collecting PyUtilib>=5.6.3 (from pyomo<5.6,>=4.4.0->oemof)
  Using cached https://files.pythonhosted.org/packages/43/04/9174c992ab7b5d5c9c29c0dce3ffbe2440dcfaf054a83b536f8253ce8384/PyUtilib-5.6.5-py2.py3-none-any.whl
Collecting ply (from pyomo<5.6,>=4.4.0->oemof)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Requirement already satisfied: appdirs in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pyomo<5.6,>=4.4.0->oemof) (1.4.3)
Collecting pyreadline>=1.7.1 (from dill<=0.2.8.5->oemof)
Collecting nose (from PyUtilib>=5.6.3->pyomo<5.6,>=4.4.0->oemof)
  Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
**multiprocess 0.70.7 has requirement dill>=0.2.9, but you'll have dill 0.2.8.2 which is incompatible.
datashader 0.6.9 has requirement testpath<0.4, but you'll have testpath 0.4.2 which is incompatible.**
Installing collected packages: numpy, pandas, networkx, nose, PyUtilib, ply, pyomo, pyreadline, dill, oemof
  Found existing installation: numpy 1.16.2+mkl
    Uninstalling numpy-1.16.2+mkl:
      Successfully uninstalled numpy-1.16.2+mkl
  Found existing installation: pandas 0.24.1
    Uninstalling pandas-0.24.1:
      Successfully uninstalled pandas-0.24.1
  Found existing installation: networkx 2.3rc1.dev20181020104102
    Uninstalling networkx-2.3rc1.dev20181020104102:
      Successfully uninstalled networkx-2.3rc1.dev20181020104102
  Found existing installation: dill 0.2.9
    Uninstalling dill-0.2.9:
      Successfully uninstalled dill-0.2.9
Successfully installed PyUtilib-5.6.5 dill-0.2.8.2 networkx-2.2 nose-1.3.7 numpy-1.15.4 oemof-0.2.3 pandas-0.23.4 ply-3.11 pyomo-5.5.1 pyreadline-2.1

C:\Python\WPy64-3680\scripts>

**I got two lines marked in red from the "WinPython Command Prompt":** 

**multiprocess 0.70.7 has requirement dill>=0.2.9, but you'll have dill 0.2.8.2 which is incompatible.
datashader 0.6.9 has requirement testpath<0.4, but you'll have testpath 0.4.2 which is incompatible.**

**Not sure the meaning of these two lines...**

**Here is what I got after running "oemof_installation_test" :**

C:\Python\WPy64-3680\scripts>oemof_installation_test

*****************************
Solver installed with oemof:

cbc: working
glpk: not working
gurobi: not working
cplex: not working

*****************************
oemof successfully installed.
*****************************

C:\Python\WPy64-3680\scripts>

**It looks like the solver has been installed. But not sure about oemof. As all of "glpk, gurobi, and cplex are not working, I am not sure whether oemof is installed or not... Is it somehow related to the two previous lines?**

**Comment by uvchik** [comment]
It seems to me that oemof is installed correctly but you have to install at least one solver. I would recommend to install the cbc solver and run the basic example.

https://oemof.readthedocs.io/en/stable/installation_and_setup.html#windows-solver

https://github.com/oemof/oemof-examples/tree/master/oemof_examples/oemof.solph/v0.2.x/basic_example

**Comment by lxlsygc** [comment]
Thank you for the help! The base example has been tested and it runs well. :)
