### ISSUE TITLE
Add add_out/add_cap variables to results object

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#58]
@gnn Can you add these variables to the results object?

**Comment by uvchik** [comment]
+1

**Comment by caro-rli** [comment]
and total costs as the objective value would be great

**Comment by caro-rli** [comment]
... or the relevant objective value if not cost optimization is chosen.

**Comment by gnn** [comment]
I pushed a few changes on the `fixes/58` branch, which hopefully fix this issue.
Could you both please test whether it works? You can access the attributes on the results as follows:
Suppose that `a_particular_storage` holds the `storage` object you are interested in, then `results[a_particular_storage].add_cap` should give you what you want.

For the objective value, I don't know where to get this after a successful solph run. Could you please tell me where the objective value is located after optimization, @simonhilpert ? Probably somewhere on the optimization model, but I guess its faster to ask you then to search around.

**Comment by simonhilpert** [comment]
you can get this via two (or even more ways) different ways:

```python 
# first 
obj_value = om.objective()

#second 
obj_value =om.objective.value()
```
I like the second one...

**Comment by gnn** [comment]
Muchas gracias. Interesting. I'd prefer the first one.
I simply added the objective attribute to the results dictionary so everybody can choose his or her preferred method.
The desired features should be there now. Please test them out.

**Comment by uvchik** [comment]
@caro-rli will not be here this week, may you merge this anyway?

**Comment by ckaldemeyer** [comment]
Should we adapt the dataframe creation, too? I guess this would only be consistent

**Comment by uvchik** [comment]
@ckaldemeyer :+1:

**Comment by gnn** [comment]
@ckaldemeyer sure thing. I still think in the long run the dataframe and the results object should become one anyway if it's possible.
@uvchik yeah, I'm gonna merge it, but I want to check that it works as expected beforehand. I'm currently running the `storage_invest.py` example for this purpose. How long does that take usually? I'm ~4h into it.

**Comment by ckaldemeyer** [comment]
Allright. I'll wait until Martin has merged back into *features/outputlib-imprivements*, add my changes and merge into *dev*

@gnn : Yep. Maybe we can have a look at it in the remaster-session in February!

**Comment by uvchik** [comment]
@gnn : The storage invest example? The first plot appears after about 35 seconds. Just tried it on the `fix/58` branch.

It will take 4 hours on the following OS :smirk: 

![arrow-down](https://upload.wikimedia.org/wikipedia/commons/4/48/C64_startup_animiert.gif)

**Comment by gnn** [comment]
Interesting. Seems to hang for me with `glpsol` hogging the CPU. `examples/storate_optimization/storage_invest.py` is the correct file to run though, right?

**Comment by simonhilpert** [comment]
Is this something that will be fixed / merged today or do we set the milestone to february?

**Comment by gnn** [comment]
I'm on it. Finally got the thing to run with the `cbc` solver and can now check out whether my code works. So we can include this in the current release.

**Comment by gnn** [comment]
Sorry for the delay. It works now and can be merged to be part of the release.

**Comment by simonhilpert** [comment]
ok, then just merge it into dev..I have some changes on an other feature branch that I will merge 
and then we can release...

**Comment by gnn** [comment]
According to my tests it should work, but I don't know whether it works the way you expect it to woark, @caro-rli . You can try it out and close the issue if you're satisfied, or tell us how to change it otherwise.
If you don't know how to get at the attributes you want, check out the documentation for the results attribute/method on the [`EnergySystem`](http://oemof-base.readthedocs.org/en/latest/api/oemof.core.html#oemof.core.energy_system.EnergySystem.results) class and the [`OptimizationModel`](http://oemof-base.readthedocs.org/en/latest/api/oemof.solph.html#oemof.solph.optimization_model.OptimizationModel.results) respectively.

**Comment by cswh** [comment]
@caro-rli: did it work out? if so, please close this issue. if not, just post an update on the matter.

**Comment by caro-rli** [comment]
Ok, I finally tested it and it works for me for the objective and the storage capacity with

```python
print(energysystem.results.objective)
print(energysystem.results[storage].add_cap)
```

But I have problems with the pv and wind components.

```python
print(energysystem.results[pv].add_out)
print(energysystem.results[wind].add_out)
```

produces an error

```
AttributeError: 'UserDict' object has no attribute 'add_out'
```

And

```python
print(energysystem.results[storage].add_out)
```

gives me "None". Shouldn't this be the maximum output power of the storage?

@gnn I tried to understand what you did in 863aa1bedf0be1b969fc9177a4b2460386eb1407 as described in #74 but this might be only concerned to the objective.

**Comment by gnn** [comment]
Hm. I don't really know whether I addressed `add_out`. Gotta check. Shouldn't take too long though, so definitely before the April release.

**Comment by gnn** [comment]
Man how fast 24 days pass. Gonna check this out today.

**Comment by gnn** [comment]
Ok. This will definitely take a little bit longer to figure out. I actually did cater for `add_out` when I first tried to fix this issue. So getting getting `"None"` for  `print(energysystem.results[storage].add_out)` really shouldn't happen. I'll have to track down where that comes from.

**Comment by caro-rli** [comment]
There might be a relation to the problem I mentioned in #149 

> The last value "energysystem.results[storage].add_cap" somehow can't be addressed when I restore a dumped energy system.

But this is somehow only the case for the storage capacity. The objective for example can be addressed also with a restored energy system.

This is the error message I get:

```
Traceback (most recent call last):
  File "/home/caro/rlihome/Git/oemof/examples/storage_optimization/storage_invest.py", line 196, in <module>
    print(energysystem.results[storage].add_cap)
  File "/usr/lib/python3.4/collections/__init__.py", line 908, in __getitem__
    raise KeyError(key)
KeyError: <oemof.core.network.entities.components.transformers.Storage object at 0x7f9652357eb8>
```

**Comment by uvchik** [comment]
@caro-rli , @gnn Is this still valid for the v0.1 release branch or was it an issue related to the old solph version?

**Comment by caro-rli** [comment]
I suppose this had been solved. Seems to work now like this:
```
energysystem.results[component][bus].invest
```
