### ISSUE TITLE
[coding] Unbundle oemof 

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#58]
The idea of oemof the idea of a package collection with packages that help modelling energy systems. Until now we have a variety of different packages following this purpose.

However, some packages are within a repository called `oemof` others not.

Now we have the idea to make `oemof` a real meta-package as the name oemof is the roof for all these packages. Following this idea `oemof-solph` would become an own repository.

Another new repository would be the `oemof-model-frame` (working name) containing the basic network functions, the EnergySystem, some tools and the outputlib (the parts of the outputlib that are not solph specific).

The `oemof` repository would contain a meta documentation with a list of all packages and a link to the sub-documentations.

`pip install oemof` will install solph (and others?) at least for a while. We could also intrduce something like `pip install oemof [full]` to get all approved packages.

We do need a test design for meta tests.

I would suggest to start with oemof-solph `v0.4.0`.

We still can publish major releases of `oemof` like distribution on linux but I do not know if this makes sense.

**Comment by uvchik** [comment]
The basic work is done :smile: :tada:

We do have two new and two redesigned repositories.

oemof/oemof (before: oemof/organisation)
oemof/oemof-solph (before: oemof/oemof)
oemof/oemof-tools (new)
oemof/oemof-network (new)

1. We renamed oemof to oemof-solph because most of the stuff there was oemof-solph anyway.
2. The rest of the code and the related docs have been moved to oemof-tools or oemof-network.
3. The general docs have been moved to oemof/oemof (overview, developer rules etc.)
4. We used cookiecutter skeletons to create the structure of the repository. Therefore a lot of services were added. We do not have to keep all of them. We may have a look and keep the best ones.
5. There is still some work to do and I do need help.

It would be great to find persons in charge for the documentation of the repositories.

They do work technically but they definitely need a review. All the general stuff should go to the oemof repository and the other repos should link there. Would be nice to have a similar structure especially in the "normal" repositories. The oemof-docs are some kind of meta docs and will have a different structure.

1. oemo-solph [person1]
2. oemof-tools [person2]
3. oemof-network [person3]
4. oemof [person4]

@oemof-developer Please help.

**Comment by uvchik** [comment]
We need to decide how to name the packages finally:

oemof-solph
oemof-network
and so on...

Please vote with thump up.

**Comment by uvchik** [comment]
We need to decide how to name the packages finally:

oemof.solph
oemof.network
and so on...

Please vote with thump up.

**Comment by joroeder** [comment]
So, do you mean whether to name "oemof.solph" or "oemof-solph" ? If "-" or ".", I don't care, but I totally agree with "solph", "network" and "tools".

I would assist to review the oemof-solph docs, but since this is the longest docu, I do not want to be in charge of it by myself.

Btw, great job! 👍👍👍

**Comment by joroeder** [comment]
Should the structure of the docs be discussed here? Or in a separate issue?

**Comment by uvchik** [comment]
> Should the structure of the docs be discussed here? Or in a separate issue?

New issue! If it is only related to solph you should open the issue there. If it is about the overall structure, which should be similar in all repos, you should open it here.

**Comment by uvchik** [comment]
> So, do you mean whether to name "oemof.solph" or "oemof-solph" ? If "-" or ".", I don't care, but I totally agree with "solph", "network" and "tools".

There are two discussion. The first is whether to use a dot "oemof.sometin" or a minus "oemof-something", the second is if you have objections against the names in general.

**Comment by uvchik** [comment]
> I would assist to review the oemof-solph docs, but since this is the longest docu, I do not want to be in charge of it by myself.

Being in charge means to organise a group, that will, revise the documentation. The first step would be to check the logical structure and to identify work-packages. It is not about doing all the work.

**Comment by uvchik** [comment]
So far I got one (!) vote, which is my vote :thinking: You can still vote until 04.05.2020-6am!

**Comment by beierd** [comment]
I like the dots better ;)

**Comment by joroeder** [comment]
> 
> 
> So far I got one (!) vote, which is my vote 🤔 You can still vote until 04.05.2020-6am!

Does a neutral opinion not count as vote?!  :blush:  :

> So, do you mean whether to name "oemof.solph" or "oemof-solph" ? If "-" or ".", I don't care, but I totally agree with "solph", "network" and "tools".

**Comment by jnnr** [comment]
I would prefer the dots as well. However, an argument against the dots that @p-snft brought up recently was that some operating systems have a problem with dots in directory names.

**Comment by gnn** [comment]
> We need to decide how to name the packages finally:

Just to clarify, we are actually NOT voting on the "package" name, but on the repository URL.
Correct me if I'm wrong @uvchik, but I think the package should contain dots as separators and so should the module name. But since the repository URL can be relativey free form, we have some freedom in choosing what to use.

And for anybody interested in the distinction of the things which can be named:
The "package" is what gets uploaded to PyPI and what one would put after `pip install`. The "module" is what gets `import`ed. Unfortunately in some cases Python also calls this a "package" but that is a different kind of "package" than what goes onto PyPI. The GitHub repository is the last part of the GitHub URL, i.e. the last part of what one would `git clone`.
So in the case of "oemof.solph", the options between which we're voting are the following ones:
`git clone https://github.com/oemof/oemof.solph.git`
`git clone https://github.com/oemof/oemof-solph.git`


Again, please correct me if I'm wrong, @uvchik.

**Comment by uvchik** [comment]
@gnn Thank you for pointing that out. I added two screenshots to show the difference. For me it is confusing to use `git clone ... oemof-solph.git` but `pip install oemof.solph`, therefore I vote for `git clone ... oemof.solph.git`.

![Bildschirmfoto_2020-04-28_08-36-27](https://user-images.githubusercontent.com/4760584/80455108-73587f00-892b-11ea-828e-eec71535e533.png)

![Bildschirmfoto_2020-04-28_08-36-11](https://user-images.githubusercontent.com/4760584/80455114-77849c80-892b-11ea-927b-9c8c263513e9.png)

**Comment by joroeder** [comment]
@gnn @uvchik thanks for the explanation and screenshots! If it is like that, I prefer having just one "name" as well.

**Comment by p-snft** [comment]
For URLs, the point signifies some change in the (internet) service hierachy. E.g. https://oemof-solph.readthedocs.io will continue to have a hyphen. Thus, I would have directories, project names, etc. with hyphens. For the PyPI-Packages, it might be considarable to keep the fullstop. Actually, I do not see a drawback in having a difference when installing using pip between the PiPy package and the default GitHub-based directory name.

**Comment by uvchik** [comment]
Thank you @p-snft for pointing that out. We will not have dots everywhere. So we could say the following.

Voting 1: Dots where possible (pypi, github, package, imports etc, but not readthedocs)
Voting 2: Directories, project names, etc. with hyphens and package (pypi, imports) with dots

We do have 4:2 for dots, but I do not feel comfortable with just 6 votes, the more as some information came after the voting of some users. 

Please use the following link for your voting:

https://terminplaner4.dfn.de/Hu7UxcZPsbjEeWaZ

**Comment by uvchik** [comment]
As a result of the [survey](https://terminplaner4.dfn.de/Hu7UxcZPsbjEeWaZ) we have to rename the following packages:

oemof.db -> oemof-db
oemof.network -> oemof-network

It think it is good that a decision has been made and that we therefore have a consistent naming structure now.
