### ISSUE TITLE
Generalize constraints.emission_limit

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof#585]
The concept of additional constraints is rather powerful. Still, it is currently only transported by example. It might be a good idea to generalize `constraints.emission_limit(om, flows=None, limit=None)` to something like `constraints.shared_limit(om, key='emission_factor', shared_between=None, limit)`. This would then transport the idea that for example also limited shared space for PV/ST can also be modelled this way.

PS: The `constraints.investment_limit(model, limit)` would be `constraints.shared_limit(om,'investment_costs', limit).

**Comment by simnh** [comment]
I like the idea!

**Comment by joroeder** [comment]
Hey, in my opinion there are two options:
1) replacing the ``constraints.emission_limit``  by a more generous formulation ``constraints.shared_limit`` like Patrik described
2) keeping the ``constraints.emission_limit`` and adding a more generous formulation. In the end there could be many constraints (like transformer components) which already indicate a specific use

The advantage of 2) is that it might be more intuitive for a constraint many people use. What do you think?

**Comment by p-snft** [comment]
If this is added e.g. in v0.3.1, API compatibility would anyway require to keep the old functionality. However, they should probably just wrap the generic `shared_limit` constraint .

**Comment by uvchik** [comment]
I like the idea :+1: 

I wrap should be the right way if it is not part of the upcoming major release. But I would add a FuturWarning and remove it in the long run. We  could keep the emission constraint as an example in the docstring of the generalised function.

**Comment by p-snft** [comment]
I would consider this done.
