### ISSUE TITLE
Add Heat Pump with temperature dependent efficiency for solph

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof#591]
Hi everyone!

We want to add a component to solph.custom that models a compression heat pump with temperature dependent efficiency. It is supposed to be a simple to use component if you want/need to model a heat pump without going into the calculation of the COP (coefficient of performance) and without going into the thermal dynamic details of a heat pump and the properties of the refrigerant. 

BTW: Modelling a heat pump considering the thermal dynamics using TESPy is the idea of [Issue #37 of oemof-examples](https://github.com/oemof/oemof-examples/issues/37) - so check out that issue if you are interessted in it!

The basic idea is that the component takes as argument two lists of temperatures: one for the temperature of the low temperature heat reservoir (temp of ambient air in case of an air-source-heat-pump) and another for the temperature of the high temperature heat reservoir (the useful energy, e.g. the flow temp of the radiator in a building). From that lists teh components precalculates the COPs and passes them to the Block-Class. From here it is more or less the simple transformer. 

The precalculation is done by calculating the carnot-efficiency from the two temperatures and then applying a factor: the quality grade. We had a look at the temperature dependency of COPs from heat pumps listed as subsidizable (german: "förderfähig") by the [BAFA](https://www.bafa.de/SharedDocs/Downloads/DE/Energie/ee_waermepumpen_anlagenliste.html) and all of them are in the range of 30-50% of the carnot-efficiency. For most of them COP=0.4*carnot-efficiency seems to be a good assumption.

I am interessted in getting some feedback from you regarding...
... would such componet be interessting for you?
... does the approach make sense at all from your point of view?
... what should such a component be capable of to be useful to you?
... do you think solph.custom is the right place for this component?

**Comment by jakob-wo** [comment]
Some mock-up code (application point of view) to give you an impression of what I am thinking of.

![grafik](https://user-images.githubusercontent.com/40822026/58419757-b9f28900-808b-11e9-8794-03735f0830a2.png)

**Comment by uvchik** [comment]
In my opinion it is more flexible like this. People can easily add different approaches.

BTW: I would not use a "low_temperature" input because you would have to add a `Bus` and a `Source`.

```python
from oemof import solph
from oemof import heat_components as heat

cop = heat.airsource_heatpump(
    temp_high=35,
    temp_low=data['air_temperature'],
    quality_grade=0.4,
    consider_icing=True,
    allow_partial_load=False)

solph.Transformer(
    label='heat_pump',
    inputs={b_el: Flow(nominal_value=60)},
    outputs={b_th: Flow()},
    conversion_factors={b_el: cop})
```

The place for the heat components is just an idea but we could collect your approach along with TESPy approaches and so on.

```python
from oemof import heat # 1
from oemof.solph import heat # 2 (I do not like it because it has nothing to do with linear models)
from oemof import heat_calculations # 3
...
```

We still may discuss if we want to create "alias components" that make it easier for new users as the parameter could be used more intuitively.  But we should use a new module for this kind of components and we have to check how they can be found in the results.

```
solph.Battery(
    c-rate=0.6,
    ....) 
```

**Comment by p-snft** [comment]
I like the idea, to have "alias components". Maybe:

```python
    class solph.custom.airsource_heatpump(solph.Transformer):
        def __init__(**kwargs):
            cop = heat.airsource_heatpump.cop(**kwargs)
            parent().__init__(conversion_factors={b_el: cop}),
                              **kwargs)
```

**Comment by jakob-wo** [comment]
I like the approach from @uvchik to use a helper function like heat.airsource_heatpump() in the given example. We considered that appraoch as well but then found that pre-caclulations in existing components (like the `_alphas` in `GenericCHP`) are done inside the component. We thought "that's the way it is meant to be done in oemof!" ;)
So...
... In favour of a module `heat` (place: option 1). 
... The low temperature bus was added on purpose and I would like to stay with it. In many cases it is important to know/ to limit what amount of heat is extracted from the ground or ground water (freezing) or from a Low-Ex heating network. Sometimes low temp heat reservoir itself might be the limiting source, e.g. temporal available wast heat, etc. Unfurtunately, the example I chose (air source heat pump) was not an good example to show that necessity.
... Totally in favour of "alias components"! (shall we open an Issue on that?)

**Comment by uvchik** [comment]
> ... Totally in favour of "alias components"! (shall we open an Issue on that?)

:+1: Yes, it is a good idea to separate both ideas in different issues!

**Comment by jnnr** [comment]
I like the idea of alias components. To keep in mind: This is already in a way implemented in oemof_tabular's [facades](https://github.com/oemof/oemof-tabular/blob/master/src/oemof/tabular/facades.py). We should understand how those two relate to each other before we initiate a new module. I guess many people use oemof/oemof without using oemof_tabular, so it would be ok to have a similar thing in oemof/oemof. But maybe this is a good point to clarify the relation between oemof_tabular and oemof?

**Comment by uvchik** [comment]
> ... In favour of a module `heat` (place: option 1).

That means that there is an own repository.


> ... The low temperature bus was added on purpose and I would like to stay with it. In many cases it is important to know/ to limit what amount of heat is extracted from the ground or ground water (freezing) or from a Low-Ex heating network. Sometimes low temp heat reservoir itself might be the limiting source, e.g. temporal available wast heat, etc. Unfurtunately, the example I chose (air source heat pump) was not an good example to show that necessity.

You are right, but for an airsource_heatpump (this was your example) it is not necessary to module two inputs. The other example are (a little) more complicated and it is not so easy to provide a ready-to-go-component as it depends on the model type.

**Comment by nesnoj** [comment]
I'm also very interested in a HP with temp-dependent COP in oemof :)
Any news here?

**Comment by p-snft** [comment]
@nesnoj: This issue proposes a usability improvement, where the time-dependent COP is automatically calculated by providing temperature time series. An approach to do this manually (simplistic Carnot HP model) could read:

```
def cop_carnot_hp(temp_out, temp_amb):
    """
    : temp_out: outlet temperature of hp (in Kelvin)
    : temp_amb: ambient temperature used for inlet (in Kelvin)
    """
    return temp_out / (temp_out - temp_amb)

cop = cop_carnot_hp(temp_out=300, temp_amb=[290, 292, ..., 288])

hp = Transformer(label='HP',
                 inputs={b_el: Flow()},
                 outputs={b_th: Flow()},
                 conversion_factors={b_th: cop})
```

**Comment by jakob-wo** [comment]
Hello everyone,
an axample (`airsource_heatpump.py`) on how to model an air-source heat pump (ASHP) with the approache mentioned above as available now with the [oemof-thermal/feature-brunch about compression heat pumps and chillers](https://github.com/oemof/oemof-thermal/tree/features/cmpr_heatpumps_and_chillers/examples/compression_heatpumps_and_chiller).
Feedback and questions on the code and the approach itself are very welcome!

In the feature-brunch you also find an example that plots the temperature dependency to show the approach dicussed here more easily:
![cop_dependence_on_temp_difference](https://user-images.githubusercontent.com/40822026/64677540-0cf41e80-d478-11e9-9b22-906e5b80a96f.png)

**Comment by nesnoj** [comment]
Thanks for getting back so quickly and the example!

> @nesnoj: This issue proposes a usability improvement, where the time-dependent COP is automatically calculated by providing temperature time series.

 Yes, I got that :). Just wanted to know whether a custom component was already implemented.

**Comment by jakob-wo** [comment]
> Just wanted to know whether a custom component was already implemented.
@nesnoj: the idea is to use a solph.transformer with COP-precalculation instead of creating a new custom component.
I would be interessted to hear if this approach suits the application you had in mind. And if not, what had to be different?

**Comment by nesnoj** [comment]
> I would be interessted to hear if this approach suits the application you had in mind. And if not, what had to be different?

Yes it does, your example is similar to what was in my mind when I was pointed to this thread. I think it's easier for new users to have an extra component with all required params instead of using helper functions, but that's a matter of taste. The "alias component" idea seems to be a good approach to me.

The precalculation works as long as the COP does not (like in this simplified approach) depend on the operation/dispatch, right? When it comes to e.g. partial load characteristics of the COP, a dedicated component for HP might be more appropriate? (I don't know if adding this dependency is possible at all?)

For now, I'm happy with the simplified approach in your example, thank you :+1:

I didn't review your entire code, just stumbled across
- the [hard-coded 2 °C threshold](https://github.com/oemof/oemof-thermal/blob/3c49f4e31fc81dd2ed805efded97d2945825099f/src/oemof/thermal/compression_heatpumps_and_chillers.py#L26) - it might be good to allow for a dew point time series? (or humidity)
- when a user tries to combine chiller and icing, [`calc_cops()` returns `None`](https://github.com/oemof/oemof-thermal/blob/3c49f4e31fc81dd2ed805efded97d2945825099f/src/oemof/thermal/compression_heatpumps_and_chillers.py#L39) - will this lead to an oemof exception? I'd rather raise a meaningful Exception or return the cops calculated [above](https://github.com/oemof/oemof-thermal/blob/3c49f4e31fc81dd2ed805efded97d2945825099f/src/oemof/thermal/compression_heatpumps_and_chillers.py#L23) (actually not a good idea)

**Comment by jakob-wo** [comment]
@nesnoj: thanks for your feedback!

>the hard-coded 2 °C threshold -  it might be good to allow for a dew point time series?

Yes, that's right - users should be able to set the threshold. I will change it.

> I'd rather raise a meaningful Exception

The component ist still under construction but you have a point - I will implement some more meaningful Exceptions soon.

**Comment by jnnr** [comment]
Can this issue be closed?

**Comment by joroeder** [comment]
I think so, since you have done this in oemof-thermal, right?

**Comment by jakob-wo** [comment]
That's correct. I will close it.
