### ISSUE TITLE
[foundation] Creation of an oemof foundation statute

### ISSUE THREAD

**Issue by busiing** [oemof/oemof#60]
Depending on the deadline for the oemof foundation decision process a charter has to be written. This might have some dependencies for the decision itself. That's why this process should be started parallel.

This issue is one task of the foundation process, open todos, see #79

**Comment by busiing** [comment]
Related open questions:

> Registering a foundation has some initial costs for registration, paying a notary.
> There is some work required setting up a foundation's statute (describing how to enter the foundation, decision processes etc.).
> What will be the membership fee? Experience tells that 200-400 Eur/a are the minimal requirements to sustain a foundation.
> Will the foundation be serving public good (gemeinnützig)?
> How much time do members spend for the foundation?
> How to prevent annoying overhead, bureaucracy, conflicts and idiosyncratic club dynamics (Vereinsmeierei)?
> Are there more examples of OSS-projects embodied by a foundation? Maybe some smaller projects could be a good example.
> 
> Some more examples of foundations (to be continued)
> 
> Energieseminar in Berlin
> Einleuchtend e.V.

**Comment by p-snft** [comment]
I created a branch to work on the [oemof foundation statute](https://github.com/oemof/oemof/blob/feature/foundation/legal/satzung.md). (It's currently in German, as we will probably register in Germany. However, I suggest to create an English translation when it starts to converge.)

**Comment by joroeder** [comment]
There is now PR #79 to elaborate the oemof foundation statute.

If anybody is interested in participating, please indicate your interest by commenting here. Then you will be added to the mailing list to organize further web-conferences for further elaboration and discussing the statute.

**Comment by c-moeller** [comment]
Thanks! I'm interested :-)

**Comment by p-snft** [comment]
Done.
