### ISSUE TITLE
Group entities in the EnergySystem class for easier access

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#60]

**Comment by cswh** [comment]
is this still valid? Or will we deal with it at the great refactoring? If so, please change the milestone accordingly.

**Comment by gnn** [comment]
I partially addressed this in the March release, but there is still some work to be done as the implementation is incomplete. Should be completed before the April release though. In the meantime, feel free to post any issues you run into with current implementation here.

**Comment by gnn** [comment]
So much for completion before the April release. Going to move that to the next release. Most of the functionality is there, but @simnh pointed me at the fact that crucial documentation is missing.

**Comment by gnn** [comment]
Ok. So now this is actually implemented and should be usable. I'm closing this. If anybody complains about missing functionality or lack of documentation, he or she can feel free to open another, more specific issue.
