### ISSUE TITLE
Implement fix value for global output in addition to sum_out_limit

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof#61]
similiar to the global output limit of a variable over the total timehorizon (sum_out_limit) but as fixed value rather than a maximum

**Comment by simonhilpert** [comment]
Interesting features, do you want this for components or busses? (or both)

**Comment by caro-rli** [comment]
At the moment I need this for the gas component to set a renewable share, or better a (1-renewable) share as non renewable share. But it might be better as a bus parameter, or even as an overall parameter for more busses, as people might have more non renewable types in their scenarios.

**Comment by caro-rli** [comment]
I can figure out how it was implemented in pahesmf. At the moment it works for me when I make a small change in the current constraint.

**Comment by uvchik** [comment]
If you are doing a cost optimisation than a maximum will be a fixed value if the alternatives are more expensive. If it would be cheaper to reach a share of 90% renewables than a share of 70% why should you force the system to 70%?

I think the easiest way is to limit the gas resource depending on the demand.

**Comment by simonhilpert** [comment]
I think it would be good if you could write down the mathematical equations your are trying to implement. 
Then we can figure out the easiest way of implementing it in the current solver-module solph. 

We were following a similar approach for @uvchik new requirements and I think we got (are getting) a clean solution...

**Comment by cswh** [comment]
how is the clean solution getting?

**Comment by caro-rli** [comment]
I have to check again what I meant with this issue. I remember I had problems with my simulation when having only a maximum limit rather than a fix value but need to reconstruct it. Will come up with this again soon or otherwise close it before march release.

**Comment by gnn** [comment]
So the March release is over and there wasn't any news on this. Do we have an update on this? Can this be closed or shall we have a look at it again before the April release?

**Comment by caro-rli** [comment]
Forgot to close this before March release.. so I'm closing it now.
