### ISSUE TITLE
[website] Add Broken Link Checker

### ISSUE THREAD

**Issue by busiing** [oemof/oemof#62]
Since we added a lot of related Models, Project and Publications there are a lot of links, which aren't "under our control". To prevent becoming a dead-end-link-cemetery the Broken Link Checker was invented to notify if there are any broken links. This tool helps to maintain our beloved website.

To integrate this tool an admin is necessary.

Integration is postponed after the creation of an oemof foundation #44.

**Comment by SuperKogito** [comment]
If I may, I would like to suggest using [urlchecker-python](https://github.com/urlstechie/urlchecker-python) or the [urlchecker-action](https://github.com/urlstechie/urlchecker-action) to detect broken links in all type of scripts (.md, .py, .js).

**Comment by uvchik** [comment]
> If I may, I would like to suggest using [urlchecker-python](https://github.com/urlstechie/urlchecker-python) or the [urlchecker-action](https://github.com/urlstechie/urlchecker-action) to detect broken links in all type of scripts (.md, .py, .js).

We do need a link checker that checks a published site not the code.

**Comment by uvchik** [comment]
What about this?
https://www.wpbeginner.com/plugins/how-to-fix-broken-links-in-wordpress-with-broken-link-checker/#brokenlinks-semrush

**Comment by SuperKogito** [comment]
sorry for the silly question but why is that different or how is that different from checking the links in the code?

**Comment by uvchik** [comment]
> sorry for the silly question but why is that different or how is that different from checking the links in the code?

It is a big difference because we do not have the code. It is an online CMS.

**Comment by busiing** [comment]
Closing argument: google bad
