### ISSUE TITLE
Pyomo issue 'not valid for indexed component' 

### ISSUE THREAD

**Issue by SystemAgent** [oemof/oemof#629]
Guys I saw that it was an issue in Mar. 2018 and I also saw it has been fixed but I am having trouble running some of the examples in storage_investment for x0.3.  
My versions are oemof==0.3.1; Pyomo==5.6.6;  
The file is v1_invest_optimize_all_technologies.py

The error is 
KeyError: 'Index \'("<oemof.solph.components.GenericStorage: \'storage\'>", "<oemof.solph.network.Bus: \'electricity\'>", 0)\' is not valid for indexed component \'flow\''. 

Thank you very much in advance, and again I am sorry if this is a solved issue and I am just missing something crucial, but do let me know :))

**Comment by uvchik** [comment]
I can not confirm this bug but the example you mentioned does not work at all.

I get an attribute error because we forgot to adapt this example to v0.3.x.

```python
AttributeError: The following attributes have been renamed from v0.2 to v0.3:

  `capacity_loss` to `loss_rate`

You are using the old names as parameters, thus setting deprecated
attributes, which is not what you might have intended.
Use the new names, or, if you know what you're doing, set these
attributes explicitly after construction instead.
```

This bug is already addressed [here](https://github.com/oemof/oemof-examples/pull/45) and will be available soon (tomorrow). So your issue reminded me to fix it.

I fixed the example by changing line 139.
```diff
- capacity_loss=0.00, initial_storage_level=0,
+ loss_rate=0.00, initial_storage_level=0,
```
Afterwards I executed the example with `oemof==v0.3.1` and `Pyomo==5.6.6` but everything works fine.

@SystemAgent Please check if you have the actual version of oemof-examples and fix line 139. Afterwards try again and post the result.

**Comment by SystemAgent** [comment]
@uvchik  Thank you very much for the prompt response! The problem with the versions was to do with my virtual environment and the Jupyter Notebook kernel that I found yesterday. When running the example from console, however, after changing the capacity_loss to loss_rate, I get a 

pyutilib.common._exceptions.ApplicationError: No executable found for solver 'cbc'

I ran the oemof_installation_test and got : 

Solver installed with oemof:

cbc: not working
glpk: not working
gurobi: not working
cplex: not working

*****************************
oemof successfully installed.

I guessed that I have messed up the installation somehow, and uninstalled the package and installed again with 'pip install oemof' but I get the same error for solvers. 

Do I need to install the Solvers separately, because the documentation says that some of them come as part of the installation of the oemof? 

Thanks a lot again !

**Comment by uvchik** [comment]
Yes, you do have to install the solver separately.

Please have a look at the [installation_and_setup]
(https://oemof.readthedocs.io/en/latest/installation_and_setup.html#installation-and-setup) chapter of the documentation. Choose your operating system and scroll down a bit to the 'solver' section.

Please close this issue if everything works fine again.

**Comment by p-snft** [comment]
Also note that sometimes the external solvers cannot be found. For example, I tried using the Snap package of PyCharm. When calling the (external) solvers, it fails due to the snap sandbox. Everything else works fine.

**Comment by SystemAgent** [comment]
Everything is working fine! Thanks a lot guys!
