### ISSUE TITLE
[website] Add google search console

### ISSUE THREAD

**Issue by busiing** [oemof/oemof#63]
Since the website gains more complexity the google search console might be a nice (and little) tool to have a controlling tool for it. This tool gives admins an overview about the clicks of the oemof homepage and its subpages - if there is an irregularity - the admin can fix the issues. Additionally, it is possible to optimize the "findability" of the homepage via google. Furthermore, it shows the search keywords, with which the searcher found our homepage. This might give us an insight into the interests of our visitors. It's just a little tool and uses the google statistics, google registers itself anyway and makes it accessible for the actual homepage owner.

To integrate this tool an admin is necessary.

Integration is postponed after the creation of an oemof foundation #44.

**Comment by p-snft** [comment]
I would object that, as it is at least doubtful whether it legally possible to include third-party tools that transfer personal data without consent. As an alternative, I would suggest an internal search.

PS: For some time, I ran a blog together with a State's attorney for internet crime. He taught me to be very strict.

**Comment by busiing** [comment]
Just to clarify - we are talking about google search console - not google analytics. 

The Search Console shows you the statistics for the visits / clicks from Google search to your site and what the robot / crawler of Google finds out about our site. Google Analystics analyses the behaviour of the users while they are surfing on your site, which is another thing.

The second thing is that you can be very critical about privacy issues, just like @p-snft's commentary says.

**Comment by p-snft** [comment]
My fault. I mixed Google search console and Google custom search. I would object the second, while the search console is fine. (Its actually more like adding the site to Google an not adding Google to the site.)

**Comment by uvchik** [comment]
What's wrong with the internal search widget?

**Comment by p-snft** [comment]
> What's wrong with the internal search widget?

You did the same mistake that I did. Google search console is a way to control the way the site is found using Google. It effect Google, not the site itself. Thus, it makes a difference for people using Google beforehand – not for the visitor to the site.

**Comment by busiing** [comment]
Closing argument: google bad
