### ISSUE TITLE
Release of v0.3.2

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#645]
There are some features and fixes about to merge and we do have a new licence.

We could release a v0.3.2 without a big fuss.

I would suggest to close the v0.3 branch for new features on November, 24 to release in the last week of November.

@oemof-developer Any objections?

**Comment by p-snft** [comment]
Sounds good. Thanks for the initiative!

**Comment by joroeder** [comment]
Yes, sounds good. It is a nice motivation to finish some stuff until then, although I don't know if I have sufficient time. So all open feature branches with milestone 3.2 which are not merged until that date will be postponed to v0.3.3 ?

**Comment by uvchik** [comment]
I would add a v0.3.3 milestone even though the next release might be already the v0.4.0 release.

The release is planned for tomorrow? Any objections?

**Comment by uvchik** [comment]
Done :tada:
