### ISSUE TITLE
[website] update contact us tab 

### ISSUE THREAD

**Issue by beierd** [oemof/oemof#65]
Dear all, 

as there has been some movement in the developer group recently we were wondering if we could bring the supporting institutions and personal contact up to date. 

Are there any objections and which institution and/or person wants to be listed after the update? 

Best, 
David

**Comment by busiing** [comment]
related issue #36

**Comment by beierd** [comment]
Heyhey, 

due to no objections and seemingly not too much discussion about the topic, I would go forward and update the tab on the **27th of April**. I would suggest that everyone who wants to be listed personally or her/his institution answers to this issue and I will update everything on 27th. 

Best, 
David

**Comment by busiing** [comment]
One objection from me. I would like to reschedule this topic in the related issue #36 and shift the further discussion to that #36 as well since this is a duplicate issue.
