### ISSUE TITLE
New custom component: Flat plate solar collector

### ISSUE THREAD

**Issue by c-moeller** [oemof/oemof#650]
We would like to add a custom component for a flat plate solar collector. The approach is depicted in the following figure:

![structure_oemof](https://user-images.githubusercontent.com/8330132/68868029-13607a00-06f7-11ea-92d5-884c0952f264.png)

1) The pvlib calculates the direct and diffuse irradiance on the collector area by considering position, azimuth and tilt of the  collector.

2) The time series of the irradiance on the collector is input for the precalculation. In the precalculation the collector efficiency is calculated by considering the collector and ambient temperature. Output is a timeseries of thermal power.

3) Finally electrical energy for pumps, and heat losses will be considered in the component.

**Comment by c-moeller** [comment]
@FranziPl I added the heat losses in the figure. They seem to be missing.

**Comment by joroeder** [comment]
Is Q_loss and P_el of the collector in your case a fix value / series? Or do they dependent on the Q_coll/Q_coll_use? In the first case, it can be represented by the existing transformer, in the second case, from its core principle, it is the same as the heatpipeline (transformer with constant loss) #618 #622 ... So, probably, it is a good idea to provide a "more general" Transformer with the option of a constant loss. This could serve as parent class for multiple facades. - btw, is there a decision how to proceed on that? #594  ... I think this is a very important decision almost all new components face.

**Comment by FranziPl** [comment]
The first idea was to define them dependending on Q_coll.

**Comment by fwitte** [comment]
I will bring a full precalculation of the heat output of solar collectors from given weather data (radiation and temperature) as well as collector data (pitch angle, south exposure, alpha1, alpha2, eta_opt and surface area) to the dev meeting and present it (maybe in the tespy <-> solph interface session). The concept seems quite similar to your suggestion @FranziPl. If you like, we can chat about this topic within the next days to prepare for the dev meeting.

**Comment by c-moeller** [comment]
@fwitte We plan to present our approach at the oemof-thermal session on Friday. Maybe we can combine it?

**Comment by c-moeller** [comment]
The related PR is here: https://github.com/oemof/oemof-thermal/pull/22
but still work in progress.

**Comment by joroeder** [comment]
> 
> 
> The first idea was to define them dependending on Q_coll.

So it is a facade with some precalculations, am I wrong? Do we want to collect these components in custom components or in oemof-thermal? I tought that's the idea of oemof-thermal. At least for me, it would be great to have a clear proceeding for future components (facades) ...actually what happens is that you are kind of parallel discussing in oemof-oemof(oemof-solph) and oemof-thermal ... maybe, this is just for confusing ;)

**Comment by FranziPl** [comment]
It should be in oemof, thermal, that's why the PR Features/solarcollector #22 is linked to it. I think, the first sentence of this issue is just a little bit confusing.
But I do agree to the fact, that we should have a clear proceeding for future components. Maybe we can come to a conclusion at the dev meeting.

**Comment by jnnr** [comment]
The flat plate collector has been released in oemof-thermal v0.0.1. Therefore I close this one. If you like, re-open the issue, transfer it to oemof-thermal or start a new one if there is need for further discussion.
