### ISSUE TITLE
Major Remastering

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#67]
This issue is meant to collect all major changes.

* Unique class names
* Solph result_object: Dataframe only, indexed by base class objects?
* Remove user headers from Spyder

@oemof/oemof-main : Feel free to extend the list!

**Comment by uvchik** [comment]
Thanks.

> Remove user headers from Spyder

* Unique class names
* Solph result_object: Dataframe only, indexed by base class objects?
* Define a header template and replace all existing headers (e.g. authors, dates, ...)

**Comment by uvchik** [comment]
* Unique class names
* Solph result_object: Dataframe only, indexed by base class objects?
* Define a header template and replace all existing headers (e.g. authors, dates, ...)
* Re-examinated the use of the EnergySystem and Simulation class. How do we use it? Do they work as expected?

**Comment by uvchik** [comment]
I opened a [wiki](../wiki/Issues-for-the-restructuring-meeting-from-6.4.-to-8.4.-in-Flensburg) to collect topics.

@oemof/oemof-main : Please add you topics regarding code and structure conventions, documentation, ... .

Please add a short comment here, to confirm that you read/ complemented the wiki.

**Comment by uvchik** [comment]
Where do we meet? Post-building? I could be there at about 13:15.

**Comment by uvchik** [comment]
@oemof/oemof-main : Who will take part?

**Comment by ckaldemeyer** [comment]
I know that me and @simnh are taking part and I am pretty sure that @gnn and @cswh are also on board.

I am not sure if @s3pp will take part because of (very) urgent project tasks.

**Comment by ckaldemeyer** [comment]
We meet in the Telekomgebäude!

**Comment by cswh** [comment]
@uvchik : We (@simnh , @gnn and @cswh) have an intensive day about openMod.sh tomorrow. Originally, we wanted to have the refactoring meeting on Thursday and Friday (if I remember correctly).

Is it ok to meet later than 13:15 tomorrow? Around 18:00 perhaps to plan the structure for Thursday and Friday? Then we should be finished with our openMod.sh issues...

**Comment by uvchik** [comment]
For me it is not worth being in Flensburg and doing my own stuff, but if you do not have time I can not do anything about it. I will bring my computer and do my own stuff. I will leave on Friday at about 15:45. If you can shift anything I will be pleased if not we will meet at 6pm.

**Comment by cswh** [comment]
Is it:
> I could be there at about 13:15.
or is it I will be there?

**Comment by cswh** [comment]
After phone communication we will try to start the joint session tomorrow around 4 pm. See you all there.

By the way: I will take part. And @gnn as well.

**Comment by uvchik** [comment]
I already booked the train, so besides delays I will be at the station at 12:45. That means that I probably will be at Telekom building at 13:15.

**Comment by ckaldemeyer** [comment]
@cswh : check your mails ;-)

**Comment by cswh** [comment]
Thank you for the nice meeting.
