### ISSUE TITLE
Specify sequence data type in Flow's docstring

### ISSUE THREAD

**Issue by nesnoj** [oemof/oemof#673]
As discussed in https://github.com/oemof/oemof-thermal/issues/51 recently, in the params of [Flow()](https://github.com/oemof/oemof/blob/0a503aa492b6b8e76c2a22d1ab51987aa9a1ee95/oemof/solph/network.py#L49) it is not fully clear what "sequence" in `numeric (sequence or scalar)` refers to (e.g. in `actual_value`) - can you use a Pandas Series? Yes, but this is not covered by the docs (actually a DF is allowed too although it doesn't make much sense to provide a multi-dimensional type).
Reading the docstring I'd assume it expects a builtin type which are - according to the [docs](https://docs.python.org/3/library/stdtypes.html?highlight=sequence#sequence-types-list-tuple-range) - list, tuple and range. 

Apparently, all [iterable](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable) objects are allowed here according to [this line in sequence()](https://github.com/oemof/oemof/blob/0a503aa492b6b8e76c2a22d1ab51987aa9a1ee95/oemof/solph/plumbing.py#L40) (except for string).

You may check with
```
>>> from collections.abc import Iterable
>>> from pandas import Series
>>> isinstance(Series([1, 2, 3]), Iterable)
True
```
The docstring should be something like
```
...
max : numeric (sequence or scalar)
      sequence must be iterable (instance of :class:`Iterable <collections.abc.Iterable>`) except :obj:`str`
...
```
(a little cumbersome though)

Do you agree?
If so, I could prepare a PR..

**Comment by p-snft** [comment]
As it is used very often, we might want to define and describe such argument types (here: 'sequence or scalar') at a single place in the documentation and link to that location.

**Comment by uvchik** [comment]
I think the docstring should look like this:
```
...
max : numeric (iterable or scalar)
      Normed maximum value of the flow.
...
```

In numpy they use array-like but I am not sure if this is a general expression in python. The scalar or the Iterable (list, array, Series, tuple...) will be converted into a solph.sequence. We could also allow sequences directly but I have not tried it. In that case we have to write `solph.sequence` in the docstring instead of just `sequence`.
