### ISSUE TITLE
Error in pyomo_fastbuild without using fast build

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#68]
@simonhilpert , @ckaldemeyer 

I get an error running the storage_invest.py on the dev branch. The error occurs in the pyomo_fastbuild module but I did not change an attribute.

```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof_base/examples/storage_optimization/storage_invest.py", line 157, in <module>
    om = OptimizationModel(energysystem=energysystem)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 121, in __init__
    assembler.registry[cls](e=None, om=self, block=block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 470, in _
    om.default_assembler(block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 179, in default_assembler
    block.optimization_options[option](self, block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/optimization_model.py", line 464, in linear_constraints
    lc.add_simple_io_relation(om, block)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/linear_constraints.py", line 183, in add_simple_io_relation
    block.indexset)
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/solph/pyomo_fastbuild.py", line 60, in l_constraint
    v._data[i] = pyomo.core.base.constraint._GeneralConstraintData(None, v)
AttributeError: 'module' object has no attribute '_GeneralConstraintData'
```

**Comment by simonhilpert** [comment]
I do not get an error on the dev branch using this example...(without and with fast_build=True)

what pyomo version are you using? (I use: Pyomo 4.2.10784)

pyomo --version in the console will print out the version


But I get an error from the outputlib...

**Comment by uvchik** [comment]
That is strange. My version is `Pyomo 4.1.10527` which is not a very old version.

It's not your fault but it is annoying if one gets an error having a version that is a few month old.

An update fixed it but I still do not understand why python goes into this module when I do not choose the fast build. That should not happen.

**Comment by simonhilpert** [comment]
Good that it fixed it. It should actually not load this module...i guess.
that is acutally the answer to your question, why we do not implement the fast_build as a standard way,
because it's based on a specific version / internal pyomo structure. 

But of course it should not throw an error if you do not select fats_build.

**Comment by uvchik** [comment]
So it is not urgent any more but could you or anybody else fix it anyway?

**Comment by simonhilpert** [comment]
@gnn can you have a look at it?

**Comment by gnn** [comment]
Yeah, I'll look into it, but probably not before the release.

**Comment by uvchik** [comment]
I found out what causes the problem:

```python
>>> print(type(model.energysystem.simulation.fast_build))
<class 'tuple'>
>>> print(model.energysystem.simulation.fast_build)
(False,)
>>> print(not model.energysystem.simulation.fast_build)
False
```

@simonhilpert , @ckaldemeyer , @gnn : Could anybody, who merged this feature fix this bug!

**Comment by simonhilpert** [comment]
Thanks, there was a ',' too much...check if it works now , then close please

**Comment by uvchik** [comment]
Thank you, seems to work now.
