### ISSUE TITLE
[docs] Documentation of the new oemof/oemof

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof#69]
This issue hosts the discussion of the new documenation of the oemof/oemof package. Let us use this place to collect comments and concrete ideas for the documentation. See the latest build here: https://oemof.readthedocs.io/en/latest/

**Comment by jnnr** [comment]
@bachibouzouk, can you give some feedback?

**Comment by smartie2076** [comment]
Hi! I wanted to give feedback to the new structure of the readthedocs, and planned to fix some typos on the way. The first issue I am meeting here: 

I was not sure how to improve the readthedocs. [Here](https://oemof.readthedocs.io/en/latest/developing_oemof.html#contribute-to-the-documentation) it reads:
> Contribute to the documentation
> If you want to contribute by improving the documentation (typos, grammar, comprehensibility), please use the developer version of the dev branch at readthedocs.org. Every fixed typo helps.

But there was only a master, no dev branch. 

Also, I am supposed to use the [pull request template](https://oemof.readthedocs.io/en/latest/developing_oemof.html#how-to-create-a-pull-request)

> Create a pull request and describe what you will do and why. Please use the pull request template we offer. It will be shown to you when you click on “New pull request”.

...but there is not really a lot predefined, except for @uvchik as a default reviewer:
![grafik](https://user-images.githubusercontent.com/44204527/81563133-2a2a1580-9396-11ea-9c07-9dff55405586.png)

Is this supposed to be this way? 

I will fix some typos now in PR #74.

**Comment by smartie2076** [comment]
**Overview page**

Notes regarding the [Overview](https://oemof.readthedocs.io/en/latest/readme.html), afaik this links to [README.rst](https://github.com/oemof/oemof/blob/master/README.rst)
* I felt like the headlines has to be sth else then "Overview" - there is no introductory chapter besides that one. (fixed in PR #74)
* Is there an intended order of the project releases below "Projects with stable releases"? Which one?
* oemof-thermal is missing a short description
* Some of the project are linked twice, ie. in the list and their description. This is not consistent:
Once: 
> * `oemof-solph <https://github.com/oemof/oemof-solph>`_
>   A model generator for energy system modelling and optimisation (LP/MILP).

Twice:
> * `demandlib <https://github.com/oemof/demandlib>`_
>   The `demandlib <https://github.com/oemof/demandlib>`_ library can be used to create load profiles for elctricity and heat knowing the annual demand. See the `documentation of the demandlib ><http://demandlib.readthedocs.io/en/latest/>`_ for examples and a full description of the library.
* Also, there are sometimes links to the documentation and sometimes not.
* This important note is somewhat hidden:
> All project libraries are free software licenced under the MIT license.

I would put this in the introductory text. (fixed in PR #74)

* I was not sure if ["Development"](https://oemof.readthedocs.io/en/latest/readme.html#development) linked to project development or to contributing to the readthedocs. It left me confused.

I hope this is kind of what you wanted to have feedback on.

**Comment by uvchik** [comment]
To move forward I would suggest the following steps.

1. Revise the main structure in one PR merge it soon (@gplssm ?)
2. Revise each chapter (if necessary) in a separate PR and merge it separatly.

My ideas:
- Overview:
- About ~~oemof~~
- ~~Installation~~ -> remove
- ~~Usage~~ -> rename to packages or tools or oemof-packages
- ~~Reference~~ -> remove
- ~~Developing oemof~~ -> join with Contributing
- Contributing
- ~~Authors~~ -> remove
- ~~Changelog~~ -> remove

**Comment by gplssm** [comment]
I began to re-work the oemof/oemof docs. Progress is discussed in [this PR](https://github.com/oemof/oemof/pull/81). The current state is shown [here](https://oemof--81.org.readthedocs.build/en/81/).
I follow you suggestion, @uvchik to create a minimal (in terms of avoiding a long discussion) version of the docs. We can than discuss individual sections again and revise them individually.

List of TODOs

- [x] Remove old docs according to suggestions
- [x] Merge developing_oemof into contributing
- [x] Overview on oemof packages
- [ ] Revisit content of README.rst, about_oemof.rst, developing_oemof.rst, and usage.rst and write about based on the existing content
- [ ] Add oemof logo to start page
- [ ] Remove "Indices and tables" from start page

**Comment by fwitte** [comment]
> Add oemof logo to start page

As you mention this, maybe this is a good idea for all packages of oemof? So the logo and a short text appear in the GitHub and pypi README as well as on the docs pages and maybe also links to the oemof.org or oemof.readthedocs page. At least for TESPy, the logo is not yet found, I do not know about the other packages. What do you think?

**Comment by gplssm** [comment]
> > Add oemof logo to start page
> 
> As you mention this, maybe this is a good idea for all packages of oemof? So the logo and a short text appear in the GitHub and pypi README as well as on the docs pages and maybe also links to the oemof.org or oemof.readthedocs page. At least for TESPy, the logo is not yet found, I do not know about the other packages. What do you think?
> 
> Edit: I think this correlates with #67

I would suggest to include the logo in every oemof-* package. Maybe some of them will used custom logos, if available. For other packages without custom logo, i.e. oemof-solph, the "standard" oemof logo would be good.
True, discussion fits better in #67 or maybe it is discussed per package.

**Comment by uvchik** [comment]
I agree using the standard logo for all packages and outsourcing the discussion about a package-logo into each repository.
