### ISSUE TITLE
[docs] The tespy description does not show on rtd

### ISSUE THREAD

**Issue by fwitte** [oemof/oemof#70]
After merging #68 it should, or is the rtd build not automated?
Cheers

![grafik](https://user-images.githubusercontent.com/20252362/79453320-d708b100-7fe9-11ea-8a34-004f2bbf7b2b.png)

**Comment by fwitte** [comment]
@uvchik, @busiing can one of you trigger an rtd build?

**Comment by uvchik** [comment]
The trigger should work now.

**Comment by fwitte** [comment]
Thanks, closing this issue then.
