### ISSUE TITLE
Duplicate information in the EnergySystem class

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#70]
We added a time index attribute named `time_idx` to the EnergySystem class and we also have a `timesteps` attribute in the Simulation class.

I calculate the timesteps using `Simulation.timesteps = range(len(EnergySystem.time_idx))`.

Do we still need both parameters or could we remove the timesteps attribute?

**Comment by ckaldemeyer** [comment]
I think we generally need to discuss which ways we want from data preparation till the optimization process (with or without the Simulation object)..

**Comment by uvchik** [comment]
That's true. I added a headword to the remastering list (#67). Feel free to edit it.

**Comment by simonhilpert** [comment]
I think we should have on standard way with the pandas Timeseries for energysystem and simulation object. In solph I would like to keep a simple list / or with integers.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
I do not understand what you mean. Can you explain again what you want and what you don't want. Maybe by showing a code example.

**Comment by uvchik** [comment]
We should discuss that at the meeting.

**Comment by uvchik** [comment]
There won't be a Simulation class since v.0.1.
