### ISSUE TITLE
[foundation] Create foundation

### ISSUE THREAD

**Issue by busiing** [oemof/oemof#71]
Since feelings have been [checked](https://github.com/oemof/oemof/issues/44). The next step to this topic would be to create a task force to address following topics (draft):

- [x] Create an oemof foundation statute (#60, PR #79)
    - [x] List potential costs of future foundation (https://etherpad.wikimedia.org/p/JsBHqBWhFnuAVZxSRiM5, thx @c-moeller)
    - [x] Organise meeting for discussion open statute issues 
    - [ ] Check statute with tax authority
- [x] Founding meeting (elections & adoption of statutes)
- [x] Foundation protocol
    - [x] Hand foundation protocol to tax authority
- [ ] Registration with the register of associations/registration court
- [ ] Notarial certification

**Comment by busiing** [comment]
Please add the people who wanted to be part of the task force on the dev meeting 2019. (unfortunately, it wasn't written down)

**Comment by busiing** [comment]
The initial task force was created at the [oemof dev meeting 2020](https://github.com/oemof/oemof/wiki/Meeting-May-2020-%28online%29). The task force will work on the issues named above and meet once per month in a short webco to present the recent developments and discuss necessary topics.

If you want to join the webco write an email to:
_EDIT_ @uvchik pls add email

It is welcomed to contribute to the topics or to join the Task Force.

**Comment by p-snft** [comment]
The ideal order would be as follows:

1. Draft an oemof foundation statute (#60 )
1a. Check with tax authority
2. Founding meeting (elections & adoption of statutes)
3. Create foundation protocol
3a. Hand foundation protocol to tax authority
4. Notarial certification and registration with the register of associations/registration court

Where the steps marked "a" are optional, if we opt for official non-profit status (means: no taxes, others may get tax deduction if they sponsor us, etc.).

**Comment by joroeder** [comment]
The next meetings for developing and discussing the foundation are every second Monday each month from 5 to 6 pm. So, the next meeting is 11 of January 2021.

If you want to participate, please indicate your interest by commenting here, or ask anybody of the people asigned in this issue.

**Comment by uvchik** [comment]
I am planning to attend.

**Comment by joroeder** [comment]
Notes from the 11th of January 2021

Attendees: @p-snft @c-moeller @joroeder  

Topics:
 * list of potential costs of future foundation was discussed and completed: [https://etherpad.wikimedia.org/p/JsBHqBWhFnuAVZxSRiM5](https://etherpad.wikimedia.org/p/JsBHqBWhFnuAVZxSRiM5)
     * resulting membership fee suggestion: institutions: 500 €/a, natural persons: 30 €/a 
 * need for decision on website (actual contract ends at 12.02.2021) if possible move to eg strato (cheaper), or stay at wordpress.com:
    * website meeting required next week: 
   
Next "regular" meeting: 08.02.2021, 5-6pm

**Comment by c-moeller** [comment]
Some notes for the next meeting:

- There will be still personnel requirements for supervising the student --> clarify, who will do that (Vorstand?) Aufwandsentschädigung?
- Also personnel is required for additional foundation tasks (formality)

- Detailfrage:
Spenden steuerlich absetzbar, Mitgliedsbeiträge nicht? --> geht das zusammen mit dem Mindestbeitrag, den wir uns überlegt haben, um flexibel zu bleiben? Aufstockung wären dann Spenden.

- Vorteile von Mitgliedern! --> Wir sollten uns nochmal Gedanken machen: Was haben (neue) (institutionelle) Mitglieder von der Mitgliedschaft?

**Comment by p-snft** [comment]
>     * Spenden steuerlich absetzbar, Mitgliedsbeiträge nicht? --> geht das zusammen mit dem Mindestbeitrag, den wir uns überlegt haben, um flexibel zu bleiben? Aufstockung wären dann Spenden.

Mitgliedsbeiträge sind genau so absetzbar wie Spenden, solange es keine Gegenleistung gibt. Und Mitgliedschaften mit beruflichem Bezug in jedem Fall – selbst ohne Gemeinnützigkeit.

**Comment by jnnr** [comment]
* For whom will the student work? For the oemof-Vorstand
  Person arbeitet für oemof
  The privilege Für das Privileg, die gewichtung zu setzen, gibt es keine Aufwandsentschädigung
  Betreuungsaufwand
  Vorstand bleibt ehrenamtlich, um kein ungleichgewicht herzustellen

* Verein gibt dem, was wir jetzt tun, einen rechtlichen Rahmen: 
  Zusätzlicher Aufwand durch foundation ist wohl recht gering.
   * 1mal im Jahr dem Amtsgericht sagen: Vorstand bleibt der gleiche.
     Das Amt muss wissen: Wer ist vertretungsberechtigt
   * Kassenprüfung

* Absetzbar?
  Comment psnf: Für Privatpersonen ist die Absetzbarkeit in jedem Fall da

* Vorteile von Mitgliedern
  Institute: Zb Logo kommt auf die oemof-Seite, es wird gezeigt, dass du oemof supportest
  Beteiligung an Kollaboration wird besser sichtbar
  A good solution to pertain visibility while contributing to a shared project.

**Comment by joroeder** [comment]
Next steps:

 * Collect foundation members
 * Organize meeting
 * Decide on open issues of Satzung

**Comment by c-moeller** [comment]
> Registration for the founding group starts at the next meeting: 8 March 2021, 5 to 6 pm

March 8th is holiday in Berlin. Could we exceptionally shift the meeting by one week? (March 15th)

> If you want to participate, please indicate your interest by commenting here, or ask anybody of the people asigned in this issue.

Shall we do a news post at oemof.org? Or after the meeting when the registration has started?

**Comment by p-snft** [comment]
I just realised that the adjusted date was not announced here: It will be **March15th**.

**Comment by jnnr** [comment]
> I just realised that the adjusted date was not announced here: It will be **March15th**.

Thanks for this update. The exact time will be 17h, I suppose?

**Comment by joroeder** [comment]
Summary of foundation meeting on 15 March 2021:

 * Explanation of the Satzung
 * Collecting open issues and questions
 * Starting to collect foundation members (9 people showed interest by showing up)
 
@ all: Please comment the Satzung #79 , if you have further issues

Next foundation meeting: **22 March 2021, 5 to 6 pm**

 * Decide on open issues of Satzung
 * Organize foundation meeting

If you want to participate, please indicate your interest by commenting here, or ask anybody of the people assigned in this issue.

**Comment by joroeder** [comment]
Summary of foundation meeting on 22 March 2021:

Attendees: @gnn @busiing @c-moeller @jnnr @joroeder 

 * Going through the Satzung and Beitragsordnung and resolving the comments and suggestions, that were consensus
 
@ all: If you find or have some issues, please comment the Satzung/Beitragsordnung/Geschäftsordnung: #79

Next foundation meeting: **12 April 2021, 5 to 6 pm**

 * Decide on open issues/suggestions of Satzung and Geschäftsordnung 
 * Organize foundation meeting

If you want to participate, please indicate your interest by commenting here, or ask anybody of the people assigned in this issue.

**Comment by p-snft** [comment]
Done - two years ago.
