### ISSUE TITLE
Project pitches - virtual spring meeting 2020

### ISSUE THREAD

**Issue by joroeder** [oemof/oemof#72]
This issue collects and organizes the "project pitches" session of the spring meeting 2020.

Please post here (name of your topic/project), if you want to pitch your current oemof project in this session.

Additionally, we should think about technical issues (e.g. collecting all slides in advance, because I don't think that this session will work fluently, if one after another person shares his/her screen).

Edit by @smartie2076: I will be the session lead. Please make sure that you register to be a presenter for this session:

>In the stream, questions can be asked via the chat. If you want to be part of the session and be able to talk you have to send an e-mail with the sessions you want to take part to the following address:
> oemof_spring_meeting_2020@posteo.eu

**Comment by B-Uhle** [comment]
I would like to pitch! My current project is ZellNetz2050. 
https://www.evt.uni-wuppertal.de/de/forschung/forschungsgruppe-betriebskonzepte-und-sektorenkopplung/zellnetz2050-simulation-des-aufbaus-zellularer-energienetzstrukturen.html

**Comment by joroeder** [comment]
I will pitch something about the application of DHNx for district heating network optimization

**Comment by uvchik** [comment]
I will talk about the `deflex` model.

**Comment by henhuy** [comment]
I will present my stemp-tool: https://wam.rl-institut.de/stemp/

**Comment by jnnr** [comment]
I will present oemoflex, a sector-integrated model on flexibility options: https://github.com/modex-flexmex/oemo-flex

**Comment by chrklemm** [comment]
I will present the [R2Q-project](https://www.fh-muenster.de/forschungskooperationen/r2q/index.php) and the [Spreadsheet Energy System Model Generator](https://spreadsheet-energy-system-model-generator.readthedocs.io/en/latest/).

**Comment by smartie2076** [comment]
Thank you for preparing your pitches! I will be leading the session tomorrow. 

Please make sure that you have prepared your up to 3-slide presentation, and store it as pdf. We should meet approx. 15 minutes ahead of time to check if we can use the screen share function for each of you. If that does not work, you should send me the pdf, or post it in the chat and I will show it. 

I will go about the order of presentations just like your time of posting :)

**Comment by smartie2076** [comment]
Thank you for your presentations! If you want others to find your projects, please add your presentation/project in the meeting´s documentation below our session "Project Pitch":

[https://etherpad.wikimedia.org/p/oemof-dev-user-2020](https://etherpad.wikimedia.org/p/oemof-dev-user-2020)

**Comment by smartie2076** [comment]
As  mentioned in #59:
Please link your presentations to the [ethercalc](https://ethercalc.org/b2zg1e72npzv) (timetable) or send it to @busiing has via email (see ethercalc).

**Comment by busiing** [comment]
All available presentations are uploaded to the website (draft) - will be public soon.
Related Issue: #41
