### ISSUE TITLE
Dump method of EnergySystem class does not work any more

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#74]
Dump method of EnergySystem class does not work any more. If I uncomment `energysystem.dump()` in the storage_invest.py I get following error message:

```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof_base/examples/storage_optimization/storage_invest.py", line 159, in <module>
    energysystem.dump()
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/core/energy_system.py", line 154, in dump
    pickle.dump(self.__dict__, open(os.path.join(dpath, filename), 'wb'))
_pickle.PicklingError: Can't pickle <function add_global_output_limit.<locals>.output_limit_rule at 0x7fd744ce88c8>: attribute lookup output_limit_rule on oemof.solph.linear_constraints failed
```

**Comment by uvchik** [comment]
How would a test looks like if do not want to include the optimisation in the testing procedure?

**Comment by gnn** [comment]
I (think I) fixed the issue with 863aa1bedf0be1b969fc9177a4b2460386eb1407. Unfortunately I hat to change to interface of getting at the objective value a little so watch out @caro-rli , the value is now directly storted in the `objective` attribute. No parentheses or `.value()` necessary anymore.

**Comment by uvchik** [comment]
Thank you. For me it works again, so I will merge it.

Some day I would like to understand how the test works but this is not so important at the moment.

**Comment by uvchik** [comment]
Merged and removed the branch.
