### ISSUE TITLE
Able to push to master without review

### ISSUE THREAD

**Issue by smartie2076** [oemof/oemof#75]
Hi! I think I would be able to push my changes to the master branch from my fork without anyone reviewing my PR #74 :

![grafik](https://user-images.githubusercontent.com/44204527/81569345-70d03d80-939f-11ea-9bcb-4f08f9dcab8e.png)

Is that intentional?

**Comment by uvchik** [comment]
Short answer: You can but you shouldn't.

We do not formalised our rules. If your changes include more than a typo or a pep8 fix you should not merge without a review but it is not forbidden. As I see it, people used this freedom in a responsible way. With a growing community, though, we could formalise these rights.

**Comment by smartie2076** [comment]
Okay. Maybe this should be added to the CONTRIBUTING.md then, so that this "soft rule" is clear. 

Not sure if you want to want to keep this issue as a reminder to edit that file - else it can be closed :)

**Comment by joroeder** [comment]
At the last oemof meeting, we decided that the team @oemof/oemof-developer-group gets "write" permission to  
[oemof/oemof](https://github.com/oemof/oemof) and [oemof/oemof-examples](https://github.com/oemof/oemof-examples) (See also #83). I think @uvchik explained the rest above. So, I will close this issue.
