### ISSUE TITLE
Getting the version number does not work.

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#79]
According to your comment in [issue 45](45#issuecomment-174015540) and commit 1cbcb1c.
The following code does not work for me. I used `pip3 install -e /path/to/oemof`.
```python
import oemof
print(oemof.__version__)
```
I think we are using the way described with number six of the following link:  
https://packaging.python.org/en/latest/single_source_version/#single-sourcing-the-version

Or is it not supposed to work if it is installed with the `-e` option.

**Comment by cswh** [comment]
it works for me with ``install -e``.

**Comment by cswh** [comment]
but I get a warning (see below) now when installing either with `pip3 install oemof` or with `pip3 install -e /path/to/oemof` (both v0.0.4).

    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'namespace_package'
    warnings.warn(msg)`

**Comment by uvchik** [comment]
@cswh : If your problem is still pending you should open a new issue. It works now on my computer and actually it is not that important.
