### ISSUE TITLE
[meeting] 2020 oemof Autumn/Winter Meeting

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof#80]
oh, I just saw that we wanted to do a web-conference last week about how to organize the next oemof meeting ;-) I think this is clear ;-)

The big question is, who will organise the next virtual meeting?

_Originally posted by @joroeder in https://github.com/oemof/oemof/issues/59#issuecomment-694381808_

According to https://github.com/oemof/oemof/issues/59#issuecomment-629218747, the date is fixed to 2.-4.12.2020.

**Comment by p-snft** [comment]
According to #59, the date is fixed to 2.-4.12.2020.

**Comment by uvchik** [comment]
I think a hybrid meeting might be interesting.

We were think of learning more about the inner core of solph and network (featuring @gnn). I think it will be a small circle that might be interested in such nerdy stuff. We could meet in real live and add some softer topics online.

@oemof-developer What do you think?

**Comment by busiing** [comment]
I won't be able to attend a meeting physically.  But feel free to open the format :)

**Comment by c-moeller** [comment]
I will ask RLI oemof developers on Thursday, what they think about the plan.

**Comment by joroeder** [comment]
> We were think of learning more about the inner core of solph and network (featuring @gnn). I think it will be a small circle that might be interested in such nerdy stuff. We could meet in real live and add some softer topics online.

A hybrid meeting is also a nice idea, I like the suggestion. I am interested in getting to know more about the oemof core.

If we agree on this mixed format, how could this look like in detail? Is the idea of the real live part, being in a conference room with video/audio, and you could also participate online? Or should it be like that: on the first day, there is a real-live-only meeting (e.g. on Wednesday), and on Thursday and Friday, there will be online sessions like at the last virtual oemof meeting?

**Comment by uvchik** [comment]
I think two ways are possible:

1. A mixture of online-focused and offline-focused sessions. The participants of the physical meeting could join the online sessions together, or next to each other or...

2. Two separated parts like @joroeder suggested. But the participants of the physical meeting need time to go home, so there has to be a break between both parts.

I like the first variant more, because we could arrange the online sessions less densely.

Besides that we can think of streaming the offline sessions.

**Comment by smartie2076** [comment]
>     1. A mixture of online-focused and offline-focused sessions. The participants of the physical meeting could join the online sessions together, or next to each other or...

I also like this one better - having a part of the devs travel somewhere and the other staying home could also create some kind of rift or difficulties to participate. 

I personally also like the idea of having decentralized meet-ups, for example of people living in the same city: These smaller groups could be working on specific issues in person, and then we could have a group call where the those groups present what they did. 

Apart from that: In the RLI oemof meeting we were not quite sure if the "speciall session" to be introduced by Günni to the oemof backbone (if I did not misunderstand) would only be part of the live meeting, if we decide for (2.).

**Comment by p-snft** [comment]
At the moment, I doubt that I would be able to justify an in-person meeting. Thus, I personally rely on the possibility to join online.

**Comment by uvchik** [comment]
Taking the actual Corona situation into account I doubt that it will be possible to to have an in-person meeting.

@oemof-developer Who would help to organise the online meeting?

**Comment by joroeder** [comment]
I would help to organize! However, I would appreciate more people get involved into the organization than last time :)

**Comment by p-snft** [comment]
> @oemof-developer Who would help to organise the online meeting?

Count me in.

Contentwise I would suggest to collect topics, future attendees name as their interests. We could just start a collection in the wiki:
* Topic
    * Would organise: (Names)
    * Interested: (Names)

(Or do you have something else in mind?)

Regarding the date we might still have time for a Doodle.

**Comment by uvchik** [comment]
> Contentwise I would suggest to collect topics, future attendees name as their interests. We could just start a collection in the wiki:

:+1: 

> Regarding the date we might still have time for a Doodle.

Do you want to change the existing date (2.-4.12.2020.)?

**Comment by p-snft** [comment]
Sorry, I forgot the date was fixed already. (And there was no announcement at oemof.org.)

**Comment by smartie2076** [comment]
Hi @all! I would like to participate in the oemof-conference. One question about the sessions: Are project-specific sessions wanted for this event? I would have a project I would like to present, but I am not sure it is of interest, or if we should wrap it into a larger session with multiple presentations. 

### Drag-and-drop interface
* oemof is used for developing the [Multi-Vector Simulator](https://github.com/rl-institut/multi-vector-simulator/), basically allowing easy energy system definition (public, open)
* Energy systems here are local, sector-coupled energy systems
* A user interface is developed with a drag-and-drop feature for energy system definition (will be public and open)
* Show screenshots / experiment with the interface, feedback
* Plans for further development
...I would imagine either a presentation of 15 minutes or for a more active session an input/tutorial session, some experimenting and then a feedback round.

**Comment by p-snft** [comment]
> Hi @ALL! I would like to participate in the oemof-conference. One question about the sessions: Are project-specific sessions wanted for this event? I would have a project I would like to present, but I am not sure it is of interest, or if we should wrap it into a larger session with multiple presentations.

For the last in-person meetings, we had poster session where this topic would fit perfectly. However, I do not know if there will be something similar this time. I will put it on the list. If it interests the others, there will be a session. (I would be interested in the GUI part. I drafted something very fundamental some time ago.)

**Comment by joroeder** [comment]
> 
> 
> Hi @ALL! I would like to participate in the oemof-conference. One question about the sessions: Are project-specific sessions wanted for this event? I would have a project I would like to present, but I am not sure it is of interest, or if we should wrap it into a larger session with multiple presentations.

The focus of this meeting should be more on the dev stuff, but this does not mean that there can not be any project presentations. I also think your session could be very interesting! And maybe, this also attracts other users to join the oemof meeting. In my opinion, it makes sense in this context to focus on some technical dev aspects of your project, like, what were the challenges in your development? How are you using oemof-solph? What are the limits of your approach? What would you do different if you start again?

**Comment by smartie2076** [comment]
Thank you @p-snft and @joroeder for the feedback. I will change the session to one where 2 or 3 other models/works can be discussed as well (with dev focus). 

@all: Is there someone who would also present a model from a dev perspective? If we had 2 or 3 other models, we could get a discussion going. If there is no-one, I would organize a rather short session.

**Comment by cfoth** [comment]
Hi @ALL. I'm an oemof beginner and interested in listening to the different oemof topics at the oemof autumn/winter meeting 2020.
Is it possible that i can get write permissions to the oemof-wiki [Meeting-December-2020](https://github.com/oemof/oemof/wiki/Meeting-December-2020-(online)), so that i can sign up for the different topics.

**Comment by p-snft** [comment]
> Hi @ALL. I'm an oemof beginner and interested in listening to the different oemof topics at the oemof autumn/winter meeting 2020.
> Is it possible that i can get write permissions to the oemof-wiki [Meeting-December-2020](https://github.com/oemof/oemof/wiki/Meeting-December-2020-(online)), so that i can sign up for the different topics.

Do you mind, just giving the list of topics here? (I know, it's not as inviting as it could be, but it helps us keeping track of the planning.)

**Comment by uvchik** [comment]
@cfoth: I changed the settings. It should be possible for you to edit the wiki.

Nevertheless, when we do have an agenda we should move to a public pad to make it easier for people to subscribe.

**Comment by cfoth** [comment]
> 
> @cfoth: I changed the settings. It should be possible for you to edit the wiki.
> 
> Nevertheless, when we do have an agenda we should move to a public pad to make it easier for people to subscribe.

Thanks a lot. I added my name to the topics.
To move to a public pad is a great idea for further meetings in the future.

**Comment by joroeder** [comment]
There is an agenda now @p-snft and me drafted!

[https://github.com/oemof/oemof/wiki/Meeting-December-2020-(online)](https://github.com/oemof/oemof/wiki/Meeting-December-2020-(online))

Please check your slot, and give feedback if something doesn't suit you. By the end of the week, there should be a newsletter with the agenda - so don't wait too long!

**Comment by baumbude** [comment]
Could you take me to the attendees list, please.
I am oemof beginner but once wrote my own tool in matlab very similar to solph (but not as deeply generic as solph) and therefore wrote my own pyomo-subsitute for matlab.

**Comment by joroeder** [comment]
> 
> 
> Could you take me to the attendees list, please.

Welcome! You are on the list 😊

**Comment by ckaldemeyer** [comment]
I would like to participate on Friday for the session _Blocks Building on experience_.

**Comment by fwitte** [comment]
Is it possible to adjust the timetable? I have lecture on Thursday at 14:00, where the Integration of TESPy block is scheduled. Maybe switch it with the jupyter notebook docs time as there do not seem to appear others interested?

**Comment by p-snft** [comment]
As there are no parallel sessions, some people did not add their names to all of them. (This includes me: I actually planned to join the jupyter session.)

**Comment by tscherwath** [comment]
Could you add me to the attendees list.

I am interested in the following topic:
- Foundation / association
- oemof.network
- DHnX
- Building on experience: What to take from individual models for the oemof-community

best,
Tim

**Comment by smartie2076** [comment]
> https://github.com/oemof/oemof/wiki/Meeting-December-2020-(online)
> 
> Please check your slot, and give feedback if something doesn't suit you. By the end of the week, there should be a newsletter with the agenda - so don't wait too long!

Hi @p-snft @joroeder! Thank you for creating the agenda. 

Sorry for the late reply, I was on vacation - would it be possible to move my session from 11.00 on Friday to anytime on Thursday? I think you did not send out a newsletter yet...

**Comment by fra-mezzera** [comment]
Hi everybody,
Could you please add me to the attendees list? I would like to follow the afternoon session (oemof.network + multiperiod optimization) on wednesday and the topics on thursday (structure of solph, TESpy and DHNx).
Will be the event also available on live streaming as for the past Spring edition?
Thank you in advance,

Francesco

**Comment by uvchik** [comment]
> Will be the event also available on live streaming as for the past Spring edition?

You can login with the "listen only" option, which is than similar to a live stream. We do not think that we will reach the limit of the conference tool, so it is not necessary to activate an addition stream.

**Comment by unndreay** [comment]
Could someone please add me to the attendees list? I'd like to follow the Reports from pkgs, Function signatures and Building on experience. Tank you in advance!

**Comment by cfoth** [comment]
> 
> 
> Could someone please add me to the attendees list? I'd like to follow the Reports from pkgs, Function signatures and Building on experience. Thank you in advance!

Hello. I added you to the attendees list.

**Comment by AntonellaConsolinno** [comment]
Hello could someone please add me to the attendees list? Thank you in adavance!

**Comment by fwitte** [comment]
done

**Comment by c-koehl** [comment]
Good morning, sorry for being so late, but I would also join you as an attendee :)

**Comment by joroeder** [comment]
The meeting successfully took place (virtual) half a year ago. So, we can close this issue.
