### ISSUE TITLE
Variable state of charge of a storage at timestep 0

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#82]
Is it possible to connect the SOC of a storage at timestep 0 to the SOC of the last timestep?

In pahesmf we had a constraint like this:

```
soc(0) = soc(-1)
```
If not, how shall we do it? Set `cap_initial='auto'`?

According to the [documentation](http://oemof.readthedocs.org/en/v0.0.3/api/oemof.core.network.entities.components.html#oemof.core.network.entities.components.transformers.Storage) the SOC has a quarter of the capacity at the first timestep.

**Comment by caro-rli** [comment]
I'm using this currently in my local example with the following:

in solph.linear_constraints line 540ff and line 549

```
-    for e in block.uids:
-      block.cap[e, t_last] = cap_initial[e]
-      block.cap[e, t_last].fix()
+#    for e in block.uids:
+#      block.cap[e, t_last] = cap_initial[e]
+#      block.cap[e, t_last].fix()
```

```
-            expr += block.cap[e, t] - cap_initial[e]
+            expr += block.cap[e, t] - block.cap[e, 8759]
```

But this is only a local workaround by now. We should build a switch for this constraint.

**Comment by ckaldemeyer** [comment]
@caro-rli : I thought this was already implemented at some stage (from me?). If it's not why don't you implement this?

**Comment by uvchik** [comment]
@caro-rli : I do not understand why you changed that but did not just start a pull request to discuss the changes and make them available for everybody?

I made a proposal (#84). Let us continue there.

**Comment by caro-rli** [comment]
@uvchik @ckaldemeyer 
Because the change is no general approach. I needed this (urgently) to get my simulation run. If I push this, other simulations might not run anymore. I'm unfortunately also very busy these days. Will do it as soon as I find the time.

**Comment by caro-rli** [comment]
Ok, I think this is now in #84. So I'm closing it.
