### ISSUE TITLE
[Wiki] How to release

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof#82]
The "How to release" description is posted in the oemof.solph wiki (https://github.com/oemof/oemof-solph/wiki/How-to-release). However, we use the instructions for releases of other repos as well (e.g. oemof-thermal, DHNx).

There is some information that we could add that are general, e.g. the reminder that for a first release of a new package, you have to first create the zenodo hook before you release. For oemof.solph, this info does not apply because it already exists.

I propose that we move the how-to to this repo (oemof), if this is possible.

**Comment by uvchik** [comment]
> I propose that we move the how-to to this repo (oemof), if this is possible.

:+1: 

Thank you @jnnr. I would keep a link on  the solph wiki.

**Comment by jnnr** [comment]
Thanks for your approval. The move is done now and a link will redirect.
