### ISSUE TITLE
[meeting Dec 2020] Session: Building up on experience 

### ISSUE THREAD

**Issue by smartie2076** [oemof/oemof#84]
As discussed, in #80 I would like to organize a session where we present and learn from our models. If you are interested to pesent your model from this perspective, please comment below. Please write a sentence about your model and what we can learn or re-utilize from your coding process.

#### Building up on experience: What to take from individual models for the oemof-community
* Presentation of models based on oemof from a dev perspective - what can we learn from individual projects?
* Structure: Model presentation for 5 minutes, learning outcomes/difficulties/oemof issues/reusable code 5 minutes, 10 minutes discussion how we could create synergies/oemof improvements
* Included subtopics:
    * [Multi-Vector Simulator](https://github.com/rl-institut/multi-vector-simulator/) (smartie2076)

**Comment by smartie2076** [comment]
I will present following model:

[Multi-Vector Simulator (MVS)](https://github.com/rl-institut/multi-vector-simulator/)
* About: Tool for simulating user-defined local sector-coupled energy systems, automatized energy system building, post-processing of results and KPI. Publicly available,  GPL-2.0 License. 
* Learning outcomes: [Energy system model graph for oemof.visio](https://github.com/oemof/oemof-solph/issues/674#), user interface with drag-and-drop feature (will be public and open), pdf-report...

**Comment by p-snft** [comment]
I can offer to introduce the ENaQ Meta Model. It is planned to be published later this year (or in beginning of 2021).

- About: Generic model offering a variety energy supply options (esp. heat) for residential buildings (mostly using Transformers).

- Learings: Small CHPs are over-subsidised in a way that purchasing and selling electricity at the same time is sometimes cheaper than own-consumptions. However, you cannot feed in while local demand is higher than local supply. Thus, I adjusted the "[solph.custom.Link](https://github.com/oemof/oemof-solph/issues/723)" to solve the problem.

**Comment by smartie2076** [comment]
Great @p-snft, I will add it to the list 👍

**Comment by joroeder** [comment]
[c-koehl](https://github.com/c-koehl) from [consolinno](https://consolinno.de/) will give an overview of their activities using oemof-solph for real world applications. I will add it to the list.

**Comment by smartie2076** [comment]
> 
> 
> [c-koehl](https://github.com/c-koehl) from [consolinno](https://consolinno.de/) will give an overview of their activities using oemof-solph for real world applications. I will add it to the list.

Nice! Can you let me know if they are presenting together or two seperate things, so that I know how much time I can give each person?

**Comment by smartie2076** [comment]
Ah, I see. It is one presentation, as I understand from the wiki.

@c-koehl, @p-snft: I would like to make an 1-hour session from this. As such, I suggest that each of us present for about 10 minutes, and then we have 10 minutes of questions, if there are any. I do not know yet how the conference tool works, so I would be glad if you could upload your presentations here (or send them to me via mail: `martha.hoffmann at rl-institut.de`). 

Lets hope to inspire our fellow devs!

**Comment by joroeder** [comment]
hey, yes, sound good. I will let them know.

**Comment by joroeder** [comment]
Maybe we left this issue open for the missing presentations of this session. Since this was half a year ago, I do not think that the missing presentations of last meeting will be updated somewhere. So, I will close this issue.
