### ISSUE TITLE
Find a new structure for the result-object/dataframe

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#85]
As the title says, a common structure for time-series, scalar values, etc. would be nice without having redundancies.

One idea would be to use a [pandas panel object](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel).

Here's a small example:

    # -*- coding: utf-8 -*-
    import pandas as pd
    import numpy as np
    
    df1 = pd.DataFrame(np.random.randn(2, 4))
    df1.columns = ['A', 'B', 'C', 'D']
    print(df1)
    
    df2 = pd.DataFrame(np.random.randn(4, 1))
    df2.columns = ['E']
    print(df2)
    
    df3 = pd.DataFrame(np.random.randn(2, 5))
    df3.columns = ['F', 'G', 'H', 'I', 'J']
    print(df3)
    
    
    data = {'Item1': df1,
            'Item2': df2,
            'Item3': df2}
    
    my_panel = pd.Panel(data)
    my_panel.describe
    my_panel['Item1']
    my_panel['Item2']
    my_panel['Item3']

Panels can also hold MultiIndex dataframes but it might also be an idea to use standard dfs..

**Comment by ckaldemeyer** [comment]
@oemof/oemof-main: feel free to add your ideas!

**Comment by uvchik** [comment]
From issue #86:

As discussed in issue #80 there is still confusion about the results.

* Is the DataFrame just an optional structure to create plots or should it be more integrated? Is it to slow to be the default structure for the results?
* What about the scalars in the DataFrame?
* Where can we store meta results such as some solver statistics
* What is an intuitive structure for results that belong to edges or components
* ...

**Comment by ckaldemeyer** [comment]
> Is the DataFrame just an optional structure to create plots or should it be more integrated? Is it to slow to be the default structure for the results?

I think it's not. The "new" creation method saved about 60-70 percent of the creation time compared to the old method and with the old method it took about 35 minutes for 11 million entries (renpass-gis).

Let's say it's 10 minutes for a big EU model. If the structure is then saved and holds all data for subsequent analyses, I think it's o.k.

**Comment by s3pp** [comment]
It`s even faster. Atm the DataFrame creation takes 3 minutes for the latest renpass-gis results. The DataFrame holds round about 9 million entries.

**Comment by ckaldemeyer** [comment]
:smile:

So I guess there's no problem :thumbsup:

**Comment by uvchik** [comment]
* Is the DataFrame just an optional structure to create plots or should it be more integrated or even replace the dictionary for the timeseries? ~~Is it to slow to be the default structure for the results?~~
* What about the scalars in the DataFrame? Do we need an extra DataFrame or will we keep the dictionary. Or see [@ckaldemeyer's approach](85#issue-131294786).
* Where can we store meta results such as some solver statistics
* What is an intuitive structure for results that belong to edges or components
* ...

**Comment by ckaldemeyer** [comment]
> Where can we store meta results such as some solver statistics

In my opinion, this belongs to the simulation object and not into the results

**Comment by uvchik** [comment]
> > Where can we store meta results such as some solver statistics

> In my opinion, this belongs to the simulation object and not into the results

I just do not want to forget them, when we try to make a coherent concept for all outcomes of the solver. But I am okay with storing them in the simulation object.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by SanderNielen** [comment]
Does the current result-object contain the following numbers: 
- the installed capacity of each component, 
- the sum of inputs/outputs of each energy carrier per component for the whole time scope,
- the value of the objective function evaluated for the optimized configuration.
In principle, the third value can be calculated from the other two (although I don't know how to invoke the objective function evaluation). 

In my opinion it is useful to have these numbers in the results object, or at least have functions to calculate them. What are your thoughts about this?

**Comment by simnh** [comment]
* no
* no 
* no 

I think functions would make sense. 

you get the objective value by optimzation_model.objective.value() (this is pyomo)

**Comment by ckaldemeyer** [comment]
@SanderNielen:

I also think your suggestions would make sense. We have a developer meeting in the beginning of April and will discuss this among several other things.

By the way: Would you mind to drop a few lines on you e. g. name, affiliation, research field and purpose to use oemof?

We are always interested in new users/developers but it's also nice to have more information than just a name ;-)

**Comment by SanderNielen** [comment]
> By the way: Would you mind to drop a few lines on you e. g. name, affiliation, research field and purpose to use oemof?

Done :D

**Comment by ckaldemeyer** [comment]
Where?

**Comment by SanderNielen** [comment]
On my personal info page.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by uvchik** [comment]
@ckaldemeyer : Is it still valid? The milestone is the oemof meeting in Flensburg.

**Comment by ckaldemeyer** [comment]
Nope.
