### ISSUE TITLE
Periodical web conference (16/02/2016) cancelled

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#87]
I just talked to @uvchik . Since all people from Flensburg are at the "Strategiewoche" in Denmark, it might make sense to cancel the date.

@oemof/oemof-main : If no one has a veto, we continue with the conferences at 16/02/2016!

**Comment by ckaldemeyer** [comment]
Another thing! We should introduce an "announcement" label :-)

**Comment by uvchik** [comment]
> @oemof/oemof-main : If no one has a veto, we continue with the conferences at 16/02/2016!

You mean the next conference on 01/03/2016.

**Comment by ckaldemeyer** [comment]
>> @oemof/oemof-main : If no one has a veto, we continue with the conferences at 16/02/2016!
>You mean the next conference on 01/03/2016.

Of course! Sorry, I was a bit in a haste...
