### ISSUE TITLE
Common oemof-paper at environinfo2016 or somewhere else

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#88]
I already suggested to write a common oemof-paper at [environinfo2016](http://enviroinfo2016.org/participation/call-for-papers-and-workshops/) via e-mail. 

@oemof/oemof-main: This issue should serve as a reminder to start a web conference in the week starting at 22/02/2016 with all people who are interested in a contribution.

**Comment by uvchik** [comment]
:+1: What time? 15:00?

**Comment by ckaldemeyer** [comment]
Should we say 22/02/2016 15:00 ?

**Comment by simonhilpert** [comment]
I think it would be good to use a latex template (I like the elsartcl class) and work collaborative on the latex file via git (either on a other server or github) 

For me it would even be ok to make a feature branch 'paper/oemof-concept' were we can develop the paper as a working paper. 

What do you think?@oemof/oemof-main

**Comment by ckaldemeyer** [comment]
Sounds good! I also like the two column IEEE Layout which we have used for our IRES paper. But I don't mind!

**Comment by ckaldemeyer** [comment]
[Authorea](www.authorea.com) provides different templates as well. But I would use it only to get inspired because our experiences were not the best ;-)

**Comment by uvchik** [comment]
A latex paper on github sounds good for me. We are used to it now and we all have accounts. Better than another account and another platform....

**Comment by caro-rli** [comment]
Hi there, I forwarded your mail, Cord, and this issue to @beritRLI since she is working on a paper on the community process, so it might be good to coordinate here. As for me, I'm planning a review paper on storage modeling in energy system models, but there is not so much progress until now... :neutral_face:

**Comment by caro-rli** [comment]
Was there a web conference this week? What was the result?

**Comment by ckaldemeyer** [comment]
nope, somehow we missed it. we can discuss it next monday

**Comment by caro-rli** [comment]
I'd like to join, but cannot make it on Monday. Would Tuesday also be ok?

**Comment by uvchik** [comment]
Tuesday afternoon would be okay for me.

**Comment by ckaldemeyer** [comment]
For me, too.

**Comment by ckaldemeyer** [comment]
So, we have a paper-related conference on Tuesday and another one today concerning structural questions, right?

**Comment by uvchik** [comment]
Couldn't we hold this conference and the structure-conference(#93) consecutively on Tuesday?

**Comment by ckaldemeyer** [comment]
:+1: O.k., so 3 pm if there are no vetos

**Comment by simonhilpert** [comment]
:+1:

**Comment by uvchik** [comment]
:+1:  3 pm is okay

**Comment by cswh** [comment]
Update from the conference:
* probably no full paper at EnvironInfo due to time/ressource constraints until end of March
* a broader (up to 3 paper) approach combined with a super documentation with major release in May

**Comment by ckaldemeyer** [comment]
> probably no full paper at EnvironInfo due to time/ressource constraints until end of March

I guess we already know that there won't be a full paper ;)

**Comment by ckaldemeyer** [comment]
I have heard via different channels that @EvaWie, @BeritRLI and @ludee (is highlighting working only for certain groups?) are planning a paper about oemof respectively mainly the experiences during the oemof development and communication processes.

I am just interested: Are the people from @oemof/oemof involved in any way?

**Comment by ckaldemeyer** [comment]
Meaning "mentioned" ;)

**Comment by ludee** [comment]
Our full paper for enviroinfo2016 had to be cancelled due to not getting done.

**Comment by ckaldemeyer** [comment]
Ah, o.k.. Thanks, anyway!

**Comment by birgits** [comment]
Can we close this issue?

**Comment by cswh** [comment]
So far the plan is to have some form of citable paper with the May release of v0.1.0. So it does not have to do anything with the Eniroinfo anymore. Therefore this issue can be closed imho.

**Comment by ckaldemeyer** [comment]
Reopened as discussed at the last meeting!

**Comment by fraukewiese** [comment]
Moin oemofs,

zwei Umstände treffen gerade prima zusammen:
- ich brauche Veröffentlichungen
- ich finde es sollte ein oemof-paper geben, das Framework bekannt machend, eingebettet in der Aussage, dass open and collaborative modelling essentiell ist für gesellschaftlich nützliche Energiesystemmodellierung.

Ich hatte schon mit Cord darüber gesprochen, er meinte, gute Idee, es gab schon Bestrebungen, aber niemand der das in die Hand genommen hat, ich solle das einfach auf Github anregen. Ich habe auf overleaf ein Artikel-Entwurf begonnen.
https://www.overleaf.com/5254475wxgygx#/16524521/

Hier ist auch das pdf dazu falls ihr Euch nicht auf Overleaf anmelden wollt (konnte das pdf irgendwie nicht hochladen, daher als .zip)
[oemof_paper_suggestion.pdf.zip](https://github.com/oemof/oemof/files/274408/oemof_paper_suggestion.pdf.zip)

Fragen an Euch:
- Wäre das ok obwohl ich gar nicht bei oemof mitgearbeitet habe?

Wenn ja:
- Findet ihr die Ausrichtung des Papers / Struktur passend?
- Wer kann und möchte beitragen?

Rückmeldung bis nächsten Donnerstag (26.Mai) wäre super - kann auch ganz kurz sein aber ich brauche Rückmeldungen um überhaupt zu wissen ob ich da weitermachen soll oder nicht.

Danke, frauke

**Comment by beritRLI** [comment]
Hallo Frauke,
dein Vorschlag hat große Überschneidungen mit dem paper, was wir gerade im open_eGo Projekt schreiben (quasi in dem Teil von eGo der aus unserem OSSE Projekt entstanden ist). 
Wir sollten abstimmen, ob das zwei paper werden, oder ob wir das zusammen schreiben. Also gerne zeitnah alle Stichpunkte angucken und Entscheidung treffen.
wo möchtest du das einreichen? wir haben über einen short bei der enviroinfo nachgedacht, weil wir die full paper deadline nicht geschafft haben, wollten aber nochmal genauer gucken, wo das passt. Ich habe auch über das journal nachgedacht, das Mark Howells jetzt übernommen hat.
gruß
Berit

**Comment by gplssm** [comment]
Auch wenn ich mich nicht als Kernentwickler von _oemof_ sehe, möchte ich zu dem Thema gerne meine Meinung abgeben!

1. Die Zeit ist reif für ein bis viele Paper über oemof! Ich denke der kollaborative/community-Ansatz verdient ein eigenes Paper. Daneben kann es noch weitere zum `core` package und den `namespace` packages geben. Und natürlich im Laufe der Zeit fortlaufen Paper zu Ergebnissen der Modellanwendung, also den Apps. Schön, dass du einen Teil von vorantreibst, Frauke! :+1: 
2. Fraukes Strukturvorschlag finde ich für den Detaillierungsgrad gut. Zunächst sollte wohl erst die Arbeit mit Eva/Martin/Berit (AP1 von _open_eGo_) koordiniert werden, dann wäre es lohnend darüber nochmal zu sprechen.
3. Die Menschen, die sich in der Entwicklung von _oemof_ hervorgetan haben und das Ding vorangetrieben haben, sollte m.E. auch die entsprechenden Autorschaften bekommen. Einen Anhaltspunkt dafür kann die [contributionsübersicht sein.](https://github.com/oemof/oemof/graphs/contributors). Aufruf an die Entwickler: fordert euch das ein! Den Interessenskonflik mit Fraukes "ich brauche Veröffentlichungen" sollte man natürlich beiderseitig zufriedenstellend lösen.

**Comment by fraukewiese** [comment]
danke für die rückmeldungen berit und guido.
wie wärs mit: kurzes paper (wir kurz ist das dann eigentlich?) beim Enviroinfo wie ihre es geplant hattet über die Herausforderungen der kollaborativen Modellentwicklung und zusätzlich mehr oemof und open source und kollaborativ als Teile für ein Journal paper. Ja, vll. energy strategy reviews. 
zu Guidos 3.: klar. das kriegen wir bestimmt gut hin.
gibts noch weitere rückmeldungen?

**Comment by uvchik** [comment]
:+1:  Ich finde den Vorstoß von Frauke auch super. Ich stimme @gplssm zu, dass noch viele weiter paper möglich und nötig sind, aber wir sollten die Diskussion schnell trennen, damit wir das eine Paper nicht mit der Diskussion über mögliche weitere Paper ausbremsen.

Deshalb schlage ich getrennte Issues für die beiden Themen (Fraukes Initiaitve / Welche weiteren Paper) vor und möglichst nicht hier sonder eher [dort](../../../oemof/organisation/issues) :smile: .

**Comment by ckaldemeyer** [comment]
> Auch wenn ich mich nicht als Kernentwickler von oemof sehe, möchte ich zu dem Thema gerne meine Meinung abgeben!

> 1. Die Zeit ist reif für ein bis viele Paper über oemof! Ich denke der kollaborative/community-Ansatz verdient ein eigenes Paper. Daneben kann es noch weitere zum core package und den namespace packages geben. Und natürlich im Laufe der Zeit fortlaufen Paper zu Ergebnissen der Modellanwendung, also den Apps. Schön, dass du einen Teil von vorantreibst, Frauke! :+1:

Das sehe ich genau so!

Ergänzend: Vielleicht sollen wir in diesem Prozess gleich evtl. nachfolgende bzw. geplante Paper abgrenzen. Ich denke da z. B. an Paper zur graphenbasierten Darstellung von Energiesystemen, o. ä..

> 2. Fraukes Strukturvorschlag finde ich für den Detaillierungsgrad gut. Zunächst sollte wohl erst die Arbeit mit Eva/Martin/Berit (AP1 von open_eGo) koordiniert werden, dann wäre es lohnend darüber nochmal zu sprechen.

Denke ich auch. Ich würde die Punchline in dem Zuge noch einmal festzurren, also klar von dem was daneben noch über oemof veröffentlicht werden soll abgrenzen.

> 3. Die Menschen, die sich in der Entwicklung von oemof hervorgetan haben und das Ding vorangetrieben haben, sollte m.E. auch die entsprechenden Autorschaften bekommen. Einen Anhaltspunkt dafür kann die contributionsübersicht sein.. Aufruf an die Entwickler: fordert euch das ein! Den Interessenskonflik mit Fraukes "ich brauche Veröffentlichungen" sollte man natürlich beiderseitig zufriedenstellend lösen.

Ich würde gerne mit auf das Paper, da ich während meiner Diss-Zeit mindestens drei Veröffentlichungen schreiben muss und zusätzlich gerne etwas "zitierfähiges" für meine oemof-Mitarbeit hätte ;-)

Insgesamt finde ich, dass es einfach an der Zeit ist da etwas rauszuhauen!

**Comment by simnh** [comment]
I totally agree with @uvchik  and additionally I think we should keep discussions in english. 

I acutally added an issue here to collect paper ideas etc. `https://github.com/oemof/organisation/issues/4`

**Comment by simnh** [comment]
Regarding the question I already talked to @fraukewiese: 

The brief summary of this talk: 

- good idea from my side, every thing else has more or less been said! 
- I think we should be able to complete the core paper first ([see here.](https://github.com/oemof/organisation/issues/4))
so that we can reference something already.

**Comment by beritRLI** [comment]
Hallo Frauke,
I suggest you have a look at the latest version of the paper that we started. We have a look at overleaf and we discuss if that should be merged in one paper.
I like the idea to make a short for the enviroinfo and then a long for the journal and I would like to work it out together.
We have a regularly webko on thursday 2:30 p.m. - may be we can use at least 30 minutes to talk about the paper (@mGlauer, @EvaWie, @ludee what do you think?). If that's not possible we should quick start a dudle for this week.
