### ISSUE TITLE
[code] How to deal with TRAVIS-CI

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#88]
I think this will effect every single oemof package. In the future we have to pay for Travis-Ci unless we do fulfill the following rules:

 1. Project must be at least 3 months old and is in active development (with regular commits and activity)
 2. Project meets the OSD specification
 3. Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
 4. Project can not provide commercial services or distribute paid versions of the software

The fact that we do develop the software (partly) at our work time seems to be sponsorship according to Travis. Furthermore, I do not think that we can afford 69 USD/month for each project. So we have to look for alternatives. Any ideas?

**Comment by uvchik** [comment]
Github actions might be an idea but we will bind the project closer to github.

**Comment by uvchik** [comment]
I tested Github actions workflows in [deflex](https://github.com/reegis/deflex) and I added a PR in [oemof.solph](https://github.com/oemof/oemof-solph/pull/746).

**Comment by p-snft** [comment]
I think Travis was phased out in most of our projects.
