### ISSUE TITLE
Documentation: referencing oemof

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/oemof#89]
I think we should provide a format to be referenced.

This could look like:

oemof. (2016). Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Licensed under GNU GPL 3. Database and source code available at https://github.com/oemof

@oemof/oemof-main : Any further suggestions?

I want to reference in our paper until Friday, so it's urgent!! ;)

**Comment by ckaldemeyer** [comment]
I have no referenced it as electronical source:

_Open Energy Modelling Framework (oemof) - A modular open source framework to model energy supply systems. Licensed under GNU GPL 3. Available at https://github.com/oemof_

Do you agree?

**Comment by uvchik** [comment]
I do not have a better idea, so go ahead :+1:

**Comment by cswh** [comment]
I agree too. See https://github.com/oemof/oemof/wiki/How-to-quote-oemof
