### ISSUE TITLE
Avoiding too many components in solph

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#93]
How can we avoid to have too many specialist components in solph?

One idea is to make it possible to connect components with additional constraints. For example a heat storage with an additional heating device could be new component (with a lot of new code) or a simple transformer and a simple storage connected with one additional constraint.

Another idea is to create virtual components within a new assembler. The heating storage with the additional device could create two blocks (transformer and storage) pass them to the according assembler and add an additional constraint.

The advantage of both ideas is that I do not have to create totally new functions that creates constraints just for the special storage.

This is just one example but I think we should think about solutions that avoid duplicate code and too many specialist components without blowing up the oemof structure too much.

I think there are more ways to make the solph structure more flexible. Therefore I would like to start the discussion...

@oemof/oemof-main : Please take part and post your ideas and preferences.

**Comment by ckaldemeyer** [comment]
> How can we avoid to have too many specialist components in solph?

> One idea is to make it possible to connect components with additional constraints. For example a heat storage with an additional heating device could be new component (with a lot of new code) or a simple transformer and a simple storage connected with one additional constraint.

> Another idea is to create virtual components within a new assembler. The heating storage with the additional device could create two blocks (transformer and storage) pass them to the according assembler and add an additional constraint.

I would prefer this option.

>The advantage of both ideas is that I do not have to create totally new functions that creates constraints just for the special storage.

>This is just one example but I think we should think about solutions that avoid duplicate code and too many specialist components without blowing up the oemof structure too much.

>I think there are more ways to make the solph structure more flexible. Therefore I would like to start the discussion...

> @oemof/oemof-main : Please take part and post your ideas and preferences.

_My opinion:_

I would generally propose that we *do not include very special components in the framework* because I think by doing this, it will get too messy and hard to maintain. But the structure should allow to *flexibly extent the basic framework blocks on application level* and we should provide good examples how to do this.

By doing this, the user has all degrees of freedom and the framework core remains well defined.

**Comment by ckaldemeyer** [comment]
Would it make sense to have a web conference or even a real life meeting for this?

**Comment by simonhilpert** [comment]
+1:

**Comment by uvchik** [comment]
@simonhilpert : Thank you for fixing the typo.

I think we should decide this at the real life meeting but sometimes it is good if there are already some ideas people can think about.

**Comment by uvchik** [comment]
@ckaldemeyer  The problem might be to define what is a `very special component` because this might differ from one to another. And the more components we have the easier we can create an energy system without writing a lot of new components. In my opinion it is more important to create a structure that makes it possible to have a lot of components without losing the overview.

Of course it is also a good idea to make it possible to pass additional constraints defined in the app directly to solph. For example `The output of transformer_1 and the output of transformer_2 should not be greater than 1000`. It would be a bad idea to create a `Two-transformer-with-limited-output-` component. Or is it already possible?

**Comment by ckaldemeyer** [comment]
> I think we should decide this at the real life meeting but sometimes it is good if there are already some ideas people can think about.

Any proposals for a date?

I am quite flexible this week except for tomorrow morning and Friday afternoon.

Maybe Thursday 3 pm?

**Comment by uvchik** [comment]
A real life meeting? On Thursday? You mean a web conference?

Friday afternoon would be possible for a web conference.

**Comment by uvchik** [comment]
Oh i just saw that you said except (!) Friday afternoon. Than maybe next week. Thursday is quite full.

**Comment by ckaldemeyer** [comment]
Yes, I meant a web conference ;-)

Sounds good. Monday 3 pm?

**Comment by uvchik** [comment]
I would prefer 4 pm, but 3 pm is also possible.

**Comment by ckaldemeyer** [comment]
4 pm is also o.k. for me

**Comment by uvchik** [comment]
Couldn't we hold this conference and the one paper-conference(#88) consecutively on Tuesday?

**Comment by simonhilpert** [comment]
I would suggest we will take 1 hour for the paper and leave some space for additional topics, such as this one. Most likely we will not be able to finish, but we can discuss next steps and some organizational stuff.

**Comment by uvchik** [comment]
:+1:

**Comment by gnn** [comment]
I definitely think that ATM `solph` and `oemof.core` are coupled too tightly and IIRC @simonhilpert agrees with me on this. We do think that `solph` should be refactored to be better decoupled from `oemof.core` and have some vague ideas about this, but it's a hard problem.

Concerning the following:
> Of course it is also a good idea to make it possible to pass additional constraints defined in the app directly to solph. For example The output of transformer_1 and the output of transformer_2 should not be greater than 1000. It would be a bad idea to create a Two-transformer-with-limited-output- component. Or is it already possible?

IMHO the "canonical" way to do this in `oemof` would currently be to attach those two `Transformer`s to a dedicated `Bus` and putting an input limit on that `Bus`.

**Comment by uvchik** [comment]
>> Of course it is also a good idea to make it possible to pass additional constraints defined in the app directly to solph. For example The output of transformer_1 and the output of transformer_2 should not be greater than 1000. It would be a bad idea to create a Two-transformer-with-limited-output- component. Or is it already possible?

>IMHO the "canonical" way to do this in oemof would currently be to attach those two Transformers to a dedicated Bus and putting an input limit on that Bus.

You are right, but this is just a simple example and there might be other ones.

**Comment by uvchik** [comment]
This will be part of the oemof refactoring.
