### ISSUE TITLE
[meeting] 2021 oemof Spring Meeting

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof#93]
At the last meeting, we suggested to have the next meeting from May 5th to 7th 2021.

Etherpad for registration and topic suggestions: https://etherpad.wikimedia.org/p/oemof_user_meeting_spring_2021

Tentative timeline: https://github.com/oemof/oemof/wiki/Meeting-May-2021-(online)

Suggested topics:
* https://github.com/oemof/oemof-solph/issues/556 (fixed costs)
* #90 (strategy for the future)
* #92 (move all oemof packages to oemof community)
* #78 (rename master to stable)
* #71 (oemof association)
* oemof/oemof-examples#66 (location of examples)
* General website orga (e.g. emails)
* #30: implementation of a user forum for oemof.org
* Changes from oemof/oemof-solph#740 targeted at users
* Development in oemof/oemof-solph#750 (includes fixed costs (see oemof/oemof-solph#556), but a more general discussion and decision on that is appreciated.
    * oemof/oemof-solph#757, oemof/oemof-solph#758 (and GenericStorage in general)

**Comment by p-snft** [comment]
I started this issue to be able to reference it from any other issue. This way, suggestions are easier to track.

**Comment by fwitte** [comment]
I would like to add some sessions for TESPy:

- Tutorial: Building a model, investigation of parameter influence
- Tutorial: Offdesign simulation of a plant
- Presentation/Discussion: Bring your own model

Topics (what plant to build/analyze) may be chosen freely.

**Comment by Fernando3161** [comment]
I would be very interested in participating in building these tutorials: 

> I would like to add some sessions for TESPy:
> 
> * Tutorial: Building a model, investigation of parameter influence
> * Tutorial: Offdesign simulation of a plant
> * Presentation/Discussion: Bring your own model
> 
> Topics (what plant to build/analyze) are subject to user preferences.

**Comment by fwitte** [comment]
- #30: implementation of a user forum for oemof.org

**Comment by fwitte** [comment]
Possible topics for TESPy tutorial session(s), let us know, what you are interested in:

- heat pump
- organic Rankine cycle
- gas turbine (maybe combined cycle)
- server cooling
- solar thermal power plant
- ... feel free to post your own suggestions! This might also include specific features of the software.

@Fernando3161, do you want to participate in the session or actually build the tutorial we are going to present?

**Comment by govind-menon110** [comment]
Hi, just letting the team know that I'd like to participate to learn from the tutorials and the meeting. Thanks!

**Comment by jelic1marko** [comment]
I would also like to state my interest in participation here, especially in the cases related to modeling heat pumps! 

> I would be very interested in participating in building these tutorials:
> 
> > I would like to add some sessions for TESPy:
> > 
> > * Tutorial: Building a model, investigation of parameter influence
> > * Tutorial: Offdesign simulation of a plant
> > * Presentation/Discussion: Bring your own model
> > 
> > Topics (what plant to build/analyze) are subject to user preferences.

**Comment by fwitte** [comment]
Hi all,
we created an etherpad and will track the topics and participant list there. The pad will be updated continuously regarding topcis and timetable: https://etherpad.wikimedia.org/p/oemof_user_meeting_spring_2021.
Have a sunny weekend!

**Comment by jokochems** [comment]
Hello everyone,
I'd like to give two talks / discussions which I added to the etherpad:
* One on the changes from https://github.com/oemof/oemof-solph/pull/740 targeted at users and
* One on the ongoing development in https://github.com/oemof/oemof-solph/pull/750
The latter includes fixed costs (see oemof/oemof-solph#556 from the list above), but a more general discussion and decision on that is appreciated.

**Comment by Fernando3161** [comment]
> @Fernando3161, do you want to participate in the session or actually build the tutorial we are going to present?

I have built small components and later integrated them with oemof.solph, but I think I lack the experience to fully develop a tutorial.

**Comment by jnnr** [comment]
Can we already define the start and end of the meeting, so that people can add a blocker to their calendar? I would have guessed that we start after noon, as traditionally, and end before noon. Shall we announce it like that?

**Comment by p-snft** [comment]
> I would have guessed that we start after noon, as traditionally, and end before noon. Shall we announce it like that?

I'd also like to stick to that tradition from good olde ofline times.

**Comment by uvchik** [comment]
> I'd also like to stick to that tradition from good old offline times.

I think we can plan the winter meeting as a real-live meeting.

**Comment by uvchik** [comment]
> Can we already define the start and end of the meeting, so that people can add a blocker to their calendar? I would have guessed that we start after noon, as traditionally, and end before noon. Shall we announce it like that?

:+1:

**Comment by uvchik** [comment]
If there is still some time we could add a PR-rescue session. There are some PRs in which are almost finished already for quite a while. Maybe we can bring them to an end, save the idea or drop them.

solph:
Add gradient constraints to investment model: [#405](https://github.com/oemof/oemof-solph/pull/405)
Heat Pipe: [#619](https://github.com/oemof/oemof-solph/pull/619)
Schedule for flows: [#666](https://github.com/oemof/oemof-solph/pull/666)
Nonequidistant timeindex: [#701](https://github.com/oemof/oemof-solph/pull/701)
GasLine [#722](https://github.com/oemof/oemof-solph/pull/722)

I really like the idea of a solph report. It could help to make solph and its models more transparent. Is there a way to continue this PR [#523](https://github.com/oemof/oemof-solph/pull/523)

Making a plan to make the kwargs explicite. Is it possible to split the work? [#733](https://github.com/oemof/oemof-solph/pull/733)

**Comment by uvchik** [comment]
Some time ago the idea of "renewable-share" constraint came up. It is is easy to implement but I think it is a bad style. If anybody is interested we could discuss the topic and/or create the constraint.

**Comment by busiing** [comment]
The initial draft was added to the [wiki](https://github.com/oemof/oemof/wiki/Meeting-May-2021-(online))

**Comment by busiing** [comment]
> If there is still some time we could add a PR-rescue session. There are some PRs in which are almost finished already for quite a while. Maybe we can bring them to an end, save the idea or drop them.
> 
> solph:
> Add gradient constraints to investment model: [#405](https://github.com/oemof/oemof-solph/pull/405)
> Heat Pipe: [#619](https://github.com/oemof/oemof-solph/pull/619)
> Schedule for flows: [#666](https://github.com/oemof/oemof-solph/pull/666)
> Nonequidistant timeindex: [#701](https://github.com/oemof/oemof-solph/pull/701)
> GasLine [#722](https://github.com/oemof/oemof-solph/pull/722)
> 
> I really like the idea of a solph report. It could help to make solph and its models more transparent. Is there a way to continue this PR [#523](https://github.com/oemof/oemof-solph/pull/523)
> 
> Making a plan to make the kwargs explicite. Is it possible to split the work? [#733](https://github.com/oemof/oemof-solph/pull/733)

@p-snft and me are meeting at 2 pm for a agenda bingo. Are you able to join, to play with us?

**Comment by uvchik** [comment]
I cannot promise, but I'll try. Where?

**Comment by jokochems** [comment]
> 
> 
> The initial draft of the agenda was added to the [wiki](https://github.com/oemof/oemof/wiki/Meeting-May-2021-(online))

Thanks a lot, @busiing!
* I had to move my session on Wednesday slightly (15:00 instead of 14:30) due to a conflict with another appointment.
* https://github.com/oemof/oemof-solph/pull/740 addresses demand response, so I removed the extra session from the agenda since this will be covered in a small tutorial / example session on wednesday.
* I was named as in charge for the district heating session. I assume, @joroeder or someone else was meant.

**Comment by jokochems** [comment]
Will we use the Big Blue Button conference tool again or is there a plan to go for another tool?

**Comment by fwitte** [comment]
Hi @busiing, thanks for your draft! I have an appointment until about 15:30/15:45 on Thursday, so I will only be able to join the session late.

**Comment by fwitte** [comment]
If there are any other tutorials planned (maybe something for solph etc.), we might need parallel sessions on Wednesday, too.

**Comment by p-snft** [comment]
> Will we use the Big Blue Button conference tool again or is there a plan to go for another tool?

Yes. @busiing will set something up.

**Comment by busiing** [comment]
> If there are any other tutorials planned (maybe something for solph etc.), we might need parallel sessions on Wednesday, too.

True. But since we don't have a space problem, I didn't want to put N columns in the table :)

**Comment by busiing** [comment]
@all please look at open spots in the agenda and for chairs and your opportunity the contribute. :)

**Comment by JulianBarinton** [comment]
Dear oemof community,

My name is Julian, and I am a Ph.D. Student at RLI off-grid team focusing on enabling the configuration of integrated water, energy, eco-, food systems. I would like to participate in the oemof spring meeting and pitch OWEEF - the open water, energy, eco-, food system framework - based on oemof. OWEEF shall add productive uses/components from the water and agricultural sector to oemof and allow the configuration of integrated WEEF systems. It would be great if you could find a time slot for a short pitch presentation! Greetings Julian

**Comment by simnh** [comment]
Hey Julian, I am not really involved in the planning, but there should definitely be a slot! I would be very interested in your ideas and planned development regarding the agriculture and water sector :-)

**Comment by fwitte** [comment]
I think it would suit the project pitch session (max 3 minutes, max 3 slides) well. There will be time after the short presentations to discuss/talk in depth about the respective topcis.

**Comment by joroeder** [comment]
> 
>   I was named as in charge for the district heating session. I assume, @joroeder or someone else was meant.

I did not put this session either :blush: However, we could convert the session into a DHNx session (current status of repo, further developments, etc.), if the person who originally posted that session has nothing against it. And what is meant by "oriented to heat losses"? @jnnr or me could chair the session (or together). So, I will change that in the wiki, and if there is anything against, please protest  :wink:

**Comment by fwitte** [comment]
This repository might be interesting regarding that session, too: https://github.com/ZigaGazvoda/Python_district_heating_calculation. A district heating system was simulated in TESPy based on geodata of pipes and the model was (as far as I know) validated with a different software. Unfortunately, the uploaded version can not be run without the proper (missing) requirements file. However, the sample inputs/outpus can be seen in the ipython notebook.

**Comment by joroeder** [comment]
> 
> 
> This repository might be interesting regarding that session, too: https://github.com/ZigaGazvoda/Python_district_heating_calculation. A district heating system was simulated in TESPy based on geodata of pipes and the model was (as far as I know) validated with a different software. Unfortunately, the uploaded version can not be run without the proper (missing) requirements file. However, the sample inputs/outpus can be seen in the ipython notebook.

Thanks for the hint, that's also very interesting. Yes, there is also [https://www.pandapipes.org/](https://www.pandapipes.org/), and maybe some more. Maybe, we can also use this session for collecting different experciences with different tools in the first part. And in the second part, we could talk about future developments of DHNx. I am really open on how to fill and use the session.

**Comment by JulianBarinton** [comment]
> I think it would suit the project pitch session (max 3 minutes, max 3 slides) well. There will be time after the short presentations to discuss/talk in depth about the respective topcis.
Great to hear from your interest @simnh. Thank you for your reply @fwitte! I will be available for the pitch of OWEEF on Wednesday from 10 am on! Looking forward to getting to know you and receiving feedback. Greets Julian

**Comment by jokochems** [comment]
Hey guys,

thanks for that interesting first day of the user & dev meeting! There are quite some interesting modeling and dev activities happening.
As discussed this morning, I moved the multiperiod modeling slot to 16:30 tomorrow. Please let me know if anyone is experiencing trouble with that shift. Sorry for being so short-notice on this one.
Of course, I'm willing to answer and discuss this one if you can't make it to the session.

Best regards and see you tomorrow (in old freshness :-D),
Johannes

**Comment by jokochems** [comment]
A short update on my sessions:
* I updated and uploaded the presentation on the multiperiod approach. Please find it [here](https://github.com/jokochems/multiperiod_oemof-solph/blob/main/multi-period_modeling_oemof-solph_overview.pdf)
* The demand response tutorial I gave, can be found [here](https://github.com/jokochems/DR_modeling_tutorial). I added a requirements.txt file for pip (only) installation.

**Comment by busiing** [comment]
- [ ] Etherpad transfer to the wiki documentation

- [ ] Collecting the presentations

- [ ] Collecting the emails
- [ ] 
- [ ] Sending the presentations to the participants

- [ ] Publish the presentations on the homepage 

- [ ] Editing group photo

- [ ] About us oemof meeting update

**Comment by busiing** [comment]
@joroeder Do you know that status-quo of collecting the presentation and emails is. I guess we forgot thinking about this.

**Comment by p-snft** [comment]
We had the meeting. Closed.
