### ISSUE TITLE
Multiple inputs into components

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#95]
The `inputs` attribute of an entity is a list. That suggests that it is possible to have more than one input. In the documentation I found: 
```
inputs (list) – List of Entities acting as input to this Entity.
```
In the init method of the `OptimizationModel` class only the first element of all inputs is used while all outputs are used:

```python
self.I = {c.uid: c.inputs[0].uid for c in self.components
          if not isinstance(c, cp.Source)}
self.O = {c.uid: [o.uid for o in c.outputs[:]] for c in self.components
          if not isinstance(c, cp.Sink)}
```
Commit 4ee86b194d changes it, so that all inputs are used now.

It will be merged with the `features/heatstorage_with_dT` branch. If you need it before that merge you can pick this commit.

@gnn / @simonhilpert : Was there a reason to use just one input?

**Comment by simonhilpert** [comment]
There was no reason - the only one was that we only had components with 1 input. Please make sure, that this works for all files inside solph : variables.py, linear_constraints, mixed_inter ....

**Comment by uvchik** [comment]
> Please make sure, that this works for all files inside solph : variables.py, linear_constraints, mixed_inter ....

I will do my best. Since we do not have proper tests I can not ensure it.

**Comment by uvchik** [comment]
I created a feature branch (`features/multiple_inputs`). All tests are okay and the example works. You can test it with you examples if you want but I think everything should work.

After your `hotfix` (a6cdc663ef) the tests did not work any more. Please make sure that all tests are okay after a commit on the `dev` branch.

**Comment by simonhilpert** [comment]
yes sorry, I will do so. My examples should work with the multilpe inputs. you already merged so I will close this issue.

**Comment by uvchik** [comment]
Sorry, could not wait :blush:
