### ISSUE TITLE
Delete connection() in oemof.tools db.py

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof#99]
The omeof package contains an outdated version of the connection()-function that is now located in the oemof.db subpackage. I would like to remove this to prevent further confusion. A hint was added to inform users that they still use this function, see ff02fe2c2ad9de8146af4badc9afa72c88e0b4a5.

Could you all please check that you aren't using it anymore and give the OK to delete it?

**Comment by ckaldemeyer** [comment]
I don't use it anymore and I'm OK with deleting.

**Comment by uvchik** [comment]
:+1: I do not use it, either. Database functions should be in `oemof.db`

**Comment by gplssm** [comment]
Thanks for feedback. 

@oemof/oemof-main I'll remove it on first on march if no one stops me.
